-- Batch 6 — featured_page_refs seeds. Applied 2026-04-22 via MCP. Archive
-- copy of the seed INSERT; re-applying is idempotent only if the table is
-- empty. If the repo's migration tooling re-runs this, it will append
-- duplicate rows. Consider a "DELETE WHERE created_at < now()" gate or
-- relying on a unique constraint in a future hygiene pass.
--
-- Pages seeded: isaiah-mini-bible, suffering-servant, bronze-serpent,
-- genealogies, messianic-psalms, seed-promise, tabernacle. Not seeded
-- (no obvious verse anchor): bible-codes (ELS is a visual demo).

INSERT INTO featured_page_refs (featured_page_slug, featured_page_title, route_prefix, book_id, chapter, verse_start, verse_end, note) VALUES
  ('isaiah-mini-bible', 'Isaiah as a Mini-Bible', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'isa'), 7, 14, 14,
    'Immanuel — the virgin birth prophecy.'),
  ('isaiah-mini-bible', 'Isaiah as a Mini-Bible', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'isa'), 9, 6, 7,
    'Wonderful, Counsellor, The mighty God, The everlasting Father.'),
  ('isaiah-mini-bible', 'Isaiah as a Mini-Bible', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'isa'), 40, 3, 5,
    'The voice of him that crieth in the wilderness — quoted by all four Gospels.'),
  ('isaiah-mini-bible', 'Isaiah as a Mini-Bible', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'isa'), 53, 1, 12,
    'The Suffering Servant chapter — Isaiah''s mini-gospel.'),
  ('isaiah-mini-bible', 'Isaiah as a Mini-Bible', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'isa'), 61, 1, 3,
    'The Spirit of the Lord GOD is upon me — quoted by Jesus in Luke 4.'),
  ('suffering-servant', 'The Suffering Servant', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'isa'), 52, 13, 15,
    'Behold, my servant shall deal prudently.'),
  ('suffering-servant', 'The Suffering Servant', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'isa'), 53, 1, 12,
    'Wounded for our transgressions.'),
  ('suffering-servant', 'The Suffering Servant', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'act'), 8, 32, 35,
    'Philip preaches Jesus from Isaiah 53.'),
  ('bronze-serpent', 'The Bronze Serpent', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'num'), 21, 4, 9, 'Moses lifts up the serpent.'),
  ('bronze-serpent', 'The Bronze Serpent', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'jhn'), 3, 14, 15,
    'As Moses lifted up the serpent... even so must the Son of man be lifted up.'),
  ('genealogies', 'Genealogies of Christ', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'mat'), 1, 1, 17, 'Matthew''s genealogy.'),
  ('genealogies', 'Genealogies of Christ', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'luk'), 3, 23, 38, 'Luke''s genealogy.'),
  ('messianic-psalms', 'Messianic Psalms', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'psa'), 2, 1, 12, 'The Messianic inauguration psalm.'),
  ('messianic-psalms', 'Messianic Psalms', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'psa'), 16, 8, 11, 'Quoted by Peter at Pentecost.'),
  ('messianic-psalms', 'Messianic Psalms', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'psa'), 22, 1, 31, 'The crucifixion psalm.'),
  ('messianic-psalms', 'Messianic Psalms', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'psa'), 110, 1, 7, 'Most-quoted OT verse in the NT.'),
  ('seed-promise', 'The Seed Promise', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'gen'), 3, 15, 15, 'The protoevangelium.'),
  ('seed-promise', 'The Seed Promise', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'gen'), 12, 1, 3, 'Abrahamic covenant.'),
  ('seed-promise', 'The Seed Promise', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'gen'), 22, 17, 18, 'The multiplied seed promise.'),
  ('seed-promise', 'The Seed Promise', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'gal'), 3, 16, 16,
    'Not to seeds... but as of one, which is Christ.'),
  ('tabernacle', 'The Tabernacle', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'exo'), 25, 8, 9, 'Let them make me a sanctuary.'),
  ('tabernacle', 'The Tabernacle', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'exo'), 40, 34, 38, 'The glory filled the tabernacle.'),
  ('tabernacle', 'The Tabernacle', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'heb'), 8, 5, 5,
    'According to the pattern shewed to thee in the mount.'),
  ('tabernacle', 'The Tabernacle', '/study',
    (SELECT id FROM books WHERE abbreviation ILIKE 'heb'), 9, 11, 14,
    'Christ being come an high priest... by a greater tabernacle.');
