-- Calvin commentary INSERT — Zechariah (batch 2, rows 11-14)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 11, 1, NULL, 'zechariah-11', 'John Calvin', 'Commentaries', E'1. Open thy doors, O Lebanon, that the fire may devour thy cedars.

1. Aperi, Libane, protas tuas, et vorabit ignis cedros tuas:

2. Howl, fir tree; for the cedar is fallen; because the mighty are spoiled: howl, O ye oaks of Bashan; for the forest of the vintage is come down.

2. Ulula abies, quia cecidit cedrus, quia fortes (vel, praestantes) vastati sunt; ululate quercus Bashan, quia descendit (hoc est, excisa est, vel, prostrate) sylva munita.

3. There is a voice of the howling of the shepherds; for their glory is spoiled: a voice of the roaring of young lions; for the pride of Jordan is spoiled.

3. Vox ululatus pastorum, quia vastata est praestantia eorum (vel, fortitudo;) vox rugitus leonum, quia vastata est superbia Iordanis.

This Chapter contains severe threatenings, by which God designed in time to warn the Jews, that if there was any hope of repentance, they might be restored by fear to the right way, and that others, the wicked and the reprobate, might be rendered inexcusable, and also that the faithful might fortify themselves against the strong temptation to despond on seeing so dreadful a calamity awaiting that nation.

This prophecy does not indeed seem consistent with the preceding prophecies; for the Prophet has been hitherto not only encouraging the people to entertain hope, but has also declared that their condition would be so happy that nothing would be wanting to render them really blessed: but now he denounces ruin, and begins with reprobation; for he says, that God had been long the shepherd of that nation, but that now he renounced all care of them; for being wearied he would no longer bear with that perverse wickedness, which he had found in them all. These things seem to be inconsistent: but we may observe, that it was needful in the first place to set before the Jews the benefits of God, that they might with more alacrity proceed with the work of building the temple, and know that their labor would not be in vain; and now it was necessary to change the strain, lest hypocrites, vainly confiding in these promises, should become hardened, as it is commonly the case; and also, lest the faithful should not entertain due fear, and thus go heedlessly before God; for nothing is more ruinous than security, inasmuch as when a license is taken to sin, God''s judgment impends over us. We hence see how useful and reasonable was this warnings of the Prophet, as he made the Jews to understand, that God would not be propitious to his people without punishing their wickedness and obstinacy.

In order to render his prophecy impressive, Zechariah addresses Libanon; as though he was God''s herald, he bids it to open its gates, for the whole wood was now given up to the fire. Had he spoken without a figure, his denunciation would not have had so much force: he therefore denounces near ruin on Lebanon and on other places.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 12, 1, NULL, 'zechariah-12', 'John Calvin', 'Commentaries', E'1. The burden of the word of the Lord for Israel, saith the Lord, which stretcheth forth the heavens, and layeth the foundation of the earth, and formeth the spirit of man within him.

1. Onus verbi Iehovae super Israel: Dicit Iehova, qui expandit coelos, et fundavit terram, et formavit spiritum hominis in medio ejus.

The inscription seems not to agree with what follows, for he does not denounce any evil on the chosen people in this chapter, but, on the contrary, comforts the miserable, and promises that God would provide for the safety of his Church. Since then Zechariah speaks only of God''s favor and aid, he seems to have mentioned burden here improperly or unreasonably; for ms'', mesha, we know, is rightly to be taken for a threatening prophecy. It might indeed be said, that he promises that God would so deliver his Church as to teach it at the same time that it would be subject to many evils and trials: but I rather think that the Prophet''s design was different, even to show that the Israelites, who had preferred exile to God''s favor, would be punished for their sloth and ingratitude, because it was through their own fault that they were not again united in one body, and that they did not rightly worship God in their own country. Interpreters have heedlessly passed over this, as though it had nothing to do with the subject: but except this be borne in mind, what is read in this chapter will be altogether without meaning. I therefore consider that the Prophet here reproves those Israelites who had rejected what they had long desired, when it was offered to them from above and beyond all hope: for nothing was so much wished for by them as a free return to their own country; and we also see how ardently all the Prophets had prayed for restoration. As then the Israelites, given to ease, and pleasures, and their worldly advantages, had counted as nothing the permission given them to return, that they might again be gathered under God''s protection, it was a base ingratitude. Hence the Prophet here reproves them, and shows that their success would be far otherwise than they imagined.

We must also observe, that those who were dispersed in different parts, were retained by their torpidity, because they did not think that the state of the people would continue; for they saw, as they had before found, that Judea was surrounded by inveterate enemies, and also that they would not be a people sufficiently strong to repel the assaults of those around them; for they had already been accustomed to bear all things, and though they might have had some courage, they had completely lost it, having been oppressed by so long a servitude. Since then the ten tribes entertained these ideas, they did not avail themselves of the present kindness of God.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 13, 1, NULL, 'zechariah-13', 'John Calvin', 'Commentaries', E'1. In that day there shall be a fountain opened to the house of David and to the inhabitants of Jerusalem for sin and for uncleanness.

1. In die illo erit fons apertus domui Davidis, et incolis Ierosolymae, ad peccatum et ad immunditiam (vel, ad expiationem et aspersionem.)

From this verse we again learn, that Zechariah promised the spirit of repentance to the Jews, so that they would find God still propitious to them, when their circumstances were brought to the verge of despair: for it would not have been enough for them to feel sorrow, except God himself became propitious and merciful to them. He had said indeed that the Spirit of grace and of commiserations would be poured forth; but he had not as yet taught clearly what he now adds respecting remission and pardon. After having then declared that there would be felt by the Jews the bitterest sorrow, because they had as it were pierced God, he now mentions the fruit of this repentance. And hence also appears what Paul means by sorrow not to be repented of; for it generates repentance unto salvation. When then our sorrow is blessed by the Lord, the end is to be regarded; for our hearts are thereby raised up to joy. But the issue of repentance, as Zechariah declares here, is ablution: and he alludes to the legal rites when he says,

A fountain shall be opened to the house of David, and to the inhabitants of Jerusalem. We know that formerly under the law many washings were prescribed to the Jews; and when any one had become defiled, to wash himself was the remedy. It is certain that water was of no value to cleanse the heart; but the sins of men, we know, are expiated by the death of Christ, so that true ablution is by the blood which he shed for us. Hence the types of the law ought no doubt to be referred to this blood. The meaning is that God would be reconciled to the Jews when they became touched with sincere sorrow, and that reconciliation would be ready for them, for the Lord would cleanse them from every defilement.

He speaks of a fountain opened; and he no doubt intimates here a difference between the law and the gospel. Water was brought daily to the temple; but it was, we know, for private washings. But Zechariah promises here a perpetual stream of cleansing water; as though he had said, "Ablution will be free to all, when God shall again receive his people into favor." Though remission of sins was formerly offered under the law, yet it is now much more easily obtained by us; not that God grants a license to sin, but that the way in which our filth is cleansed, has become more evident since the coming of Christ.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 14, 1, NULL, 'zechariah-14', 'John Calvin', 'Commentaries', E'21. Yea, every pot in Jerusalem and in Judah shall be holiness unto the Lord of hosts: and all they that sacrifice shall come and take of them, and seethe therein: and in that day there shall be no more the Canaanite in the house of the Lord of hosts. 21. Et erit omnis lebes in Ierusalem et Iehudah sanctitas Iehovae exercituum; et venient omnes qui sacrificabunt et accipient ex ipsis et coquent in ipsis; et non erit Chamanaeus (alii vertunt non erit mercator) amplius in domo Iehovae exercituum die illo. The Prophet explains here more clearly what we have already considered -- that such would be the reverence for God, and the fear of him through the whole world, that whatever men undertook would be a sacrifice to him: he therefore says, that all the kettles, or pots, or vessels, would be sacred to God. And this is fulfilled when men regard this end -- to glorify God through their whole life, as Paul exhorts us to do. (1 Corinthians 10:31.) Our provisions and our beds, and all other things, become then holy to God, when we really devote ourselves to him, and regard in all the actions of our life the end which I have mentioned, even to testify in truth that he is our God, and that we are under his guidance. By such comparisons then does Zechariah teach us, that men will be sacred to God; for nothing they touch shall be unclean, but what was before profane shall be sanctified to his glory. Come, he says, shall they who sacrifice, and shall boil flesh in pots; as though he had said, That such would be the multitude of men who would ascend to offer sacrifices to God, that the vessels of the temple before in use would not be sufficient. It would hence be necessary to apply for that purpose what was previously profane. The language of Isaiah is similar, for he says that they who were Levites would become priests of the first order, and that those of the common people would become Levites, so that they might all come nigh to God. (Isaiah 66:20,21.) The meaning then of the Prophet is now clear -- that he wished to stir up the Jews to constancy and firmness, who regarded their small number as their reproach and were almost disheartened: as then they thought that they had in vain returned to their own country, as the Lord did not gather the whole people, he says that God''s worship would become more celebrated than at the time when the state of things was most flourishing in Judea; for assemble they would, from the whole world, to offer sacrifices to God at Jerusalem, so that the whole city, with all its utensils, would be sacred to God, for the pots and the sacred vessels of the temple, used before under the law, would not be sufficient. And he adds, And there shall be no Canaanite in the', false, false, 'sourced', 'published');
