-- Calvin commentary INSERT — Isaiah (batch 7, rows 61-66)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 61, 1, NULL, 'isaiah-61', 'John Calvin', 'Commentaries', E'1. The Spirit of the Lord Jehovah. As Christ explains this passage with reference to himself, (Luke 4:18) so commentators limit it to him without hesitation, and lay down this principle, that Christ is introduced as speaking, as if the whole passage related to him alone. The Jews laugh at this, as an illadvised application to Christ of that which is equally applicable to other prophets. My opinion is, that this chapter is added as a seal to the former, to confirm what had hitherto been said about restoring the Church of Christ; and that for this purpose Christ testifies that he has been anointed by God, in consequence of which he justly applies this prophecy to himself; for he has exhibited clearly and openly what others have laid down ill an obscure manner. But this is not inconsistent with the application of this statement to other prophets, whom the Lord has anointed; for they did not speak in their own name as individuals, or claim this authority for themselves, but were chiefly employed in pointing out the office of Christ, to whom belongs not only the publication of these things, but likewise the accomplishment of them. This chapter ought, therefore, to be understood in such a sense, that Christ, who is the Head of the prophets, holds the chief place, and alone makes all those revelations; but that Isaiah, and the other prophets, and the apostles, contribute their services to Christ, and each performs his part in making known Christ''s benefits. And thus we see that those things which Isaiah said would be accomplished by Christ, have now been actually accomplished. On that account Jehovah hath anointed me. This second clause is added in the room of exposition; for the first would have been somewhat obscure, if he had said nothing as to the purpose for which he was endued with the Spirit of God; but now it is made far more clear by pointing out the use, when he declares that. he discharges a public office, that he may not be regarded as a private individual. Whenever Scripture mentions the Spirit, and says that he "dwelleth in us," (Romans 8:11; 1 Corinthians 3:16) let us not look upon it as something empty or unmeaning, but let us contemplate his power and efficacy. Thus, after having spoken of the Spirit of God, the Prophet next mentions the "anointing," by which he means the faculties which flow from him, as Paul teaches that the gifts are indeed various, but the Spirit is one. (1 Corinthians 12:4) This passage ought to be carefully observed, for no man can claim right or authority to teach unless he show that he has been prompted to it by the Spirit of God, as Paul also affirms that "no man can call Jesus Lord, but by the Holy Ghost." (1 Corinthians 12:3) But, it will be said, we see that almost all men boast of having the Spirit of God; for the Pope, and the', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 62, 1, NULL, 'isaiah-62', 'John Calvin', 'Commentaries', E'1. On account of Zion I will not be silent. That sad captivity being at hand, which was almost to blot out the name of the whole nation, it was necessary to confirm and encourage believers by many words, that with strong and assured confidence they might rely on these promises under the burden of the cross. Here, therefore, the Prophet, discharging that office which had been entrusted to him, openly declares that he will not be slack in the performance of his duty, and will not cease to speak, till he encourage the hearts of believers by the hope of future salvation, that they may know and be fully convinced that God will be the deliverer of his Church. He too might have been dismayed by the unbelief of that people, and might have lost courage when he saw that matters were every day growing worse, and when he foresaw that terrible vengeance. But, notwithstanding so great difficulties, he will still persist in his duty, that all may know that neither the massacre of the people nor their unbelief can prevent God from executing his promises at the proper time.

And on account of Jerusalem I will not rest. It was necessary that these things should be frequently repeated, because such is the depravity of our mind that we speedily forget God''s promises. When he says that he will not cease to speak, he likewise reminds others of their duty, that they may take courage, and expect with assured confidence their restoration, though it be long delayed, and even that their unwearied attention may answer to the voice of God which constantly addresses them. We know by experience every day how necessary this is, while Satan endeavors by every method to turn us aside from the right course.

At the same time he shews what ought to be the aim of godly teachers, namely, to spend and devote themselves entirely for the advantage of the Church; for when he says "on account of Zion," he means that our chief care ought to be that the Church may be preserved, and that none are good and faithful teachers but they who hold the salvation of the Church so dear as to spare no labors. Some explain this as relating to prayer, but I choose rather to refer it to doctrine; and it is more natural to view it as meaning'' that no inconvenience or annoyance shall wear out his patience, and no opposition shall retard him from proceeding in the office of teaching which God has enjoined on him concerning the redemption of the Church. For if he had survived that very sad calamity, the unbelieving multitude would undoubtedly have persecuted him, as well as the other Prophets, by many reproaches; but whatever may happen, he says that he is fortified by unshaken firmness, never to be dumb through shame, but to proceed with unremitting eagerness in his course.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 63, 1, NULL, 'isaiah-63', 'John Calvin', 'Commentaries', E'1. Who is this that cometh from Edom? This chapter has been violently distorted by Christians, as if what is said here related to Christ, whereas the Prophet speaks simply of God himself; and they have imagined that here Christ is red, because he was wet with his own blood which he shed on the cross. But the Prophet meant nothing of that sort. The obvious meaning is, that the Lord comes forth with red garments in the view of his people, that all may know that he is their protector and avenger; for when the people were weighed down by innumerable evils, and at the same time the Edomites and other enemies, as if they had been placed beyond the reach of all danger, freely indulged in wickedness, which remained unpunished, a dangerous temptation might arise, as if these things happened by chance, or as if God did not care for his people, or chastised them too severely. If the Jews were punished for despising God, much more the Edomites, and other avowed enemies of the name of God, ought to have been punished.

The Prophet meets this very serious temptation by representing God the avenger as returning from the slaughter of the Edomites, as if he were drenched with their blood. There is great liveliness and energy in a description of this sort, Who is this? for that question raises the hearts of the hearers into a state of astonishment, and strikes them more forcibly than a plain narrative. On this account the Prophet employed it, in order to arouse the hearts of the Jews from their slumbering and stupefaction.

We know that the Edomites were somewhat related to the Jews by blood; for they were descended from the same ancestors, and derived their name from Esau, who was also called Edom. (Genesis 36:1, 8, 9.) Having corrupted the pure worship of God, though they bore the same mark of circumcision, they persecuted the Jews with deadly hatred. They likewise inflamed the rage of other enemies against the Jews, and shewed that they took great pleasure in the ruin of that people, as is evident; from the encouraging words addressed by them to its destroyers.

"Remember, O Lord, (says the Psalmist,) the children of Edom, who, in the day of the destruction of Jerusalem, said, Raze, raze it even to the foundations." (Psalm 137:7.)

The Prophet, therefore, threatens that judgment shall be passed on the Edomites, that none may imagine that they shall escape punishment for that savage cruelty with which they burned towards their brethren; for God will punish all wicked men and enemies of the Church in such a manner as to shew that the Church is the object of his care.

Beautiful in his raiment. Because spots of blood pollute and stain the conquerors, Isaiah affirms that God will nevertheless be "beautiful in his raiment," after having taken vengeance on the enemies.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 64, 1, NULL, 'isaiah-64', 'John Calvin', 'Commentaries', E'1. O that thou wouldest rend the heavens! The particle lv'' (lu) appears to me, in this passage, to denote a wish; for, although it has many significations, yet the context shews that this signification is more appropriate to this passage than any other. Here believers burst forth into earnest prayer, as usually happens, when in sore adversity we do not find plain terms to be sufficiently forcible for our purpose.

God is said to "rend the heavens," when he unexpectedly gives some uncommon and striking proof of his power; and the reason of this mode of expression is, not only that men, when they are hard pressed, commonly look up to heaven, from which they expect assistance, but that miracles, by interrupting the order of nature, open up for themselves an unusual path. Now, when God renders no assistance, he appears to be shut up in heaven, and to disregard what is taking place on earth. For this reason he is said to open and "rend the heavens," when he holds out to us some testimony of his presence; because otherwise we think that he is at a great distance from us.

That thou wouldest come down. This expression, like the former, is adapted to the estimation of our flesh; for God does not need to move from one place to another, but accommodates himself to us, that we may understand those subjects better. (Genesis 11:5; 18:21.)

Let the mountains flow down. That is,

"Let thy majesty be openly displayed, and let the elements, struck by the perception of it, yield and obey." (Psalm 18:11.)

This will appear more plainly from what immediately follows.

2. As by the burning of a melting fire, the fire hath made the water to boil. All this might be read either in the future or in the subjunctive; as if he had said, "O Lord, if thou camest down, the nations would tremble at thy presence; thine enemies would instantly be melted away." But I think that the translation which I have given is more simple; for it is very certain that the Prophet here alludes to Mount Sinai, where the Lord openly revealed himself to the people. Hence we see also the gross absurdity of the division of this chapter; since those events are related in support of that prayer which ought rather to have been placed at the beginning of the chapter.

We have formerly seen that the prophets, when they relate that God assisted his people, bring forward an instance in the history of redemption. Whenever therefore the prophets mention this history, they include all the benefits that were ever bestowed by God on his people; not only when he delivered them from the tyranny of Pharaoh, when he appeared to them in Mount Sinai, but also when, during forty years, he supplied them with all that was necessary in the wilderness, when he drove out their enemies, and led them into the possession of the land of Canaan.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 65, 1, NULL, 'isaiah-65', 'John Calvin', 'Commentaries', E'1. I have manifested myself. The Prophet now passes on to another doctrine; for he shews that God has good reason for rejecting and casting off the Jews. It is because they have profited nothing by either warnings or threatenings to be brought back from their errors into the right way. But that they might not think that the Lord''s covenant would on that account be made void, he adds that he will have another people which formerly was no people, and that where he was formerly unknown, his name Shall be well known and highly celebrated. The Jews looked on this as monstrous, and reckoned it to be altogether inconsistent with the covenant which the Lord made with Abraham, (Genesis 17:7,) if such a benefit were extended to any others than his posterity. But the Prophet intended to strip them of the foolish confidence of imagining that God was bound to the posterity of Abraham; for the Lord had not restricted himself to them but on an absolute condition, and if this were violated by them, they would be deprived, like covenant-breakers and traitors, of all the advantage derived from the covenant. Nor was this promise made to Abraham alone, and to those who were descended from him, but to all who should be ingrafted by faith into his family. But it will be more convenient to begin with the second verse, in which he explains the cause of the rejection, that we may more fully understand the Prophet''s design.

2. I have stretched out my hands. He accuses the Jews, and complains of their ingratitude and rebellion; and in this manner he proves that there is no reason why they should say that the Lord does them wrong if he bestow his grace on others. The Jews conducted themselves proudly and insolently toward God, as if they had been elected through their own merit. On account of their ingratitude and insolence the Lord rejects them as unworthy, and complains that to no purpose did he "stretch out his hands" to draw and bring them back to him.

By "the stretching out of the hands" he means the daily invitation. There are various ways in which the Lord "stretches out his hands to us;" for he draws us to him, either effectually or by the word. In this passage it must relate chiefly to the word. The Lord never speaks to us without at the same time "stretching out his hand" to join us to himself, or without causing us to feel, on the other hand, that he is near to us. He even embraces us, and shews the anxiety of a father, so that, if we do not comply with his invitation, it must be owing entirely to our own fault.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 66, 1, NULL, 'isaiah-66', 'John Calvin', 'Commentaries', E'1. This saith Jehovah. This discourse is different from the preceding one; for here the Prophet exclaims against the Jews, who, puffed up with vain confidence in the sacrifices and the temple, indulged freely in their pleasures, and flattered themselves in their sins under this pretense. He shews that this confidence is not only foolish and groundless, but diabolical and accursed; for they grossly mock God who endeavor to serve and appease him by outward ceremonies. Accordingly, he reproaches them with endeavoring to frame an idol in place of God, when they shut him up in the temple. Next, he speaks of the renovation of the Church, and of the extension of it throughout the whole world. Heaven is my throne. His aim being to shake off the self-complancency of the pretended or hypocritical worshippers of God, he begins with his nature. By assigning "heaven" for his habitation, he means that the majesty of God fills all things, and is everywhere diffused; and that he is so far from being shut up in the temple, that he is not shut up or confined within any place whatever. The Scripture often teaches that God is in heaven; not that he is shut up in it, but in order that we may raise our minds above the world, and may not entertain any low, or carnal, or earthly conceptions of him; for the mere sight of heaven ought to carry us higher, and transport us into admiration. And yet, in innumerable passages, he protests that he is with us, that his power is everywhere diffused, in order that we may not imagine that he is shut up in heaven. It may be thought that this is beyond all controversy, and was at that time acknowledged by all; for who did not know that heaven and earth are filled by the majesty of God? They might therefore object that there is no man who wishes to thrust God out of heaven, and that the Prophet has no good reason for waxing wroth and breaking out into such violent invective. And undoubtedly they rejected with great haughtiness this doctrine of the Prophet, and were highly irritated and enraged, as if great injury had been done to them. But it is easy to reply that, when men endeavor to appease God according to their own fancy, they frame an idol that is altogether contrary to his majesty, Relying on their useless ceremonies, they thought that they had performed their duty well when they went frequently to the temple, and offered in it prayers and sacrifices. The Prophet shews that the majesty of God must not be measured by this standard, and that all that they bring forward, unaccompanied by purity of heart, are absolute trifles; for since it is evident from his dwelling-place being in heaven that the nature of God is spiritual, if the worship do not correspond to that nature, it is undoubtedly wicked and corrupted. Where is that house which ye will', false, false, 'sourced', 'published');
