-- Calvin commentary INSERT — Matthew (batch 3, rows 21-28)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 21, 1, NULL, 'matthew-21', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 22, 1, NULL, 'matthew-22', 'John Calvin', 'Commentaries', E'1. And Jesus answering, spoke again by parables, and said, 2. The kingdom of heaven is like a human king who made a marriage for his son, 3. And sent out his servants to call those who were invited to the marriage, and they refused to come. 4. Again he sent out other servants, saying, Tell those who are invited, Lo, I have prepared my dinner, my oxen and fatlings are killed, and all things are ready: come to the marriage. 5. But they treated it with indifference, and went away, one to his farm, and another to his merchandise: 6. And the rest took his servants, and abused and killed them. 7. But when the king heard it, he was angry, and sent his soldiers, and slew these murderers, and burnt up their city. 8. Then he said to his servants, The marriage is indeed ready, but those who were invited were not worthy. 9. Go then to the highways, and whomsoever you shall find invite to the marriage. 10. And his servants went out to the roads, and collected all that they found, both bad and good, so that the marriage-apartment was filled with guests. 11. And the king, having come in to see the guests, when he saw there a man not wearing the wedding garment, 12. Said to him, Friend, how camest thou hither, not having the wedding garment? And he was speechless. 13. Then said the king to his attendants, Bind him hand and foot, and cast him into outer darkness: weeping and gnashing of teeth will be there. 14. For many are called, but few are chosen.

15. And when one of those who sat at table with him heard these things, he said to him, Blessed is he that eateth bread in the kingdom of God. 16. But he said to him, A certain man had prepared a great supper, and had invited many. 17. And he sent his servant at the hour of supper to say to those who were invited, Come; for all things are now ready. 18. And they all began together to excuse themselves. 19. The first said to him, I have purchased an estate, and I must go and see it: I beseech thee hold me excused. 20. And another said, I have married a wife, and therefore I cannot come. 21. And the servant returned, and brought back these things to his master. Then the master of the house, being angry, said to his servant, Go out quickly into the streets and lanes of the city, and bring in hither the poor, and the maimed, and the lame, and the blind. 22. And the servant said, Sir, it is done as thou hast commanded, and still there is room. 23. And the master said to the servant, Go out to the roads and hedges, and compel them to come in, that my house may be filled. 24.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 23, 1, NULL, 'matthew-23', 'John Calvin', 'Commentaries', E'1. Then Jesus spoke to the multitude, and to his disciples, 2. Saying, The scribes and the Pharisees sit in the chair of Moses. 3. Observe and do, therefore, all things whatever they command you to observe; but do not according to their works; for they say and do not. 4. For they bind heavy and intolerable burdens, and lay them on men''s shoulders; but they refuse to touch them with their finger. 5. And they do all their works that they may be seen by men, and make their phylacteries broad, and wear large fringes on their robes, 6. And love the first places at entertainments, and the first seats in the synagogues, 7. And salutations in the marketplace, and to be called by men Rabbi. 8. But as for you, be not called Rabbi; for there is one who is your Master, Christ; and you are all brethren. 9. And do not call any one on earth your Father; for one is your Father, who is in heaven. 10. And be not called Masters; for one is your Master, Christ. 11. He who is greatest among you shall be your servant. 12. But he that exalteth himself shall be humbled; and he that humbleth himself shall be exalted.

38. And he said to them in his doctrine, Beware of the scribes, who love to walk in robes, and love salutations in the marketplaces, 39. And the first seats in the synagogues, and the first places at entertainments.

45. And one of the lawyers answering said to him, Master, in saying these things thou also reproachest us. 46. And he said, Woe also to you, lawyers! for you load men with burdens which are intolerable; and you yourselves touch not the burdens with one of your fingers. (A little before.)

45. And while all the people were hearing, he said to his disciples, 46. Beware of the scribes, who desire to walk in robes, and love salutations in the marketplaces and the first seats in the synagogues, and the first places at entertainments.

Matthew 23:1. Then Jesus spoke to the multitudes. This warning was highly useful, that, amidst contentions and the noise of combats, amidst the trouble and confusion of public affairs, amidst the destruction of proper and lawful order, the authority of the word of God might remain entire. The design of Christ was, that the people might not, in consequence of being offended at the vices of the scribes, throw away reverence for the Law. For we know how prone the minds of men are to entertain dislike of the Law; and more especially when the life of their pastors is dissolute, and does not correspond to their words, almost all grow wanton through their example, as if they had received permission to sin with impunity.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 24, 1, NULL, 'matthew-24', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 25, 1, NULL, 'matthew-25', 'John Calvin', 'Commentaries', E'14. For as a certain man, setting out on a journey, called his servants, and delivered to them his goods. 15. And to one he gave five talents, and to another two, and to another one; to every one according to his own ability; and immediately set out. 16. And he who had received five talents went away and traded with them, and amassed other five talents. 17. And likewise he who had received two, he also gained other two. 18. But he who had received one went away, and dug in the earth, and hid his master''s money. 19. And after a long time the master of those servant cometh, and reckoneth with them. 20. And he who had received five talents, saying, Master, thou deliveredst to me five talents: lo, I have gained by them other five talents. 21. His master saith to him, Well done, good and faithful servant; thou has tbeen faithful over a few things, I will place thee over many things: enter thou into the joy of thy master. 22. And he also who had received two talents came, and said, Master, thou deliveredst to me two talents: lo, I have gained by them other two. 23. His master saith to him, Well done, good and faithful servant; thou hast been faithful over a few things: enter thou into the joy of thy master. 24. But he who had received one talent came and said, Master, knew thee that thou art a harsh man, reaping where thou didst not sow, and gathering where didst not scatter: 25. And, being afraid, I went away, and hid thy talent in the earth: lo, thou hast what is thine. 26. And his master answering said to him, Wicked and slothful servant, thou knowest that I reap where I sowed not, and gather where I did not scatter: 27. Thou oughtest therefore to have given my money to the bankers, and, when I came, I would have received my own with usury. 28. Take away then from him the talent, and give it to him who hath ten talents. 29. For to every one that hath shall be given, and he shall abound; but he that hath not, even that which he hath shall be taken from him. 30. And cast out the unprofitable servant into outer darkness, where shall be weeping and gnashing of teeth.

11. While they were hearing these things, he added, and spoke a parable, because he was near Jerusalem, and because they thought that the kingdom of God would immediately be revealed. 12. He said therefore, A certain nobleman set out for a distant country, to receive for himself a kingdom, and to return. 13. And, having called his ten servants, he gave to them ten pounds, and said to them, Trade till I come. 14. And his citizens hated him, and sent a message after him, saying, We will not have this man to reign over us. 15.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 26, 1, NULL, 'matthew-26', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 27, 1, NULL, 'matthew-27', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 28, 1, NULL, 'matthew-28', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published');
