-- Calvin commentary INSERT — 1 Thessalonians (batch 1, rows 1-5)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 52, 1, 1, NULL, '1-thessalonians-1', 'John Calvin', 'Commentaries', E'2 We give thanks to God. He praises, as he is wont, their faith and other virtues, not so much, however, for the purpose of praising them, as to exhort them to perseverance. For it is no small excitement to eagerness of pursuit, when we reflect that God has adorned us with signal endowments, that he may finish what he has begun, and that we have, under his guidance and direction, advanced in the right course, in order that we may reach the goal. For as a vain confidence in those virtues, which mankind foolishly arrogate to themselves, puffs them up with pride, and makes them careless and indolent for the time to come, so a recognition of the gifts of God humbles pious minds, and stirs them up to anxious concern. Hence, instead of congratulations, he makes use of thanksgivings, that he may put them in mind, that everything in them that he declares to be worthy of praise, is a kindness from God. He also turns immediately to the future, in making mention of his prayers. We thus see for what purpose he commends their previous life.

3 Unceasingly remembering you. While the adverb unceasingly might be taken in connection with what goes before, it suits better to connect it in this manner. What follows might also be rendered in this way: Remembering your work of faith and labor of love, etc. Nor is it any objection to this that there is an article interposed between the pronoun humon and the noun ergou, for this manner of expression is frequently made use of by Paul. I state this, lest any one should charge the old translator with ignorance, from his rendering it in this manner. As, however, it matters little as to the main point which you may choose, I have retained the rendering of Erasmus.

He assigns a reason, however, why he cherishes so strong an affection towards them, and prays diligently in their behalf -- because he perceived in them those gifts of God which should stir him up to cherish towards them love and respect. And, unquestionably, the more that any one excels in piety and other excellences, so much the more ought we to hold him in regard and esteem. For what is more worthy of love than God? Hence there is nothing that should tend more to excite our love to individuals, than when the Lord manifests himself in them by the gifts of his Spirit. This is the highest commendation of all among the pious -- this the most sacred bond of connection, by which they are more especially bound to each other. I have said, accordingly, that it is of little importance, whether you render it mindful of your faith, or mindful of you on account of your faith.

Work of faith I understand as meaning the effect of it.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 52, 2, 1, NULL, '1-thessalonians-2', 'John Calvin', 'Commentaries', E'3 For our exhortation. He confirms, by another argument, the Thessalonians in the faith which they had embraced -- inasmuch as they had been faithfully and purely instructed in the word of the Lord, for he maintains that his doctrine was free from all deception and uncleanness. And with the view of placing this matter beyond all doubt, he calls their conscience to witness. The three terms which he makes use of may, it would seem, be distinguished in this manner: imposture may refer to the substance of doctrine, uncleanness to the affections of the heart, guile to the manner of acting. In the first place, therefore, he says that they had not been deluded or imposed upon by fallacies, when they embraced the kind of doctrine that had been delivered to them by him. Secondly, he declares his integrity, inasmuch as he had not come to them under the influence of any impure desire, but actuated solely by upright disposition. Thirdly, he says that he had done nothing fraudulently or maliciously, but had, on the contrary, manifested a simplicity befitting a minister of Christ. As these things were well known to the Thessalonians, they had a sufficiently firm foundation for their faith.

4 As we have been approved. He goes even a step higher, for he appeals to God as the Author of his apostleship, and he reasons in this manner: "God, when he assigned me this office, bore witness to me as a faithful servant; there is no reason, therefore, why men should have doubts as to my fidelity, which they know to have been approved of by God. Paul, however, does not glory in having been approved of, as though he were such of himself; for he does not dispute here as to what he had by nature, nor does he place his own power in collision with the grace of God, but simply says that the Gospel had been committed to him as a faithful and approved servant. Now, God approves of those whom he has formed for himself according to his own pleasure.

Not as pleasing men. What is meant by pleasing men has been explained in the Epistle to the Galatians, (Galatians 1:10) and this passage, also, shews it admirably. For Paul contrasts pleasing men, and pleasing God, as things that are opposed to each other. Farther, when he says -- God, who trieth our hearts, he intimates, that those who endeavor to obtain the favor of men, are not influenced by an upright conscience, and do nothing from the heart. Let us know, therefore, that true ministers of the gospel ought to make it their aim to devote to God their endeavors, and to do it from the heart, not from any outward regard to the world, but because conscience tells them that it is right and proper.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 52, 3, 1, NULL, '1-thessalonians-3', 'John Calvin', 'Commentaries', E'1 Wherefore, when we could no longer endure. By the detail which follows, he assures them of the desire of which he had spoken. For if, on being detained elsewhere, he had sent no other to Thessalonica in his place, it might have seemed as though he were not so much concerned in regard to them; but when he substitutes Timothy in his place, he removes that suspicion, more especially when he prefers them before himself. Now that he esteemed them above himself, he shews from this, that he chose rather to be left alone than that they should be deserted: for these words, we judged it good to be left alone, are emphatic. Timothy was a most faithful companion to him: he had at that time no others with him; hence it was inconvenient and distressing for him to be without him. It is therefore a token of rare affection and anxious desire that he does not refuse to deprive himself of all comfort, with the view of relieving the Thessalonians. To the same effect is the word eudokesamen, which expresses a prompt inclination of the mind.

2 Our brother. He assigns to him these marks of commendation, that he may shew the more clearly how much inclined he was to consult their welfare: for if he had sent them some common person, it could not have afforded them much assistance; and inasmuch as Paul would have done this without inconvenience to himself, he would have given no remarkable proof of his fatherly concern in regard to them. It is, on the other hand, a great thing that he deprives himself of a brother and fellow-laborer, and one to whom, as he declares in Philippians 2:20, he found no equal, inasmuch as all aimed at the promotion of their own interests. In the mean time, he procures authority for the doctrine which they had received from Timothy, that it may remain the more deeply impressed upon their memory.

It is, however, with good reason that he says that he had sent Timothy with this view -- that they might receive a confirmation of their faith from his example. They might be intimidated by unpleasant reports as to persecutions; but Paul''s undaunted constancy was fitted so much the more to animate them, so as to keep them from giving way. And, assuredly, the fellowship which ought to subsist between the saints and members of Christ extends even thus far -- that the faith of one is the consolation of others. Thus, when the Thessalonians heard that Paul was going on with indefatigable zeal, and was by strength of faith surmounting all dangers and all difficulties, and that his faith continued everywhere victorious against Satan and the world, this brought them no small consolation. More especially we are, or at least ought to be, stimulated by the examples of those by whom we were instructed in the faith, as is stated in the end of the Epistle to the Hebrews.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 52, 4, 1, NULL, '1-thessalonians-4', 'John Calvin', 'Commentaries', E'1 Furthermore. This chapter contains various injunctions, by which he trains up the Thessalonians to a holy life, or confirms them in the exercise of it. They had previously learned what was the rule and method of a pious life: he calls this to their remembrance. As, says he, ye have been taught. Lest, however, he should seem to take away from them what he had previously assigned them, he does not simply exhort them to walk in such a manner, but to abound more and more. When, therefore, he urges them to make progress, he intimates that they are already in the way. The sum is this, that they should be more especially careful to make progress in the doctrine which they had received, and this Paul places in contrast with frivolous and vain pursuits, in which we see that a good part of the world very generally busy themselves, so that profitable and holy meditation as to the due regulation of life scarcely obtains a place, even the most inferior. Paul, accordingly, reminds them in what manner they had been instructed, and bids them aim at this with their whole might. Now, there is a law that is here enjoined upon us -- that, forgetting the things that are behind, we always aim at farther progress, (Philippians 3:13) and pastors ought also to make this their endeavor. Now, as to his beseeching, when he might rightfully enjoin -- it is a token of humanity and modesty which pastors ought to imitate, that they may, if possible, allure people to kindness, rather than violently compel them. 3 For this is the will of God. This is doctrine of a general nature, from which, as from a fountain, he immediately deduces special admonitions. When he says that this is the will of God, he means that we have been called by God with this design. "For this end ye are Christians -- this the gospel aims at -- that ye may sanctify yourselves to God." The meaning of the term sanctification we have already explained elsewhere in repeated instances -- that renouncing the world, and clearing ourselves from the pollutions of the flesh, we offer ourselves to God as if in sacrifice, for nothing can with propriety be offered to Him, but what is pure and holy. That ye abstain. This is one injunction, which he derives from the fountain of which he had immediately before made mention; for nothing is more opposed to holiness than the defilement of fornication, which pollutes the whole man. On this account he assigns the lust of concupiscence to the Gentiles, who know not God. "Where the knowledge of God reigns, lusts must be subdued." By the lust of concupiscence, he means all base lusts of the flesh, but, at the same time, by this manner of expression, he brands with dishonor all desires that allure us to pleasure and carnal delights, as in Romans 13:14, he bids us have no care for the', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 52, 5, 1, NULL, '1-thessalonians-5', 'John Calvin', 'Commentaries', E'1 But as to times. He now, in the third place, calls them back from a curious and unprofitable inquiry as to times, but in the mean time admonishes them to be constantly in a state of preparation for receiving Christ. He speaks, however, by way of anticipation, saying, that they have no need that he should write as to those things which the curious desire to know. For it is an evidence of excessive incredulity not to believe what the Lord foretells, unless he marks out the day by certain circumstances, and as it were points it out with the finger. As, therefore, those waver between doubtful opinions who require that moments of time should be marked out for them, as if they would draw a conjecture from some plausible demonstration, he accordingly says that discussions of this nature are not necessary for the pious. There is also another reason -- that believers do not desire to know more than they are permitted to learn in God''s school. Now Christ designed that the day of his coming should be hid from us, that, being in suspense, we might be as it were upon watch.

2 Ye know perfectly. He places exact knowledge in contrast with an anxious desire of investigation. But what is it that he says the Thessalonians know accurately? It is, that the day of Christ will come suddenly and unexpectedly, so as to take unbelievers by surprise, as a thief does those that are asleep. This, however, is opposed to evident tokens, which might portend afar off his coming to the world. Hence it were foolish to wish to determine the time precisely from presages or prodigies.

3 For when they shall say. Here we have an explanation of the similitude, the day of the Lord will be like a thief in the night. Why so? because it will come suddenly to unbelievers, when not looked for, so that it will take them by surprise, as though they were asleep. But whence comes that sleep? Assuredly from deep contempt of God. The prophets frequently reprove the wicked on account of this supine negligence, and assuredly they await in a spirit of carelessness not merely that last judgment, but also such as are of daily occurrence. Though the Lord threatens destruction, they do not hesitate to promise themselves peace and every kind of prosperity. And the reason why they fall into this destructive indolence is, because they do not see those things immediately accomplished, which the Lord declares will take place, for they reckon that to be fabulous that does not immediately present itself before their eyes. For this reason the Lord, in order that he may avenge this carelessness, which is full of obstinacy, comes all on a sudden, and contrary to the expectation of all, precipitates the wicked from the summit of felicity.', false, false, 'sourced', 'published');
