-- Calvin commentary INSERT — Hosea (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 1, 1, NULL, 'hosea-1', 'John Calvin', 'Commentaries', E'1. The word of the LORD that came unto Hosea-- the son of Beeri-- in the days of Uzziah-- Jotham-- Ahaz-- and Hezekiah-- kings of Judah-- and in the days of Jeroboam the son of Joash-- king of Israel.

1. Sermo Jehovae-- qui fuit ad Hoseam filium Beri-- diebus Uzia-- Jotham-- Achaz-- Ezechiae-- regum Jehuda-- et diebus Jarobeam filii Joas regis Israel.

This first verse shows the time in which Hosea prophesied. He names four kings of Judah, -- Uzziah, Jotham, Ahab, Hezekiah. Uzziah, called also Azariah, reigned fifty-two years; but after having been smitten with leprosy, he did not associate with men, and abdicated his royal dignity. Jotham, his son, succeeded him. The years of Jotham were about sixteen, and about as many were those of king Ahab, the father of Hezekiah; and it was under king Hezekiah that Hosea died. If we now wish to ascertain how long he discharged his office of teaching, we must take notice of what sacred history says, -- Uzziah began to reign in the twenty seventh year of Jeroboam, the son of Joash. By supposing that Hosea performed his duties as a teacher, excepting a few years during the reign of Jeroboam, that is, the sixteen years which passed from the beginning of Uzziah''s reign to the death of Jeroboam, he must have prophesied thirty-six years under the reign of Uzziah. There is, however, no doubt but that he began to execute his office some years before the end of Jeroboam''s reign.

Here, then, there appear to be at least forty years. Jotham succeeded his father, and reigned sixteen years; and though it be a probable conjecture, that the beginning of his reign is to be counted from the time he undertook the government, after his father, being smitten with leprosy, was ejected from the society of men, it is yet probable that the remaining time to the death of his father ought to come to our reckoning. When however, we take for granted a few years, it must be that Hosea had prophesied more than forty-five years before Ahab began to reign. Add now the sixteen years in which Ahab reigned and the number will amount to sixty-one. There remain the years in which he prophesied under the reign of Hezekiah. It cannot, then, be otherwise but that he had followed his office more than sixty years, and probably continued beyond the seventieth year.

It hence appears with how great and with how invincible courage and perseverance he was endued by the Holy Spirit. But when God employs our service for twenty or thirty years we think it very wearisome, especially when we have to contend with wicked men, and those who do not willingly undertake the yoke, but pertinaciously resist us; we then instantly desire to be set free, and wish to become like soldiers who have completed their time.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 2, 1, NULL, 'hosea-2', 'John Calvin', 'Commentaries', E'1. Say ye unto your brethren, Ammi; and to your sisters, Ruhamah.

1. Dicite fratribus vestris-- Populus meus; et sororibus vestris-- Dilecta.

The Prophet having spoken of the people''s restoration, and promised that God would some time receive into favour those whom he had before rejected, now exhorts the faithful mutually to stir up one another to receive this favour. He had previously mentioned a public proclamation; for it is not in the power of men to make themselves the children of God, but God himself freely adopts them. But now the mutual exhortation of which the Prophet speaks follows the proclamation; for God at the same time invites us to himself. After we are taught in common, it remains then that each one should extend his hand to his brethren, that we may thus with one consent be brought together to the Lord.

This then is what the Prophet means by saying, Say ye to your brethren, my omi, and to your sisters rvchmh ruchamah; that is, since I have promised to be propitious to you, you can now safely testify this to one another. We then see that this discourse is addressed to each of the faithful, that they may mutually confirm themselves in the faith, after the Lord shall offer them favour and reconciliation. Let us now proceed -- __________________________________________________________________

2. Plead with your mother, plead: for she is not my wife, neither am I her husband: let her therefore put away her whoredoms out of her sight, and her adulteries from between her breasts;

2. Litigate cum matre vestra-- litigate; quia ipsa non uxor mea-- et ego non maritus ejus: et tollat (hoc est-- tollat igitur) scortationes suas e facie sua-- et adulteria sua e medio uberum suorum.

The Prophet seems in this verse to contradict himself; for he promised reconciliation, and now he speaks of a new repudiation. These things do not seem to agree well together that God should embrace, or be willing to embrace, again in his love those whom he had before rejected, -- and that he should at the same time send a bill of divorce, and renounce the bond of marriage. But if we weigh the design of the Prophet, we shall see that the passage is very consistent, and that there is in the words no contrariety. He has indeed promised that at a future time God would be propitious to the Israelites: but as they had not yet repented, it was needful to deal again more severely with them, that they might return to their God really and thoroughly subdued. So we see that in Scripture, promises and threatening are mingled together, and rightly too. For were the Lord to spend a whole month in reproving sinners they may in that time fall away a hundred times.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 3, 1, NULL, 'hosea-3', 'John Calvin', 'Commentaries', E'1. Then said the LORD unto me, Go yet, love a woman beloved of her friend, yet an adulteress, according to the love of the LORD toward the children of Israel, who look to other gods, and love flagons of wine.

1. Et dixit jehova ad me, Adhuc vade, ama mulierem dilectum a marito (ad verbum, a proximo, vel, socio: sed intelligit comparem) et quae adultera est (sed copula debet resolvi in adversativam, quae tamen adultera est,) secundum amorem Jehovae erga filios Israel: et ipsi (hoc est, quitamen) respiciunt ad deos alienos, et amant lagenas (vel, cados) uvarum.

The substance of this chapter is, that it was God''s purpose to keep in firm hope the minds of the faithful during the exile, lest being overwhelmed with despair they should wholly faint. The Prophet had before spoken of God''s reconciliation with his people; and he magnificently extolled that favor when he said, Ye shall be as in the valley of Achor, I will restore to you the abundance of all blessings; in a word, ye shall be in all respects happy.'' But, in the meantime, the daily misery of the people continued. God had indeed determined to remove them into Babylon. They might, therefore, have despaired under that calamity, as though every hope of deliverance were wholly taken from them. Hence the Prophet now shows that God would so restore the people to favor, as not immediately to blot out every remembrance of his wrath, but that his purpose was to continue for a time some measure of his severity.

We hence see that this prediction occupies a middle place between the denunciation the Prophet previously pronounced and the promise of pardon. It was a dreadful thing, that God should divorce his people and cast away the Israelites as spurious children: but a consolation was afterwards added. But lest the Israelites should think that God would immediately, as on the first day, be so propitious to them as to visit them with no chastisement, it was the Prophet''s design expressly to correct this mistake, as though he said, God will indeed receive you again, but in the meantime a chastisement is prepared for you, which by its intenseness would break down your spirits were it not that this comfort will ease you, and that is, that God, though he punishes you for your sins, yet continues to provide for your salvation, and to be as it were your husband.'' We now perceive the intention of the Prophet. But I shall first run over the words, and then return to the subject

Jehovah said to me, Go yet and love a woman. There is no doubt but that God describes here the favor he promises to the Israelites in a type or vision: for they are too gross in their notions, who think that the Prophet married a woman who had been a harlot.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 4, 1, NULL, 'hosea-4', 'John Calvin', 'Commentaries', E'1. Hear the word of the LORD, ye children of Israel: for the LORD hath a controversy with the inhabitants of the land, because there is no truth, nor mercy, nor knowledge of God in the land.

1. Audite verbum Jehova, filii Israel, quia lis Jehovae cum incolis terrae; quia nulla fides, (aut, veritas, nulla fidelitas,) et nulla beneficientia, etnulla cognito Dei in terra.

2. By swearing, and lying, and killing, and stealing, and committing adultery, they break out, and blood toucheth blood.

2. Maledicere, et mentiri, et occidere, et furari, et adulterium committere perruperunt, et sanguines sanguinibus fuerunt continui.

This is a new discourse by the Prophet, separate from his former discourses. We must bear in mind that the Prophets did not literally write what they delivered to the people, nor did they treat only once of those things which are now extant with us; but we have in their books collected summaries and heads of those matters which they were wont to address to the people. Hosea, no doubt, very often descanted on the exile and the restoration of the people, forasmuch as he dwelt much on all the things which we have hitherto noticed. Indeed, the slowness and dullness of the people were such, that the same things were repeated daily. But it was enough for the Prophets to make and to write down a brief summary of what they taught in their discourses.

Hosea now relates how vehemently he reproved the people, because every kind of corruption so commonly prevailed, that there was no sound part in the whole community. We hence see what the Prophet treats of now; and this ought to be observed, for hypocrites wish ever to be flattered; and when the mercy of God is offered to them, they seek to be freed from every fear. It is therefore a bitter thing to them, when threatening are mingled, when God sharply chides them. "What! we heard yesterday a discourse on God''s mercy, and now he fulminates against us. He is then changeable; if he were consistent, would not his manner of teaching be alike and the same today?" But men must be often awakened, for forgetfulness of God often creeps over them; they indulge themselves, and nothing is more difficult than to lead them to God; nay, when they have made some advances, they soon turn aside to some other course.

We hence see that men cannot be taught, except God reproves their sins by his word; and then, lest they despond, gives them a hope of mercy; and except he again returns to reproofs and threatening. This is the mode of address which we find in all the Prophets.

I now come to the Prophet''s words: Hear, he says, the word of Jehovah, ye children of Israel, the Lord has a dispute, etc.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 5, 1, NULL, 'hosea-5', 'John Calvin', 'Commentaries', E'1. Hear ye this, O priests; and hearken, ye house of Israel; and give ye ear, O house of the king; for judgment is toward you, because ye have been a snare on Mizpah, and a net spread upon Tabor.

1. Audite hoc sacerdotes, et attendite domus, et domus regis auscultate, quia vobis judicam (hoc est, judicium in vos dirigitur) nam laqueus fuistis (hoc est, tanquam laqueus, sabaudienda est k, nota similitudinis et addenda ad nomen phch, fuistis ergo tanquam laques) in Mizpah, et rete expansum super Tabor.

The Prophet here again preaches against the whole people: but he mainly directs his discourse to the priests and the rulers; for they were the source of the prevailing evils: the priests, intent on gain, neglected the worship of God; and the chief men, as we have seen, were become in every way corrupt. Hence the Prophet here especially inveighs against these orders, and at the same time, records some vices which then prevailed among the people, and that through the fault of the priests and rulers. But before I pursue farther the subject of the Prophets something must be said of the words.

When he says, To you is judgment, some explain it, "It is your duty to do judgment," to maintain government, that every one may discharge his own office; for judgment is taken for rectitude; the word mspht, mesgepheth, means a right order of things. Hence they think that the priests and rulers are here condemned for discharging so badly their office, because they had no care for what was right. But this sense is too strained. The Prophet, therefore, I doubt not, summons here the priests and the king''s counselors to God''s tribunal, that they might give an answer there; for the contempt of God, we know, prevailed among the great; they were secure, as though exempt from judgment, as though released from laws and all order. To you, then is judgment; that is, God addresses you by name, and declares that he will be your avenger, though ye heedlessly despise his judgment.

Some again take mtsphh, metsephe, for a beacon, and thus translate, "Ye have been a snare instead of a beacon." But this mistake is refuted by the second clause, for the Prophet adds immediately, a net expanded over Tabor: and it is well known that Mizpah and Tabor were high mountains, and for their height celebrated and renowned; we also know that hunting was common on these mountains. The Prophet, then, no doubt means here, that both the priests and the king''s counselors were like snares and nets: "As fowlers and hunters were wont to spread their nets and snares on mount Mizpah and on Tabor; so the people also have been ensnared by you." This is the plain meaning of the words.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 6, 1, NULL, 'hosea-6', 'John Calvin', 'Commentaries', E'1. Come, and let us return unto the Lord: for he hath torn, and he will heal us; he hath smitten, and he will bind us up. 1. Venite et convertamur ad Jehovam, quia ipse rapuit et sanabit nos; percussit et alligabit plagas nostras. In the last chapter the Prophet said, that the Israelites, after having been subdued by chastisements and judgments, would again turn back from following error to seek God. But as terror drives men away from approaching God, he now adds, that the measure of afflictions would not be such as would discourage their minds and produce despair; but rather inspire them with the assurance, that God would be propitious to them: and that he might set this forth the better, he introduces them as saying, Come, let us go to the Lord: and this mode of speaking is very emphatical. But we must know that the reason here given, why the Israelites could return safely and with sure confidence to God, is, that they would acknowledge it as his office to heal after he has smitten, and to bring a remedy for the wounds which he has inflicted. The Prophet means by these words, that God does not so punish men as to pour forth his wrath upon them for their destruction; but that he intends, on the contrary, to promote their salvation, when he is severe in punishing their sins. We must then remember, as we have before observed, that the beginning of repentance is a sense of God''s mercy; that is, when men are persuaded that God is ready to give pardon, they then begin to gather courage to repent; otherwise perverseness will ever increase in them; how much soever their sin may frighten them, they will yet never return to the Lord. And for this purpose I have elsewhere quoted that remarkable passage in Psalm 130, With thee is mercy, that thou mayest be feared;'' for it cannot be, that men will obey God with true and sincere heart, except a taste of his goodness allures them, and they can certainly determine, that they shall not return to him in vain, but that he will be ready, as we have said, to pardon them. This is the meaning of the words, when he says, Come, and let us turn to the Lord; for he has torn and he will heal us; that is, God has not inflicted on us deadly wounds; but he has smitten, that he might heal. At the same time, something more is expressed in the Prophet''s words, and it is this, that God never so rigidly deals with men, but that he ever leaves room for his grace. For by the word, torn, the Prophet alludes to that heavy judgment of which he had before spoken in the person of God: the Lord then made himself to be like a cruel wild beast, "I will be as a lion, I will devour, I will tear, and no one shall', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 7, 1, NULL, 'hosea-7', 'John Calvin', 'Commentaries', E'1. When I would have healed Israel, then the iniquity of Ephraim was discovered, and the wickedness of Samaria: for they commit falsehood; and the thief cometh in, and the troop of robbers spoileth without. 1. Dum medeor Israel, tunc retecta fuit iniquitas Ephraim et malitiae Samariae, quia gesserunt se mendaciter (vel, fallaciter; ad verbum, fecerunt fellaciam;) et fur ingressus est, spoliavit praedo foris. God, that he might show how corrupt was the state of all the people of Israel, compares himself here to a physician, who, while he wishes to try remedies, acknowledges that there are hid more grievous diseases; which is often the case. When a sick person sends for a physician, his disease will be soon discovered; but it may be that he has for many years labored under other hidden complaints, which do not immediately come to the knowledge of the physician. He may indeed think that the symptoms of the disease are those which proceed from a source more hidden; but on the third or fourth days after having tried some remedies he then knows that there is some hidden malady. God then says, that by applying remedies he had found out how corrupt Israel was, While I was healing my people, he says, then I knew what was the iniquity of Samaria and of all Ephraim. By Samaria he means the principal part of the kingdom; for that city, as it is well known, was the capital and the chief seat of government. The Prophet therefore says, that the iniquities of Samaria were then discovered to be, not common, but inveterate diseases. This is the meaning. We now see what God had in view; for the people might deceive themselves, as it often happens, and say, "We are not indeed wholly free from every vice; but God ought not however to punish us so severely, for what nation is there under the sun which does not labour under the common diseases?" But the Prophet here answers, that the people of Israel were so corrupt, that light remedies would not do for them. God then here undertakes the office of a physician, and says, "I have hitherto wished to heal Israel, and this was my design, when I hewed them by my Prophets, and employed my word as a sword; and afterwards when I added chastisements; but now I have found that their wickedness is greater than can be corrected by such remedies." The iniquity of Ephraim then has been discovered, he says, and then I perceived the vices of Samaria Now this place teaches, that though the vices of men do not immediately appear, yet they who deceive themselves, and disguise themselves to others, gain nothing, nor are they made free before God, and their fault is not lessened, nor are they absolved from guilt; for at last their hidden vices will come to light: and this especially happens, when the Lord performs the office of a physician towards them; for we see that', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 8, 1, NULL, 'hosea-8', 'John Calvin', 'Commentaries', E'1. Set the trumpet to thy mouth. He shall come as an eagle against the house of the Lord, because they have transgressed my covenant, and trespassed against my law.

1. Super palatum tuum tuba, tanquam aquila super domum Jehovae, quia transgressi sunt foedus meum, et contra legem meam impie egerunt (vel, perfide segesserunt.)

Interpreters nearly all agree in this, that the Prophet threatens not the kingdom of Israel, but the kingdom of Judah, at the beginning of this chapter, because he names the house of God, which they take to be the temple. I indeed allow, that the Prophet has spoken already, in two places, of the kingdom of Judah, but as it were in passing. He has, it is true, introduced some reproofs and threatening, but so that the distinction was quite clear; and we see that he now goes to the kingdom of Judah, but in the second verse, he names Israel, and yet continues his discourse. To thy mouth, he says, the trumpet, etc.; and afterwards he adds, To me shall they cry, My God; we know thee, Israel. Here, certainly, the discourse is addressed to the ten tribes. I am therefore by no means induced to explain the beginning of the chapter by applying it to the kingdom of Judah: and I certainly do wonder that interpreters have mistaken in a matter so trifling; for the house of God means not only the temple, but also the whole people. As Israel retained this boast, that they were a people holy to God, and that they were his family, he says, "Put or set the trumpet to thy mouth, and proclaim the war, which is now nigh at hand; for the enemy hastens, who is to attack the house of God, that is, this holy people, who cover themselves with the name of God, and who, trusting in their election and adoption, think that they shall be free from all evils; war shall come as an eagle against this house of God."

Had the Prophet added any thing which could be referred peculiarly to the kingdom of Judah, I should willingly accede to their opinion, who think that the house of God is the sanctuary. But let the whole context be read, and any one may easily perceive, that the Prophet speaks of Israel no less in the first verse than in the second and third. For, as it has been said, he lays down no difference, but pursues throughout his teaching or discourse in the same strain.

He says first, A trumpet to thy mouth, or, "Set to thy mouth the trumpet." It is an exhibition, (hypotyposis;) for we know that God, in order to affect more powerfully the people, clothes his Prophets with various characters. The Prophet then is introduced here as a herald who proclaims war, or a messenger, or by whatever name you may be pleased to call him.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 9, 1, NULL, 'hosea-9', 'John Calvin', 'Commentaries', E'1. Rejoice not, O Israel, for joy, as other people: for thou hast gone a whoring from thy God, thou hast loved a reward upon every cornfloor.

1. Ne laeteris Israel super exultatione sicuti populi, quia scortata es a Deo tuo: dilexisti mercedem super omnes areas tritici.

It is not known at what time the Prophet delivered this discourse, but it is enough to know that it is directed against the obstinate wickedness of the people, because they could by no means be turned to repentance, though their defection was, at the same time, manifest. He now declares that God was so angry, that no success could be hoped for. And this warning ought to be carefully noticed; for we see that hypocrites as long as God spares or indulges them, take occasion to be secure: they think that they have sure peace with God, when he bears with them even for a short time; and further, except the drawn sword appears, they are never afraid. Since, then, men sleep so securely in their vices, especially when the Lord treats them with forbearance and kindness, the Prophet here declares, that the Israelites had no reason to rejoice for their prosperity, or to flatter themselves under this cover, that the Lord had not immediately taken vengeance on them; for he says, that though all people under heaven were prosperous, yet Israel would be miserable, because he had committed fornication against his God.

We now perceive the meaning of the Prophet. Israel, he says, rejoice not thou with exultations like the people; that is, "Whatever prosperity may happen to thee, though God may seem propitious by not afflicting thee, but kindly bearing with thee, -- nay, though he may bountifully nourish thee, and may seem to give thee many proofs of paternal favor, yet there is no reason for thee to felicitate thyself, for vain will be this joy, because an unhappy end awaits thee." Thou hast committed fornication, he says, against thy God This warning was very necessary. This vice, we know, has ever prevailed among men, that they are blind to their sins as long as the Lord spares them; and experience, at the present day, most fully proves, that the same disease still cleaves to our marrow. As it is so, let this passage of the Prophet awaken us, so that we may not rejoice, though great prosperity may smile on us; but let us rather inquire, whether God has a just cause of anger against us. Though he may not openly put forth his hand, though he may not pursue us, we ought yet to anticipate his wrath; for it is the proper office of faith, not only to find out from present punishment that God is angry, but also to fear, on account of any prevailing vices, the punishment that is far distant. Let us then learn to examine ourselves, and to make a severe scrutiny, even when the Lord conceals his displeasure, and visits us not for our sins.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 28, 10, 1, NULL, 'hosea-10', 'John Calvin', 'Commentaries', E'1. Israel is an empty vine, he bringeth forth fruit unto himself: according to the multitude of his fruit he hath increased the altars; according to the goodness of his land they have made goodly images.

1. Vites spoliata Israel, fructum ponet sibi: secundum multitudinem fructus sui multiplicavit altaria (in altaribus multiplicavit;) secundum bonitatem (hoc est, proventum fertilem) terrae suae benefecerunt in statuis (alii, bonas fecerunt statuas; sed prior versio mihi magis probatur.)

Interpreters explain this verse in various ways. Those who think vvqq, bukok, here applied to the vine, means "empty," are mistaken; for the Prophet means rather, that Israel was like a vine, which is robbed after the ingathering is come: for the word vqq, bekok, means properly to pillage, or to plunder. But the Prophet compares the gathering of grapes to robbing; and this view best suits the place. He says, then, that Israel is like a robbed vine; for it was stripped of its fruit; and then he adds, He will make fruit for himself The verb svh, shue, means to equal; and many render it thus, -- He will equalize fruit to himself, or, "fruit has been squalled to him." But this rendering brings out no clear sense. I rather follow those who render it, "to lay up." This verb means also sometimes "to lie;" at least some thus render the clause, "Fruit will lie to him:" and though, in the sense of lying, it has a different final letter, svh, shue, it is yet said to be derived from this root, so that there is a change of ''"alef" into h"he", as grammarians think: and yet it does not seem probable that sv'', shua means to lie. But they elicit this sense, "Israel is a plundered vine; therefore fruit will lie to him;" that is, it will bring no produce, for that will happen to it which is wont to be, when robbers have laid waste fields and vineyards. But as I have said already, some more correctly render it, "to lay up;" He will lay up fruit for himself Some, however, read the sentence as a question, -- "Will Israel lay up fruit for himself?" Then the sense is, that Israel was so plundered, that no restitution could be hoped for. But these interpreters do not seem to understand the mind of the Prophet.

I collect a different meaning from the words, and that is, that Israel would lay up fruit for himself after the robbing, and sacred history confirms this view: for this people, we know, had been in various ways chastised; so, however, that they gathered new strength. For the Lord intended only to admonish them gently, that they might be healed; but nothing, as it has before appeared, was effected by God''s moderation. The case, however, was so, that Israel produced new fruit, as a vine, after having been robbed one year, brings forth a new vintage; for one ingathering does not kill the vine.', false, false, 'sourced', 'published');
