-- Calvin commentary INSERT — 2 Peter (batch 1, rows 1-3)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 61, 1, 1, NULL, '2-peter-1', 'John Calvin', 'Commentaries', E'1. Simon Peter. Prayer takes the first place at the beginning of this Epistle, and then follows thanksgiving, by which he excites the Jews to gratitude, lest they should forget what great benefits they had already received from God''s hand. Why he called himself the servant and an apostle of Jesus Christ, we have elsewhere stated, even because no one is to be heard in the Church, except he speaks as from the mouth of Christ. But the word servant has a more general meaning, because it includes all the ministers of Christ, who sustain any public office in the Church. There was in the apostleship a higher rank of honor. He then intimates, that he was not one from the rank of ministers, but was made by the Lord an apostle, and therefore superior to them. Like precious faith. This is a commendation of the grace which God had indiscriminately shewed to all his elect people; for it was no common gift, that they had all been called to one and the same faith, since faith is the special and chief good of man. But he calls it like or equally precious, not that it is equal in all, but because all possess by faith the same Christ with his righteousness, and the same salvation. Though then the measure is different, that does not prevent the knowledge of God from being common to all, and the fruit which proceeds from it. Thus we have a real fellowship of faith with Peter and the Apostles. He adds, through the righteousness of God, in order that they might know that they did not obtain faith through their own efforts or strength, but through God''s favor alone. For these things stand opposed the one to the other, the righteousness of God (in the sense in which it is taken here) and the merit of man. For the efficient cause of faith is called God''s righteousness for this reason, because no one is capable of conferring it on himself. So the righteousness that is to be understood, is not that which remains in God, but that which he imparts to men, as in Romans 3:22. Besides, he ascribes this righteousness in common to God and to Christ, because it flows from God, and through Christ it flows down to us. 2. Grace and peace. By grace is designated God''s paternal favor towards us. We have indeed been once for all reconciled to God by the death of Christ, and by faith we come to the possession of this so great a benefit; but as we perceive the grace of God according to the measure of our faith, it is said to increase according to our perception when it becomes more fully known to us. Peace is added; for as the beginning of our happiness is when God receives us into favor; so the more he confirms his love in our hearts, the richer blessing he confers on us, so that we become happy', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 61, 2, 1, NULL, '2-peter-2', 'John Calvin', 'Commentaries', E'1. But there were. As weak consciences are usually very grievously and dangerously shaken, when false teachers arise, who either corrupt or mutilate the doctrine of faith, it was necessary for the Apostle, while seeking to encourage the faithful to persevere, to remove out of the way an offense of this kind. He, moreover, comforted those to whom he was writing, and confirmed them by this argument, that God has always tried and proved his Church by such a temptation as this, in order that novelty might not disturb their hearts. "Not different," he says, "will be the condition of the Church under the gospel, from what it was formerly under the law; false prophets disturbed the ancient Church; the same thing must also be expected by us."

It was necessary expressly to shew this, because many imagined that the Church would enjoy tranquillity under the rein of Christ; for as the prophets had promised that at his coming there would be real peace, the highest degree of heavenly wisdom, and the full restoration of all things, they thought that the Church would be no more exposed to any contests. Let us then remember that the Spirit of God hath once for all declared, that the Church shall never be free from this intestine evil; and let this likeness be always borne in mind, that the trial of our faith is to be similar to that of the fathers, and for the same reason -- that in this way it may be made evident, whether we really love God, as we find it written in Deuteronomy 13:3.

But it is not necessary here to refer to every example of this kind; it is enough, in short, to know that, like the fathers, we must contend against false doctrines, that our faith ought by no means to be shaken on account of discords and sects, because the truth of God shall remain unshaken notwithstanding the violent agitations by which Satan strives often to upset all things.

Observe also, that no one time in particular is mentioned by Peter, when he says there shall be false teachers, but that all ages are included; for he makes here a comparison between Christians and the ancient people. We ought, then, to apply this truth to our own time, lest, when we see false teachers rising up to oppose the truth of God, this trial should break us down. But the Spirit reminds us, in order that we may take the more heed; and to the same purpose is the whole description which follows.

He does not, indeed, paint each sect in its own colors, but particularly refers to profane men who manifested contempt towards God. The advice, indeed, is general, that we ought to beware of false teachers; but, at the same time, he selected one kind of such from whom the greater danger arose.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 61, 3, 1, NULL, '2-peter-3', 'John Calvin', 'Commentaries', E'1. Lest they should be wearied with the Second Epistle as though the first was sufficient, he says that it was not written in vain, because they stood in need of being often stirred up. To make this more evident, he shews that they could not be beyond danger, except they were well fortified, because they would have to contend with desperate men, who would not only corrupt the purity of the faith, by false opinions, but do what they could to subvert entirely the whole faith.

By saying, I stir up your pure mind, he means the same as though he had said, "I wish to awaken you to a sincerity of mind." And the words ought to be thus explained, "I stir up your mind that it may be pure and bright." For the meaning is, that the minds of the godly become dim, and as it were contract rust, when admonitions cease. But we also hence learn, that men even endued with learning, become, in a manner, drowsy, except they are stirred up by constant warnings.

It now appears what is the use of admonitions, and how necessary they are; for the sloth of the flesh smothers the truth once received, and renders it inefficient, except the goads of warnings come to its aid. It is not then enough, that men should be taught to know what they ought to be, but there is need of godly teachers, to do this second part, deeply to impress the truth on the memory of their hearers. And as men are, by nature, for the most part, fond of novelty and thus inclined to be fastidious, it is useful for us to bear in mind what Peter says, so that we may not only willingly suffer ourselves to be admonished by others, but that every one may also exercise himself in calling to mind continually the truth, so that our minds may become resplendent with the pure and clear knowledge of it.

2. That ye may be mindful. By these words he intimates that we have enough in the writings of the prophets, and in the gospel, to stir us up, provided we be as diligent as it behoves us, in meditating on them; and that our minds sometimes contract a rust, or become bedimmed through darkness, is owing to our sloth. That God may then continually shine upon us, we must devote ourselves to that study: let our faith at the same time acquiesce in witnesses so certain and credible. For when we have the prophets and apostles agreeing with us, nay, as the ministers of our faith, and God as the author, and angels as approvers, there is no reason that the ungodly, all united, should move us from our position. By the commandment of the apostles he means the whole doctrine in which they had instructed the faithful.

3. Knowing this first.', false, false, 'sourced', 'published');
