-- Calvin commentary INSERT — 1 Corinthians (batch 2, rows 11-16)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 11, 1, NULL, '1-corinthians-11', 'John Calvin', 'Commentaries', E'1. Imitators of me. From this it appears, how absurdly chapters are divided, inasmuch as this sentence is disjoined from what goes before, with which it ought to have been connected, and is joined to what follows, with which it has no connection. Let us view this, then, as the close of the preceding chapter. Paul had there brought forward his own example in confirmation of his doctrine. Now, in order that the Corinthians may understand that this would be becoming in them, he exhorts them to imitate what he had done, even as he had imitated Christ

Here there are two things to be observed -- first, that he prescribes nothing to others that he had not first practiced himself; and, secondly, that he directs himself and others to Christ as the only pattern of right acting. For while it is the part of a good teacher to enjoin nothing in words but what he is prepared to practice in action, he must not, at the same time, be so austere, as straightway to require from others everything that he does himself, as is the manner of the superstitious. For everything that they contract a liking for they impose also upon others, and would have their own example to be held absolutely as a rule. The world is also, of its own accord, inclined to a misdirected imitation, (kakozelian) and, after the manner of apes, strive to copy whatever they see done by persons of great influence. We see, however how many evils have been introduced into the Church by this absurd desire of imitating all the actions of the saints, without exception. Let us, therefore, maintain so much the more carefully this doctrine of Paul -- that we are to follow men, provided they take Christ as their grand model, (prototupon,) that the examples of the saints may not tend to lead us away from Christ, but rather to direct us to him.

2. Now I praise you He passes on now to another subject-to instruct the Corinthians, what decorum ought to be observed in the sacred assemblies. For as a man''s dress or gesture has in some cases the effect of disfiguring, and in others of adorning him, so all actions are set off to advantage by decorum, and are vitiated by the want of it. Much, therefore, depends upon decorum (to prepon,) and that not merely for securing for our actions gracefulness and beauty, but also to accustom our minds to propriety. While this is true in a general way as to everything, it holds especially as to sacred things; for what contempt, and, eventually, what barbarism will be incurred, if we do not preserve dignity in the Church, by conducting ourselves honorably and becomingly? Hence he prescribes some things that are connected with public order, by which sacred assemblies are rendered honorable.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 12, 1, NULL, '1-corinthians-12', 'John Calvin', 'Commentaries', E'1. Now concerning spiritual things. He goes on to correct another fault. As the Corinthians abused the gifts of God for ostentation and show, and love was little, if at all, regarded, he shows them for what purpose believers are adorned by God with spiritual gifts -- for the edification of their brethren. This proposition, however, he divides into two parts; for, in the first place, he teaches, that God is the author of those gifts, and, secondly, having established this, he reasons as to their design. He proves from their own experience, that those things in which they gloried, are bestowed upon men through the exercise of God''s favor; for he reminds them how ignorant they were, and stupid, and destitute of all spiritual light, previously to God''s calling them. Hence it appears, that they had been furnished with them -- not by nature, but through God''s unmerited benignity.

As to the words; when he says -- I would not that ye should be ignorant, we must supply the expression -- as to what is right, or as to what is your duty, or some similar expression; and by spiritual things he means spiritual gifts, as to which we shall have occasion to see afterwards. In what follows there is a twofold reading; for some manuscripts have simply hoti others add hote. The former means because -- assigning a reason: the latter means when; and this latter reading suits much better. But besides this diversity, the construction is in other respects confused; but still, the meaning is evident. Literally, it is this -- Ye know, that when ye were Gentiles, after dumb idols, according as ye were led, following I have, however, faithfully given Paul''s meaning. By dumb idols he means -- having neither feeling nor motion.

Let us learn from this passage how great is the blindness of the human mind: when it is without the illumination of the Holy Spirit, inasmuch as it stands in amazement at dumb idols, and cannot rise higher in searching after God; nay more, it is led by Satan as if it were a brute. He makes use of the term Gentiles here, in the same sense as in Ephesians 2:12.

Ye were at one time Gentiles, says he, without God, strangers to the hope of salvation, etc.

Perhaps, too, he reasons by way of contrast. What if they should now show themselves to be less submissive to God, after his having taken them under his care, to be governed by his word and Spirit, than they formerly discovered themselves to be forward and compliant, in following the suggestions of Satan!

3. Wherefore I give you to know. Having admonished them from their own experience, he sets before them a general doctrine, which he deduces from it; for what the Corinthians had experienced in themselves is common to all mankind -- to wander on in error, previously to their being brought back, through the kindness of God, into the way of truth.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 13, 1, NULL, '1-corinthians-13', 'John Calvin', 'Commentaries', E'1. If should speak with the tongues of men. He begins with eloquence, which is, it is true, an admirable gift, considered in itself, but, when apart from love, does not recommend a man in the estimation of God. When he speaks of the tongue of angels, he uses a hyperbolical expression to denote what is singular, or distinguished. At the same time, I explain it rather as referring to the diversity of languages, which the Corinthians held in much esteem, measuring everything by ambition -- not by fruit. "Make yourself master," says he, "of all the languages, not of men merely, but even of Angels. You have, in that case, no reason to think, that you are of higher estimation in the sight of God than a mere cymbal, if you have not love."

2. And if I should have the gift of prophecy. He brings down to nothing the dignity of even this endowment, which, nevertheless, he had preferred to all others. To know all mysteries, might seem to be added to the term prophecy, by way of explanation, but as the term knowledge is immediately added, of which he had previously made mention by itself, (1 Corinthians 12:8,) it will deserve your consideration, whether the knowledge of mysteries may not be used here to mean wisdom. As for myself, while I would not venture to affirm that it is so, I am much inclined to that opinion.

That faith, of which he speaks, is special, as is evident from the clause that is immediately added -- so that I remove mountains Hence the Sophists accomplish nothing, when they pervert this passage for the purpose of detracting from the excellence of faith. As, therefore, the term faith is (polusemon) used in a variety of senses, it is the part of the prudent reader to observe in what signification it is taken. Paul, however, as I have already stated, is his own interpreter, by restricting faith, here, to miracles. It is what Chrysostom calls the "faith of miracles," and what we term a "special faith," because it does not apprehend a whole Christ, but simply his power in working miracles; and hence it may sometimes exist in a man without the Spirit of sanctification, as it did in Judas.

3. And if I should expend all my possessions. This, it is true, is worthy of the highest praise, if considered in itself; but as liberality in many cases proceeds from ambition -- not from true generosity, or even the man that is liberal is destitute of the other departments of love, (for even liberality, that is inwardly felt, is only one department of love,) it may happen that a work, otherwise so commendable, has, indeed, a fair show in the sight of men, and is applauded by them, and yet is regarded as nothing in the sight of God.

And if I should give up my body.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 14, 1, NULL, '1-corinthians-14', 'John Calvin', 'Commentaries', E'1. Covet spiritual gifts. Lest the Corinthians should object that they wronged God, if they despised his gifts, the Apostle anticipates this objection by declaring, that it was not his design to draw them away even from those gifts that they had abused -- nay rather he commends the pursuit of them, and wishes them to have a place in the Church. And assuredly, as they had been conferred for the advantage of the Church, man''s abuse of them ought not to give occasion for their being thrown away as useless or injurious, but in the meantime he commends prophecy above all other gifts, as it was the most useful of them all. He observes, therefore, an admirable medium, by disapproving of nothing that was useful, while at the same time he exhorts them not to prefer, by an absurd zeal, things of less consequence to what was of primary importance. Now he assigns the first place to prophecy. Covet, therefore, spiritual gifts -- that is, "Neglect no gift, for I exhort you to seek after them all, provided only prophecy holds the first place."

2. For he that speaketh in another tongue, speaketh, etc. He now shows from the effect, why it was that he preferred prophecy to other gifts, and he compares it with the gift of tongues, in which it is probable the Corinthians exercised themselves the more, because it had more of show connected with it, for when persons hear a man speaking in a foreign tongue, their admiration is commonly excited. He accordingly shows, from principles already assumed, how perverse a thing this is, inasmuch as it does not at all contribute to the edifying of the Church. He says in the outset -- He that speaketh in another tongue, speaketh not unto men, but unto God: that is, according to the proverb, "He sings to himself and to the Muses." In the use of the word tongue, there is not a pleonasm, as in those expressions -- "She spake thus with her mouth," and "I caught the sound with these ears." The term denotes a foreign language. The reason why he does not speak to men is -- because no one heareth, that is, as an articulate voice. For all hear a sound, but they do not understand what is said.

He speaketh in the Spirit -- that is, "by a spiritual gift, (for in this way I interpret it along with Chrysostom.) He speaketh mysteries and hidden things, and things, therefore, that are of no profit." Chrysostom understands mysteries here in a good sense, as meaning -- special revelations from God. I understand the term, however, in a bad sense, as meaning -- dark sayings, that are obscure and involved, as if he had said, "He speaks what no one understands."

3. He that prophesieth, speaketh unto men "Prophecy," says he, "is profitable to all, while a foreign language is a treasure hid in the earth.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 15, 1, NULL, '1-corinthians-15', 'John Calvin', 'Commentaries', E'1. Now I make known to you. He now enters on another subject -- the resurrection -- the belief of which among the Corinthians had been shaken by some wicked persons. It is uncertain, however, whether they doubted merely as to the ultimate resurrection of the body, or as to the immortality of the soul also. It is abundantly well known, that there were a variety of errors as to this point. Some philosophers contended that souls are immortal. As to the resurrection of the body, it never entered into the mind of any one of them. The Sadducees, however, had grosser views; for they thought of nothing but the present life; nay more, they thought that the soul of man was a breath of wind without substance. It is not, therefore, altogether certain (as I have already said) whether the Corinthians had at this time gone to such a height of madness, as to cast off all expectation of a future life, or whether they merely denied the resurrection of the body; for the arguments which Paul makes use of seem to imply, that they were altogether bewitched with the mad dream of the Sadducees.

For example, when he says,

Of what advantage is it to be baptized for the dead? (1 Corinthians 15:29.)

Were it not better to eat and to drink? (1 Corinthians 15:32.)

Why are we in peril every hour? (1 Corinthians 15:30,)

and the like, it might very readily be replied, in accordance with the views of the philosophers, "Because after death the soul survives the body." Hence some apply the whole of Paul''s reasoning contained in this chapter to the immortality of the soul. For my part, while I leave undetermined what the error of the Corinthians was, yet I cannot bring myself to view Paul''s words as referring to anything else than the resurrection of the body. Let it, therefore be regarded as a settled point, that it is of this exclusively that he treats in this chapter. And what if the impiety of Hymeneus and Philetus had extended thus far, who said that the resurrection was already past, (2 Timothy 2:18,) and that there would be nothing more of it? Similar to these, there are at the present day some madmen, or rather devils, who call themselves Libertines. To me, however, the following conjecture appears more probable -- that they were carried away by some delusion, which took away from them the hope of a future resurrection, just as those in the present day, by imagining an allegorical resurrection, take away from us the true resurrection that is promised to us.

However this may be, it is truly a dreadful case, and next to a prodigy, that those who had been instructed by so distinguished a master, should have been capable of falling so quickly into errors of so gross a nature.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 16, 1, NULL, '1-corinthians-16', 'John Calvin', 'Commentaries', E'1. But concerning the collection Luke relates (Acts 11:28) that the prediction of Agabus, foretelling that there would be a famine under Claudius Caesar, gave occasion for alms being collected by the saints, with the view of affording help to the brethren in Jerusalem. For though the Prophet had foretold, that this calamity would be generally prevalent almost throughout the world, yet as they were more heavily oppressed with penury at Jerusalem, and as all the Gentile Churches were bound, if they would not be held guilty of very great ingratitude, to afford aid to that place from which they had received the gospel, every one, consequently, forgetful of self, resolved to afford relief to Jerusalem. That the pressure of want was felt heavily at Jerusalem, appears from the Epistle to the Galatians, (Galatians 2:10,) where Paul relates, that he had been charged by the Apostles to stir up the Gentiles to afford help. Now the Apostles would never have given such a charge, had they not been constrained by necessity. Farther, this passage is an evidence of the truth of what Paul states there also -- that he had been careful to exhort the Gentiles to afford help in such a case of necessity. Now, however, he prescribes the method of relief; and that the Corinthians may accede to it the more readily, he mentions that he had already prescribed it to the Churches of Galatia; for they would necessarily be the more influenced by example, as we are wont to feel a natural backwardness to anything that is not ordinarily practiced. Now follows the method -- by which he designed to cut off all hinderances and impediments.

2. On one of the Sabbaths. The end is this -- that they may have their alms ready in time. He therefore exhorts them not to wait till he came, as anything that is done suddenly, and in a bustle, is not done well, but to contribute on the Sabbath what might seem good, and according as every one''s ability might enable -- that is, on the day on which they held their sacred assemblies. The clause rendered on one of the Sabbaths, (kata mian sabbaton,) Chrysostom explains to mean -- the first Sabbath. In this I do not agree with him; for Paul means rather that they should contribute, one on one Sabbath and another on another; or even each of them every Sabbath, if they chose. For he has an eye, first of all, to convenience, and farther, that the sacred assembly, in which the communion of saints is celebrated, might be an additional spur to them. Nor am I more inclined to admit the view taken by Chrysostom -- that the term Sabbath is employed here to mean the Lord''s day, (Revelation 1:10,) for the probability is, that the Apostles, at the beginning, retained the day that was already in use, but that afterwards, constrained by the superstition of the Jews, they set aside that day, and substituted another.', false, false, 'sourced', 'published');
