-- Calvin commentary INSERT — Amos (batch 1, rows 1-9)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 1, 1, NULL, 'amos-1', 'John Calvin', 'Commentaries', E'1. The words of Amos, who was among the herdmen of Tekoa, which he saw concerning Israel in the days of Uzziah king of Judah, and in the days of Jeroboam the son of Joash king of Israel, two years before the earthquake.

1. Verba Amos, qui fuit inter pastores (vel, pecuarios) ex Tucua: quae vidit super Israel diebus Uzziah regis Juhudah, et diebus Jarobeam filii Joas regis Israel, biennio ante motum (vel chasma) terrae. nominibus, quia de sensu Prophetae satis constabit. Nunc venio ad inscriptionem libri.)

Amos boasts not here, in speaking of his own words, that he adduced anything as from himself, but avows himself to be only the minister of God; for he immediately adds that he received them by a vision. God himself raised up the Prophets and employed their labor; And, at the same time, guided them by his Spirit, that they might not announce anything but what had been received from him, but faithfully deliver what had proceeded from him alone. These two things then, well agree together, -- that the prophecies which follow were the words of Amos and that they were words revealed to him from above; for the word chzh, chese, which Amos uses, properly means, to see by revelation; and these revelations were called prophecies.

But he says, that he was among the shepherds of Tekoa. This was a mean towns and had been shortly before surrounded by walls and had ever been previously a village. He then mentions not his country, because it was celebrated, or as though he could derive thereby more authority or renown: but, on the contrary he calls himself a Tekoan, because God drew him forth from an obscure place, that he might set him over the whole kingdom of Israel. They are therefore mistaken, as I think, who suppose that Amos was called one of the shepherds on account of his riches, and the number of his flocks; for when I weigh every thing, I see not how could this be. I indeed allow that nqdym, nukodim are not only shepherds who do the work, but men possessing flocks, carrying on a large business; for the king of Moab is said to have been a nqd, nukod, and that he fed large flocks; but it was by hired shepherds. As to the Prophets I do not see how this can be applied to him; for Tekoa was not a place famous for wealth; and as I have said, it was a small town, and of no opulence. I do not then doubt, but that Amos, by saying that he was a shepherd, pours contempt on the pride of the king of Israel, and of the whole people; for as they had not deigned to hear the Prophets of God, a keeper of sheep was sent to them.

It must be further noticed, that he is not called a shepherd of Tekoa, but from Tekoa; and interpreters have not observed this preposition.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 2, 1, NULL, 'amos-2', 'John Calvin', 'Commentaries', E'1. Thus saith the LORD; For three transgressions of Moab, and for four, I will not turn away the punishment thereof; because he burned the bones of the king of Edom into lime: 1. Sic dicit Jehova, Super tribus sceleribus Moab et super quatuor non convertam eum (vel, non convertam me, sicut prius diximus,) quia ipse combussitossa regis Edom in calcem: 2. But I will send a fire upon Moab, and it shall devour the palaces of Kerioth: and Moab shall die with tumult, with shouting, and with the sound of the trumpet: 2. Et mittam ignem in Moab qui comedet palatia, (qryvt, alii vertunt urbium appellative: sed magis arbitror esse proprium nomen loci) et morietur in tumultu Moab, in strepitu, in clangore tubae. 3. And I will cut off the judge from the midst thereof, and will slay all the princes thereof with him, saith the Lord. 3. Et excidam judicem e medio ejus, et omnes principes ejus occidam cum eo, dicit Jehova. Now Amos prophesies here against the Moabites, and proclaims respecting them what we have noticed respecting the other nations, -- that the Moabites were wholly perverse, that no repentance would be hoped for, as they had added crimes to crimes, and reached the highest pitch of wickedness; for, as we have said, the number, seven, imports this. The Prophet then charges the Moabites here with perverseness: and hence we learn that God''s vengeance did not come hastily upon them, for their wickedness was intolerable since they thus followed their crimes. But he mentions one thing in particular, -- that they had burnt the bones of the king of Edom. Some take bones here for courage, as though the Prophet had said, that the whole strength of Edom had been reduced into ashes: but this is a strained exposition; and its authors themselves confess that they are forced to it by necessity, when yet there is none. The comment given by the Rabbis does not please them, -- that the body of a certain king had been burnt, and then that the Moabites had strangely applied the ashes for making a cement instead of lime. Thus the Rabbis trifle in their usual way; for when an obscure place occurs, they immediately invent some fable; though there be no history, yet they exercise their wit in fabulous glosses; and this I wholly dislike: but what need there is of running to allegory, when we may simply take what the Prophet says, that the body of the king of Edom had been burnt: for the Prophet, I doubt not, charges the Moabites with barbarous cruelty. To dig up the bodies of enemies, and to burn their bones, -- this is an inhuman deed, and wholly barbarous. But it was more detestable in the Moabites, who had some connection with the people of Edom; for they descended from the same family; and the memory of that relationship ought to have continued, since Abraham brought up Lot, the father of the', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 3, 1, NULL, 'amos-3', 'John Calvin', 'Commentaries', E'1. Hear this word that the Lord hath spoken against you, O children of Israel, against the whole family which I brought up from the land of Egypt, saying, 1. Audite verbum hoc quod pronunciat Jehova super vos, filii Israel, super totam familiam eduxi (vel, ascendere feci) e terra Aegypti, dicendo, 2. You only have I known of all the families of the earth: therefore I will punish you for all your iniquities. 2. Tantummodo vos cognovi ex omnibus familiis terrae: propterea visitabo super vos omnes iniquitates vestras. The Prophet wished doubtless by these words to confirm his own authority, for he saw that his doctrine was regarded with contempt: and it is probable that the words recited here were not only once delivered by him, but had been often repeated. We know how great was the pride and confidence of that people: it was therefore needful to beat it down, that they might be habituated to dread and fear, when God reproved them by his Prophets. It was then the common mode of speaking, when he said, Hear the word which God has spoken concerning your, O children of Israel. He brings forward here the name of God, that they might know that they had not to do with a mortal man, or with a shepherd, such as he was. We then observe here, what I have just referred to, and that is, that the Prophet seeks to strengthen his authority as a teacher, that he might gain more respect among the people. But he adds, concerning the whole family which I brought up out of Egypt It is certain that this discourse was not addressed except to the ten tribes; why, then, does the Prophet speak here so generally? Even because the kingdom of Israel formed the greater portion of the race of Abraham, and on this account they boasted that the adoption continued to be possessed by them. Since, then, they despised the tribe of Judah, and the half-tribe of Benjamin, which was connected with it, and had ever boasted of their great number, the Prophet says here, by way of concession, that they were indeed the blessed seed, the posterity of Abraham; in a word, the elect people, whom God had redeemed from Egypt. Then the Prophet includes not here the kingdom of Judah, but concedes to the Israelites what they boasted, -- that they were the elect people, the holy race of Abraham, the very nation which had been miraculously delivered. "Let, then," he says, "all these boastings be granted, yet God will not, on this account, desist from executing his judgment upon them." We now apprehend the design of the Prophet: he first seeks to gain respect for his doctrine, and takes occasion to speak of his own vocation, that he brought nothing of his own, but only discharged faithfully the office committed to him; yea, that he was the organ of the Holy Spirit, and adduced nothing from his own mind, but only', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 4, 1, NULL, 'amos-4', 'John Calvin', 'Commentaries', E'1. Hear this word, ye kine of Bashan, that are in the mountain of Samaria, which oppress the poor, which crush the needy, which say to their masters, Bring, and let us drink.

1. Audite verbum hoc vaccae Basan, qui estis in monte Samariae, quae opprimitis pauperes, quae conteritis egenos, quae dicitis dominis eorum, Affer et bibemus.

He who divided the chapters seems not to have well considered the Prophet''s argument: for he pursues here his reproof of the rich, and he had been prophesying against the chief men in the kingdom of Israel. We indeed know how much ferocity there is in the rich, when they become formidable to others by their power. Hence the Prophet here laughs to scorn their arrogance: Hear, he says, this word; as though he said, "I see how it will be; for these great and pompous men will haughtily despise my threatening, they will not think themselves exposed to God''s judgment; and they will also think that wrong is done to them: they will inquire, Who I am,'' and ask, How dares a shepherd assail them with so much boldness?'' "Hear then ye cows; as though he said, that he cared not for the greatness in which they prided themselves. "What then is your wealth? It is even fatness: then I make no more account of you than of cows; ye are become fat; but your power will not terrify me; your riches will not deprive me of the liberty of treating you as it becomes me and as God has commanded me." We hence see that the Prophet here assails with scorn the chief men of the kingdom, who wished to be sacred and untouched. The Prophet asks by what privilege they meant to excuse themselves for not hearing the word of the Lord. If they pleaded their riches and their own authority; "These," he says, "are fatness and grossness; ye are at the same time cows and I will regard you as cows; and I will not deal with you less freely than I do with my cattle." We now then perceive the Prophet''s intention.

But he goes on with his similitude: for though he here accuses the chiefs of the kingdom of oppressing the innocent and of distressing the poor, he yet addresses them in the feminine gender, who dwell, he says, on the mountain of Samaria, who oppress the poor, who consume the needy, who say, etc. He does not think them worthy of the name of men; and yet they wished to be viewed a class separate from the common people, as though they were some heroes or halfgods. The Prophet, by way of contempt, calls them here cows; and he also withholds from them the name of men.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 5, 1, NULL, 'amos-5', 'John Calvin', 'Commentaries', E'1. Hear ye this word which I take up against you, even a lamentation, O house of Israel. 1. Audite verbum hoc quod ego tollo super vos, lamentum domus Israel. Some render the verse thus, "Hear ye this word, because upon you, or for you, I raise a lamentation:" but we shall hereafter speak more at large as to the proper rendering. Let us see what the subject is. The Prophet here denounces on the Israelites the punishment they had deserved; and yet they did not think that it was nigh; and they ferociously despised, I have no doubt, the denunciation itself, because no chance had as yet taken place, which might have pointed out such a destruction. Hence the Prophet and his threatenings were both despised. He however threatens them here in severe terms with the judgment of God, which they feared not: and this is the reason why he says, Hear ye. It was not, indeed, without reason that he thus began and intimated that they greatly flattered themselves, nay, that they stopped their ears against wholesome counsels: the admonition would have been otherwise superfluous. The Prophet then indirectly reproves that supine indifference in which the Israelites indulged themselves. But with regard to the words, some, as I have before mentioned, refer this lamentation to Amos himself, as though he had said, that he lamented the state of the people, finding that they were so stupid, and did not perceive how dreadful the wrath of God is. Since, then, they thus flattered themselves in their sins, those interpreters think that the Prophet here assumes the character of a mourner for that irreclaimable people. Hear, he says, this word even because I lament over you. For the more refractory the people were, the more touched with grief the prophet no doubt was: for he saw how horrible the judgment of God was, which was nigh them, on account of their stubbornness. No wonder then that the Prophet says here, that he undertook or raised lamentation for the people; and this mode of speaking is common in Scripture. But yet I rather think that another sense is more suitable to this place, which becomes evident by putting in an exegetic particle, Hear ye then this word which I raise upon you, even a lamentation, etc. The word ms'', mesha, rendered burden, is derived from the verb ns'', nusha, which means to raise up: and there is a striking allusion to the subject treated of here. For the Prophet does not here simply teach the people, nor comfort them, nor does he only warn them, but he denounces on them the last punishment. We hence see the import of the expression, to raise up a word; it was the same as though he said, "I lay on you this prophecy:" for a burden is laid on the shoulders of men when God''s wrath is denounced. It afterwards follows, Even a lamentation, O house of Israel; which means, "I raise upon you', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 6, 1, NULL, 'amos-6', 'John Calvin', 'Commentaries', E'1. Woe to them that are at ease in Zion, and trust in the mountain of Samaria, which are named chief of the nations, to whom the house of Israel came! 1. Vae securis in Sion et confidentibus in monte Samaria, qui celebres fuerunt principio gentium, et ingressi sunt ad illos domus Israel. The Prophet now directs his discourse not only to the Israelites, to whom he was especially given as an instructor and teacher, but includes the Jews also: and yet he addresses not all indiscriminately, but only the chief men, who were intent on their pleasures, as though they were exempt from the common miseries: for he does not, as many suppose, reprove here luxury and pride only; but we must remember a fact connected with their case, -- that they were not awakened by God''s judgments; when God severely punished the sins of the people, the chief men remained ever heedlessly in their own dregs. This security is now condemned by our Prophet. And this is a very common evil, as we may see, in the present day. For when the Lord afflicts a country with war or with famine, the rich make great gain of such evils. They abuse the scourges of God; for we see merchants getting rich in the midst of wars, inasmuch as they scrape together a booty from every quarter. For they who carry on war are forced to borrow money, and also the peasants and mechanics, that they may pay taxes; and then, that they may live, they are obliged to make unjust conditions: thus the rich increase in wealth. They also who are in authority, and in favor at the court of princes, make more gain in wars, in famine, and in other calamities, than during times of peace and prosperity: for when peace nourishes, the state of things is then more equable; but when the poor are burdened, the rest grow fat. And this is the evil now noticed by the Prophet. Hence he pronounces here a curse on the secure and those at ease; not that it is an evil thing, or in itself displeasing to God, when any one quietly enjoys his leisure; but, not to be moved, when the Lord openly shows himself to be displeased and angry, when his scourges are manifestly inflicted, but to indulge ourselves more in pleasures, -- this is to provoke him, as it were, designedly. The secure, then, and the presumptuous the Prophet here condemns, for it became them to humble themselves when they saw that God was incensed against them. They were not indeed more just than the multitude; and when God treated the common people with such severity, ought not the chiefs to have looked to themselves, and have examined their own life? As they did not do this, but made themselves drunk with pleasures, and put far off every fear and thought that the scourges of God were nothing to them, -- this was a contempt deservedly', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 7, 1, NULL, 'amos-7', 'John Calvin', 'Commentaries', E'1. Thus hath the Lord God shewed unto me; and, behold, he formed grasshoppers in the beginning of the shooting up of the latter growth; and, lo, it was the latter growth after the king''s mowings.

1. Sic ostendit mihi Dominus, et ecce formans locustas principio ascensionis herbae (hoc est, quum incipit herba ascendere: lqs, proprie significat secundam herbam, quam vocamus, Regian) et ecce herba post sectiones (vel, tonsuras, ut alii vertunt) Regis.

2. And it came to pass, that when they had made an end of eating the grass of the land, then I said, O Lord God, forgive, I beseech thee: by whom shall Jacob arise? for he is small.

2. Et factum est dum perficeret ad comendendum (hoc est, quum jam fere in totum absumpsisset herbam terrae,) tunc dixi, Adonai Jehova, parce, obsecro: quis stabit (vel, quis restituet) Jacob, quia parvus est?

3. The Lord repented for this: It shall not be, saith the Lord.

3. Poenituit Jehovam super hoc; Non erit, dixit Jehova.

Amos shows in this chapter that God had already often deferred the punishments which he had yet determined to inflict on the people; and thus he reminds the Israelites of their perverseness, inasmuch as they had abused the forbearance of God, and repented not after a long lapse of time: for God had suspended his judgments for this end -- that they might willingly return to the right way, as he commonly allures men by his kindness, provided they be teachable. Since then this forbearance of God had been without fruit, Amos reproves the Israelites, though he had also another object in view: for ungodly men, we know, when God spares them and does not immediately indict the punishments they deserve, laugh at them, and harden themselves for the future, so that they fear nothing; and when the Lord threatens, and does not instantly execute his vengeance, they then especially think that all threatening are mere bugbears; and therefore they harden their minds in security and think that they can with impunity trifle with God. Inasmuch then as this obstinacy prevailed among the Israelites, the Prophet here shows in various ways, that in vain they gloried, and thus securely despised the judgment of God; for though the Lord for a time had spared them, yet the final vengeance was not far distant. This is the sum of the whole: but such expression must be considered in its order.

A vision, he says, had been shown to him by the Lord; and the vision was, that God himself had formed locusts. Yet some think yvtsr, iutsar, to be a noun, and render it, creation; others, a swarm or a troop. But these are forced expositions. The Lord then, I doubt not, formed locusts in the Prophet''s presence, which devoured all the grass.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 8, 1, NULL, 'amos-8', 'John Calvin', 'Commentaries', E'1. Thus hath the Lord God shewed unto me: and behold a basket of summer fruit.

1. Sic ostendit mihi Dominus Jehova; et ecce corbis fructus aestivi (vel, canistrum.) Et dixit, Quid tu vides, Amos?

2. And he said, Amos, what seest thou? And I said, A basket of summer fruit. Then said the Lord unto me, The end is come upon my people of Israel; I will not again pass by them any more.

2. Et dixit, Corbem (vel, canistrum) fructus aestivi: et dixit Jehova mihi, Venit finis super populum meum Israel; non adjiciam amplius transire in eo.

By these words or by this vision the Prophet confirms what we have already observed -- that paternal chastisements would no longer be exercised towards the people of Israel. God indeed, as it is well known, had so treated that people, that he ever spared them even in their greatest calamities. It was with a suspended hand that God ever struck that people, until after many trials they at length seemed so refractory, as not to be benefited by such remedies. This subject then Amos now pursues: but a vision was shown to him to confirm more fully God''s judgment, or at least to produce a greater impression on the minds of the people.

God showed to him a Basket full of summer-fruit. By summer-fruit, I doubt not, he means a ripe punishment, as though he said, that the vices of the people had ripened, that vengeance could no longer be deferred: for an exposition of the vision immediately follows, when he says, that the end of the people had come, etc.; and this we have already explained in the third vision. But there is a similarity in the Hebrew words, which cannot be expressed either in Greek or Latin. qyts, kits means a summer-fruit, qts, kots, signifies an end: one letter only is inserted in the word, summer-fruit, which God showed in a basket; and then he adds that qts, kots, the end had come. But as to the main point, we see that there is nothing ambiguous. We will now return to the first thing.

Thus God showed to me. There is no need of repeating what I have already discussed. The Prophet here prefaces, that he adduced nothing without authority, but only faithfully related what had been commanded him from above. And this ought to be carefully observed; for God ever so employed his Prophets, that he yet reserved for himself entire the right of teaching, and never transferred his own office to men, that is, as to the authority. Then he says, The Lord Jehovah showed to me, and, lo, a basket of summer-fruit. We may understand cherries by summer-fruit, and those fruits which have no solid vigor to continue long; but this is too refined. I take the simple meaning, that punishment had now become ripe; for the people had not repented, though they had been so often warned; it was then as it were summer.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 30, 9, 1, NULL, 'amos-9', 'John Calvin', 'Commentaries', E'1. I saw the Lord standing upon the altar: and he said, Smite the lintel of the door, that the posts may shake: and cut them in the head, all of them; and I will slay the last of them with the sword: he that fleeth of them shall not flee away, and he that escapeth of them shall not be delivered.

1. Vidi Dominum stantem super altare, et dixit, Percute superliminare et coommovebunter postes, et affliget (vel, afflige, in modo imperativo) in capite omnes, et novissimum ipsorum (vel, posteritatem) gladio occidam; non effuget ex ipsis fugiens, neque evadet ex ipsis qui evadit.

The Prophet confirms the threatening which we have already explained; for he says that the people would be soon removed, as there was now no hope of repentance. But it must first be observed, that he speaks not here of the profane temples which Jeroboam the first had built in Dan and in Bethel, but of the true and lawful temple; for it would not have been befitting that this vision should have been made to the Prophet in one of those profane temples, from which, we know, God was far away. Had God appeared in Dan or Bethel, it would have been an indirect approbation of superstition. They are then mistaken who think that the vision was given to the Prophet in any other place than on mount Zion, as we have shown in other places. For the Prophets say not, that God had spoken either in Dan or in Bethel, nor had there been any oracle announced from these places; for God designed in every way to show that he had nothing to do with those profane rites and abominations. It is then certain that God appeared to his Prophet on mount Zion, and on the lawful altar.

Let us now see the design of the vision. The greater part of interpreters think that the destruction of the kingdom and of the priesthood is predicted here, at the time when Zedekiah was taken and led ignominiously into exile, and when his children were killed, and when afterwards the temple was erased and the city demolished. But this prediction, I doubt not, ought to be extended much farther, even to the many calamities which immediately followed, by which at length the whole people were destroyed. I therefore do not confine what is here said to the demolition of the city and of the temple. But the meaning of the Prophet is the same as though he had said, that the Israelites as well as the Jews in vain boasted of their descent and of other privileges with which they had been honored: for the Lord had resolved to destroy them, and also the temple, which they employed as a cloak to cover their iniquities. We now then understand the intention of the Prophet.', false, false, 'sourced', 'published');
