-- Calvin commentary INSERT — Malachi (batch 1, rows 1-4)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 39, 1, 1, NULL, 'malachi-1', 'John Calvin', 'Commentaries', E'1. The burden of the word of the LORD to Israel by Malachi.

1. Onus sermonis Iehovae ad Israel in manu Maleachi.

They who explain ms'', mesha, burden, as signifying prophecy, without exception, are mistaken, as I have elsewhere reminded you; for prophecy is not everywhere called a burden; and whenever this word is expressed, there is ever to be understood some judgment of God; and it appears evident from Jeremiah 23:38, that this word was regarded as ominous, so that the ungodly, when they wished to brand the Prophets with some mark of reproach, used this as a common proverb, "It is a burden," intimating thereby that nothing else was brought by the Prophets but threatenings and terrors, in order that they might have some excuse for closing their ears, and for evading all prophecies by giving them an unhappy and ominous name.

As we proceed it will become evident that the doctrine of Malachi is not without reason called a Burden; for as I have stated in part, and as it will be more fully seen hereafter, it was necessary that the people should be summoned before God''s tribunal, inasmuch as many sins had again begun to prevail among them, and such as could not be endured: and for this reason he says that God''s judgment was at hand.

But under the name of Israel he refers only to those who had returned to their own country, whether they were of the tribe of Judah and Benjamin, or of the tribe of Levi. It is nevertheless probable that there were also some mixed with them from the other tribes: but the Jews and their neighbors, the half tribe of Benjamin, had almost alone returned to their country, with the exception of the Levites, who had been their guides in their journey, and encouraged the rest of the people. They were yet called Israel indiscriminately, since among them only pure religion continued: but they who remained dispersed among foreign and heathen nations, had as it were lost their name, though they had not wholly departed from the pure worship of God and true religion. Hence, by way of excellency, they were called Israel, who had again assembled in the holy land, that they might there enjoy the inheritance promised them from above.

The word hand, as we have observed elsewhere, means ministration. The meaning then is, that this doctrine proceeded from God, but that a minister, even Malachi, was employed as an instrument; so that he brought nothing as his own, but only related faithfully what had been committed to him by God from whom it came. It then follows -- __________________________________________________________________

2. I have loved you, saith the LORD. Yet ye say, Wherein hast thou loved us? Was not Esau Jacob''s brother? Saith the LORD: yet I loved Jacob,

2. Dilexi vos, dicit Jehovah; et dixistis, In quo dilexisti nos? Annon frater Esau erat ipsi Jacob? dicit Jehova; et dilexi Jacob,

3.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 39, 2, 1, NULL, 'malachi-2', 'John Calvin', 'Commentaries', E'17. Ye have wearied the LORD with your words. Yet ye say, Wherein have we wearied him? When ye say, Every one that doeth evil is good in the sight of the LORD, and he delighteth in them; or, Where is the God of judgment?

17. Fatigastis Iehovam in verbis vestris, et dixistis, In quo fatigavimus eum? Quum dicitis, Quicunque facit malum gratus est in oculis Iehovae, et in ipsis se oblectat; vel, Ubi Deus judicii?

The Prophet here reproves the Jews who expostulated with God in their adversity, as though he had undeservedly forsaken them, and had not brought them immediate help. Thus are hypocrites wont to do; unless God immediately assists them, they not only indirectly complain, but also break out into open blasphemies; for they think that God is bound to them, and hence they assail him more boldly, and even with greater freedom and insolence. It is indeed a proof of true piety when we patiently submit to the judgments of God, and when, as Jeremiah teaches us by his own example,

"we sustain his wrath, because we know that we have sinned." (Jeremiah 3:14.)

But as hypocrites are conscious of nothing wrong, (for they flatter themselves, and stupify their own consciences,) because they examine not themselves, they think that God acts unjustly towards them when he does not immediately bring them aid. Such was the dishonesty of the people of whom the Prophet now speaks.

He says that they had wearied God, that is, that they had been troublesome to him by their clamorous complaints; for the verb, yg, igo, means to be weary; he says then that they unreasonably complained of God''s slowness. It is indeed a mode of speaking taken from men, for we know that no passions belong to God; but as elsewhere God reproves them because they saddened his Spirit, (Psalm 106:33,) so he says here that they wearied him. We now perceive the Prophet''s meaning.

But there is a dilemma presented in the words; for the Jews thought that God favored the wicked, inasmuch as he did not immediately punish them, or that he was now unlike himself, and forgot his own nature. The difficulty or the dilemma appears not at the first view, as they seemed to have repeated the same thing. But in the first clause they accuse God of injustice; and in the second they intimate that there is no God, for he cannot exist without exercising judgment. Then the passages contains two clauses differing from each other -- "God has either changed his nature, and so is no God, or he favors our enemies; for he does not immediately execute vengeance." We see then that they concluded that God either acted unjustly, or that there was no God. But we have mentioned the cause of this blasphemy -- the Jews did not examine themselves, and therefore did not confess that they deserved these chastisements.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 39, 3, 1, NULL, 'malachi-3', 'John Calvin', 'Commentaries', E'1. Behold, I will send my messenger, and he shall prepare the way before me: and the Lord, whom ye seek, shall suddenly come to his temple, even the messenger of the covenant, who ye delight in: behold, he shall come, saith the LORD of hosts. 1. Ecce ego mitto Angelum meum, et purgabit viam coram facie mea; et mox veniet ad templum suum Dominus, quem vos quaeritis, et Angelo foederis quem vos expetitis; ecce venit, dicit Iehova exercituum. Here the Prophet does not bring comfort to the wicked slanderers previously mentioned, but asserts the constancy of his faith in opposition to their blasphemous words; as though he had said, "Though they impiously declare that they have been either deceived or forsaken by the God in whom they had hoped, yet his covenant shall not be in vain." The design of what is announced is like that of the declaration made elsewhere, "Though men are perfidious and false, yet God remains true, and cannot depart from his own nature." (Numbers 23:19.) God then does here gloriously triumph over the Jews, and alleges his own covenant in opposition to their disgraceful slanders, because their wicked murmurings could not hinder him to accomplish his promises and to perform in due time what they thought would never be done; and he adopts a demonstrative adverb in order to show the certainty of what is said. Behold, he says, I send my messenger, who will clear the way before my face This passage ought doubtless to be understood of John the Baptist, for Christ himself so explains it, than whom no better interpreter can be found; and since John the Baptist was the messenger of Christ, the beginning of the verse can be applied to no other person. Afterwards the Father himself speaks as we shall see: but as he who appeared in the flesh is the same God with the Father, it is no wonder that he speaks, and then that the words which follow are spoken in the person of the Father. There is here a striking allusion to Moses, whose office it was to intercede, that God might not in his just wrath destroy the whole people; for as then the majesty of God was more than could be borne without an intercessor, so that the people through fear cried out "Speak thou to us lest we die," (Exodus 20:19,) so also now does Malachi teach us, that there is need of an intercessor, by whom God''s wrath might be mitigated, which the Jews had extremely provoked. This office John the Baptist undertook, who prepared the Jews to hear the voice of Christ. By saying that he would send a messenger to clear his way, he indirectly reproved the Jews, by whom many hindrances were thrown as it were in the way; as though he had said, "They prevent by the obstacles they raise up the redemption and the promised salvation to be revealed: there will therefore be the need of', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 39, 4, 1, NULL, 'malachi-4', 'John Calvin', 'Commentaries', E'21 and I said, What are these coming to do? and he said, saying, Those are the horns which have scattered Judah, so that no one could raise up his head; but these are come to frighten them, to thrust away the horns of the nations, which raised the horn against the land of Judah to scatter it. (57) __________________________________________________________________ 1 And I raised my eyes and saw, and behold a man in whose hand was a measuring-line: 2 and I said, Where art thou going? And he said to me, To measure Jerusalem, that I may see what is its breadth, and what is its length. 3 And behold the angel who was speaking with me, he went forth, and another angel went forth to meet him, and said to him, 4 Run, speak to this youth, saying, -- In the villages shall dwell Jerusalem, For the number of men and cattle in it: 5 And I shall be to it, saith Jehovah, A wall of fire round about, And for glory shall I be in the midst of it 6 Ho! Ho! flee ye From the land of the north, saith Jehovah: For to the four winds of heaven Have I scattered you, saith Jehovah. (65) 7 Ho! Zion! be thou delivered, Who dwellest with the daughter of Babylon. 8 For thus saith Jehovah of hosts, After the glory hath he sent me To the nations with spoiled you: For he who touches you Touches the apple of his eye. 9 For, behold, I shake my hand over them, And they shall be a prey to their servants; And ye shall know That Jehovah of hosts hath sent me. 10 Exult and rejoice, thou daughter of Zion; For behold I am coming, And will dwell in thy midst, saith Jehovah: 11 And join themselves shall many nations To Jehovah in that day; And they shall be to me a people, And I will dwell in the midst of thee; And thou shalt know, That Jehovah of hosts has sent me to thee: 12 And Jehovah will take Judah As his hereditary portion in the holy land; And he will yet choose Jerusalem. Be silent all flesh before Jehovah; Be silent all flesh before Jehovah; Fore roused he is from his holy habitation. __________________________________________________________________ 1 And he showed me Joshua the high priest standing before the angel of Jehovah, and Satan standing at his right hand to oppose him. 2 And Jehovah said to Satan, -- Rebuke thee, Satan, let Jehovah; Yea, rebuke thee let Jehovah, Who has chosen Jehovah: Is not this a brand snatched from the fire! 3 And Joshua was clad in sordid garments, and stood before the angel: 4 and he answered and said to those who stood before him, saying, Take the sordid garments from off him: and he said to him, See I have made to pass from thee thine iniquity, and I will clothe thee with new garments. 5 And I said,', false, false, 'sourced', 'published');
