-- Calvin commentary INSERT — Ezekiel (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 1, 1, NULL, 'ezekiel-1', 'John Calvin', 'Commentaries', E'1. Now it came to pass in the thirtieth year, in the fourth month, in the fifth day of the month, as I was among the captives by the river of Chebar, that the heavens were opened, and I saw visions of God.

1. Et fuit tricesimo anno, quarto meuse quinta mensis, et ego in medio Captivitatis, super fluvium Chebar aperti sunt coeli, et vidi visiones Dei.

2. In the fifth day of the month, which was the fifth year of king Jehoiachin''s captivity.

2. In quinta mensis, ipse est annus quintus captivitatis regis Joiakim.

We see that the Prophet was called to the office of a Teacher in the fifth year after Jehoiachin had voluntarily surrendered himself to the king of Babylon, (2 Kings 24:15); and had been dragged into exile, together with his mother: for it was, says he, "in the thirtieth year." The greater part of the Commentators follow the Chaldee Paraphrast, and understand him to date from the finding of the Book of the Law. It is quite clear, flint this year was the eighteenth of king Josiah; but in my computation, I do not subscribe to the opinion of those who adopt this date. For this phrase -- "the thirtieth year," would then appear too obscure and forced. We nowhere read that succeeding writers adopted this date as a standard. Besides, there is no doubt that the usual method among the Jews was to begin to reckon from a Jubilee. For this was a point of starting for the future. I therefore do not doubt that this thirtieth year is reckoned from the Jubilee. Nor is my opinion a new one; for Jerome makes mention of it, although he altogether rejects it, through being deceived by an opposite opinion. But since it is certain that the Jews used this method of computation, and made a beginning from Jobel, that is, the Jubilee, this best explains the thirtieth year If any one should object, that we do not read that this eighteenth year of king Josiah was the usual year in which every one returned to his own lands, (Leviticus 25) and liberty was given to the slaves, and the entire restoration of the whole people took place, yet the answer is easy, although we cannot ascertain in what year the Jobel fell, it is sufficient for us to assign the Jubilee to this year, because the Jews followed the custom of numbering their years from this institution. As, then, the Greeks had their Olympiads, the Romans their Consuls, and thence their computation of annals; so also the Hebrews were accustomed to begin from the year Jobel, when they counted their years on to the next restoration, which I have just mentioned. It is therefore probable that this was a Jubilee year -- it is probable, then, that this was the Jubilee.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 2, 1, NULL, 'ezekiel-2', 'John Calvin', 'Commentaries', E'1. And he said unto me, Son of man, stand upon thy feet, and I will speak unto thee. 1. Et dixit ad me, Fili hominis sta super pedes tuos, et loquar tecum. 2. And the spirit entered into me when he spake unto me, and set me upon my feet, that I heard him that spake unto me. 2. Et venit in me spiritus cum loqueretur ad me, et statuit me super pedes meos, et audivi loquentem ad me. Here the Prophet narrates that he was chosen by the command of God. For God never prostrates his people so as to leave them lying upon the earth, but continually raises them afterwards. As to the reprobate, they are so frightened at the sight of God, that they utterly fall and never rise again. But it is different with the faithful, because the pride of the flesh is corrected in them; then God stretches forth his hand to them, and restores them, as it were, from death to life. And this difference we must mark diligently, because we see the impious often dread the voice of God. But if they disdainfully despise him when speaking, they are frightened by his hand when some signs of his wrath and vengeance appear: but yet they remain lifeless. In like manner the faithful dread the voice of God, but the result is altogether different, as we see here: because after God has humbled them, he commands them to be of good courage, and shows that he intended nothing else but to establish them by his power. At the same time the Prophet teaches that nothing was accomplished by this voice till the Spirit was added. God indeed works efficiently by his own words, but we must hold that this efficacy is not contained in the words themselves, but proceeds from the secret instinct of the Spirit. The Prophet therefore shows us both truths. On one side he says, I heard the voice of God, so that I stood on my feet: God thus wished to animate his confidence: but he adds that he was not raised up by the voice, until the Spirit placed him on his feet This work of the Spirit, then, is joined with the word of God. But a distinction is made, that we may know that the external word is of no avail by itself, unless animated by the power of the Spirit. If any one should object, that the word was useless, because not efficacious by itself, the solution is at hand, that if God takes this method of acting there is no reason why we should object to it. But we have a still clearer reply: since God always works in the hearts of men by the Spirit, yet his word is not without fruit; because, as God enlightens us by the sun, and yet he alone is the Father of Lights, and the splendor of the sun is profitless except as God uses it as', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 3, 1, NULL, 'ezekiel-3', 'John Calvin', 'Commentaries', E'1. Moreover he said unto me, Son of man, eat that thou findest; eat this roll, and go speak unto the house of Israel.

1. Et dixit mihi, Fili hominis, quod inveneris, comedendo comede, volumen hoc, et vade loquere ad domum Israel.

2. So I opened my mouth, and he caused me to eat that roll.

2. Et aperui os meum, et pavit me volumine isto.

When the Prophet is ordered to eat whatever he receives, this ought not to be extended to everything which he meets with, but, whatever may be the taste of the book, he is forbidden to refuse it: for its bitterness might possibly cause him to reject the threats of God. Lastly, the quality of the book is noted, because it contained nothing but the material for sorrow. He adds, that he opened his mouth, for the sake of obedience; by which he signifies that he was not curious or dainty in seeking to taste it, but that he took what was divinely offered him, without the slightest hesitation. Now he adds -- __________________________________________________________________

3. And he said unto me, Son of man, cause thy belly to eat, and fill thy bowels with this roll that I give thee. Then did I eat it; and it was in my mouth as honey for sweetness.

3. Et dixit mihi, Fili hominis, ventrem tuum pasce, et viscera tua reple volumine isto, quod ego do tibi, et comedi, et fuit in ore meg tanquam mel in dulcedine.

Ezekiel, as we have just seen, proceeds to say, that a book was given him to eat, because God''s servants ought to speak from the inmost affection of their heart. We know that many have a tongue sufficiently fluent, but use it only for ostentation: meanwhile, God treats their vanity as a laughing stock, because their labor is fruitless. Hence we must observe the passage of Paul already quoted, "the kingdom of God is with power." (1 Corinthians 4:20.) But the efficacy of the Holy Spirit is not exerted unless when he who is called to teach applies his serious endeavors to attain to the discharge of his duty. For this reason, then, Ezekiel is commanded to eat the roll Next he says, it was as sweet as honey; and, but a little before, he said it was filled with curses: therefore, either he had put off all humanity, or ought to be grieved, when he found himself appointed to be the herald of God''s vengeance. But, in other places, we saw that the servants of God were endued with feelings of an opposite kind; for, as they were often rough and stern like their work, so they condoled with the miserable people: but, their grief did not hinder them from proceeding in the discharge of their duty.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 4, 1, NULL, 'ezekiel-4', 'John Calvin', 'Commentaries', E'1. Thou also, son of man, take thee a tile, and lay it before thee, and pourtray upon it the city, even Jerusalem: 1. Et tu, Fili hominis, sume tibi laterem, et pone ipsum coram facie tua, et pinge super ipsum urbem, nempe Hierosolymam: 2. And lay siege against it, and build a fort against it, and cast a mount against it; set the camp also against it, and set battering rams against it round about. 2. Et pone contra eam obsidionem, et extrue contra eam turrim, et funde adversus eam aggerem, et pone adversus eam castra, et statue contra eam arietes in circuitu. 3. Moreover take thou unto thee an iron pan, and set it for a wall of iron between thee and the city: and set thy face against it, and it shall be besieged, and thou shalt lay siege against it. This shall be a sign to the house of Israel. 3. Et tu sume tibi patenam vel sartaginem ferream, et pone illam murum ferreum inter to et inter urbem: et obfirma faciem tuam adversus eam vel contra ex opposito, et sit in obsidionem, et obsidebis eam. Hoe signum domui Israel. Here God begins to speak more openly by means of his servant, and not to speak only, but to signify by an outward symbol what he wishes to be uttered by his mouth. Hence he orders the Prophet to paint Jerusalem on a brick Take therefore, he says, a brick, and place it in thy sight: then paint on it a city, even Jerusalem This is one command: then erect a tower against it. He describes the form of ancient warfare; for then when they wished to besiege cities, they erected mounds from which they filled up trenches: then they moved about wooden towers, so that they might collect the soldiers into close bands, and they had other machines which are not now in use. For fire-arms took away that ancient art of warfare. But God here Simply wishes the picture of a city to be besieged by Ezekiel. Then he orders him to set up a pan or iron plate, like a wall of iron This had been a childish spectacle, unless God had commanded the Prophet to act so. And hence we infer, that sacraments cannot be distinguished from empty shows, unless by the word of God. The authority of God therefore is the mark of distinction, by which sacraments excel, and have their weight and dignity, and whatever men mingle with them is frivolous. For this reason we say that all the pomps of which the Papal religion is full are mere trifles. Why so? because men have thought out whatever dazzles the eyes of the simple, without any command of God. But if any one now objects, that the water in baptism cannot penetrate as far as the soul, so as to purge it of inward and hidden filth, we have this ready answer: baptism ought not to be considered in its', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 5, 1, NULL, 'ezekiel-5', 'John Calvin', 'Commentaries', E'1. And thou, son of man, take thee a sharp knife, take thee a barber''s razor, and cause it to pass upon thine head and upon thy beard: then take thee balances to weigh, and divide the hair

1. Et tu, fili hominis, sume tibi gladium acutum, novaculum tonsorum, sume eum tibi, et transire fac, super caput tuum, et super barbam tuam: et sume tibi stateram ponderis, et divide illa.

2. Thou shalt burn with fire a third part in the midst of the city, when the days of the siege are fulfilled: and thou shalt take a third part, and smite about it with a knife: and a third part thou shalt scatter in the wind; and I will draw out a sword after them.

2. Tertiam partem igne combures in medio urbis, ut completi fuerint dies obsidionis: sumes tertiam partem, percuties gladio per circuitum ejus, tertiam vero partem sparges in ventum: et gladium evaginabo post eos.

3. Thou shalt also take thereof a few in number, and bind them in thy skirts.

3. Et sumes inde exiguum in numero, et ligabis illa in alis tuis.

4. Then take of them again, and cast them into the midst of the fire, and burn them in the fire; for thereof shall a fire come forth into all the house of Israel.

4. Et ex illis adhuc sumes, et projicies illa in medium ignis mittes et combures illa igne, unde egredetur ignis in totum domum Israel.

By another vision God confirms what he had lately taught concerning the siege of Jerusalem. For he orders the Prophet to shave the hairs off his head and his beard, then to distribute them into three parts, and to weigh them in a balance. He mentions a just balance, that equity may be preserved, and that one portion may not surpass another. There is no doubt that by the hairs he understands the inhabitants of Jerusalem, as by the head he understands the seat itself of their dwelling-place. Then the application will follow; but this I shall pass by today, because I cannot proceed farther. It is sufficient to hold briefly, that men are here designated by hairs, for hair can scarcely be counted, indeed that of the beard is countless; such was the multitude at Jerusalem, for we know that the city was very populous. We know, again, that it took occasion for pride from this; when they saw that they were strong in the multitude of their people, they thought themselves equal, if not superior, to all enemies, and hence their foolish confidence, which destroyed them. God then commanded the Prophet to shave off all the hairs of his head and of his beard. Thus he taught that not even one man should escape the slaughter, because he says, make the sword pass, or pass it, over thy head, then over thy chin, so that nothing may remain.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 6, 1, NULL, 'ezekiel-6', 'John Calvin', 'Commentaries', E'1. And the word of the LORD came unto me, saying, 1. Et fuit sermo Iehovæ ad me dicendo, 2. Son of man, set thy face toward the mountains of Israel, and prophesy against them, 2. Fili hominis, pone faciem tuam ad montes Israel, et prophetiza ad eos, 3. And say, Ye mountains of Israel, hear the word of the Lord GOD; Thus saith the Lord GOD to the mountains, and to the hills, to the rivers, and to the valleys; Behold, I even I, will bring a sword upon you, and I will destroy your high places. 3. Et dic, Montes Israel audite sermonem Dominatoris Iehovæ: sic dicit Dominator Iehovah montibus et collibus, rivis et vallibus: ecce ego adducem contra vos gladium, et perdam excelsa vestra. The Prophet now turns himself to the kingdom of Israel, since he had formerly spoken concerning the Jews alone. He says that he was divinely sent to the mountains of Israel. The first question may arise about the time; for the kingdom of Israel had been cut off, and the ten tribes dragged into exile- and the kingdom had come to an end in Ezekiel''s time. The time, therefore, does not seem to accord with the denunciation of the Prophet as to what had happened many years previously. But nothing will appear out of place, if we say that it was partly prophecy and partly doctrine, so that the Israelites might understand why they were driven out of their country, and dispersed among the nations. I say that God''s plans were partly explained to the exiles, that they might know why God had driven them to distant lands: for this punishment would not have been useful had not God convinced them of its cause. But although the kingdom had fallen, it is probable that some of the people were remaining: for the Assyrian did not carry off so many thousand men, and his kingdom would have been burdened by such a multitude. Doubtless he collected the flower of the people, and permitted the commonalty to remain there: for he sent from his own kingdom inhabitants for the deserted soil. But the change was great and ruinous to the king himself, and vexatious to all alike. Although, therefore, the kingdom did not exist any longer -- nay, even the name of Israel was almost extinct, because there was no mass of people, and they dwelt in their country like foreigners and guests, yet there was still some portion of them left. Now, we collect from the words of the Prophet that they were obstinate, because they were not induced by either the exile of their brethren, or their own calamity, to leave their own superstitions, and embrace the true and pure worship of God. Since, therefore, this chastisement did not profit them, hence the Prophet is ordered to preach against them It is ascertained from the first chapter that Ezekiel received this command after the destruction of the kingdom of Israel, (Ezekiel 1:1, 2)', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 7, 1, NULL, 'ezekiel-7', 'John Calvin', 'Commentaries', E'1. Moreover, the word of the LORD came unto me, saying,

1. Et fuit sermo Iehovæ ad me, dicendo,

2. Also, thou son of man, thus saith the Lord GOD unto the land of Israel; An end, the end is come upon the four corners of the land.

2. Et tu fili hominis, sic dicit Dominator Iehovah terrae Israel, vel de terra; finis, venit finis super quatuor alas terrae.

Ezekiel seems here too verbose; for he repeats the same sentiments almost in the same words. But the reason which I have brought forward must be marked, if God had only uttered his commands shortly, when the people were not only slow to believe but of a perverse disposition, his message had proved cold and ineffectual. With this design he uses, as we have seen, many words, and now repeats the same: he now changes his expression, because he ought by all means to stimulate that sloth, or rather sluggishness, under which the people labored. Another thing to be noted is, that he came not once only by God''s command to preach to the people, but. that he was often sent to stir up their minds. For if he had included in one context what God had enjoined, the Israelites might for the time have thought of God''s judgment, but a prophecy once uttered would have easily escaped them. Besides, when Ezekiel testifies that he was sent by God, and afterwards returns and affirms that he brings new commands, this was more effectual to influence their minds. Now we see the meaning of the phrase, the word was given by Jehovah For this prophecy is distinguished from the former, and yet the matter is the same, without any difference, as it seems to weave in with the same discourse: this, indeed, is true, but he ought to be sent twice, that the people may understand that not once only, but twice and perpetually, what he heard from God''s mouth was to be repeated: since it was sufficiently clear, that God was anxious for their safety, since he never ceased to exhort them. Thus, therefore, says the Lord Jehovah concerning the land of Israel: an end is coming, an end upon the four corners of the land Here God seems to regard the moderate punishments which he had already inflicted on the kingdom of Israel. For we know that they often felt God''s hand, but when some relaxation was afforded them, they thought themselves escaped, so they forgot their wickedness and went on in it so carelessly that it was very clear that they despised God, unless when he oppressed them with his dreadful power. This seems the meaning of the word end, and it is emphatically repeated: an end is coming, an end upon the four corners of the land He puts, indeed, wings, but intends it metaphorically for four different regions.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 8, 1, NULL, 'ezekiel-8', 'John Calvin', 'Commentaries', E'1. And it came to pass in the sixth year, in the sixth month, in the fifth day of the month, as I sat in mine house, and the elders of Judah sat before me, that the hand of the Lord GOD fell there upon me. 1. Et fuit anno sexto, mense sexto, die quinto mensis, ego sedebam domi meae, et Seniores Jehudah sedentes coram facie mea, et cecidit super me illic manus Dominatoris Iehovae. There is no doubt that a prophetic vision is here narrated; for the Prophet was not carried to Jerusalem, nor had he changed his place, nor were the elders of Judah before him, but he seemed to himself to be seized by the Spirit of God, that he might perceive the pollutions by which the Jews had profaned the temple. For he says, that he was at home when this vision occurred to him, and yet it was possible for him to be walking in the field. He does not, therefore, relate the thing as done, but simply teaches how God appeared, and adds the circumstances. By elders of Judah I do not understand captives, but those who were then dwelling at Jerusalem, that they should be witnesses of this prophecy, and so all excuse and pretense of mistake was taken away from them. He also expresses the time at which this vision happened, namely the sixth year, which he numbers from the exile of Jechoniah, as we saw in the first chapter. Hence an interval of a year and two months has elapsed since the first vision which was then unfolded, and the present which is now to be treated. Since, therefore, fourteen months had elapsed, God appeared again to his Prophet. This circumstance of the time is by no means superfluous, for this shows the great obstinacy of the people. The Prophet, as I have said, numbers the years from the exile of the king. But they were accustomed to count from the jubilee year; but he now renews the grief for that slaughter, when the king was treated ignominiously as a vile captive, and was harassed as a slave by the enemy. Since, therefore, the Prophet humbles the Jews by this computation of years, hence it appears how hardened was their obstinacy, as they did not grow wise though so severely chastened. But we shall see that they were seized with a prodigious madness, so that they cast aside the worship of God, they heaped together on every side new idolatries, and infected the temple with their abominations. We saw in Jeremiah (Jeremiah 7:17, and Jeremiah 44:17-19) that the worship of God was overthrown in the city Jerusalem, and in the temple itself; for they poured out libations to the workmanship of heaven -- others translate, the queen of heaven, but we have shown that those places ought to be understood of all the stars -- since, therefore, they offered incense to the workmanship of heaven, then they afterwards took to themselves', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 9, 1, NULL, 'ezekiel-9', 'John Calvin', 'Commentaries', E'1. He cried also in mine ears with a loud voice, saying, Cause them that have charge over the city to draw near, even every man with his destroying weapon in his hand.

1. Et clamavit voce magna in aure mea dicendo, appropinquate praefecturae urbis: et quisque instrumentum perditionis suae in manu sua.

Now the manner of that vengeance which was lately mentioned is expressed. Hence the Prophet says, God exclaimed, so that his command reached to the Chaldeans, who were to be executors of his vengeance, and therefore the imperative mood pleases me better, approach ye therefore. Those who consider the tense past say "visitations," nor can they do otherwise, because no sense can be elicited from the words -- to have approached the prefecture of the city. But if we read the imperative mood, the sense agrees very well, approach ye the prefecture: the thing is put for the persons, or the name of the men may be understood, and thus phqdvt, phekdoth, may be taken in the genitive case. As to the general meaning, God commands his servants who held authority over the devoted city, to approach, or apply themselves, or be ready to fulfill his work, and let each, says he, have his instrument of destruction: here destruction is taken actively. For God does not mean that the Chaldeans were armed for their own destruction, but for that of the Jews, and the ruin of the city. It follows -- __________________________________________________________________

That is, "in my hearing." -- Calvin.

Some translate "they have approached" in the past tense, but the other rendering seems to me to suit better, as God commands to approach; "approach ye therefore." -- Calvin

Others translate, "visitations." -- Calvin.

We must understand, "let him have." -- Calvin.

That is, "his warlike instrument of destruction." -- Calvin. __________________________________________________________________

2. And, behold, six men came from the way of the higher gate, which lieth toward the north, and every man a slaughter-weapon in his band; and one man among them was clothed with linen, with a writer''s inkhorn by his side: and they went in, and stood beside the brasen altar.

2. Et ecce sex viri venientes e via portae superioris quae est e regione aquilonis: et cuique instrumentum mallei sui in manu sua: et vir unus in medio ipsorum vestitus lineis, et atramentarium scribae in lumbis ejus: et venerunt, et steterunt e regione altaris aenei.

Now the Prophet writes that God''s command was not vain or empty, because the effect appears directly by vision. Therefore six men offered themselves. Why again he names six, rather than more or fewer, I have not found out. For some cite the thirty-ninth chapter of Jeremiah, where eight leaders are referred to who were in Nebuchadnezzar''s army, and had the chief authority; but first they vary in number, then they twist themselves in many ways.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 10, 1, NULL, 'ezekiel-10', 'John Calvin', 'Commentaries', E'1. Then I looked, and, behold, in the firmament that was above the head of the cherubims there appeared over them as it were a sapphire stone, as the appearance of the likeness of a throne.

1. Et aspexi, et ecce super expansionem quae erat super caput cherubim tanquam lapis sapphiri, sicut aspectus similitudinis solii quod videbatur super cos.

Here the Prophet relates another vision which has a great likeness to the first which he related to us in the first chapter, but it has another object, as we shall soon see. Since we discussed the chief members of the vision in the first chapter, I shall now therefore be shorter. I shall only glance at what I formerly said, and at the same time point out any difference. But before we descend to that, God''s design in this vision must be understood. God wished to bear witness to the Jews that he had nothing further in common with them, because he intended to leave the temple, and then to consume the whole city with burning. But lest this threat should be unheeded by the Jews, God''s majesty was placed before them so fearfully that it might strike even the obstinate with fear. Now I come to the words. He says, that he saw again over the heads of the cherubim a throne, whose color was like sapphire Instead of living creatures he now puts cherubim, and there is no doubt that those living creatures of which he formerly spoke were cherubim. But because the vision occurs in the temple, God begins familiarly to explain to his servant what was previously too obscure. For he had seen the four living creatures near the river Chebar, namely, in a profane country. When therefore the Jews and Israelites were absent as exiles far from the temple, it is no wonder that God did not appear so clearly to his Prophet as he now does when brought into the temple. For although the Prophet has not changed his place, yet he does not seem to have been transferred to Jerusalem in vain, and to behold what was done in the temple. This is the reason why he now calls those cherubim which he had before called simply living creatures. But we have explained why four cherubim were seen, while only two were in the sanctuary, namely, because the Jews were almost buried in gross ignorance. They had long ago departed from the pursuit of sincere piety, and the light of celestial doctrine had been almost extinct among them. Since, therefore, the ignorance of the people was so gross, something rude must be put before them, or otherwise they could not understand what they ought to learn.

Now it is by no means doubtful that God obliquely wishes to reprove that base ignorance, because it was not his fault that they did not perceive in the law and the temple whatever was useful to be known for their salvation.', false, false, 'sourced', 'published');
