-- Calvin commentary INSERT — 1 Corinthians (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 1, 1, NULL, '1-corinthians-1', 'John Calvin', 'Commentaries', E'1. Paul, called to be an Apostle In this manner does Paul proceed, in almost all the introductions to his Epistles, with the view of procuring for his doctrine authority and favor. The former he secures to himself from the station that had been assigned to him by God, as being an Apostle of Christ sent by God; the latter by testifying his affection towards those to whom he writes. We believe much more readily the man whom we look upon as regarding us with affection, and as faithfully endeavoring to promote our welfare. In this salutation, therefore, he claims for himself authority, when he speaks of himself as an Apostle of Christ, and that, too, as called by God, that is, set apart by the will of God Now, two things are requisite in any one that would be listened to in the Church, and would occupy the place of a teacher; for he must be called by God to that office, and he must faithfully employ himself in the discharge of its duties. Paul here lays claim to both. For the name, Apostle, implies that the individual conscientiously acts the part of an ambassador for Christ (2 Corinthians 5:19), and proclaims the pure doctrine of the gospel. But as no one ought to assume this honor to himself, unless he be called to it, he adds, that he had not rashly intruded into it, but had been appointed to it by God. Let us learn, therefore, to take these two things together when we wish to ascertain what kind of persons we ought to esteem as ministers of Christ, -- a call to the office, and faithfulness in the discharge of its duties. For as no man can lawfully assume the designation and rank of a minister, unless he be called, so it were not enough for any one to be called, if he does not also fulfill the duties of his office. For the Lord does not choose ministers that they may be dumb idols, or exercise tyranny under pretext of their calling, or make their own caprice their law; but at the same time marks out what kind of persons they ought to be, and binds them by his laws, and in fine chooses them for the ministry, or, in other words, that in the first place they may not be idle, and, secondly, that they may confine themselves within the limits of their office. Hence, as the apostleship depends on the calling, so the man who would be reckoned an apostle, must show himself to be really such: nay more, so must every one who demands that credit be given him, or that his doctrine be listened to. For since Paul rests on these arguments for establishing his authority, worse than impudent were the conduct of that man who would think to have any standing without such proofs. It ought, however, to be observed, that it is not enough for any one to hold out', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 2, 1, NULL, '1-corinthians-2', 'John Calvin', 'Commentaries', E'1. And I, when I came Paul having begun to speak of his own method of teaching, had straightway fallen into a discussion as to the nature of gospel preaching generally. Now again he returns to speak of himself, to show that nothing in him was despised but what belonged to the nature of the gospel itself, and did in a manner adhere to it. He allows therefore that he had not had any of the aids of human eloquence or wisdom to qualify him for producing any effect, but while he acknowledges himself to be destitute of such resources, he hints at the inference to be drawn from this -- that the power of God shone the more illustriously in his ministry, from its standing in no need of such helps. This latter idea, however, he will be found bringing forward shortly afterwards. For the present he simply grants that he has nothing of human wisdom, and in the meantime reserves to himself this much -- that he published the testimony of God Some interpreters, indeed, explain the testimony of God in a passive sense; but as for myself, I have no doubt that another interpretation is more in accordance with the Apostle''s design, so that the testimony of God is that which has come forth from God -- the doctrine of the gospel, of which he is the author and witness. He now distinguishes between speech and wisdom (logon apo tos sophias.) Hence what I noticed before is here confirmed -- that hitherto he has not been speaking of mere empty prattling, but has included the entire training of human learning. 2. For I did not reckon it desirable. As krinein, in Greek, has often the same meaning as eklegein, that is to choose out anything as precious, there is, I think, no person of sound judgment but will allow that the rendering that I have given is a probable one, provided only the construction admits of it. At the same time, if we render it thus -- "No kind of knowledge did I hold in esteem," there will be nothing harsh in this rendering. If you understand something to be supplied, the sentence will run smoothly enough in this way -- "Nothing did I value myself upon, as worth my knowing, or on the ground of knowledge." At the same time I do not altogether reject a different interpretation -- viewing Paul as declaring that he esteemed nothing as knowledge, or as entitled to be called knowledge, except Christ alone. Thus the Greek preposition and, would, as often happens, require to be supplied. But whether the former interpretation is not disapproved of, or whether this latter pleases better, the substance of the passage amounts to this: "As to my wanting the ornaments of speech, and wanting, too, the more elegant refinements of discourse, the reason of this was, that I did not aspire at them, nay rather, I despised them, because there was one thing only that', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 3, 1, NULL, '1-corinthians-3', 'John Calvin', 'Commentaries', E'1. And I, brethren He begins to apply to the Corinthians themselves, that he had said respecting carnal persons, that they may understand that the fault was their own -- that the doctrine of the Cross had not more charms for them. It is probable, that in mercantile minds like theirs there was too much confidence and arrogance still lingering, so that it was not without much ado and great difficulty that they could bring themselves to embrace the simplicity of the gospel. Hence it was, that undervaluing the Apostle, and the divine efficacy of his preaching, they were more prepared to listen to those teachers that were subtle and showy, while destitute of the Spirit. Hence, with the view of beating down so much the better their insolence, he declares, that they belong to the company of those who, stupefied by carnal sense, are not prepared to receive the spiritual wisdom of God. He softens down, it is true, the harshness of his reproach by calling them brethren, but at the same time he brings it forward expressly as a matter of reproach against them, that their minds were suffocated with the darkness of the flesh to such a degree that it formed a hindrance to his preaching among them. What sort of sound judgment then must they have, when they are not fit and prepared as yet even for hearing! He does not mean, however, that they were altogether carnal, so as to have not one spark of the Spirit of God -- but that they had still greatly too much of carnal sense, so that the flesh prevailed over the Spirit, and did as it were drown out his light. Hence, although they were not altogether destitute of grace, yet, as they had more of the flesh than of the Spirit, they are on that account termed carnal This sufficiently appears from what he immediately adds -- that they were babes in Christ; for they would not have been babes had they not been begotten, and that begetting is from the Spirit of God.

Babes in Christ This term is sometimes taken in a good sense, as it is by Peter, who exhorts us to be like new-born babes, (1 Peter 2:2,) and in that saying of Christ,

Unless ye become as these little children, ye shall not enter into the kingdom of God, (Luke 18:17.)

Here, however, it is taken in a bad sense, as referring to the understanding. For we must be children in malice, but not in understanding, as he says afterwards in 1 Corinthians 14:20, -- a distinction which removes all occasion of doubt as to the meaning. To this also there is a corresponding passage in Ephesians 4:14.

That we be no longer children tossed to and fro with every wind of doctrine, and made the sport of human fallacies, but may day by day grow up, etc

2.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 4, 1, NULL, '1-corinthians-4', 'John Calvin', 'Commentaries', E'1. Let a man so account of us As it was a matter of no little importance to see the Church in this manner torn by corrupt factions, from the likings or dislikings that were entertained towards individuals, he enters into a still more lengthened discussion as to the ministry of the word. Here there are three things to be considered in their order. In the first place, Paul describes the office of a pastor of the Church. Secondly, he shows, that it is not enough for any one to produce a title, or even to undertake the duty -- a faithful administration of the office being requisite. Thirdly, as the judgment formed of him by the Corinthians was preposterous, he calls both himself and them to the judgment-seat of Christ. In the first place, then, he teaches in what estimation every teacher in the Church ought to be held. In this department he modifies his discourse in such a manner as neither, on the one hand, to lower the credit of the ministry, nor, on the other, to assign to man more than is expedient. For both of these things are exceedingly dangerous, because, when ministers are lowered, contempt of the word arises, while, on the other hand, if they are extolled beyond measure, they abuse liberty, and become "wanton against the Lord." (1 Timothy 5:11.) Now the medium observed by Paul consists in this, that he calls them ministers of Christ; by which he intimates, that they ought to apply themselves not to their own work but to that of the Lord, who has hired them as his servants, and that they are not appointed to bear rule in an authoritative manner in the Church, but are subject to Christ''s authority -- in short, that they are servants, not masters.

As to what he adds -- stewards of the mysteries of God, he expresses hereby the kind of service. By this he intimates, that their office extends no farther than this, that they are stewards of the mysteries of God In other words, what the Lord has committed to their charge they deliver over to men from hand to hand -- as the expression is -- not what they themselves might choose. "For this purpose has God chosen them as ministers of his Son, that he might through them communicate to men his heavenly wisdom, and hence they ought not to move a step beyond this." He appears, at the same time, to give a stroke indirectly to the Corinthians, who, leaving in the background the heavenly mysteries, had begun to hunt with excessive eagerness after strange inventions, and hence they valued their teachers for nothing but profane learning. It is an honorable distinction that he confers upon the gospel when he terms its contents the mysteries of God. But as the sacraments are connected with these mysteries as appendages, it follows, that those who have the charge of administering the word are the authorized stewards of them also.

2.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 5, 1, NULL, '1-corinthians-5', 'John Calvin', 'Commentaries', E'1. It is generally reported that there is among you. Those contentions having originated, as has been observed, in presumption and excessive confidence, he most appropriately proceeds to make mention of their diseases, the knowledge of which should have the effect of humbling them. First of all, he shows them what enormous wickedness it is to allow one of their society to have an illicit connection with his mother-in-law. It is not certain, whether he had seduced her from his father as a prostitute, or whether he kept her under pretense of marriage. This, however, does not much affect, the subject in hand; for, as in the former case, there would have been an abominable and execrable whoredom, so the latter would have involved an incestuous connection, abhorrent to all propriety and natural decency. Now, that he may not seem to charge them on doubtful suspicions, he says, that the case which he brings forward is well known and in general circulation. For it is in this sense that I take the particle holos (generally) as intimating that it was no vague rumor, but a matter well known, and published everywhere so as to cause great scandal.

From his saying that such a kind of whoredom was not named even among the Gentiles, some are of opinion, that he refers to the incest of Reuben, (Genesis 35:22,) who, in like manner, had an incestuous connection with his mother-in-law. They are accordingly of opinion, that Paul did not make mention of Israel, because a disgraceful instance of this kind had occurred among them, as if the annals of the Gentiles did not record many incestuous connections of that kind! This, then, is an idea that is quite foreign to Paul''s intention; for in making mention of the Gentiles rather than of the Jews, he designed rather to heighten the aggravation of the crime. "You," says he, "permit, as though it were a lawful thing, an enormity, which would not be tolerated even among the Gentiles -- nay more, has always been regarded by them with horror, and looked upon as a prodigy of crime." When, therefore, he affirms that it was not named among the Gentiles, he does not mean by this, that no such thing had ever existed among them, or was not recorded in their annals, for even tragedies have been founded upon it; but that it was held in detestation by the Gentiles, as a shameful and abominable monstrosity, for it is a beastly lust, which destroys even natural modesty. Should any one ask, "Is it just to reproach all with the sin of one individual?" I answer, that the Corinthians are accused, not because one of their number has sinned, but because, as is stated afterwards, they encouraged by connivance a crime that was deserving of the severest punishment.

2.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 6, 1, NULL, '1-corinthians-6', 'John Calvin', 'Commentaries', E'1. Dare any of you This is the first statement -- that, if any one has a controversy with a brother, it ought to be decided before godly judges, and that it ought not to be before those that are ungodly. If the reason is asked, I have already said, that it is because disgrace is brought upon the gospel, and the name of Christ is held up as it were to the scoffings of the ungodly. For the ungodly, at the instigation of Satan, are always eagerly on the watch for opportunities of finding occasion of calumny against the doctrine of godliness. Now believers, when they make them parties in their disputes, seem as though they did on set purpose furnish them with a handle for reviling. A second reason may be added -- that we treat our brethren disdainfully, when we of our own accord subject them to the decisions of unbelievers.

But here it may be objected: "As it belongs to the office of the magistrate, and as it is peculiarly his province to administer justice to all, and to decide upon matters in dispute, why should not even unbelievers, who are in the office of magistrate, have this authority, and, if they have it, why are we prevented from maintaining our rights before their tribunals?" I answer, that Paul does not here condemn those who from necessity have a cause before unbelieving judges, as when a person is summoned to a court; but those who, of their own accord, bring their brethren into this situation, and harass them, as it were, through means of unbelievers, while it is in their power to employ another remedy. It is wrong, therefore, to institute of one''s own accord a law-suit against brethren before unbelieving judges. If, on the other hand, you are summoned to a court, there is no harm in appearing there and maintaining your cause.

2. Know ye not that the saints. Here we have an argument from the less to the greater; for Paul, being desirous to show that injury is done to the Church of God when judgments on matters of dispute connected with earthly things are carried before unbelievers, as if there were no one in the society of the godly that was qualified to judge, reasons in this strain: "Since God has reckoned the saints worthy of such honor, as to have appointed them to be judges of the whole world, it is unreasonable that they should be shut out from judging as to small matters, as persons not qualified for it." Hence it follows, that the Corinthians inflict injury upon themselves, in resigning into the hands of unbelievers the honor that has been conferred upon them by God.

What is said here as to judging the world ought to be viewed as referring to that declaration of Christ:

When the Son of Man shall come, ye shall sit, etc.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 7, 1, NULL, '1-corinthians-7', 'John Calvin', 'Commentaries', E'1. It is good for a man. The answer consists of two parts. In the first, he teaches that it were good for every one to abstain from connection with a woman, provided it was in his power to do so. In the second, he subjoins a correction to this effect, that as many cannot do this, in consequence of the weakness of their flesh, these persons must not neglect the remedy which they have in their power, as appointed for them by the Lord. Now we must observe what he means by the word good, when he declares that it is good to abstain from marriage, that we may not conclude, on the other hand, that the marriage connection is therefore evil -- a mistake which Jerome has fallen into, not so much from ignorance, in my opinion, as from the heat of controversy. For though that great man was endowed with distinguished excellences, he labored, at the same time, under one serious defect, that when disputing he allowed himself to be hurried away into great extravagancies, so that he did not keep within the bounds of truth. The inference then which he draws is this "It is good not to touch a woman: it is therefore wrong to do so." Paul, however, does not make use of the word good here in such a signification as to be opposed to what is evil or vicious, but simply points out what is expedient on account of there being so many troubles, vexations, and anxieties that are incident to married persons. Besides, we must always keep in view the limitation which he subjoins. Nothing farther, therefore, can be elicited from Paul''s words than this -- that it is indeed expedient and profitable for a man not to be bound to a wife, provided he can do otherwise. Let us explain this by a comparison. Should any one speak in this way: "It were good for a man not to eat, or to drink, or to sleep" -- he would not thereby condemn eating, or drinking, or sleeping, as things that were wrong -- but as the time that is devoted to these things is just so much taken from the soul, his meaning would be, that we would be happier if we could be free from these hindrances, and devote ourselves wholly to meditation on heavenly things. Hence, as there are in married life many impediments which keep a man entangled, it were on that account good not to be connected in marriage.

But here another question presents itself, for these words of Paul have some appearance of inconsistency with the words of the Lord, in Genesis 2:18, where he declares, that it is not good for a man to be without a wife.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 8, 1, NULL, '1-corinthians-8', 'John Calvin', 'Commentaries', E'1. Concerning things offered unto idols. He begins with a concession, in which he voluntarily grants and allows to them everything that they were prepared to demand or object. "I see what your pretext is: you make Christian liberty your pretext. You hold out that you have knowledge, and that there is not one of you that is so ignorant as not to know that there is but one God. I grant all this to be true, but of what avail is that knowledge which is ruinous to the brethren?" Thus, then, he grants them what they demand, but it is in such a way as to show that their excuses are empty and of no avail.

Knowledge puffeth up He shows, from the effects, how frivolous a thing it is to boast of knowledge, when love is wanting. "Of what avail is knowledge, that is of such a kind as puffs us up and elates us, while it is the part of love to edify?" This passage, which otherwise is somewhat obscure, in consequence of its brevity, may easily be understood in this way -- "Whatever is devoid of love is of no account in the sight of God; nay more, it is displeasing to him, and much more so what is openly at variance with love Now that, knowledge of which you boast, O ye Corinthians, is altogether opposed to love, for it puffs up men with pride, and leads to contempt of the brethren, while love is concerned for the welfare of brethren, and exhorts us to edify them. Accursed, then, be that knowledge which makes men proud, and is not regulated by a desire of edifying."

Paul, however, did not mean, that this is to be reckoned as a fault attributable to learning -- that those who are learned are often self-complacent, and have admiration of themselves, accompanied with contempt of others. Nor did he understand this to be the natural tendency of learning -- to produce arrogance, but simply meant to show what effect knowledge has in an individual, that has not the fear of God, and love of the brethren; for the wicked abuse all the gifts of God, so as to exalt themselves. Thus riches, honors, dignities, nobility, beauty, and other things of that nature, puff up; because men, elated through a mistaken confidence in these things, very frequently become insolent. Nor is it always so; for we see that many who are rich and beautiful, and abounding in honors, and distinguished for dignity and nobility, are, nevertheless, of a modest disposition, and not at all tainted with pride. And even when it does happen to be so, it is, nevertheless, not proper that we should put the blame upon what we know to be gifts of God; for in the first place that were unfair and unreasonable; and farther, by putting the blame upon things that are not blameworthy, we would exempt the persons themselves from blame, who alone are in fault.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 9, 1, NULL, '1-corinthians-9', 'John Calvin', 'Commentaries', E'1. Am I not free? He confirms by facts what he had stated immediately before, -- that he would rather never taste of flesh during his whole life, than give occasion of stumbling to a brother, and, at the same time, he shows that he requires nothing more from them than what he had himself practiced. And, assuredly, natural equity requires that whatever law is imposed by any one upon others, should be submitted to by himself. More especially a Christian teacher should impose upon himself this necessity, that he may have it always in his power to confirm his doctrine by an exemplary life. We know by experience, that it is a very unpleasant thing that Paul required from the Corinthians -- to refrain, for the sake of their brethren, from making use of the liberty that was allowed them. He could scarcely have demanded this, if he had not taken the lead and shown them the way. And he had, it is true, promised that he would do this, but, as he might not be believed by all on his simply promising for the future, he makes mention of what he had already done. He brings forward a remarkable instance, in respect of his having denied himself the liberty which he might otherwise have used, purely in order that he might give the false Apostles no occasion for calumniating. He had preferred to earn his food with his own hands, rather than be supported at the expense of the Corinthians, to whom he administered the Gospel.

He treats, however, at great length of the right of the Apostles to receive food and clothing. This he does, partly for the purpose of stirring them up the more to forego many things for the sake of their brethren after his example, because they were unduly tenacious in the retaining of their own rights, and partly for the purpose of exposing more fully in view the unreasonableness of calumniators, who took occasion for reviling from what was anything but blameworthy. He speaks, also, interrogatively, in order to press the matter home more closely. The question -- Am I not free? is of a general nature. When he adds -- Am I not an Apostle? he specifies a particular kind of liberty. "If I am an Apostle of Christ, why should my condition be worse than that of others?" Hence he proves his liberty on the ground of his being an Apostle.

Have I not seen Jesus Christ? He expressly adds this, in order that he may not be reckoned inferior in any respect, to the other Apostles, for this one thing the malevolent and envious bawled out on all occasions -- that he had received from the hands of men whatever he had of the gospel, inasmuch as he had never seen Christ. And, certainly, he had not had converse with Christ while he was in the world, but Christ had appeared to him after his resurrection.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 46, 10, 1, NULL, '1-corinthians-10', 'John Calvin', 'Commentaries', E'1. All were under the cloud. The Apostle''s object is to show, that the Israelites were no less the people of God than we are, that we may know, that we will not escape with impunity the hand of God, which punished them with so much severity. For the sum is this -- "If God spared not them, neither will he spare you, for your condition is similar." That similarity he proves from this -- that they had been honored with the same tokens of God''s grace, for the sacraments are badges by which the Church of God is distinguished. He treats first of baptism, and teaches that the cloud, which protected the Israelites in the desert from the heat of the sun, and directed their course, and also their passage through the sea, was to them as a baptism; he says, also, that in the manna, and the water flowing from the rock, there was a sacrament which corresponded with the sacred Supper.

They were, says he, baptized in Moses, that is, under the ministry or guidance of Moses. For I take the particle eis to be used here instead of en, agreeably to the common usage of Scripture, because we are assuredly baptized in the name of Christ, and not of any mere man, as he has stated in 1 Corinthians 1:13, and that for two reasons. These are, first, because we are by baptism initiated into the doctrine of Christ alone; and, secondly, because his name alone is invoked, inasmuch as baptism is founded on his influence alone. They were, therefore, baptized in Moses, that is, under his guidance or ministry, as has been already stated. How? In the cloud and in the sea. "They were, then, baptized twice," some one will say. I answer, that there are two signs made mention of, making, however, but one baptism, corresponding to ours.

Here, however, a more difficult question presents itself. For it is certain, that the advantage of those gifts, which Paul makes mention of, was temporal. The cloud protected them from the heat of the sun, and showed them the way: these are outward advantages of the present life. In like manner, their passage through the sea was attended with this effect, that they got clear off from Pharaoh''s cruelty, and escaped from imminent hazard of death. The advantage of our baptism, on the other hand, is spiritual. Why then does Paul turn earthly benefits into sacraments, and seek to find some spiritual mystery in them? I answer, that it was not without good reason that Paul sought in miracles of this nature something more than the mere outward advantage of the flesh. For, though God designed to promote his people''s advantage in respect of the present life, what he had mainly in view was, to declare and manifest himself to be their God, and under that, eternal salvation is comprehended.

The cloud, in various instances, is called the symbol of his presence.', false, false, 'sourced', 'published');
