-- Calvin commentary INSERT — Titus (batch 1, rows 1-3)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 56, 1, 1, NULL, 'titus-1', 'John Calvin', 'Commentaries', E'1. A servant of God This extended and laborious commendation of his apostleship shows that Paul had in view the whole Church, and not Titus alone; for his apostleship was not disputed by Titus, and Paul is in the habit of proclaiming the titles of his calling, in order to maintain his authority. Accordingly, just as he perceives those to whom he writes to be disposed, he deals largely or sparingly in those ornaments. Here his design was, to bring into subjection those who had haughtily rebelled; and for this reason he extols his apostleship in lofty terms. He therefore writes this Epistle, not that it may be read in solitude by Titus in his closet, but that it may be openly published.

An Apostle of Jesus Christ First, he calls himself "a servant of God," and next adds the particular kind of his ministry, namely, that he is "an Apostle of Christ;" for there are various ranks among the servants of God. Thus he descends from the general description to the particular class. We ought also to keep in remembrance what I have said elsewhere, that the word servant means something else than ordinary subjection, (on account of which all believers are called "servants of God,") and denotes a minister who has received a particular office. In this sense the prophets were formerly distinguished by this title, and Christ himself is the chief of the prophets:

"Behold my servant, I have chosen him." (Isaiah 42:1.)

Thus David, with a view to his royal dignity calls himself "a servant of God." Perhaps, also, it is on account of the Jews that he designates himself "a servant of God;" for they were wont to lower his authority by alleging the law against him. He therefore wishes to be accounted an Apostle of Christ in such a manner that he may likewise glory in being a servant of the eternal God. Thus he shows not only that those two titles are quite consistent with each other, but that they are joined by a bond which cannot be dissolved.

According to the faith of the elect of God If any one doubt about his apostleship, he procures credit for it by a very strong reason, connecting it with the salvation "of the elect of God." As if he had said, "There is a mutual agreement between my apostleship and the faith of the elect of God; and, therefore, it will not be rejected by any man who is not a reprobate and opposed to the true faith."

By "the elect" he means not only those who were at that time alive, but all that had been from the beginning of the world; for he declares that he teaches no doctrine which does not agree with the faith of Abraham and of all the fathers. So, then, if any person in the present day wishes to be accounted a successor of Paul, he must prove that he is the minister of the same doctrine.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 56, 2, 1, NULL, 'titus-2', 'John Calvin', 'Commentaries', E'1. But speak thou the things which become sound doctrine He points out the remedy for driving away fables, namely, that Titus should devote himself to edification. He gives the appellation of sound doctrine to that which may instruct men to godliness; for all trifles vanish away, when that which is solid is taught. When he enjoins him to speak those things which agree with "sound doctrine," it is as if he had said, that Titus must be continually employed in this preaching; for to mention these things once or twice would not be enough. And Paul does not speak of the discourse of a single day; but so long as Titus shall hold the office of pastor, he wishes him to be employed in teaching this doctrine. "Sound doctrine" is so called from the effect produced by it; as, on the contrary, he says, that unskillful men dote about questions which do no good. Sound, therefore, means wholesome, that which actually feeds souls. Thus, by a single word, as by a solemn proclamation, he banishes from the Church all speculations which serve rather to promote ostentation than to aid godliness, as he did in both of the Epistles to Timothy. He makes "sound doctrine" to consist of two parts. The first is that which magnifies the grace of God in Christ, from which we may learn where we ought to seek our salvation; and the second is that by which the life is framed to the fear of God, and inoffensive conduct. Although the former, which includes faith, is far more excellent, and therefore ought to be more zealously inculcated; yet Paul, in writing to Timothy, was not careful about attending to order; for he had to deal with an intelligent man, to whom he would offer an insult, if he dictated to him word by word, as is usually done to apprentices or beginners. Under the person of Titus, indeed, he instructs the whole church of Crete; yet he attends to the rules of propriety, that he may not appear to distrust his prudence. Besides, the reason why he is longer in his exhortations is, that they who gave their whole attention to idle questions -- needed especially to be exhorted to the practice of a good and holy life; for nothing is better fitted to restrain the wandering curiosity of men than to know in what duties they ought to be employed. 2. That aged men be sober He begins with particular duties, that the discourse may be better adapted to the instruction of the people. And he does so, not only that he may accommodate himself to their capacity, but that he may press every one more closely; for a general doctrine produces a less powerful impression; but when by holding out a few cases, he has instructed every person about his duty, there is no one who may not easily conclude, that the Lord has sufficiently instructed him as to the work in which he', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 56, 3, 1, NULL, 'titus-3', 'John Calvin', 'Commentaries', E'1 Remind them to be subject to principalities and powers From many passages it is evident that the Apostles had great difficulty in keeping the common people subject to the authority of magistrates and princes. We are all by nature desirous of power; and the consequence is, that no one willingly is subject to another. Besides, perceiving that nearly all the principalities and powers of the world were at that time opposed to Christ they thought them unworthy of receiving any honor. The Jews especially, being an untamable race, did not cease to mutiny and rage. Thus, after having spoken of particular duties, Paul now wishes to give a general admonition to all, to observe peaceably the order of civil government, to submit to the laws, to obey magistrates. That subjection to princes, and that obedience to magistrates, which he demands, is extended to edicts, and laws, and other parts of civil government.

What he immediately adds, To be ready for every good work, may be applied to the same subject, as if he had said, "All who do not refuse to lead a good and virtuous life, will cheerfully yield obedience to magistrates." For, since they have been appointed for the preservation of mankind, he who desires to have them removed, or shakes off their yoke, is an enemy of equity and justice, and is therefore devoid of all humanity. Yet if any prefer to interpret it without any immediate relation to the context, I have no objection; and indeed there can be no doubt that, in this sentence, he recommends to them kind offices towards their neighbors throughout their whole life.

2 To speak evil of no one He now lays down the method of maintaining peace and friendship with all men. We know that there is nothing to which the disposition of every man is more prone than to despise others in comparison of himself. The consequence is, that many are proud of the gifts of God; and this is accompanied by contempt for their brethren, which is immediately followed by insult. He therefore forbids Christians to glory over others, or to reproach them, whatever may be their own superior excellence. Yet he does not wish them to flatter the vices of wicked men; he only condemns the propensity to slander.

Not given to fighting As if he had said, "Quarrels and contentions must be avoided." The old translation has therefore rendered it better, Not quarrelsome; for there are other ways of fighting than the sword or the fist. And from what follows it is evident that this is the meaning; for he points out the remedies for the evil, when he enjoins them to be kind, and to shew all meekness towards all men; for "kindness" is contrasted with the utmost rigor of law, and "meekness" with bitterness.', false, false, 'sourced', 'published');
