-- Calvin commentary INSERT — Deuteronomy (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 1, 1, NULL, 'deuteronomy-1', 'John Calvin', 'Commentaries', E'1. These are the words. These two latter passages properly belong to the supplements, wherein God afterwards more clearly and familiarly illustrated the Law previously given by Him; they comprehend also exhortations, by which He subdued the people''s minds to obedience, and eulogies, by which He commended and confirmed the Law. The sum is, that Moses is appointed the minister and ambassador of God, who by his mouth prescribes to Israel all that is right and just. But when he says, "beside the covenant, which he made with them in Horeb," (Deuteronomy 29:1,) necessary that the Decalogue should be more fully explained, lest its brevity should render it obscure to an ignorant and slow-hearted people. For God did not, like earthly kings, learn from experience to enrich His law by new precepts, but considered the people''s dull and weak understanding. The particle of exception, "beside," does not, therefore, designate anything additional, but only signifies that God had again repeated His covenant, that it might be more distinctly and certainly understood. In which respect He gave an extraordinary proof of His indulgence, that previous to their entering the land, He renewed His covenant about forty years after its first promulgation, and added a clear exposition of it, because He had then to do with a new generation. For this reason the place is expressly mentioned, because from thence the lapse of time is made evident. __________________________________________________________________', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 2, 1, NULL, 'deuteronomy-2', 'John Calvin', 'Commentaries', E'1. Then we turned and took our journey. The time in which they struck their camp is not stated in the book of Numbers. This verse, therefore, will aptly connect the history, since otherwise there would be an abruptness in what immediately follows, he then briefly indicates what was the nature of their journeying until the time appointed; viz., that, by wearying themselves in vain in circuitous wanderings, they might, at length, learn to follow God directly, and not to decline from the way which He points out. __________________________________________________________________', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 3, 1, NULL, 'deuteronomy-3', 'John Calvin', 'Commentaries', E'4. And we took all the cities. He here more fully relates what He had brieflytouched upon in Numbers. He says that sixty, well-fortified cities were taken, besides the villages. Hence we infer both the extent of the country, and also the special power of God in the aid He afforded them, in that they took, in so short a time, so many cities well closed in, and begirt with high walls; as if they were merely travelling, through a peaceful land in security, and with nothing to do.

After the eighth verse, lie repeats connectedly what he had separately related respecting the two kingdoms; and in order that the places might be more certainly identified, he mentions two other names for mount Hermon, stating that it was called Sirion by the Sidonians, and Shenir by the Amorites. Finally, he adds that Og, king of Bashan, was a giant, and the only survivorof that race. As a memorialof his lofty stature, he alleges his iron bedstead, the length of which was as much as nine cubits, according to the common measure of that period. By this circumstance he again magnifies the marvellous help of God, in that he was overcome by the children of Israel, who might, by his stature, have singly terrified a whole army.

The enormous stature of the giants is apparent from this passage. Herodotus records, that the body of Orestes, disinterred by command of the oracle, was seven cubits in length. Pliny, although he does not cite his authority, subscribes to this testimony. Gellius thinks that this was fabulous, as also what Homer writes with respect to the diminution of men''s height in process of time; but his erroneous view is confuted by almost universal consent. What Pliny himself relates is indeed incredible, that in Crete a body was discovered, by an opening of the earth, forty-six cubits long, which some thought to be the body of Orion, and others of Etion. But if we believe that there were giants, (which is not only affirmd by the sacred Scriptures, but also recorded by almost all ancient writers,) we need not be surprised if they were more than eight cubits in height. Although, however, the race of giants began to disappear in the time of Moses, still, in after ages, there existed persons who approached to this ancient stature, as in the time of Augustus and Claudius there was one man about ten feet in height, and another nine feet nine inches. Moses, therefore, intimates nothing more than that this monstrous race of men gradually died out, so that the enormous height of Og, king of Bashan, was an unusual sight. __________________________________________________________________

Herod, Clio, Section 68.

Homer, I1. lib. 12:381-3, 446-9; lib. 20:286, 7.

Fr. "Comme sous l''empire d''Auguste il y avoit un homme haut de dix pieds, et sous l''empire de Claude un un peu moindre;" as under the empire of Augustus there was a man ten feet high, and, under that of Claudius, one somewhat shorter.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 4, 1, NULL, 'deuteronomy-4', 'John Calvin', 'Commentaries', E'44. And this is the Law. This last passage refers to the same thing, viz., that the Law was promulgated anew when the people had now reached the threshold of the promised land, in order that they might be more disposed to obedience, especially when the two tribes and a half had now, by the conquest of the Amorites, obtained a resting-place and a home; for this is the reason why their habitation is mentioned, because the taste of the favor already received ought to stir up their zeal to proceed more cheerfully. We shall elsewhere remark on the country and names of places. It is sufficient here to recollect, that the memory of the Law was renewed, after their inheritance without the promised land had been obtained by the sons of Reuben and Gad, and half the tribe of Manasseh, and when their assured possession was before the eyes of the rest. But Moses shews that, although he might explain the Law at fuller length, still nothing had been added to that summary which was originally promulgated; but he rather indicates, that whatever he had taught them during the forty years, had had no other object than that they might more faithfully and exactly keep the Law of God. __________________________________________________________________ __________________________________________________________________

The First Commandment

3. Thou shalt have no other gods before me.

3. Non erunt tibi dii alieni coram facie mea.

A REPETITION OF THE SAME

7. Thou shalt have none other gods before me.

7. Non erunt tibi dii alieni coram facie mea. __________________________________________________________________

Exodus 20:3 Thou shalt have no other gods before me. In this commandment God enjoins that He alone should be worshipped, and requires a worship free from all superstition. For although it seems to be a simple prohibition, yet must we deduce an affirmation from the negative, as will be more apparent from the following words. Therefore does He set Himself before them, in order that the Israelites may look to Him alone; and claims His own just right, in order that it may not be transferred elsewhere. All do not agree in the exposition of the words, for some construe the word phnym, panim, "anger," as if it were said, "Thou shalt not make to thyself other gods to provoke my anger;" and I admit that the Hebrew word is often used in this sense. The other interpretation, however, seems to me the more correct, "Make not to thyself gods before my face." Yet still there remains a difference of opinion, for people are not agreed as to the particle l, gnel. Some explain it, "Make not to thyself gods above me, or whom thou mayest prefer to me;" and they quote the passage in Deuteronomy 21:15-17, wherein God forbids a man, if he have two wives, and children by both, to transfer the rights of primogeniture to the second before the face of the first-born.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 5, 1, NULL, 'deuteronomy-5', 'John Calvin', 'Commentaries', E'22. These words the Lord spoke. That there may be no doubt about the authority of the law, and that it may not be depreciated by the people, Moses recalls to their memory that the presence of God, as He spoke it, was manifested by sure tokens; for this was the object of the fire, the clouds, and the darkness, whereby God''s voice was signalized, lest its source might be obscure. He adds, that it was "a great voice," i.e., a voice which had, in an unwonted manner, penetrated far and wide. Nor are the witnesses few, whom he cites, but all that vast multitude, which for the most part would have been more disposed to extinguish the glory of God, unless it had been there made known by manifest proofs. The sum is, that there is no question as to who was the Lawgiver, whose majesty was then proclaimed by tremendous prodigies, and presented before the eyes of an immense multitude. It will be more convenient to speak elsewhere of the two tables. When Moses states that God "added no more," he signifies that a perfect rule of life is contained in the ten commandments, and that, when their instruction is fully received, the whole body of wisdom is attained to, so that the people need seek to know no more; when God, then, made an end of speaking, he Himself laid down the bounds of legitimate inquiry.

23. And it came to pass, when ye heard. Lest the Israelites should undervalue his teaching, because he had been put between them by God as their minister, Moses meets the objection, (by reminding them) that it was done at their petition and request. We know how proudly they were wont to reject him; as if they saw in him nothing but what was earthly and human; it was needful, then, that God Himself should speak to rescue His servant from the contempt of posterity. For the people themselves, being convicted of their foolish and preposterous request, could never afterwards have any pretext for rejecting Moses, as if he had not evidenced the truth of his calling. And here their astonishing perverseness betrayed itself, in not being ashamed to refuse credit to the holy Prophet, after he had been approved by so many miracles. Assuredly, if they had been just and honest judges, it would have been sufficiently notorious, and certain to them, that Moses did not speak of himself, or of his own impulse, but that he was the organ of the Spirit; yet the doctrine of God was scorned by these proud, and perverse, and fretful beings, because it was brought to them by the hands of a mortal man. They, therefore, by their importunate desires, draw down God from heaven, to speak Himself; but immediately terror seizes on their minds, so that they flee from His voice.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 6, 1, NULL, 'deuteronomy-6', 'John Calvin', 'Commentaries', E'13. ... shalt swear by his name.

13. Per nomen ejus jurabis.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 7, 1, NULL, 'deuteronomy-7', 'John Calvin', 'Commentaries', E'6. For thou art a holy people. He explains more distinctly what we have lately seen respecting God''s gratuitous love; for the comparison of the fewness of the people with the whole world and all nations, illustrates in no trifling degree the greatness of God''s grace; and this subject is considerably enlarged upon. Almost the same expressions will very soon be repeated, and also in the Song of Moses; but there by way of reproof, whilst here it is directed to a different object, as is plain from the context, viz., that they might be, by so great a blessing, laid under obligation to devote themselves and their services to God. He begins by declaring the end of their election, viz., that God had deigned to bestow this peculiar honor upon them that He might acquire unto Himself a holy people, pure from all pollutions, and then, by adding the circumstance I have adverted to, he magnifies the excellence of the benefit. From his argument drawn from their dignity, that they ought therefore to labor after holiness, we gather, that in proportion to the abundance of grace with which any one is endued, he is solemnly bound to live piously and justly. For God does not wish the gifts he bestows upon us to lie idle, but to produce their appropriate fruits; and we must especially remember that when He adopts us, and gathers us into His Church, we are not "called to uncleanness," but to purity of life, and to shew forth the praises of him who hath called us out of darkness into his marvellous light." (1 Thessalonians 4:7, and 1 Peter 2:9.) The Hebrew word sglh, segullah, which we translate "peculiaris," special, some understand to mean a "treasure," or a precious and desirable thing, as was stated on Exodus 19. Undoubtedly it appears from many passages that gold, silver, pearls, and the like, are designated by this word; but substantially it is agreed that this title is given to the elect people, because God delights Himself in them; and herein His incomparable goodness shines forth, that He so highly esteems such miserable and worthless creatures, (homunciones.) Hence, too, it appears that by His holy calling He, as it were, creates out of nothing "things which are not," that they may excel every earthly being.

7. The Lord did not set his love upon you. He proves it to be of God''s gratuitous favor, that He has exalted them to such high honor, because He had passed over all other nations, and deigned to embrace them alone. For an equal distribution of God''s gifts generally casts obscurity upon them in our eyes; thus the light of the sun, our common food, and other things, which all equally enjoy, either lose their value, or, at any rate, do not obtain their due honor; whilst what is peculiar is more conspicuous.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 8, 1, NULL, 'deuteronomy-8', 'John Calvin', 'Commentaries', E'1. All the commandments. Although the first verse might have been included among the promises, whereby, as we shall hereafter see, the Law was ratified by Moses, because he here exhorts and incites the Israelites to obedience by proposing to them the hope of reward; still it appeared to me that I might conveniently insert it here, since the design of Moses was simply this, to attract them by the sweetness of the promised inheritance to receive the doctrines of the Law. This sentence, then, may be justly counted among those whereby their minds were prepared to submit themselves to God with the gentleness and docility that became them; as though he had said, because the land of Canaan is now not far from you, its very nearness ought to encourage you to take upon you God''s yoke more cheerfully; for the same God, who this day declares to you His law, invites you to the enjoyment of that land, which He promised with an oath to your fathers. And certainly it is evident from this latter clause of the verse, that Moses did not simply promise them a reward if they should keep the law; but rather set before them the previous favor, wherewith God had gratuitously prevented them, in order that they might, on their part, shew themselves grateful for it Moses calls the commandments his, not (as we have already seen) because he had invented them himself, but because he faithfully handed them down from the dictation of God''s own mouth. And this we may also more fully gather from the following verse, wherein he recounts the mercies of the time past, and at the same time calls to their recollection by how many proofs God had instructed them, to form and accustom them to obedience. In the first place, he bids them remember generally the dealings of God, which they had seen for forty years, and then descends to particulars, viz., that God had proved them by afflictions, "to know what was in their heart;" for thus may the expressions be paraphrased, "to humble thee, and to prove thee, to know what was in thine heart;" in which words he admonishes them, that they were painfully tried by many troubles and difficulties not without very good reason, viz., because they had need of such trial. Yet, at the same time, he indirectly reproves their obstinacy, which was then detected; since otherwise, if all things had gone prosperously with them, it would have been easy for them to pretend great fear of God, though, as was actually discovered, it did not really exist.

3. And he humbled thee, and suffered thee to hunger. Inasmuch as they were sometimes made to suffer hunger in the wilderness, he proves the advantage of this discipline, because they thus learnt that the human race does not live by bread and wine alone, but by the secret power of God.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 9, 1, NULL, 'deuteronomy-9', 'John Calvin', 'Commentaries', E'1. Thou art to pass over Jordan this day. The whole of this passage contains an eulogy on the gratuitous liberality of God, whereby He had bound the people to Himself unto the obedience of the Law. But this (as we have already seen) ought to have been a most pressing stimulus to incite the people, and altogether to ravish them to the worship and love of God, to whom they were under so great obligation. The design of Moses, then, was to shew that the Israelites, for no merit of their own, but by the signal bounty of God, would be heirs of the land of Canaan; and that this entirely flowed from the covenant and their gratuitous adoption; in order that, on their part, they should persevere in the faithful observation of the covenant, and so should be the more disposed to honor Him. For it would be too disgraceful that they, whom God had prevented by His grace, should not meet Him, as it were, by voluntarily submitting to His dominion. Moreover, lest they should arrogate anything to themselves, he commends the greatness of God''s power, in that they could not be victorious over so many nations, unless by the miraculous aid of heaven. With this view, he states that these nations excelled not only in greatness and multitude, but also in military valor. He adds that their cities were great and impregnable; and, finally, that in them were the children of the giants, formidable from their enormous stature. For Anak (as is related in Joshua 15 ) was a celebrated giant, whose descendants were called Anakim. And, to take away all doubt about this, he cites themselves as witnesses, that they were so terrified by their appearance as to wish to turn back again. We now understand the object of all these details, viz., that God''s glory may shine forth in the victories and success of the people. The words "whom thou knowest, and of whom thou hast heard," have reference to the spies; for these giants had not yet become openly known to the people; but he transfers the case of a few to them all, because, by the account the spies had given, terror had invaded the whole camp, as though they had actually come into conflict with them. Since, then, they had been persuaded of their inferiority to their enemies, and utterly disheartened by the report they received, Moses convicts them on their own evidence, lest, perchance, they might hereafter assume to themselves the praise which was due to God alone. But we are taught in these words, that such is the ingratitude of mankind, that they obscure, as much as they can, God''s bounties, and never yield, except when driven to conviction.

3. Understand therefore this day.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 10, 1, NULL, 'deuteronomy-10', 'John Calvin', 'Commentaries', E'4. Hear, O Israel. When Moses proclaims that God is One, the statement is not confined to His sole essence, which is incomprehensible, but must be also understood of His power and glory, which had been manifested to the people; as though he had said, that they would be guilty of rebellion unless they abode in the One God, who had laid them under such obligations to Himself. Therefore he not only calls him Jehovah, but at the same time infers that He is the God of that people whom he addresses, "Thy God." Thus all other deities are brought to nought, and the people are commanded to fly and detest whatever withdraws their minds from the pure knowledge of Him; for although His name may be left to Him, still He is stripped of His majesty, as soon as He is mixed up with a multitude of others. Thus He says by Ezekiel, (Ezekiel 20:39,) "Go ye, serve ye every one his idols;" in which words He not only repudiates all mixed worship, but testifies that He would rather be accounted nothing than not be worshipped undividedly. The orthodox Fathers aptly used this passage against the Arians; because, since Christ is everywhere called God, He is undoubtedly the same Jehovah who declares Himself to be the One God; and this is asserted with the same force respecting the Holy Spirit.

13. Thou shalt fear the Lord thy God. Hence it is more evident why He has just declared that there is One God, viz., that He alone may be undividedly worshipped; for unless our minds are fixed on Him alone, religion is torn, as it were, into divers parts, and this is soon followed by a labyrinth of errors. But, first, he calls for reverence, and then for the worship which may testify and demonstrate it. "Fear" contains in it the idea of subjection, when men devote themselves to God, because His terrible majesty keeps them in their proper place. Hence results worship, which is the proof of piety. But we must observe that the fear enjoined in this passage is voluntary, so that men influenced by it desire nothing more than to obey God. When I stated, therefore, that God brings us under the yoke by a sense of His power and greatness, I did not understand that a violent and servile obedience is extorted from us; I only wished to affirm that men cannot be induced to obey God, before they have been subdued by fear; because their innate corruption always carries with it a contempt for religion, and a spirit of licentiousness. Therefore, in Jeremiah (Jeremiah 5:22), in order to exhort men to fear, He sets forth His terrible power in restraining the strength of the sea; but this fear leads on His true worshippers further.', false, false, 'sourced', 'published');
