-- Calvin commentary INSERT — Romans (batch 2, rows 11-16)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 45, 11, 1, NULL, 'romans-11', 'John Calvin', 'Commentaries', E'1. I say then, etc. What he has hitherto said of the blindness and obstinacy of the Jews, might seem to import that Christ at his coming had transferred elsewhere the promises of God, and deprived the Jews of every hope of salvation. This objection is what he anticipates in this passage, and he so modifies what he had previously said respecting the repudiation of the Jews, that no one might think that the covenant formerly made with Abraham is now abrogated, or that God had so forgotten it that the Jews were now so entirely alienated from his kingdom, as the Gentiles were before the coming of Christ. All this he denies, and he will presently show that it is altogether false. But the question is not whether God had justly or unjustly rejected the people; for it was proved in the last chapter that when the people, through false zeal, had rejected the righteousness of God, they suffered a just punishment for their presumption, were deservedly blinded, and were at last cut off from the covenant.

The reason then for their rejection is not now under consideration; but the dispute is concerning another thing, which is this, That though they deserved such a punishment from God, whether yet the covenant which God made formerly with the fathers was abolished. That it should fail through any perfidiousness of men, was wholly unreasonable; for Paul holds this as a fixed principle, that since adoption is gratuitous and based on God alone and not on men, it stands firm and inviolable, howsoever great the unfaithfulness of men may be, which may tend to abolish it. It was necessary that this knot should be untied, lest the truth and election of God should be thought to be dependent on the worthiness of men.

For I am also an Israelite, etc. Before he proceeds to the subject, he proves, in passing, by his own example, how unreasonable it was to think that the nation was utterly forsaken by God; for he himself was in his origin an Israelite, not a proselyte, or one lately introduced into the commonwealth of Israel. As then he was justly deemed to be one of God''s special servants, it was an evidence that God''s favor rested on Israel. He then assumes the conclusion as proved, which yet he will hereafter explain in a satisfactory manner.

That in addition to the title of an Israelite, he called himself the seed of Abraham, and mentioned also his own tribe; this he did that he might be counted a genuine Israelite, and he did the same in his Epistle to the Philippians, Philippians 3:4. But what some think, that it was done to commend God''s mercy, inasmuch as Paul sprung from that tribe which had been almost destroyed, seems forced and far-fetched.

2. God has not cast away, etc.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 45, 12, 1, NULL, 'romans-12', 'John Calvin', 'Commentaries', E'1. I therefore beseech you by the mercies (miserationes -- compassions) of God, etc. We know that unholy men, in order to gratify the flesh, anxiously lay hold on whatever is set forth in Scripture respecting the infinite goodness of God; and hypocrites also, as far as they can, maliciously darken the knowledge of it, as though the grace of God extinguished the desire for a godly life, and opened to audacity the door of sin. But this exhortation teaches us, that until men really apprehend how much they owe to the mercy of God, they will never with a right feeling worship him, nor be effectually stimulated to fear and obey him. It is enough for the Papists, if they can extort by terror some sort of forced obedience, I know not what. But Paul, that he might bind us to God, not by servile fear, but by the voluntary and cheerful love of righteousness, allures us by the sweetness of that favor, by which our salvation is effected; and at the same time he reproaches us with ingratitude, except we, after having found a Father so kind and bountiful, do strive in our turn to dedicate ourselves wholly to him.

And what Paul says, in thus exhorting us, ought to have more power over us, inasmuch as he excels all others in setting forth the grace of God. Iron indeed must be the heart which is not kindled by the doctrine which has been laid down into love towards God, whose kindness towards itself it finds to have been so abounding. Where then are they who think that all exhortations to a holy life are nullified, if the salvation of men depends on the grace of God alone, since by no precepts, by no sanctions, is a pious mind so framed to render obedience to God, as by a serious meditation on the Divine goodness towards it?

We may also observe here the benevolence of the Apostle''s spirit, -- that he preferred to deal with the faithful by admonitions and friendly exhortations rather than by strict commands; for he knew that he could prevail more with the teachable in this way than in any other.

That ye present your bodies, etc. It is then the beginning of a right course in good works, when we understand that we are consecrated to the Lord; for it hence follows, that we must cease to live to ourselves, in order that we may devote all the actions of our life to his service.

There are then two things to be considered here, -- the first, that we are the Lord''s, -- and secondly, that we ought on this account to be holy, for it is an indignity to God''s holiness, that anything, not first consecrated, should be offered to him.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 45, 13, 1, NULL, 'romans-13', 'John Calvin', 'Commentaries', E'1. Let every soul, etc. Inasmuch as he so carefully handles this subject in connection with what forms the Christian life, it appears that he was constrained to do so by some great necessity which existed especially in that age, though the preaching of the gospel at all times renders this necessary. There are indeed always some tumultuous spirits who believe that the kingdom of Christ cannot be sufficiently elevated, unless all earthly powers be abolished, and that they cannot enjoy the liberty given by him, except they shake off every yoke of human subjection. This error, however, possessed the minds of the Jews above all others; for it seemed to them disgraceful that the offspring of Abraham, whose kingdom flourished before the Redeemer''s coming, should now, after his appearance, continue in submission to another power. There was also another thing which alienated the Jews no less than the Gentiles from their rulers, because they all not only hated piety, but also persecuted religion with the most hostile feelings. Hence it seemed unreasonable to acknowledge them for legitimate princes and rulers, who were attempting to take away the kingdom from Christ, the only Lord of heaven and earth.

By these reasons, as it is probable, Paul was induced to establish, with greater care than usual, the authority of magistrates, and first he lays down a general precept, which briefly includes what he afterwards says: secondly, he subjoins an exposition and a proof of his precept.

He calls them the higher powers, not the supreme, who possess the chief authority, but such as excel other men. Magistrates are then thus called with regard to their subjects, and not as compared with each other. And it seems indeed to me, that the Apostle intended by this word to take away the frivolous curiosity of men, who are wont often to inquire by what right they who rule have obtained their authority; but it ought to be enough for us, that they do rule; for they have not ascended by their own power into this high station, but have been placed there by the Lord''s hand. And by mentioning every soul, he removes every exception, lest any one should claim an immunity from the common duty of obedience.

For there is no power, etc. The reason why we ought to be subject to magistrates is, because they are constituted by God''s ordination. For since it pleases God thus to govern the world, he who attempts to invert the order of God, and thus to resist God himself, despises his power; since to despise the providence of him who is the founder of civil power, is to carry on war with him. Understand further, that powers are from God, not as pestilence, and famine, and wars, and other visitations for sin, are said to be from him; but because he has appointed them for the legitimate and just government of the world.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 45, 14, 1, NULL, 'romans-14', 'John Calvin', 'Commentaries', E'1. Him indeed, etc. He passes on now to lay down a precept especially necessary for the instruction of the Church, -- that they who have made the most progress in Christian doctrine should accommodate themselves to the more ignorant, and employ their own strength to sustain their weakness; for among the people of God there are some weaker than others, and who, except they are treated with great tenderness and kindness, will be discouraged, and become at length alienated from religion. And it is very probable that this happened especially at that time; for the Churches were formed of both Jews and Gentiles; some of whom, having been long accustomed to the rites of the Mosaic law, having been brought up in them from childhood, were not easily drawn away from them; and there were others who, having never learnt such things, refused a yoke to which they had not been accustomed.

Now, as man''s disposition is to slide from a difference in opinion to quarrels and contentions, the Apostle shows how they who thus vary in their opinions may live together without any discord; and he prescribes this as the best mode, -- that they who are strong should spend their labor in assisting the weak, and that they who have made the greatest advances should bear with the more ignorant. For God, by making us stronger than others, does not bestow strength that we may oppress the weak; nor is it the part of Christian wisdom to be above measure insolent, and to despise others. The import then of what he addresses to the more intelligent and the already confirmed, is this, -- that the ampler the grace which they had received from the Lord, the more bound they were to help their neighbors.

Not for the debatings of questions. This is a defective sentence, as the word which is necessary to complete the sense is wanting. It appears, however, evident, that he meant nothing else than that the weak should not be wearied with fruitless disputes. But we must remember the subject he now handles: for as many of the Jews still clave to the shadows of the law, he indeed admits, that this was a fault in them; he yet requires that they should be for a time excused; for to press the matter urgently on them might have shaken their faith.

He then calls those contentious questions which disturb a mind not yet sufficiently established, or which involve it in doubts. It may at the same time be proper to extend this farther, even to any thorny and difficult questions, by which weak consciences, without any edification, may be disquieted and disturbed. We ought then to consider what questions any one is able to bear, and to accommodate our teaching to the capacity of individuals.

2. Let him who believes, etc.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 45, 15, 1, NULL, 'romans-15', 'John Calvin', 'Commentaries', E'1. We then who are strong, etc. Lest they who had made more advances than others in the knowledge of God should think it unreasonable, that more burden was to be laid on them than on others, he shows for what purpose this strength, by which they excelled others, was bestowed on them, even that they might so sustain the weak as to prevent them to fall. For as God has destined those to whom he has granted superior knowledge to convey instruction to the ignorant, so to those whom he makes strong he commits the duty of supporting the weak by their strength; thus ought all gifts to be communicated among all the members of Christ. The stronger then any one is in Christ, the more bound he is to bear with the weak.

By saying that a Christian ought not to please himself, he intimates, that he ought not to be bent on satisfying himself, as they are wont to be, who are content with their own judgment, and heedlessly neglect others: and this is indeed an admonition most suitable on the present subject; for nothing impedes and checks acts of kindness more than when any one is too much swallowed up with himself, so that he has no care for others, and follows only his own counsels and feelings.

2. Let indeed every one of us, etc. He teaches us here, that we are under obligations to others, and that it is therefore our duty to please and to serve them, and that there is no exception in which we ought not to accommodate ourselves to our brethren when we can do so, according to God''s word, to their edification.

There are here two things laid down, -- that we are not to be content with our own judgment, nor acquiesce in our own desires, but ought to strive and labor at all times to please our brethren, -- and then, that in endeavoring to accommodate ourselves to our brethren, we ought to have regard to God, so that our object may be their edification; for the greater part cannot be pleased except you indulge their humor; so that if you wish to be in favor with most men, their salvation must not be so much regarded, but their folly must be flattered; nor must you look to what is expedient, but to what they seek to their own ruin. You must not then strive to please those to whom nothing is pleasing but evil.

3. For even Christ pleased not himself, etc. Since it is not right that a servant should refuse what his lord has himself undertaken, it would be very strange in us to wish an exemption from the duty of bearing the infirmities of others, to which Christ, in whom we glory as our Lord and King, submitted himself; for he having no regard for himself, gave up himself wholly to this service.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 45, 16, 1, NULL, 'romans-16', 'John Calvin', 'Commentaries', E'3. Salute Prisca and Aquila The testimonies which he brings here in favor of some individuals, were partly intended for this end, that by honoring those who were faithful and worthy, faithfulness itself might be honored, and that they who could and would do more good than others, might have authority; and partly that they themselves might study to act in a manner corresponding to their past life, and not fail in their religious course, nor ever grow languid in their pious ardor.

It is a singular honor which he ascribes here to Prisca and Aquila, especially with regard to a woman. The modesty of the holy man does on this account more clearly shine forth; for he disdained not to have a woman as his associate in the work of the Lord; nor was he ashamed to confess this. She was the wife of Aquila, and Luke calls her Priscilla. (Acts 18:2.)

4. To whom not only I, etc. As Prisca and Aquila had not spared their life for preserving the life of Paul, he testifies that he himself was individually thankful to them: he however adds, that thanks were given them by all the Churches of Christ; and he added this that he might, by such an example, influence the Romans. And deservedly dear and precious to all the Gentiles was the life of such a man, as it was an incomparable treasure: it was therefore no wonder that all the Churches of the Gentiles thought themselves to be under obligations to his preservers.

What he adds respecting the Church in their house is worthy of being observed; for he could not have more splendidly adorned their household than by giving it the title of a Church. The word congregation, which Erasmus has adopted, I do not approve; for it is plainly evident, that Paul, by way of honor, had used the sacred name of Church.

5. Who is the first-fruit, etc. This is an allusion to the rites of the law; for as men are sanctified to God by faith, they who first offer themselves are fitly called the first-fruit. Whosoever then is called first in time to the faith, Paul allows him the prerogative of honor: yet he retains this eminence only when the end corresponds with the beginning. And doubtless it is no common honor when God chooses some for first-fruits: and there is in addition a greater and an ampler trial of faith, through a longer space of time, provided they who have first begun are not wearied in their course.

6. He again testifies his gratitude, in recording the kindness of Mary to him. Nor is there any doubt but that he commemorates these praises, in order to recommend those whom he praised to the Romans.

7.', false, false, 'sourced', 'published');
