-- Calvin commentary INSERT — 2 Thessalonians (batch 1, rows 1-3)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 53, 1, 1, NULL, '2-thessalonians-1', 'John Calvin', 'Commentaries', E'1 To the Church of the Thessalonians which is in God. As to the form of salutation, it were superfluous to speak. This only it is necessary to notice -- that by a Church in God and Christ is meant one that has not merely been gathered together under the banner of faith, for the purpose of worshipping one God the Father, and confiding in Christ, but is the work and building as well of the Father as of Christ, because while God adopts us to himself, and regenerates us, we from him begin to be in Christ. (1 Corinthians 1:30)

3 To give thanks. He begins with commendation, that he may have occasion to pass on to exhortation, for in this way we have more success among those who have already entered upon the course, when without passing over in silence their former progress, we remind them how far distant they are as yet from the goal, and stir them up to make progress. As, however, he had in the former Epistle commended their faith and love, he now declares the increase of both. And, unquestionably, this course ought to be pursued by all the pious -- to examine themselves daily, and see how far they have advanced. This, therefore, is the true commendation of believers -- their growing daily in faith and love. When he says always, he means that he is constantly supplied with new occasion. He had previously given thanks to God on their account. He says that he has now occasion to do so again, on the ground of daily progress. When, however, he gives thanks to God on this account, he declares that the enlargements, no less than the beginnings, of faith and love are from him, for if they proceeded from the power of men, thanksgiving would be pretended, or at least worthless. Farther, he shews that their proficiency was not trivial, or even ordinary, but most abundant. So much the more disgraceful is our slowness, inasmuch as we scarcely advance one foot during a long space of time.

As is meet. In these words Paul shews that we are bound to give thanks to God, not only when he does us good, but also when we take into view the favors bestowed by him upon our brethren. For wherever the goodness of God shines forth, it becomes us to extol it. Farther, the welfare of our brethren ought to be so dear to us, that we ought to reckon among our own benefits everything that has been conferred upon them. Nay more, if we consider the nature and sacredness of the unity of Christ''s body, such a mutual fellowship will have place among us, that we shall reckon the benefits conferred upon an individual member as gain to the whole Church. Hence, in extolling God''s benefits, we must always have an eye to the whole body of the Church.

4 So that we ourselves glory in you.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 53, 2, 1, NULL, '2-thessalonians-2', 'John Calvin', 'Commentaries', E'1 Now I beseech you, by the coming. It may indeed be read, as I have noted on the margin, concerning the coming, but it suits better to view it as an earnest entreaty, taken from the subject in hand, just as in 1 Corinthians 15:31, when discoursing as to the hope of a resurrection, he makes use of an oath by that glory which is to be hoped for by believers. And this has much more efficacy when he adjures believers by the coming of Christ, not to imagine rashly that his day is at hand, for he at the same time admonishes us not to think of it but with reverence and sobriety. For it is customary to adjure by those things which are regarded by us with reverence. The meaning therefore is, "As you set a high value on the coming of Christ, when he will gather us to himself, and will truly perfect that unity of the body which we cherish as yet only in part through means of faith, so I earnestly beseech you by his coming not to be too credulous, should any one affirm, on whatever pretext, that his day is at hand."

As he had in his former Epistle adverted to some extent to the resurrection, it is possible that some fickle and fanatical persons took occasion from this to mark out a near and fixed day. For it is not likely that this error had taken its rise earlier among the Thessalonians. For Timothy, on returning thence, had informed Paul as to their entire condition, and as a prudent and experienced man had omitted nothing that was of importance. Now if Paul had received notice of it, he could not have been silent as to a matter of so great consequence. Thus I am of opinion, that when Paul''s Epistle had been read, which contained a lively view of the resurrection, some that were disposed to indulge curiosity philosophized unseasonably as to the time of it. This, however, was an utterly ruinous fancy, as were also other things of the same nature, which were afterwards disseminated, not without artifice on the part of Satan. For when any day is said to be near, if it does not quickly arrive, mankind being naturally impatient of longer delay, their spirits begin to languish, and that languishing is followed up shortly afterwards by despair.

This, therefore, was Satan''s subtlety: as he could not openly overturn the hope of a resurrection with the view of secretly undermining it, as if by pits underground, he promised that the day of it would be near, and would soon arrive. Afterwards, too, he did not cease to contrive various things, with the view of effacing, by little and little, the belief of a resurrection from the minds of men, as he could not openly eradicate it.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 53, 3, 1, NULL, '2-thessalonians-3', 'John Calvin', 'Commentaries', E'2 That we may be delivered. The old interpreter has rendered it, not unhappily, in my opinion -- unreasonable Now, by this term, as also by that which immediately follows, (ton poneron,) evil, Paul means wicked and treacherous men, who lurked in the Church, under the name of Christians, or at least Jews, who with a mad zeal for the law furiously persecuted the gospel. He knew, however, how much danger impended over them from both these classes. Chrysostom, however, thinks that those only are meant who maliciously oppose the gospel by base doctrines, -- not by weapons of violence, as for example, Alexander, Hymeneus, and the like; but for my part, I extend it generally to all kinds of dangers and enemies. He was at that time proceeding towards Jerusalem, and wrote in the midst of his journeyings. Now, he had already been divinely forewarned that imprisonments and persecutions awaited him there. (Acts 20:23.) He means, however, deliverance, so that he may come off victorious, whether by life or by death.

All have not faith. This might be explained to mean, "Faith is not in all." This expression, however, were both ambiguous and more obscure. Let us therefore retain Paul''s words, by which he intimates that faith is a gift of God that is too rare to be found in all. God, therefore, calls many who do not come to him by faith. Many pretend to come to him, who have their heart at the farthest distance from him. Farther, he does not speak of all indiscriminately, but merely animadverts upon those that belong to the Church: for the Thessalonians saw that very many held faith in abhorrence; nay, they saw how small was the number of believers. Hence it would have been unnecessary to say this as to strangers; but Paul simply says that all that make a profession of faith are not such in reality. Should you take in all Jews, they appeared to have nearness to Christ, for they ought to have recognized him by means of the law and the prophets. Paul, there can be no question specially marks out those with whom he would have to do. Now, it is probable that they were those who, while they had the appearance and honorary title of piety, were nevertheless very far from the reality. From this came the conflict.

With the view of shewing, therefore, that it was not groundlessly, or without good reason, that he dreaded contests with wicked and perverse men, he says that faith is not common to all, because the wicked and reprobate are always mixed with the good, as tares are with the good wheat. (Matthew 13:25.) And this ought to be remembered by us whenever we have annoyance given us by wicked persons, who nevertheless desire to be reckoned as belonging to the society of Christians -- that all men have not faith.', false, false, 'sourced', 'published');
