-- Calvin commentary INSERT — Nahum (batch 1, rows 1-3)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 34, 1, 1, NULL, 'nahum-1', 'John Calvin', 'Commentaries', E'1.. The burden of Nineveh. The book of the vision of Nahum the Elkoshite.

1. Onus Nineveh: Liber visionis Nahum Helkosi:

Though a part of what is here delivered belongs to the Israelites and to the Jews, he yet calls his Book by what it principally contains; he calls its the burden of Nineveh Of this word ms'', mesha, we have spoken elsewhere. Thus the Prophets call their prediction, whenever they denounce any grievous and dreadful vengeance of God: and as they often threatened the Jews, it hence happened, that they called, by way of ridicule, all prophecies by this name ms'', mesha, a burden. But yet the import of the word is suitable. It is the same thing as though Nahum had said that he was sent by God as a herald, to proclaim war on the Ninevites for the sake of the chosen people. The Israelites may have hence learnt how true and unchangeable God was in his covenant; for he still manifested his care for them, though they had by their vices alienated themselves from him.

He afterwards adds, sphr chzvn, sapher chezun, the book of the vision This clause signifies, that he did not in vain denounce destruction on the Ninevites, because he faithfully delivered what he had received from God. For if he had simply prefaced, that he threatened ruin to the Assyrian,, some doubt might have been entertained as to the event. But here he seeks to gain to himself authority by referring to God''s name; for he openly affirms that he brought nothing of his own, but that this burden had been made known to him by a celestial oracle: for chzh, cheze, means properly to see, and hence in Hebrew a vision is called chzvn, chezun,. But the Prophets, when they speak of a vision, do not mean any fantasy or imagination, but that kind of revelation which is mentioned in Numbers 14, where God says, that he speaks to his Prophets either by vision or by dream. We hence see why this was added -- that the burden of Nineveh was a vision; it was, that the Israelites might know that this testimony respecting God''s vengeance on their enemies was not brought by a mortal man, and that there might be no doubt but that God was the author of this prophecy.

Nahum calls himself an Elkoshite. Some think that it was the name of his family. The Jews, after their manner, say, that it was the name of his father; and then they add this their common gloss, that Elkos himself was a Prophet: for when the name of a Prophet''s father is mentioned, they hold that he whose name is given was also a Prophet. But these are mere trifles: and we have often seen how great is their readiness to invent fables.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 34, 2, 1, NULL, 'nahum-2', 'John Calvin', 'Commentaries', E'1. He that dasheth in pieces is come up before thy face: keep the munition, watch the way, make thy loins strong, fortify thy power mightily

1. Ascendit destructor coram facie tua; custodi munitionem, respice viam, robora lumbos, fortifica vires valde:

2. For the LORD hath turned away the excellency of Jacob, as the excellency of Israel: for the emptiers have emptied them out, and marred their vine branches.

2. Quia abstulit (alii vertunt, recedere fecit; alii, quiescere fecit) Jehova fortitudinem (alii, superbiam) Jacob, sicuti fortitudinem (vel, superbiam, est idem nomen) Israel; quia evacuarunt avacuantes, et palmites eorum succiderunt.

The waster spoken of here by the Prophet, some consider him to have been Sennacherib, and others, Nebuchodonosor. The verb lh, ole, is also variously explained: it is often taken metaphorically in Hebrew for vanishing, as we say in French, Il s''en va en fumee; for smoke ascends, and this is the reason for the metaphor. They then elicit this meaning, -- that a destroyer had ascended before the face of the chosen people, that is, openly; so that it was evidently the work of God, that the Assyrians vanished, who had come to lay waste the whole land: Vanished then has the destroyer; and then before thy face, that is, manifestly, and before thine eyes. mtsvrh ntsvr, nutsur metsure, guard the fortress; that is let every one return to his own city, and keep watch, as it is usually done; for the country shall be left without men; and watch the way, that is, look out which way Sennacherib took in coming to assail the holy city; that way shall be now free from enemies; and then, keep firm or strengthen the loins, for chzq, chesek, sometimes means to keep firm, -- keep firm then or strengthen the loins, that thou mayest not relax as before, but stand courageously, for there is no one who can terrify thee; and, lastly, fortify strength greatly, that is, doubt not but thou shalt be hereafter strong enough to retain thy position; for cut off shall be that monarchy, which has been an oppression to thee. But others take a different view and say, -- that the destroyer had ascended, that is, that Sennacherib had come; and what follows, they think, was intended to strike terror, as though the Prophet said "Now while ye are besieged keep watch, and be careful to preserve your fortresses and strengthen all your strongholds; but all this will avail nothing. -- Why? Because God has taken away the pride of Jacob as he has the pride of Israel." This is the second explanation. Others again think, that the Prophet addresses here the Assyrians, and that Nebuchodonosor is here called a waster, by whom the empire was removed, and Nineveh, as it has often been stated, was destroyed.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 34, 3, 1, NULL, 'nahum-3', 'John Calvin', 'Commentaries', E'1. Woe to the bloody city! it is all full of lies and robbery; the prey departeth not;

1. O urbs sanguinaria! Tota mendacio (vertunt) rapina plena est; non recedit praeda (vel, non recedet praeda.)

The Prophet, as I have said, more clearly expresses here the reason why the vengeance of God would be so severe on the Ninevites, -- because they had wholly given themselves up to barbarous cruelty; and hence he calls it the bloody city. Bloody city! he says. The exclamation is emphatical. Though hv, eu, sometimes means Woe; yet it is put here as though the Prophet would have constrained Nineveh to undergo its punishment, O sanguinary city, then, the whole of it is full of kchs cachesh: the word signifies leanness and the Prophet no doubt joins here together two words, which seem to differ widely, and yet they signify the same thing. For phrq, perek, means to lay by; and kchs, cachesh, is taken for a lie or vanity, when there is nothing solid in what is said: but the Prophet, I doubt not, means by both words the spoils of the city Nineveh. It was then full of leanness for it had consumed all others; it was also full of spoils, for it had filled itself. But the meaning of the Prophet is in no way dubious; for at length he adds, Depart shall not the prey; that is as some think, it shall not be withdrawn from the hands of conquerors; but others more correctly think that a continued liberty in plundering is intended, that the Assyrians were constantly employed in pillaging and kept within no bounds.

We hence see that the Prophet now shows why God says, that he would be an adversary to the Ninevites, because he could not endure its unjust cruelty. He bore with it indeed for a time; for he did not immediately execute his judgment; but yet he never forgot his own people.

As, then, God has once declared by the mouth of his Prophet that he would be the avenger of the cruelty which the Assyrians had exercised, let us know that he retains still his own nature; and whatever liberty he may for a time grant to tyrants and savage wild beasts, he yet continues to be a just avenger. It is our duty calmly to bear injuries, and to groan to him; and as he promises to be at length our helper, it behaves us to flee to him, and to ask him to succor us, so that seeing his Church oppressed, and tyrants exercising licentiously their power, he may hasten the time to restrain them. If then we were at all times to continue thus resigned under God''s protection, there is no doubt but that he would be ready even at this day to execute a similar judgment to that which the city Nineveh and its people had to endure. __________________________________________________________________

Grant, Almighty God.', false, false, 'sourced', 'published');
