-- Calvin commentary INSERT — Colossians (batch 1, rows 1-4)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 51, 1, 1, NULL, 'colossians-1', 'John Calvin', 'Commentaries', E'1 Paul an Apostle. I have already, in repeated instances, explained the design of such inscriptions. As, however, the Colossians had never seen him, and on that account his authority was not as yet so firmly established among them as to make his private name by itself sufficient, he premises that he is an Apostle of Christ set apart by the will of God. From this it followed, that he did not act rashly in writing to persons that were not known by him, inasmuch as he was discharging an embassy with which God had intrusted him. For he was not bound to one Church merely, but his Apostleship extended to all. The term saints which he applies to them is more honorable, but in calling them faithful brethren, he allures them more willingly to listen to him. As for other things, they may be found explained in the foregoing Epistles.

3. We give thanks to God. He praises the faith and love of the Colossians, that it may encourage them the more to alacrity and constancy of perseverance. Farther, by shewing that he has a persuasion of this kind respecting them, he procures their friendly regards, that they may be the more favourably inclined and teachable for receiving his doctrine. We must always take notice that he makes use of thanksgiving in place of congratulation, by which he teaches us, that in all our joys we must readily call to remembrance the goodness of God, inasmuch as everything that is pleasant and agreeable to us is a kindness conferred by him. Besides, he admonishes us, by his example, to acknowledge with gratitude not merely those things which the Lord confers upon us, but also those things which he confers upon others.

But for what things does he give thanks to the Lord? For the faith and love of the Colossians. He acknowledges, therefore, that both are conferred by God: otherwise the gratitude were pretended. And what have we otherwise than through his liberality? If, however, even the smallest favors come to us from that source, how much more ought this same acknowledgment to be made in reference to those two gifts, in which the entire sum of our excellence consists?

To the God and Father. Understand the expression thus -- To God who is the Father of Christ. For it is not lawful for us to acknowledge any other God than him who has manifested himself to us in his Son. And this is the only key for opening the door to us, if we are desirous to have access to the true God. For on this account, also, is he a Father to us, because he has embraced us in his only begotten Son, and in him also sets forth his paternal favor for our contemplation.

Always for you, Some explain it thus -- We give thanks to God always for you, that is, continually. Others explain it to mean -- Praying always for you.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 51, 2, 1, NULL, 'colossians-2', 'John Calvin', 'Commentaries', E'1. I would have you know. He declares his affection towards them, that he may have more credit and authority; for we readily believe those whom we know to be desirous of our welfare. It is also an evidence of no ordinary affection, that he was concerned about them in the midst of death, that is, when he was in danger of his life; and that he may express the more emphatically the intensity of his affection and concern, he calls it a conflict. I do not find fault with the rendering of Erasmus -- anxiety; but, at the same time, the force of the Greek word is to be noticed, for agon is made use of to denote contention. By the same proof he confirms his statement, that his ministry is directed to them; for whence springs so anxious a concern as to their welfare, but from this, that the Apostle of the Gentiles was under obligation to embrace in his affection and concern even those who were unknown to him? As, however, there is commonly no love between those who are unknown to each other, he speaks slightingly of the acquaintance that is contracted from sight, when he says, as many as have not seen my face in the flesh; for there is among the servants of God a sight different from that of the flesh, which excites love. As it is almost universally agreed that the First Epistle to Timothy was written from Laodicea, some, on this account, assign to Galatia that Laodicea of which Paul makes mention here, while the other was the metropolis of Phrygia Pacatiana. It seems to me, however, to be more probable that that inscription is incorrect, as will be noticed in its proper place.

2. That their hearts may receive consolation. He now intimates what he desires for them, and shews that his affection is truly apostolic; for he declares that nothing else is desired by him than that they may be united together in faith and love. He shews, accordingly, that it was by no unreasonable affection (as happens in the case of some) that he had been led to take upon himself so great a concern for the Colossians and others, but because the duty of his office required it.

The term consolation is taken here to denote that true quietness in which they may repose. This he declares they will at length come to enjoy in the event of their being united in love and faith. From this it appears where the chief good is, and in what things it consists -- when mutually agreed in one faith, we are also joined together in mutual love. This, I say, is the solid joy of a pious mind -- this is the blessed life.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 51, 3, 1, NULL, 'colossians-3', 'John Calvin', 'Commentaries', E'1. If ye are risen with Christ. Ascension follows resurrection: hence, if we are the members of Christ we must ascend into heaven, because he, on being raised up from the dead, was received up into heaven, (Mark 16:19,) that he might draw us up with him. Now, we seek those things which are above, when in our minds we are truly sojourners in this world, and are not bound to it. The word rendered think upon expresses rather assiduity and intensity of aim: "Let your whole meditation be as to this: to this apply your intellect -- to this your mind." But if we ought to think of nothing but of what is heavenly, because Christ is in heaven, how much less becoming were it to seek Christ upon the earth. Let us therefore bear in mind that that is a true and holy thinking as to Christ, which forthwith bears us up into heaven, that we may there adore him, and that our minds may dwell with him.

As to the right hand of God, it is not confined to heaven, but fills the whole world. Paul has made mention of it here to intimate that Christ encompasses us by his power, that we may not think that distance of place is a cause of separation between us and him, and that at the same time his majesty may excite us wholly to reverence him.

2. Not the things that are on earth. He does not mean, as he does a little afterwards, depraved appetites, which reign in earthly men, nor even riches, or fields, or houses, nor any other things of the present life, which we must

use, as though we did not use them, (1 Corinthians 7:30, 31)

but is still following out his discussion as to ceremonies, which he represents as resembling entanglements which constrain us to creep upon the ground. "Christ," says he, "calls us upwards to himself, while these draw us downwards." For this is the winding-up and exposition of what he had lately touched upon as to the abolition of ceremonies through the death of Christ. "The ceremonies are dead to you through the death of Christ, and you to them, in order that, being raised up to heaven with Christ, you may think only of those things that are above. Leave off therefore earthly things." I shall not contend against others who are of a different mind; but certainly the Apostle appears to me to go on step by step, so that, in the first instance, he places traditions as to trivial matters in contrast with meditation on the heavenly life, and afterwards, as we shall see, goes a step farther.

3. For ye are dead. No one can rise again with Christ, if he has not first died with him. Hence he draws an argument from rising again to dying, as from a consequent to an antecedent, meaning that we must be dead to the world that we may live to Christ.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 51, 4, 1, NULL, 'colossians-4', 'John Calvin', 'Commentaries', E'1. Masters, what is just. He mentions first, what is just, by which term he expresses that kindness, as to which he has given injunction in the Epistle to the Ephesians. (Ephesians 6:8.) But as masters, looking down as it were from aloft, despise the condition of servants, so that they think that they are bound by no law, Paul brings them under control, because both are equally under subjection to the authority of God. Hence that equity of which he makes mention. And mutual equity. Some understand it otherwise, but I have no doubt that Paul here employed isoteta to mean analogical or distributive right, as in Ephesians, ta auta, (the same things.) For masters have not their servants bound to them in such a manner as not to owe something to them in their turn, as analogical right to be in force among all ranks. 2. Continue in prayer. He returns to general exhortations, in which we must not expect an exact order, for in that case he would have begun with prayer, but Paul had not an eye to that. Farther, as to prayer, he commends here two things; first, assiduity; secondly, alacrity, or earnest intentness. For, when he says, continue, he exhorts to perseverance, while he makes mention of watching in opposition to coldness, and listlessness. He adds, thanksgiving, because God must be solicited for present necessity in such a way that, in the mean time, we do not forget favors already received. Farther, we ought not to be so importunate as to murmur, and feel offended if God does not immediately gratify our wishes, but must receive contentedly whatever he gives. Thus a twofold giving of thanks is necessary. As to this point something has also been said in the Epistle to the Philippians. (Philippians 4:6.) 3. Pray also for us. He does not say this by way of pretense, but because, being conscious to himself of his own necessity, he was earnestly desirous to be aided by their prayers, and was fully persuaded that they would be of advantage to them. Who then, in the present day, would dare to despise the intercessions of brethren, which Paul openly declares himself to stand in need of? And, unquestionably, it is not in vain that the Lord has appointed this exercise of love between us -- that we pray for each other. Not only, therefore, ought each of us to pray for his brethren, but we ought also, on our part, diligently to seek help from the prayers of others, as often as occasion requires. It is, however, a childish argument on the part of Papists, who infer from this, that the dead must be implored to pray for us. For what is there here that bears any resemblance to this? Paul commends himself to the prayers of the brethren, with whom he knows that he has mutual fellowship according to the commandment of God: who will deny that this reason does not hold in the', false, false, 'sourced', 'published');
