-- Calvin commentary INSERT — 2 Corinthians (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 1, 1, NULL, '2-corinthians-1', 'John Calvin', 'Commentaries', E'1. Paul an Apostle As to the reasons why he designates himself an Apostle of Christ, and adds that he has obtained this honor by the will of God, see the foregoing Epistle, where it has been observed that none are to be listened to but those, who have been sent by God, and speak from his mouth, and that, consequently, to secure authority for any one, two things are required -- a call, and fidelity on the part of the person who is called, in the execution of his office. Both of these Paul claims for himself. The false apostles, it is true, do the same; but then, by usurping a title that does not belong to them, they gain nothing among the sons of God, who can with the utmost ease convict them of impertinence. Hence the mere name is not enough, if there be not the reality along with it, so that he who gives himself out as an Apostle must also show himself to be such by his work.

To the Church of God We must always keep it in view, his recognising a Church to exist, where there was such a conflux of evils. For the faults of individuals do not prevent a society that has genuine marks of religion from being recognised as a Church. But what does he mean by the expression -- with all saints? Were those saints unconnected with the Church? I answer, that this phrase refers to believers, who were dispersed hither and thither, throughout various corners of the province -- it being likely, that in that greatly disturbed period, when the enemies of Christ were everywhere venting their rage, many were scattered abroad, who could not conveniently hold sacred assemblies.

3 Blessed be God He begins (as has been observed) with this thanksgiving -- partly for the purpose of extolling the goodness of God -- partly, with the view of animating the Corinthians by his example to the resolute endurance of persecutions; and partly, that he may magnify himself in a strain of pious glorying, in opposition to the malignant slanderings of the false apostles. For such is the depravity of the world, that it treats with derision martyrdoms, which it ought to have held in admiration, and endeavours to find matter of reproach in the splendid trophies of the pious. Blessed be God, says he. On what account? who comforteth us -- the relative being used instead of the causal particle. He had endured his tribulations with fortitude and alacrity: this fortitude he ascribes to God, because it was owing to support derived from his consolation that he had not fainted.

He calls him the Father of our Lord Jesus Christ, and not without good reason, where blessings are treated of; for where Christ is not, there the beneficence of God is not.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 2, 1, NULL, '2-corinthians-2', 'John Calvin', 'Commentaries', E'23. I call God for a witness. He now begins to assign a reason for his change of purpose; for hitherto he has merely repelled calumny. When, however, he says that he spared them, he indirectly throws back the blame upon them, and thus shows them that it would be unfair if he were put to grief through their fault, but that it would be much more unfair if they should permit this; but most of all unfair if they should give their assent to so base a calumny, as in that case they would be substituting in their place an innocent person, as if he had been guilty of their sin. Now he spared them in this respect, that if he had come he would have been constrained to reprove them more severely, while he wished rather that they should of their own accord repent previously to his arrival, that there might be no occasion for a harsher remedy, which is a signal evidence of more than paternal lenity. For how much forbearance there was in shunning this necessity, when he had just ground of provocation!

He makes use, also, of an oath, that he may not seem to have contrived something to serve a particular purpose. For the matter in itself was of no small importance, and it was of great consequence that he should be entirely free from all suspicion of falsehood and pretence. Now there are two things that make an oath lawful and pious -- the occasion and the disposition. The occasion I refer to is, where an oath is not employed rashly, that is, in mere trifles, or even in matters of small importance, but only where there is a call for it. The disposition I refer to is, where there is not so much regard had to private advantage, as concern felt for the glory of God, and the advantage of the brethren: For this end must always be kept in view, that our oaths may promote the honor of God, and promote also the advantage of our neighbours in a matter that is befitting.

The form of the oath must also be observed -- first, that he calls God to witness; and, secondly, that he says upon my soul For in matters that are doubtful and obscure, where man''s knowledge fails, we have recourse to God, that he, who alone is truth, may bear testimony to the truth. But the man that appeals to God as his witness, calls upon him at the same time to be an avenger of perjury, in the event of his declaring what is false. This is what is meant by the phrase upon my soul. "I do not object to his inflicting punishment upon me, if I am guilty of falsehood." Although, however, this is not always expressed in so many words, it is, notwithstanding, to be understood.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 3, 1, NULL, '2-corinthians-3', 'John Calvin', 'Commentaries', E'1. Do we begin It appears that this objection also was brought forward against him -- that he was excessively fond of publishing his own exploits, and brought against him, too, by those who were grieved to find that the fame, which they were eagerly desirous to obtain, was effectually obstructed in consequence of his superior excellence. They had already, in my opinion, found fault with the former Epistle, on this ground, that he indulged immoderately in commendations of himself. To commend here means to boast foolishly and beyond measure, or at least to recount one''s own praises in a spirit of ambition. Paul''s calumniators had a plausible pretext -- that it is a disgusting and odious thing in itself for one to be the trumpeter of his own praises. Paul, however, had an excuse on the ground of necessity, inasmuch as he gloried, only because he was shut up to it. His design also raised him above all calumny, as he had nothing in view but that the honor of his apostleship might remain unimpaired for the edification of the Church; for had not Christ''s honor been infringed upon, he would readily have allowed to pass unnoticed what tended to detract from his own reputation. Besides, he saw that it was very much against the Corinthians, that his authority was lessened among them. In the first place, therefore, he brings forward their calumny, letting them know that he is not altogether ignorant as to the kind of talk, that was current among them.

Have we need? The answer is suited (to use a common expression) to the person rather than to the thing, though we shall find him afterwards saying as much as was required in reference to the thing itself. At present, however, he reproves their malignity, inasmuch as they were displeased, if he at any time reluctantly, nay even when they themselves constrained him, made mention of the grace that God had bestowed upon him, while they were themselves begging in all quarters for epistles, that were stuffed entirely with flattering commendations. He says that he has no need of commendation in words, while he is abundantly commended by his deeds. On the other hand, he convicts them of a greedy desire for glory, inasmuch as they endeavored to acquire favor through the suffrages of men. In this manner, he gracefully and appropriately repels their calumny. We must not, however, infer from this, that it is absolutely and in itself wrong to receive recommendations, provided you make use of them for a good purpose. For Paul himself recommends many; and this he would not have done had it been unlawful. Two things, however, are required here -- first, that it be not a recommendation that is elicited by flattery, but an altogether unbiassed testimony; and secondly, that it be not given for the purpose of procuring advancement for the individual, but simply that it may be the means of promoting the advancement of Christ''s kingdom.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 4, 1, NULL, '2-corinthians-4', 'John Calvin', 'Commentaries', E'1. Having this ministry. He now returns to a commendation of himself personally, from which he had digressed into a general discussion, in reference to the dignity of the gospel. As, therefore, he has been treating of the nature of the gospel, so he now shows how faithful and upright a minister of it he is. He has previously shown, what is the true gospel of Christ. He now shows what he preaches to be such. "Having," says he, "this ministry" -- that ministry, the excellence of which he had extolled in terms so magnificent, and the power and usefulness of which he had so abundantly shown forth. Hence, in order that he may not seem to extol himself too much, he premises that it was not by his own efforts, or by his own merits, that he had reached such a pinnacle of honor, but had been led forward by the mercy of God exclusively. Now there was more implied in making the mercy of God the reason of his Apostleship, than if he had attributed it to the grace of God. We faint not that is, we are not deficient in our duty, so as not to discharge it with fidelity.

2. But renounce the hidden things. While he commends his own sincerity, he, on the other hand, indirectly reproves the false Apostles, who, while they corrupted by their ambition the genuine excellence of the gospel, were, nevertheless, desirous of exclusive distinction. Hence the faults, from which he declares himself to be exempt, he indirectly imputes to them. By the hidden things of disgrace, or concealments, some understand the shadows of the Mosaic law. Chrysostom understands the expression to mean the vain show, by which they endeavored to recommend themselves. I understand by it -- all the disguises, with which they adulterated the pure and native beauty of the gospel. For as chaste and virtuous women, satisfied with the gracefulness of natural beauty, do not resort to artificial adornings, while harlots never think themselves sufficiently adorned, unless they have corrupted nature, so Paul glories in having set forth the pure gospel, while others set forth one that was disguised, and covered over with unseemly additions. For as they were ashamed of the simplicity of Christ, or at least could not have distinction from true excellencies of Apostles, they framed a new gospel, not unlike a profane philosophy, swelled up with empty bombast, while altogether devoid of the efficacy of the Spirit. Spurious ornaments of this nature, by which the gospel is disfigured, he calls the concealments of disgrace, because the nakedness of those, who have recourse to concealments and disguises, must of necessity be dishonorable and disgraceful.

As to himself, he says that he rejects or disdains disguises, because Christ''s face, the more that it is seen opened up to view in his preaching, shines forth so much the more gloriously.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 5, 1, NULL, '2-corinthians-5', 'John Calvin', 'Commentaries', E'1. For we know. Here follows an amplification (epexergasia) or embellishment of the foregoing statement. For Paul has it in view, to correct in us impatience, dread, and dislike of the cross, contempt for what is mean, and in fine, pride, and effeminacy; and this can only be accomplished by raising up our minds as high as heaven, through contempt of the world. Now he has recourse to two arguments. On the one hand, he shows the miserable condition of mankind in this life, and on the other hand, the supreme and perfect blessedness, which awaits believers in heaven after death. For what is it that keeps men so firmly bound in a misplaced attachment to this life, but their deceiving themselves with a false imagination -- thinking themselves happy in living here? On the other hand, it is not enough to be aware of the miseries of this life, if we have not at the same time in view the felicity and glory of the future life. This is common to good and bad alike -- that both are desirous to live. This, also, is common to both -- that, when they consider, how many and how great miseries they are here exposed to, (with this difference, however, that unbelievers know of no adversities but those of the body merely, while the pious are more deeply affected by spiritual distresses,) they often groan, often deplore their condition, and desire a remedy for their evils. As, however, all naturally view death with horror, unbelievers never willingly quit this life, except when they throw it off in disgust or despair. Believers, on the other hand, depart willingly, because they have a better hope set before them beyond this world. This is the sum of the argument. Let us now examine the words one by one. We know, says he. This knowledge does not spring from the human intellect, but takes its rise from the revelation of the Holy Spirit. Hence it is peculiar to believers. Even the heathens had some idea of the immortality of the soul, but there was not one of them, that had assurance of it -- not one of them could boast that he spoke of a thing that was known to him. Believers alone can affirm this, to whom it has been testified of by the word and Spirit of God. Besides, it is to be observed, that this knowledge is not merely of a general kind, as though believers were merely in a general way persuaded, that the children of God will be in a better condition after death, and had no assurance as to themselves individually, for of how very little service this would be for affording a consolation, so difficult of attainment! On the contrary, every one must have a knowledge peculiar to himself, for this, and this only, can animate me to meet death with cheerfulness -- if I am fully persuaded, that I am departing to a better life. The body,', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 6, 1, NULL, '2-corinthians-6', 'John Calvin', 'Commentaries', E'1. Assisting. He has repeated the instructions of embassy with which the ministers of the gospel have been furnished by God. After they have faithfully communicated these instructions, they must also use their endeavor, that they may be carried into effect, in order that their labor may not be in vain. They must, I say, add continual exhortation''s, that their embassy may be efficacious. This is what he means by sunergountes, (fellow-workers,) that is, devoted to the advancement of the work; for it is not enough to teach, if you do not also urge. In this way, the particle sun would have a relation to God, or to the embassy, which he assigns to his servants. For the doctrine of the gospel is helped by exhortations, so as not to be without effect, and ministers connect their endeavors with God''s commission; as it is the part of an ambassador to enforce by arguments, what he brings forward in the name of his prince. The particle sun may also be taken as referring to the endeavors of ministers in common; for if they do the Lord''s work in good earnest, they must mutually lend a helping hand to each other, so as to give assistance to each other. I rather prefer, however, the former exposition. Chrysostom interprets it as referring to the hearers, with whom ministers are fellow-workers, when they rouse them up from slothfulness and indolence. Ministers are here taught, that it is not enough simply to advance doctrine. They must also labor that it may be received by the hearers, and that not once merely, but continually. For as they are messengers between God and men, the first duty devolving upon them is, to make offer of the grace of God, and the second is, to strive with all their might, that it may not be offered in vain. 2. For he saith, In an acceptable time. He quotes a prediction of Isaiah, exceedingly appropriate to the exhortation of which he speaks. It is without doubt of the kingdom of Christ that he there speaks, as is manifest from the context. The Father, then, appointing his Son a leader, for the purpose of gathering together a Church, addresses him in these words: "I have heard thee in an acceptable time." (Isaiah 49:8.) We know, however, what a degree of correspondence there is between the Head and the members. For Christ was heard in our name, as the salvation of all of us is entrusted into his hand, and nothing else has he taken under his charge. Hence we are all admonished in the person of Christ -- not to slight the opportunity that is afforded for obtaining salvation. While the rendering of the Greek interpreter is, euprosdekton, (acceptable,) the word made use of by the Prophet is, rtsvn, (ratson,) that is, benevolence, or free favour. The quotation must be applied to the subject in hand in this way: "As God specifies a particular time for the exhibition of his', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 7, 1, NULL, '2-corinthians-7', 'John Calvin', 'Commentaries', E'1. These promises, therefore. God, it is true, anticipates us in his promises by his pure favor; but when he has, of his own accord, conferred upon us his favor, he immediately afterwards requires from us gratitude in return. Thus what he said to Abraham, I am thy God, (Genesis 17:7,) was an offer of his undeserved goodness, yet he at the same time added what he required from him -- Walk before me, and be thou perfect As, however, this second clause is not always expressed, Paul instructs us that in all the promises this condition is implied, that they must be incitements to us to promote the glory of God. For from what does he deduce an argument to stimulate us? It is from this, that God confers upon us such a distinguished honor. Such, then, is the nature of the promises, that they call us to sanctification, as if God had interposed by an implied agreement. We know, too, what the Scripture teaches in various passages in reference to the design of redemption, and the same thing must be viewed as applying to every token of his favor. From all filthiness of flesh and spirit. Having already shown, that we are called to purity, he now adds, that it ought to be seen in the body, as well as in the soul; for that the term flesh is taken here to mean the body, and the term spirit to mean the soul, is manifest from this, that if the term spirit meant the grace of regeneration, Paul''s statement in reference to the pollution of the spirit would be absurd. He would have us, therefore, pure from defilements, not merely inward, such as have God alone as their witness; but also outward, such as fall under the observation of men. "Let us not merely have chaste consciences in the sight of God. We must also consecrate to him our whole body and all its members, that no impurity may be seen in any part of us." Now if we consider what is the point that he handles, we shall readily perceive, that those act with excessive impudence, who excuse outward idolatry on I know not what pretexts. For as inward impiety, and superstition, of whatever kind, is a defilement of the spirit, what will they understand by defilement of the flesh, but an outward profession of impiety, whether it be pretended, or uttered from the heart? They boast of a pure conscience; that, indeed, is on false grounds, but granting them what they falsely boast of, they have only the half of what Paul requires from believers. Hence they have no ground to think, that they have given satisfaction to God by that half; for let a person show any appearance of idolatry at all, or any indication of it, or take part in wicked or superstitious rites, even though he were -- what he cannot be -- perfectly upright in his own mind, he would, nevertheless, not', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 8, 1, NULL, '2-corinthians-8', 'John Calvin', 'Commentaries', E'1. I make known to you. He commends the Macedonians, but it is with the design of stimulating the Corinthians by their example, although he does not expressly say so; for the former had no need of commendation, but the latter had need of a stimulus. And that he may stir up the Corinthians the more to emulation, he ascribes it to the grace of God that the Macedonians had been so forward to give help to their brethren. For although it is acknowledged by all, that it is a commendable virtue to give help to the needy, they, nevertheless, do not reckon it to be a gain, nor do they look upon it as the grace of God Nay rather, they reckon, that it is so much of what was theirs taken from them, and lost. Paul, on the other hand, declares, that we ought to ascribe it to the grace of God, when we afford aid to our brethren, and that it ought to be desired by us as a privilege of no ordinary kind.

He makes mention, however, of a twofold favor, that had been conferred upon the Macedonians. The first is, that they had endured afflictions with composure and cheerfulness. The second is, that from their slender means, equally as though they had possessed abundance, they had taken something -- to be laid out upon their brethren. Each of these things, Paul affirms with good reason, is a work of the Lord, for all quickly fail, that are not upheld by the Spirit of God, who is the Author of all consolation, and distrust clings to us, deeply rooted, which keeps us back from all offices of love, until it is subdued by the grace of the same Spirit.

2. In much trial -- In other words, while they were tried with adversity, they, nevertheless, did not cease to rejoice in the Lord: nay, this disposition rose so high, as to swallow up sorrow; for the minds of the Macedonians, which must otherwise have been straitened, required to be set free from their restraints, that they might liberally furnish aid to the brethren.

By the term joy he means that spiritual consolation by which believers are sustained under their afflictions; for the wicked either delude themselves with empty consolations, by avoiding a perception of the evil, and drawing off the mind to rambling thoughts, or else they wholly give way to grief, and allow themselves to be overwhelmed with it. Believers, on the other hand, seek occasions of joy in the affliction itself, as we see in the 8th chapter of the Romans.

And their deep poverty. Here we have a metaphor taken from exhausted vessels, as though he had said, that the Macedonians had been emptied, so that they had now reached the bottom.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 9, 1, NULL, '2-corinthians-9', 'John Calvin', 'Commentaries', E'1. Ministering. This term seems not very applicable to those that give of their substance to the poor, inasmuch as liberality is deserving of a more splendid designation. Paul, however, had in view, what believers owe to their fellowmembers. For the members of Christ ought mutually to minister to each other. In this way, when we relieve the brethren, we do nothing more than discharge a ministry that is due to them. On the other hand, to neglect the saints, when they stand in need of our aid, is worse than inhuman, inasmuch as we defraud them of what is their due.

2. For which I have boasted. He shows the good opinion that he had of them from this, that he had, in a manner, stood forward as their surety by asserting their readiness. But what if he rashly asserted more than the case warranted? For there is some appearance of this, inasmuch as he boasted, that they had been ready a year before with it, while he is still urging them to have it in readiness. I answer, that his words are not to be understood as though Paul had declared, that what they were to give was already laid aside in the chest, but he simply mentioned what had been resolved upon among them. This involves no blame in respect of fickleness or mistake. It was, then, of this promise that Paul spoke.

3. But I have sent the brethren. He now brings forward the reason -- why it is that, while entertaining a favorable opinion as to their willingness, he, nevertheless, sets himself carefully to exhort them. "I consult," says he, "my own good name and yours; for while I promised in your name, we would, both of us in common, incur disgrace, if words and deeds did not correspond. Hence you ought to take my fears in good part."

4. In this confidence The Greek term being hupostasis the Old Interpreter has rendered it substantiam, (substance.) Erasmus renders it argumentum, (subject-matter,) but neither is suitable. Budaeus, however, observes, that this term is sometimes taken to mean boldness, or confidence, as it is used by Polybius when he says, ouch houto ten dunamin hos ten hupostasin kai tolman autou katapeplegmenon ton enantion -- "It was not so much his bodily strength, as his boldness and intrepidity, that proved confounding to the enemy." Hence hupotatikos sometimes means one that is bold and confident. Now every one must see, how well this meaning accords with Paul''s thread of discourse. Hence it appears, that other interpreters have, through inadvertency, fallen into a mistake.

5. As a blessing, not in the way of niggardliness In place of blessing, some render it collection. I have preferred, however, to render it literally, as the Greeks employed the term eulogias to express the Hebrew word vrkh, (beracah,) which is used in the sense of a blessing, that is, an invoking of prosperity, as well as in the sense of beneficence.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 47, 10, 1, NULL, '2-corinthians-10', 'John Calvin', 'Commentaries', E'1. I exhort you. The speech is abrupt, as is frequently the case with speeches uttered under the influence of strong feeling. The meaning is this: "I beseech you, nay more, I earnestly entreat you by the gentleness of Christ, not to compel me, through your obstinacy, to be more severe than I would desire to be, and than I will be, towards those who despise me, on the ground of my having nothing excellent in external appearance, and do not recognize that spiritual excellence, with which the Lord has distinguished me, and by which I ought rather to be judged of."

The form of entreaty, which he makes use of, is taken from the subject in hand, when he says -- by the meekness and gentleness of Christ Calumniators took occasion to find fault with him, because his bodily presence was deficient in dignity, and because, on the other hand, when at a distance, he thundered forth in his Epistles. Both calumnies he befittingly refutes, as has been said, but he declares here, that nothing delights him more than gentleness, which becomes a minister of Christ, and of which the Master himself furnished an example.

Learn of me, says he, for I am meek and lowly. My yoke is easy and my burden is light. (Matthew 11:29, 30.)

The Prophet also says of him,

His voice will not be heard in the streets: a bruised reed he shall not break, etc. (Isaiah 42:2, 3.)

That gentleness, therefore, which Christ showed, he requires also from his servants. Paul, in making mention of it, intimates that he is no stranger to it. "I earnestly beseech you not to despise that gentleness, which Christ showed us in his own person, and shows us every day in his servants, nay more, which ye see in me."

Who in presence He repeats this, as if in the person of his adversaries, by way of imitating them. Now he confesses, so far as words go, what they upbraided him with, yet, as we shall see, in such a way as to concede nothing to them in reality.

2. I beseech you, that I may not be bold, when I am present. Some think, that the discourse is incomplete, and that he does not express the matter of his request. I am rather of opinion, however, that what was wanting in the former clause is here completed, so that it is a general exhortation. "Show yourselves docile and tractable towards me, that I may not be constrained to be more severe." It is the duty of a good pastor to allure his sheep peacefully and kindly, that they may allow themselves to be governed, rather than to constrain them by violence. Severity, it is true, is, I acknowledge, sometimes necessary, but we must always set out with gentleness, and persevere in it, so long as the hearer shews himself tractable. Severity must be the last resource.', false, false, 'sourced', 'published');
