-- Calvin commentary INSERT — Jeremiah (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 1, 1, NULL, 'jeremiah-1', 'John Calvin', 'Commentaries', E'1. The words of Jeremiah the son of Hilkiah, of the priests that were in Anathoth in the land of Benjamin:

1. Verba Jeremiae filii Helkiae, ex sacerdotibus qui erant in Anathoth, in terra Benjamin,

2. To whom the word of the LORD came in the days of Josiah the son of Amon king of Judah, in the thirteenth year of his reign.

2. Nempe (''sr explicative hic ponitur) fecit sermo Jehovae ad ipsum, in diebus Josiea, filii Amon, regis Jehudah, decimo tertio anno regm ejus;

3. It came also in the days of Jehoiakim the son of Josiah king of Judah, unto the end of the eleventh year of Zedekiah the son of Josiah king of Judah, unto the carrying away of Jerusalem captive in the fifth month.

3. Et fuit (hoc est, perrexit in, cursum vocationis suae) diebus Joakim, filii Josiae, regis Jehudah, usque ad complementum undecimi anni Zedechiae, filii Josiae, regis Jehudah, ad transmigrationem Jerusalem, mense quinto.

I Have said that the time, when Jeremiah began to discharge his office of a Prophet in God''s Church, is not stated here without reason, and that it was when the state of the people was extremely corrupt, the whole of Religion having become vitiated, because the Book of the Law was lost: for nowhere else can be found the rule according to which God is to be worshipped; nor can right knowledge be obtained from any other source. It was then, at the time when impiety had by a long custom prevailed among the Jews, that Jeremiah suddenly came forth. There was then laid on his shoulders the heaviest burden; for many enemies must have risen to oppose him, when he attempted to bring back the people to the pure doctrine of the law, which the greater part were then treading under their feet.

He calls himself the son of Hilkiah The Rabbins think that this Hilkiah was the priest by whom the Book of Moses was found five years after: but this seems not to me probable. The conjecture also of Jerome is very frivolous, who concludes that the Prophet was a boy when he began to prophesy, because he calls himself nr (nor,) a child, a little farther on, as though he did not use the word metaphorically. At what age he was called to the prophetic office, we do not know; it is, however, probable that he was of mature age, for it was a work of high authority; and further, had he been a youth, doubtless such a miracle would not have been passed over in silence, that is, that he was made a prophet before the age of maturity.

With regard to his father, it is nothing strange that the Rabbins have regarded him as the high priest; for we know that they are always prone to vain boastings.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 2, 1, NULL, 'jeremiah-2', 'John Calvin', 'Commentaries', E'1. Moreover, the word of the LORD came to me, saying,

1. Et fuit sermo Jehovae ad me, dicendo,

2. Go and cry in the ears of Jerusalem, saying, Thus saith the LORD; I remember thee, the kindness of thy youth, the love of thine espousals, when thou wentest after me in the wilderness, in a land that was not sown.

2. Vade et clama ad aures Jerusalem, dicendo, Sic dicit Jehova, Recordatus sum tui propter misericordiam adolescentiae tuae et dilectionem desponsationis tuae, quum me sequuta es (quum venisti post me, profecta es post me) in deserto, in terra non seminata.

God now mentions to his servant the commands which he was to convey to the king and priests, and to the whole people; for by the ears of Jerusalem he means all its inhabitants. God here intimates that the Jews were unworthy of being cared for by him any more; but that he is induced by another reason not to reject them wholly, until he had found out by experience their irreclaimable wickedness. So then he makes this preface, I remember thee for the kindness of thy youth, and the love of thy espousals In these words he shews that he regarded not what the Jews deserved, nor acknowledged any worthiness in them, as the reason why he was solicitous for their salvation, and endeavored to bring them to the right way by the labors of his Prophet, but that this is to be ascribed to his former benefits.

Some render the words, "I remember the piety or kindness of thy youth;" and lk lak, may be thus taken, as it is in other places. Others omit this word; while others consider a copulative to be understood, "I remember thee, and the kindness of thy youth." But none, as I think, have attained to the meaning of the Prophet: there is yet no obscurity in the words, if a preposition be considered as being understood, so as to read thus, -- that God remembered his people for the kindness which he had shewn to them, and for the love which he had manifested towards them from the beginning. Then the real meaning of the Prophet I think to be this, -- that God here takes away every ground for pride and boasting from the Jews; as though he had said, that they were worthy, they had no reason to think; but that he was still their Father, and was therefore unwilling that the benefits he had formerly conferred upon them should be wholly lost. There is, in short, given here a reason why God sent Jeremiah after the other prophets; as though he had said, "It is a testimony to you of the paternal care which I shew to you, when I send my Prophet to give you a hope of pardon, if ye return to the right way and be reconciled to me.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 3, 1, NULL, 'jeremiah-3', 'John Calvin', 'Commentaries', E'1. They say, If a man put away his wife, and she go from him, and become another man''s, shall he return unto her again? shall not that land be greatly polluted? but thou hast played the harlot with many lovers; yet return again to me, saith the LORD. l. Dicendo, si dimiserit vir uxorem suam, et profecta ab eo, fuepit viri alterius, (id est, transierit ad alium virum) an revertetur ad eam adhuc? Annon pollutione polluta est terra in hoc? et tu scortata es cum sociis multis; revertere tamen ad me, dicit Jehova. Many regard this verse as connected with the last, and thus read them connectedly, "God hates false confidences, because he says, "etc. But this seems not to me to be suitable; for Jeremiah brings before us here a new subject, -- that God seeks to be reconciled to his people, according to what a husband does, who desires to receive into favor an unchaste wife, and is ready to grant her full pardon, and to take her again as a chaste and faithful wife. This verse, then, cannot be connected with the foregoing, in which, as we have seen, the people are condemned. The word lsmr lamer, means the same, as I think, as when we say in French, par maniere de dire, or as when it is commonly said, "Suppose a case." For the Prophet does not here introduce God as the speaker, but lays before us a common subject, with this preface, l''mr, lamer, that is, "Be it so, that a man divorces his wife, and she becomes allied to another husband, can she again return to her first husband? This is not usually done; but I will surpass whatever kindness there may be among men, for I am ready to receive thee, provided thou wilt in future observe conjugal fidelity, and part with thy adulteries and adulterers." As to the main point, there is here no ambiguity: for God shews that he would be reconciled to the Jews, provided they proceeded not obstinately in their sinful courses. But in order to set forth more fully his mercy, he uses a comparison which must be a little more attentively considered. He had before said that he held the place of a husband, that the people occupied the station of a wife; and then he complained of the base perfidy of the people, who had forsaken him, and said that they had acted like a wife who, having despised her husband, prostituted herself to such adulterers as might happen to meet her: but he now adds, "Behold, if a man dismisses his wife, and she becomes the wife of another, he will never receive her again." And this was forbidden by the law. "But I am ready, "he says, "to receive thee, though I had not given thee the usual divorce at my pleasure, as husbands are wont to do who repudiate their wives, when there is anything displeasing in them." It is not a', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 4, 1, NULL, 'jeremiah-4', 'John Calvin', 'Commentaries', E'1. If thou wilt return, O Israel, saith the Lord, return unto me: and if thou wilt put away thine abominations out of my sight, then shalt thou not remove. 1. Si reverteris Israel, dicit Jehova, ad me revertere (vel, apud me quiesce;) et si abstuleris abominationes tuas a facie mea, et non fueris vagus (alii, et non migrabis.) The Prophet no doubt requires here from the people a sincere return to God, inasmuch as they had often pretended to confess their sins, and had given many signs of repentance, while they were acting deceitfully with him. As then they had often dealt falsely with God and with his prophets, Jeremiah bids them to return to God without any disguise and in good faith. With regard to what is here substantially taught, this is the Prophet''s meaning; but there is some ambiguity in the words. Some read thus, "If thou returnest, Israel, to me, saith Jehovah, "connecting "to me, ''ly, "with the first clause, then they read separately "tsvv, teshub, thou shalt rest;" and so they think that what follows is the repetition of the same thing, "If thou wilt take away thine abominations from before me, thou shalt not migrate;" that is, I will not cast thee out as I have threatened. Others take the verb tsvv, teshub, in the same sense, (for it is the same verb repeated,) "If thou wilt return, Israel, return to me." The Prophet doubtless bids the Israelites to return to God in sincerity, and without any disguise, and not to act falsely with him, as they had often done. I have as yet mentioned only what others have thought; but, in my judgment, the most suitable rendering is, "If thou wilt return, Israel, rest in me, "arrete toi, as we say in French. Rest then in me; and then a definition is given, If thou wilt take away thine abominations (for the copulative is to be taken as expletive or explanatory) from my sight, and wilt not wander What some of those I have referred to have given as their rendering, "If thou wilt return to me, Israel, thou shalt rest," I wholly reject, as it seems forced: but I allow this reading, "If thou wilt return, Israel, thou shalt rest in me;" or this, "If thou wilt return, Israel, return to me;" for the difference is not great. The Prophet here evidently condemns the hypocrisy which the Israelites had practiced; for they had often professed themselves as ready to render obedience to God, and afterwards proved that they had made a false profession. Since then deceit and emptiness had been so often found in them, the Prophet demands here, in the name and by the command of God, that they should in truth and sincerity return to him. If this reading be approved, "Israel, return to me," the intimation is, that they ever took circuitous courses, that they might not return directly to God: for it is usual with hypocrites to make', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 5, 1, NULL, 'jeremiah-5', 'John Calvin', 'Commentaries', E'1. Run ye to and fro through the streets of Jerusalem, and see now, and know, and seek in the broad places thereof, if ye can find a man, if there be any that executeth judgment, that seeketh the truth; and I will pardon it. 1. Circuite per vias (alii vertunt, inquirite, vel, explorate, vel, investigate per vias) Jerusalem, et videte, agedum, (hic enim ''n est hortantis, proximo versu debuit verti nunc, vae nunc mihi,) et cognoscite, et inquirite, in vicis ejus (in compitis ejus,) an invenietis virum, an erit quifaciat judicium (hoc est, rectitudinem,) qui quaerat veritatem, et parcam illi. In this verse, as in those which follow, God shews that he was not too rigid or too severe in denouncing utter ruin on his people, because their wickedness was wholly incurable, and no other mode of treating them could be found. We, indeed, know that it is often testified in Scripture, that God is patient and waits until sinners repent. Since then God everywhere extols his kindness, and promises to be merciful even to the worst if they repent, and since he of his own accord anticipates sinners, it may appear strange that he rises with so much severity against his own Church. But we know how refractory the ungodly are; and hence they hesitate not to expostulate with God, and willfully accuse him, as though he treated them with cruelty. It is then for this reason, that God now shews that he was not, as it were, at liberty to forgive the people; "Even if I would, "he says, "I could not." He speaks, indeed, after the manner of men; but in this way, as I have said, he shews that he tried all expedients, before he had recourse to extreme severity, but that there was no remedy, on account of the desperate wickedness of the people. And this is what the words fully express. Go round, he says, through the streets of Jerusalem, and see, I pray, and know; inquire through all the cross-ways Jeremiah might have said in one sentence, "If one man be found in the city, I am ready to forgive: "but God here permits the whole world to inquire diligently and carefully what was the state of the holy city, which ever gloried in that title. But he now, as also in the next verse, speaks of Jerusalem. He had spoken also of the neighboring cities; but as the holiness of the whole land seemed then to have its seat and habitation at Jerusalem, God here addresses that city, which as yet retained some appearance of sanctity, and excelled other cities. He then says, Inquire, see, know, look, whether there is a man, etc. He allows here all men to form a judgment, as though he had said, "Let all be present, since the Jews seek to create an ill-will towards me, and complain of too much rigor, as though I treated them unhumanly; let all who wish come as judges, let', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 6, 1, NULL, 'jeremiah-6', 'John Calvin', 'Commentaries', E'1. O ye children of Benjamin, gather yourselves to flee out of the midst of Jerusalem, and blow the trumpet in Tekoa, and set up a sign of fire in Bethhaccerem: for evil appeareth out of the north, and great destruction.

1. Congregamini filii Benjamin e medio Jerusalem, et in Thekua clangite tuba, et Bethhacherem tollite signum; quia malum visum est ab Aquilone et afflictio magna.

WE have already seen that oftentimes punishment is not only mentioned by this Prophet as being nigh at hand, but is also set as it were before our eyes; and we have shewn the reason for this, -- because men are not only deaf, but wholly thoughtless, whenever God threatens them. As reproofs make no impressions, and even threatenings are not sufficient to arouse and awake them, it is necessary to set before them vivid descriptions, and to represent the event as present. Jeremiah continues this mode of teaching; he addresses the tribe of Benjamin; for one half of Jerusalem was in the territory of that tribe; And as he was from Anathoth, he addresses his own people and kindred rather than others, as he could use greater freedom. Had he directly reproved the Jews, they might not have so well borne with him; but as he begins with his neighbors, the tribe of Benjamin, it became more easy to bear his reproofs.

Some understand the words, "Be ye assembled, and flee;" others read, "Go ye in haste, "but for what reason I know not. I do not think that flight is meant here; but I rather regard the Prophet as ironically encouraging the citizens of Jerusalem and their neighbors to go forth, as it is usual, to meet their enemies; and this we may easily learn from the context: Be ye assembled, he says, from the midst of Jerusalem; that is, Be aroused and go forth. And he indirectly condemns their indulgences, for they had been lying as it were in the bosom of their mother. Like infants in the womb, the Jews were not apprehensive of any danger; they indulged themselves, and were wholly secure and thoughtless. Hence he says, "From the midst of Jerusalem be ye assembled."

Then he says, Blow ye the trumpet in Tekoa. They were wont, no doubt, when any danger was at hand, to blow the trumpet in that town; and then the citizens of Jerusalem went forth in large bodies to resist their enemies: for the Prophet follows the usual custom, and speaks as of things well known. And set up a sign on the house of Haccerem, hkrm. No doubt this place was so called, because many forces were planted there. It means literally the house of the vineyard. It is, indeed, a proper name; but its etymology ought to be borne in mind; for as vines were usually planted on hills, it is probable that this place stood high; and a sign might have been thence given to many around.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 7, 1, NULL, 'jeremiah-7', 'John Calvin', 'Commentaries', E'1. The word that came to Jeremiah from the Lord, saying,

1. Sermo qui datus fuit Jeremiae (qui factus fuit ad Jeremiam, qui datus fuit, ad verbum) a Jehova, dicendo,

2. Stand in the gate of the Lord''s house, and proclaim there this word, and say, Hear the word of the Lord, all ye of Judah, that enter in at these gates to worship the Lord

2. Sta in porta domus Jehovae (hoc est, Templum,) et clama illic hunc sermonem (hoc est, vociferare hunc sermonem, vel, cum clamore prefer,) et dicas, Audite sermonem Jehovae cunctus Jehudah, qui ingredimini per has portas, ut adoretis Jehovam:

3. Thus saith the Lord of hosts, the God of Israel, Amend your ways and your doings, and I will cause you to dwell in this place.

3. Sic dicit Jehova exercituum, Deus Israel, Bonas facite vias vestras et studia vestra, et habitabo vobiscum in hoc loco;

4. Trust ye not in lying words, saying, The temple of the Lord, The temple of the Lord, The temple of the Lord, are these.

4. Ne confidatis vobis (hoc est, ne vobis fiduciam ponatis, vel, adjiciatis vobis fiduciam) ad verba mendacii, dicendo, Templum Jehovae, Templum Jehovae, Templum Jehovae sunt.

Here the Prophet gives a short account of the sermon, in which he severely reproved the people, because his labor had been useless, though he had sharply and severely reproved them. He says then, that he had a command from above to stand at the gate of the Temple. This was indeed usually done by the prophets: but God seems to have intended that this reproof should be heard by all. He says further, that he was commanded to address the whole tribe of Judah

It is hence probable, and what may be easily concluded, that this discourse was delivered on a feast -- day, when there was the usual assembly of the people. He could not indeed have made this address on other days; for then the inhabitants of the city only frequented the Temple. But on the feast -- days they usually came from the neighboring towns and from the whole country to celebrate God''s rightful worship, which had been prescribed in the law. Since then Jeremiah addressed the whole tribe of Judah, we hence conclude, that he spoke not only to the inhabitants of the city, but also to the whole tribe, which came together to keep the feast -- day.

Now the object of his sermon was, to exhort them seriously to repent, if they wished God to be reconciled to them. So the Prophet shews, that God did not regard their sacrifices and external rites, and that this was not the way, as they thought, of appeasing him. For after they had celebrated the feast, every one returned home, as though they all, after having made an expiation, had God propitious to them.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 8, 1, NULL, 'jeremiah-8', 'John Calvin', 'Commentaries', E'1. At that time, saith the Lord, they shall bring out the bones of the kings of Judah, and the bones of his princes, and the bones of the priests, and the bones of the prophets, and the bones of the inhabitants of Jerusalem, out of their graves:

1. In die illo, dicit Jehova, extrahent ossa regum Jehudah et ossa principum ejus, et ossa sacerdotum, et ossa prophetarum, et ossa civium Jerosolymae (habitantium,) e sepulchris suis;

2. And they shall spread them before the sun, and the moon, and all the host of heaven, whom they have loved, and whom they have served, and after whom they have walked, and whom they have sought, and whom they have worshipped: they shall not be gathered, nor be buried; they shall be for dung upon the face of the earth.

2. Et expendent coram sole et luna et toto exercitu coelorum, quae dilexerunt (nam relativum neutrum comprehendit et solem et lunam et exercitum; vel, si magis placeat vertere, quos exercitus dilexerunt,) et quibus servierunt, et post quos ambularunt, et quos quaesierunt, et coram quibus prostrati sunt (hoc est, se inclinarunt;) neque colligentur, et non sepelientur, in stercus in terrae superficie erunt.

I Have said that Jeremiah repeats in the first verse what he had before said, -- that the Jews would be deprived of their graves, in order that there might be on the dead a mark of God''s vengeance; as though he had said, that after having been destroyed by the hand of enemies, they would have their punishment extended farther by having their dead bodies exposed to the wild beasts and birds. The faithful, as I have said, suffer no loss, when burial is denied them; but yet they do not disregard burial, inasmuch as it is a badge of the resurrection. Though God suffers them to be involved in this disgrace with the reprobate, yet this does not hinder but that God should execute his vengeance on the wicked by such a temporal punishment as turns to a blessing to the faithful. It is therefore no unmeaning denunciation, when the Prophet says that the time was at hand, when their bones would be taken out of their graves.

He mentions the bones of kings, and of priests, and of prophets, and of the whole people The kings thought that as soon as they were hid in their graves, their dead bodies would be deemed sacred: the same notion prevailed as to rulers, priests, and prophets: but he says that no grave would be untouched or free from the outrage of enemies; and thus he shews, that the city would be rooted up from its foundations. Were the city to remain safe, the graves would be spared. Hence this punishment could not have been inflicted, without the very foundations of the city being dug up by the enemies.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 9, 1, NULL, 'jeremiah-9', 'John Calvin', 'Commentaries', E'2 And they shall spread them before the sun, And the moon, and all the host of heaven, Which they have loved and served, And after which they have walked, And which they have sought, And before which they have bowed themselves; They shall not be gathered nor buried; For dung on the face of the land shall they be: 3 And chosen shall be death, Rather than life, by all the residue, Who shall remain of this wicked nation, Who shall remain in all the places Where I shall drive them, saith Jehovah of hosts. 4 Thou shalt also say to them, Thus saith Jehovah, -- Shall not they who have fallen rise again? If any one turns aside shall he not return? 5 Why rebel does this people at Jerusalem With a perpetual rebellion? They have held fast deceit, They have refused to return. 6 I hearkened and heard; they will not speak aright; There is no one who repents of his wickedness, And says, "What have I done?" Every one turns to his own course, Like a horse who rushes into battle. (1:425) 7 Even the stork in the heavens knows its times; The turtle also, and the swallow and the crane, Observe the time of their journey; But my people know not the judgment of Jehovah. 8 How say ye, "We are wise And the law of Jehovah is with us:" Surely, behold in vain Hath the writer prepared his pen, In vain are the scribes! 9 Ashamed are the wise, terrified and taken; Behold the word of Jehovah have they rejected; And wisdom, what is it to them! (1:432) 10 I will therefore give their wives to aliens, And their fields to inheritors; For from the least even to the greatest, Every one is given to covetousness; From the prophet even to the priest, All have acted deceitfully; 11 And healed have they the wound Of the daughter of my people slightly, By saying, "Peace, peace," when there was no peace. 12 Had they shame, that they had done abomination? Even of shame they were not ashamed, And how to blush they knew not: Fall therefore shall they with the fallen; At the time of their visitation They shall perish, saith Jehovah. 13 Destroying, I will destroy them, saith Jehovah; No grapes shall be on the vine, And no figs on the fig-tree; The leaf also shall fall, And what I gave them shall pass from them. 14 Why do we sit still? Assemble ye, And let us enter into fortified cities, And let us rest there: Surely, Jehovah our God hath made us silent, And given us waters of gall to drink: Because we have sinned against Jehovah. (1:442) 15 We looked for peace, but there was no good; For time of healing, but behold terror. 16 From Dan is heard the snorting of his horses; At the sound of the neighing of his strong ones, Tremble does the whole land; For they will', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 10, 1, NULL, 'jeremiah-10', 'John Calvin', 'Commentaries', E'1. Hear ye the word which the LORD speaketh unto you, O house of Israel: 1. Audite verbum quod loquitur (sermonem quem profert) Jehova ad vos, domus Israel: 2. Thus saith the LORD, Learn not the way of the heathen, and be not dismayed at the signs of heaven; for the heathen are dismayed at them. 2. Sic dicit Jehova, Viam gentium ne didiceritis, et a signis coelorum ne metuatis; quoniam metuunt ab illis gentes. Jeremiah enters here on a new subject. Though he had, no doubt, taught this truth often, yet I consider it as distinct from what has gone before; for he begins here a new attack on those superstitions to which the Jews were then extremely addicted. He exhorts them first to hear the word of Jehovah; for they had so hardened themselves in the errors which they had derived from the Gentiles, and the contagion had so prevailed, that they could not be easily drawn away from them. This, then, is the reason why he used a sort of preface, and said, Hear ye the word of Jehovah, which he speaks to you, O house of Israel He then mentions the error in which the Chaldeans and the Egyptians were involved; for they were, we know, very attentive observers of the stars. And this is expressly stated, because the Jews despised God''s judgments, and greatly feared what were foolishly divined. For when any one, by looking at the stars, threatened them with some calamity, they were immediately terrified; but when God denounced on them, as with the sound of a trumpet, a calamity by his Prophets, they were not at all moved. But it will be better to examine the very words of the Prophet, as then we shall more plainly see the drift of the whole. Learn not, he says, the way of the nations The Hebrew grammarians take ''l, al ''t at. Way, we know, is everywhere taken for all those customs and habits by which human life is regulated, He then forbids them to pay attention to the rules of life observed by the Gentiles. And one thing he specifies, Be not terrified by celestial signs. He afterwards shews how vain were the practices of the Gentiles; being devoted to idols, they worshipped them in the place of God, though framed by the skill of man. But there are other words added, For the heathens are terrified by them There is a threefold exposition of this clause. Some take ky, ki, properly a causative, in the sense of k, caph, which denotes likeness, "as the Gentiles are terrified by them." Others regard it as an adversative, "though," and ky, ki, has often this meaning. There are also others who give this explanation, "For it is the case with the Gentiles, that they are terrified by them;" as though God had said, that it was extremely absurd in the Jews to be terrified by celestial signs, for they ought to have left this folly,', false, false, 'sourced', 'published');
