-- Calvin commentary INSERT — John (batch 3, rows 21-21)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 43, 21, 1, NULL, 'john-21', 'John Calvin', 'Commentaries', E'1. After these things Jesus manifested himself again. The Evangelist still labors to prove the resurrection of Christ, and relates, that he appeared to seven disciples, among whom he mentions Thomas, not out of respect to him, so much as because his testimony ought to be the more readily believed in proportion to the obstinacy of his unbelief. The Evangelist enters sufficiently into detail; for he carefully collects all the circumstances which contribute to prove the truth of the history. We have formerly mentioned that the Lake of Tiberias, according to the Hebrew custom, is called the Sea of Tiberias.

3. I am going to fish. That Peter gave his attention to fishing, ought not to be regarded as inconsistent with his office. By breathing on him, Jesus had ordained him to be an Apostle, as we saw a little before; but he abstained from the exercise of the apostleship for a short time, till he should be clothed with new power. For he had not yet been enjoined to appear in public for the discharge of his office of teaching, but had only been reminded of his future calling, that he and the others might understand that they had not in vain been chosen from the beginning. Meanwhile, they do what they were accustomed to do, and what belonged to men in private life. It is true that Paul, in the midst of his employment as a preacher, gained the support of his life by his own hands, but it was for a different reason; for his time was so arranged, that the labors of his hands did not withdraw him from teaching. Peter and his companions, on the other hand, give themselves up entirely to fishing, because they are not hindered from doing so by any public employment.

And that night they caught nothing. God permitted them to toil to no purpose during the whole night, in order to prove the truth of the miracle; for if they had caught any thing what followed immediately afterwards would not have so clearly manifested the power of Christ, but when, after having toiled ineffectually during the whole night, they are suddenly favored with a large take of fishes, they have good reason for acknowledging the goodness of the Lord. In the same manner, also, God often tries believers, that he may lead them the more highly to value his blessing. If we were always prosperous, whenever we put our hand to labor, scarcely any man would attribute to the blessing of God the success of his exertions, all would boast of their industry, and would kiss their hands. But when they sometimes labor and torment themselves without any advantage, if they happen afterwards to succeed better, they are constrained to acknowledge something out of the ordinary course; and the consequence is, that they begin to ascribe to the goodness of God the praise of their prosperity and success.

6. Cast the net on the right side of the ship.', false, false, 'sourced', 'published');
