-- Calvin commentary INSERT — Psalms (batch 11, rows 101-110)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 101, 1, NULL, 'psalms-101', 'John Calvin', 'Commentaries', E'1. I will sing of mercy and of judgment: unto thee, O Jehovah! will I sing psalms. 2. I will behave myself prudently in a perfect way, till thou comest to me: I will walk in the integrity of my heart in the midst of thy house. 3. I will not set a wicked thing before my eyes: I hate the work of those who turn aside; it shall not adhere to me. 4. The perverse heart shall depart from me: I will not know evil 5. Whoso slandereth his neighbor in secret, him will I destroy: the man whose eyes are lofty, and whose heart is wide, I cannot endure.

1 I will sing of mercy and of judgment What David here says concerning singing must be understood by the reader as intimating that this psalm contains the substance of his meditations with himself, as to what kind of king he would be whenever he should be put in possession of the sovereign power which had been promised him. To sing therefore of mercy and of judgment, is equivalent to declaring in solemn terms, that he would be a just and an upright king. Augustine understands this as meaning that God is to be praised, whether he punish men with severity, or whether he show himself merciful to them; but this interpretation is too refined. David does not speak of God''s secret judgments, but of the due administration of the kingdom, that he might both by words and deeds fulfill his vocation. When he asserts, Unto thee, O Jehovah! will I sing psalms, he acknowledges that it was by the favor of God that he was appointed to so distinguished and honorable an office; for it would have been an act of presumptuous rashness for him to have thrust himself into it, at the mere impulse of his own mind. He very properly comprehends all princely virtues under these two particulars, mercy and judgment; for as it is the principal duty of a king to yield to every man his own right, so he is also required to possess a considerate love and compassion towards his subjects. Solomon therefore justly says, (Proverbs 16:12) "The throne is established by righteousness."

2 I will behave myself prudently in a perfect way David here shows that he carefully considered how weighty a charge was laid upon him when he was made king. We know, and it is a truth taught us by experience, that almost all kings are intoxicated with the splendors of royalty; and the proverb was not used without foundation in ancient times, "A king must be born either a king or a fool." It is indeed a mistake to say that kings are born fools. Men were led to speak in this manner, because it commonly happens that those who are invested with the government of kingdoms and empires are fools and blockheads.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 102, 1, NULL, 'psalms-102', 'John Calvin', 'Commentaries', E'1 O Jehovah! hear my prayer This earnestness shows, again, that these words were not dictated to be pronounced by the careless and light-hearted, which could not have been done without grossly insulting God. In speaking thus, the captive Jews bear testimony to the severe and excruciating distress which they endured, and to the ardent desire to obtain some alleviation with which they were inflamed. No person could utter these words with the mouth without profaning the name of God, unless he were, at the same time, actuated by a sincere and earnest affection of heart. We ought particularly to attend to the circumstance already adverted to, that we are thus stirred up by the Holy Spirit to the duty of prayer in behalf of the common welfare of the Church. Whilst each man takes sufficient care of his own individual interests, there is scarcely one in a hundred affected as he ought to be with the calamities of the Church. We have, therefore, the more need of incitements, even as we see the prophet here endeavoring, by an accumulation of words, to correct our coldness and sloth. I admit that the heart ought to move and direct the tongue to prayer; but, as it often flags or performs its duty in a slow and sluggish manner, it requires to be aided by the tongue. There is here a reciprocal influence. As the heart, on the one hand, ought to go before the words, and frame them, so the tongue, on the other, aids and remedies the coldness and torpor of the heart. True believers may indeed often pray not only earnestly but also fervently, while yet not a single word proceeds from the mouth. There is, however, no doubt that by crying the prophet means the vehemence into which grief constrains us to break forth.

2 Hide not thy face from me in the day of my affliction The prayer, that God would not hide his face, is far from being superfluous. As the people had been languishing in captivity for the space of nearly seventy years, it might seem that God had for ever turned away his favor from them. But they are, notwithstanding, commanded, in their extreme affliction, to have recourse to prayer as their only remedy. They affirm that they cry in the day of their affliction, not as hypocrites are accustomed to do, who utter their complaints in a tumultuous manner, but because they feel that they are then called upon by God to cry to him.

Make haste, answer me Having elsewhere spoken more fully of these forms of expression, it may suffice, at present, briefly to observe, that when God permits us to lay open before him our infirmities without reserve, and patiently bears with our foolishness, he deals in a way of great tenderness towards us.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 103, 1, NULL, 'psalms-103', 'John Calvin', 'Commentaries', E'1. Bless Jehovah, O my soul! The prophet, by stirring up himself to gratitude, gives by his own example a lesson to every man of the duty incumbent upon him. And doubtless our slothfulness in this matter has need of continual incitement. If even the prophet, who was inflamed with a more intense and fervent zeal than other men, was not free from this malady, of which his earnestness in stimulating himself is a plain confession, how much more necessary is it for us, who have abundant experience of our own torpor, to apply the same means for our quickening? The Holy Spirit, by his mouth, indirectly upbraids us on account of our not being more diligent in praising God, and at the same time points out the remedy, that every man may descend into himself and correct his own sluggishness. Not content with calling upon his soul (by which he unquestionably means the seat of the understanding and affections) to bless God, the prophet expressly adds his inward parts, addressing as it were his own mind and heart, and all the faculties of both. When he thus speaks to himself, it is as if, removed from the presence of men, he examined himself before God. The repetition renders his language still more emphatic, as if he thereby intended to reprove his own slothfulness.

2. And forget not any of his benefits Here, he instructs us that God is not deficient on his part in furnishing us with abundant matter for praising him. It is our own ingratitude which hinders us from engaging in this exercise. In the first place, he teaches us that the reason why God deals with such liberality towards us is, that we may be led to celebrate his praise; but at the same time he condemns our inconstancy, which hurries us away to any other object rather than to God. How is it that we are so listless and drowsy in the performance of this the chief exercise of true religion, if it is not because our shameful and wicked forgetfulness buries in our hearts the innumerable benefits of God, which are openly manifest to heaven and earth? Did we only retain the remembrance of them, the prophet assures us that we would be sufficiently inclined to perform our duty, since the sole prohibition which he lays upon us is, not to forget them.

3. Who forgiveth all thy iniquities He now enumerates the different kinds of the divine benefits, in considering which he has told us that we are too forgetful and slothful. It is not without cause that he begins with God''s pardoning mercy, for reconciliation with him is the fountain from which all other blessings flow. God''s goodness extends even to the ungodly; but they are, notwithstanding, so far from having the enjoyment of it, that they do not even taste it.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 104, 1, NULL, 'psalms-104', 'John Calvin', 'Commentaries', E'1. Bless Jehovah, O my soul! O Jehovah my God! thou art exceeding great; thou hast clothed thyself with praise and glory. 2. Being arrayed with light as with a garment; and spreading out the heavens as a curtain: 3. Laying the beams of his upper rooms in the waters; making the clouds his chariot; and walking upon the wings of the wind; 4. Making the winds his messengers; and his ministers a flaming fire.

1 Bless Jehovah, O my soul! After having exhorted himself to praise God, the Psalmist adds, that there is abundant matter for such an exercise; thus indirectly condemning himself and others of ingratitude, if the praises of God, than which nothing ought to be better known, or more celebrated, are buried by silence. In comparing the light with which he represents God as arrayed to a garment, he intimates, that although God is invisible, yet his glory is conspicuous enough. In respect of his essence, God undoubtedly dwells in light that is inaccessible; but as he irradiates the whole world by his splendor, this is the garment in which He, who is hidden in himself, appears in a manner visible to us. The knowledge of this truth is of the greatest importance. If men attempt to reach the infinite height to which God is exalted, although they fly above the clouds, they must fail in the midst of their course. Those who seek to see him in his naked majesty are certainly very foolish. That we may enjoy the light of him, he must come forth to view with his clothing; that is to say, we must cast our eyes upon the very beautiful fabric of the world in which he wishes to be seen by us, and not be too curious and rash in searching into his secret essence. Now, since God presents himself to us clothed with light, those who are seeking pretexts for their living without the knowledge of him, cannot allege in excuse of their slothfulness, that he is hidden in profound darkness. When it is said that the heavens are a curtain, it is not meant that under them God hides himself, but that by them his majesty and glory are displayed; being, as it were, his royal pavilion.

3. Laying the beams of his chambers in the waters David now proceeds to explain at greater length what he had briefly stated under the figure of God''s raiment. The scope of the passage is shortly this, that we need not pierce our way above the clouds for the purpose of finding God, since he meets us in the fabric of the world, and is everywhere exhibiting to our view scenes of the most vivid description. That we may not imagine that there is any thing in Him derived, as if, by the creation of the world, he received any addition to his essential perfection and glory, we must remember that he clothes himself with this robe for our sake.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 105, 1, NULL, 'psalms-105', 'John Calvin', 'Commentaries', E'1. Praise ye Jehovah; invoke his name: announce his works among the peoples. 2. Sing ye to him: sing psalms to him: speak ye of all his wonders. 3. Rejoice ye in his holy name: let the heart of those who seek Jehovah rejoice. 4. Seek ye Jehovah, and his strength: seek his face continually. 5. Remember the marvelous works which he hath performed; his wonders, and the judgments of his mouth.

1 Praise ye Jehovah, etc. The object of these opening words simply is, that the offspring of Abraham should place all their blessedness in the free adoption of God. It was indeed a blessing not to be despised that they had been created men, that they had been cherished in the world by God''s fatherly care, and that they had received sustenance at his hand; but it was a far more distinguished privilege to have been chosen to be his peculiar people. While the whole human race are condemned in Adam, the condition of the Israelites was so different from all other nations, as to give them ground to boast, that they were consecrated to God. This is the reason why the prophet heaps together so many words in commendation of this grace. He does not treat of the government of the whole world as he did in the preceding psalm, but he celebrates the fatherly favor which God had manifested towards the children of Israel. He indeed names in general his works, and his wonders, but he limits both to that spiritual covenant by which God made choice of a church, that might lead on earth a heavenly life. He does not intend to include as among these wonders, that the sun, moon, and stars, daily rise to give light to the world, that the earth produces its fruit in its seasons, that every living creature is supplied with abundance of all good things for its food, and that the human family are liberally provided with so many conveniences; but he celebrates the sovereign grace of God, by which he chose for himself from amongst the lost race of Adam a small portion to whom he might show himself to be a father. Accordingly, he enjoins them to rejoice in the name of God, and to call upon him; a privilege by which the Church alone is distinguished. Whence it follows, that this language is addressed to none but true believers, whom God would have to glory in his name, since he has taken them under his special protection.

4 Seek ye Jehovah, and his strength Although he had in the preceding verse characterized the faithful by the honorable designation, those who seek God, yet he again exhorts them to earnestness in seeking him, which is not an unnecessary exhortation.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 106, 1, NULL, 'psalms-106', 'John Calvin', 'Commentaries', E'1. Praise ye Jehovah This exhortation supplies the want of a title; not that the psalm contains nothing else than thanksgiving and praise to God, but that the people, from the experience of past favors, may obtain the assurance of reconciliation; and thus entertain the hope that God, although at present offended, would soon be pacified towards them. In celebrating the praises of God, therefore, he orders them to call to mind such things as would have a tendency to assuage their grief on account of present ills, and to animate their spirits, and prevent them from sinking into despair.

2 Who shall express. This verse is susceptible of two interpretations; for if you read it in connection with the one immediately following, the sense will be, that all men are not alike equal to the task of praising God, because the ungodly and the wicked do nothing else than profane his holy name with their unclean lips; as it is said in the fiftieth psalm: "But unto the wicked God saith, What hast thou to do to declare my statutes, or that thou shouldest take my covenant in thy mouth?" And hence to this sentence the following clause should have been annexed, in the form of a reply, Blessed are they that keep judgment I am of opinion, however, that the prophet had another design, namely, that there is no man who has ever endeavored to concentrate all his energies, both physical and mental, in the praising of God, but will find himself inadequate for so lofty a subject, the transcendent grandeur of which overpowers all our senses. Not that he exalts the power of God designedly to deter us from celebrating its praises, but rather as the means of stirring us up to do so to the utmost of our power. Is it any reason for ceasing our exertions, that with whatever alacrity we pursue our course, we yet come far short of perfection? But the thing which ought to inspire us with the greatest encouragement is, the knowledge that, though ability may fail us, the praises which from the heart we offer to God are pleasing to him; only let us beware of callousness; for it would certainly be very absurd for those who cannot attain to a tithe of perfection, to make that the occasion of their not reaching to the hundredth part of it.

3 Blessed are they that keep judgment I make a distinction between this and the preceding verse, and yet so as to preserve the connection between them. For the prophet, having declared the magnitude of God''s power to be such that no tongue could utter all its praises, now says, that the praises of the lip merely are not acceptable to God, but that the concurrence of the heart is indispensable, nay, that even the whole of our deportment must be in unison with this exercise.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 107, 1, NULL, 'psalms-107', 'John Calvin', 'Commentaries', E'1. Praise Jehovah, because he is good: because his mercy endureth for ever. 2. Let the redeemed of Jehovah say this, whom he hath redeemed out of the hand of the afflicted. 3. Whom he hath gathered out of the lands, from the east, and from the west, from the north, and from the south. 4. They wandered from the way in the solitary desert, they did not find a city of habitation. 5. Both hungry and thirsty, so that their soul fainted within them. 6. In their straits they called upon Jehovah, and he delivered them from all their afflictions. 7. And he directed them by a right way, that they might come to a city of habitation. 8. Let them praise the mercy of Jehovah in his prescience, and his marvelous works in the presence of the sons of men. 9. Because he hath satisfied the longing soul, and hath filled the hungry soul with goodness.

1 Praise Jehovah. We have already explained this verse, for it formed the commencement of the preceding psalm. And it appears that it was not only frequently used among the Jews, but also so incorporated with other psalms, that when one part of the chorus on the one side was singing a portion of the psalm, the other part of the chorus on the opposite side in its turn, after each succeeding verse, responded, Praise Jehovah, because he is good, etc The penman of this psalm, whoever he was, has, instead of the ordinary preface, inserted this beautiful sentiment, in which praise and thanksgiving to God were so frequently expressed by the Israelitish Church. Immediately he proceeds to speak more particularly. And first, he exhorts those to offer up a tribute of gratitude to God; who, after having been delivered from slavery and imprisonment, and after a long and painful journey, arrived in safety at their place of abode. These he calls the redeemed of God; because, in wandering through the trackless desert, and howling wilderness, they many a time would have been prevented from returning home, had not God, as it were, with his outstretched hand, appeared as their guard and their guide. He does not here refer to travelers indiscriminately, but to such as either by hostile power, or by any other kind of violence, or by stern necessity, having been banished to distant regions, felt themselves to be in the midst of imminent dangers; or it may be, that he refers to those who had been made prisoners by enemies, pirates, or other robbers. He reminds them that it was by no casual occurrence that they had been driven about in that manner, and had been brought back to their native country, but that all their wanderings had been under the superintending providence of God.

But the second verse might be conjoined with the first, as if the prophet were commanding the persons whom he was addressing to sing this celebrated ode.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 108, 1, NULL, 'psalms-108', 'John Calvin', 'Commentaries', E'1. My heart is prepared, O God! my heart is prepared; I will sing and give praise, even with my glory. 2. Awake, psaltery and harp: I will arise at break of day. 3. I will praise thee, O Jehovah! among the people; and sing unto thee among the nations: 4. Because thy goodness is great above the heavens, and thy truth unto the clouds. 5. Be thou, O God! exalted above the heavens; and thy glory above all the earth: 6. That thy chosen may be set free, save me by thy right hand, and hear me. 7. God has spoken in his holiness; I will rejoice, I will divide Shechem, and measure the valley of Succoth. 8. Gilead is mine; Manasseh is mine; Ephraim is the strength of my head: Judah is my lawgiver. 9. Moab is the pot of my washing; over Edom I will cast my shoe; over Philistina I will triumph. 10. Who will bring me into the fortified city? who will bring me even unto Edom? 11. Wilt not thou, O God! who hadst repulsed us? and wentest not out, O God! with our armies? 12. Lord us help out of our tribulations; because the help of man is vain. 13. Through God we will do valiantly, and he shall trample under foot our enemies.

Because this psalm is composed of parts taken from the fifty-seventh and sixtieth psalms, it would be superfluous to repeat, in this place, what we have already said by way of exposition in those psalms. __________________________________________________________________

"Ou, mon duc." -- Fr. marg. "Or, my leader."

"The 108th psalm is altogether made up of extracts from the others; its first part being identical (with the exceptions of a few slight variations) with the third division of the 57th; its second, with the second division of the 60th. And both these borrowed parts are discriminated, both in the 57th and 60th psalms, from the rest of the context by the word Selah. This is a remarkable fact, and illustrates strongly one of the functions of the Diapsalma. These parts were, then, to a certain degree, regarded as distinct compositions, which occasionally were disjointed from their original context; the very change of sentiment and strain, which originated the word Diapsalma, sanctioning such an occasional practice." -- Jebb''s Literal Version of the Book of Psalms, with Dissertations, volume 2, page 109. __________________________________________________________________ __________________________________________________________________

This psalm consists of three parts. It begins with a complaint; next follows an enumeration of various imprecations; and then comes a prayer with an expression of true gratitude. And although David here complains of the injuries which he sustained, yet, as he was a typical character, everything that is expressed in the psalm must properly be applied to Christ, the Head of the Church, and to all the faithful, inasmuch as they are his members; so that when unjustly treated and tormented by their enemies, they may apply to God for help, to whom vengeance belongs. __________________________________________________________________', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 109, 1, NULL, 'psalms-109', 'John Calvin', 'Commentaries', E'1. O God of my praise! be not silent; 2. Because the mouth of the wicked and the mouth of deceit are opened upon me: they have spoken against me with the tongue of guile. 3. And they have encompassed me with the words of hatred, and have contended with me without cause. 4. On account of my love they have been opposed to me; but I gave myself to prayer. 5. They rendered to me evil for good, and hatred for love.

1 O God of my praise! be not silent In these words, which may be considered as an introduction to the psalm, David declares that he neither could find nor would desire any other than God to stand forward in vindication of the integrity of his heart. For in denominating him the God of his praise, he intrusts to him the vindication of his innocence, in the face of the calumnies by which he was all but universally assailed. Some are of opinion that this clause is to be understood as referring to David''s having actually declared that he himself was the publisher of God''s praises; but the scope of the passage is opposed to such an interpretation; for we find David appealing to the judgment of God against the unjust and cruel hatred to which he was subjected in the world. There is in the words an implied contrast, because, when calumny is rampant, innocence is duly and properly estimated by none but God only. The meaning of the passage is this: Lord, although I may be regarded as the vilest of the vile, and exposed to the reproach of the world, yet thou wilt maintain the uprightness of my character, and on this account thou wilt also set forth my praise. This interpretation corresponds well with that which is immediately subjoined, be not silent For when we are overwhelmed by the aspersions of the wicked, it would surely be improper on the part of God, who is the witness of our innocence, to remain silent. At the same time, what I formerly stated must not be forgotten, that while David mourns over the injuries which he in particular was suffering, yet, in his own person, he represented Christ, and the whole body of his Church. From this we are taught, when we are subjected to every species of indignity by men, to repose with perfect confidence under the protection of God alone. No man, however, can, with sincerity of heart, surrender himself entirely into the hand of God, except he has first formed the resolution of treating with contempt the reproaches of the world, and is also fully persuaded that he has God as the defender of his cause.

2 Because the mouth of the wicked David here very plainly declares, that he was the more solicitous to obtain help from God, in consequence of justice not being found among men.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 19, 110, 1, NULL, 'psalms-110', 'John Calvin', 'Commentaries', E'1. Jehovah said to my Lord, Sit at my right hand, until I make thine enemies thy footstool. 2. Jehovah shall send out of Zion the scepter of thy power: rule thou in the midst of thine enemies. 3. Thy people shall come with voluntary offerings, at the time of the assembling of thine army, in beauty of holiness: from the womb as from the morning dawn to thee has been the dew of thy youth.

1 Jehovah said to my Lord What is here stated might to some extent be applied to the person of David, inasmuch as he neither ascended the royal throne illegally, nor did he find his way to it by nefarious artifices, nor was he raised to it by the fickle suffrages of the people, but it was by the direct authority of God that he reigned over Israel. It may be justly affirmed of all the kings of the earth, that they have been placed upon their thrones by the hand of God, for the kingdoms of this world are appointed by the decree of heaven, and "there is no power but of God," (Romans 13:1) Besides, as this kingdom was altogether peculiar, it was the design of David to make a distinction between it and all other kingdoms. God indeed invests kings with authority, but they are not consecrated as David was, that like him, in consequence of the holy anointing oil, they might be elevated to the rank of Christ''s vicegerents. In the eighty-second psalm they are called gods, because by the will of God they hold their position, and in some respects are his representatives, (all power being lodged in him;) but they are not clothed with that sacred majesty by which David was honored to be a type of God''s only begotten Son. Moreover, he justly observes that the kingdom was conferred upon him in a totally different manner from other earthly kings, who, while they acknowledge that it is by the grace of God they reign, yet, at the same time, do not consider that they are sustained by his power, but, on the contrary, imagine that they reign either by their own policy, by hereditary right, or by the kindness of fortune; and, therefore, in so far as it respects themselves, it must be affirmed, that they have no legitimate title to reign. And since they do not recognize the hand of God in what they derive from him, his command cannot be properly addressed to them. David, who was well aware that he was anointed by God to be king over Israel, and who maintained an obscure and retired position until summoned to assume the reins of government, shows good cause why he is not to be classed with the ordinary kings of the earth; meaning that he reigned by a Divine right.', false, false, 'sourced', 'published');
