-- Calvin commentary INSERT — Habakkuk (batch 1, rows 1-3)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 35, 1, 1, NULL, 'habakkuk-1', 'John Calvin', 'Commentaries', E'1. The burden which Habakkuk the prophet did see.

1. Onus quod vidit Chabakuk Propheta.

The greater part of interpreters refer this burden to the Chaldeans and the monarchy of Babylon; but of this view I do not approve, and a good reason compels me to dissent from their opinion: for as the Prophet addresses the Jews, and without any addition calls his prophecy a burden, there is no doubt but that he refers to them. Besides, their view seems wholly inconsistent, because the Prophet dreads the future devastation of the land, and complains to God for allowing His chosen and elect people to be so cruelly treated. What others think is more correct--that this burden belonged to the Jews.

What the Prophet understood by the word ms'', mesha, has been elsewhere stated. Habakkuk then reproves here his own nation, and shows that they had in vain disdainfully resisted all God''s prophets, for they would at length find that their threatening would be accomplished. The burden, then, which the Prophet Habakkuk saw, was this--That God, after having exercised long forbearance towards the Jews, would at length be the punisher of their many sins. It now follows-- __________________________________________________________________

2. O LORD, how long shall I cry, and thou wilt not hear! even cry out unto thee of violence, and thou wilt not save!

2. Quousque, Jehova, clamabo, et non exaudies? Vociferabor ad te ob violentiam, et non servabis?

3. Why dost thou shew me iniquity, and cause me to behold grievance? for spoiling and violence are before me: and there are that raise up strife and contention.

3. Quare ostendis mihi iniquitatem, et moestiam aspicere facis? Et direptio et violentia in conspectu meo? et est qui litem et contentionem excitet.

As I have already reminded you, interpreters think that the Prophet speaks here of future things, as though he had in his view the calamity which he afterwards mentions; but this is too strained a meaning; I therefore doubt not but that the Prophet expostulates here with God for so patiently indulging a reprobate people. For though the Prophets felt a real concern for the safety of the people, there is yet no doubt but that they burned with zeal for the glory of God; and when they saw that they had to contend with refractory men, they were then inflamed with a holy displeasure, and undertook the cause of God; and they implored His aid to bring a remedy when the state of things had become desperate. I therefore consider that the Prophet here solicits God to visit these many sins in which the people had hardened themselves. And hence we conclude that he had previously exercised his office of a teacher; for it would have been otherwise improper for him to begin his work with such a complaint and expostulation. He had then by experience found that the people were extremely perverse.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 35, 2, 1, NULL, 'habakkuk-2', 'John Calvin', 'Commentaries', E'1. I will stand upon my watch, and set me upon the tower, and will watch to see what he will say unto me, and what I shall answer when I am reproved.

1. Super speculam meam stabo, et statuam me super arcem, et speculabor ad videndum quid loquatur mecum, et quid respondeam ad increpationem meam.

We have seen in the first chapter Habakkuk 1:2-3 that the Prophet said in the name of all the faithful. It was indeed a hard struggle, when all things were in a perplexed state and no outlet appeared. The faithful might have thought that all things happened by chance, that there was no divine providence; and even the Prophet uttered complaints of this kind. He now begins to recover himself from his perplexities; and he ever speaks in the person of the godly, or of the whole Church. For what is done by some interpreters, who confine what is said to the prophetic office, I do not approve; and it may be easy from the contempt to learn, that the Prophet does not speak according to his private feeling, but that he represents the feelings of all the godly. So then we ought to collect this verse with the complaints, which we have before noticed; for the Prophet, finding himself sinking, and as it were overwhelmed in the deepest abyss, raises himself up above the judgement and reason of men, and comes nearer to God, that he might see from on high the things which take place on earth, and not judge according to the understanding of his own flesh, but by the light of the Holy Spirit. For the tower of which he speaks is patience arising from hope. If indeed we would struggle perseveringly to the last, and at length obtain the victory over all trials and conflicts, we must rise above the world.

Some understand by tower and citadel the Word of God: and this may in some measure be allowed, though not in every respect suitable. If we more fully weigh the reason for the metaphor, we shall be at no loss to know that the tower is the recess of the mind, where we withdraw ourselves from the world; for we find how disposed we are all to entertain distrust. When, therefore, we follow our own inclination, various temptations immediately lay hold on us; nor can we even for a moment exercise hope in God: and many things are also suggested to us, which take away and deprive us of all confidence: we become also involved in variety of thoughts, for when Satan finds men wandering in their imaginations and blending many things together, he so entangles them that they cannot by any means come nigh to God. If then we would cherish faith in our hearts, we must rise above all these difficulties and hindrances.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 35, 3, 1, NULL, 'habakkuk-3', 'John Calvin', 'Commentaries', E'1. A prayer of Habakkuk the prophet upon Shigionoth.

1. Precatio Chabakuk Prophetae super ignorantiis (vel, super canticis, aut instrumentis musicis.)

There is no doubt but that the Prophet dictated this form of prayer for his people, before they were led into exile, that they might always exercise themselves in the study of religion. We indeed know that God cannot be rightly and from the heart worshipped but in faith. Hence, in order to confine the dispersed Israelites within due limits, so that they might not fall away from true religion, the Prophet here sets before them the materials of faith, and stimulates them to prayer: and we know, that our faith cannot be supported in a better way than by the exercise of prayer.

Let us then bear in mind, that the way of fostering true religion, prescribed here to the miserable Israelites while dispersed in their exile, was to look up to God daily, that they might strengthen their faith; for they could not have otherwise continued in their obedience to God. They would, indeed, have wholly fallen away into the superstitions of the Gentiles, had not the memory of the covenant, which the Lord had made with them, remained firm in their hearts: and we shall presently see that the Prophet lays much stress upon this circumstance.

He calls it his own prayer, not because he used it himself privately, or composed it for himself, but that the prayer might have some authority among the people; for they knew that a form of prayer dictated for them by the mouth of a Prophet, was the same as though the Spirit itself was to show them how they were to pray to God. The name, then, of Habakkuk is added to it, not because he used it himself, but that the people might be more encouraged to pray, when they knew that the Holy Spirit, through the Prophet, had become their guide and teacher.

There is some difficulty connected with the word sgynvt, sheginut. The verb sgg, shegag, or sgh, shege, means, to act inconsiderately; and from sgh, shege, is derived sgyvn, shegiun. Many render it, ignorance; some, delight. Some think it to be the beginning of a song; others suppose it to be a common melody; and others, a musical instrument. Thus interpreters differ. In the seventh Psalm David, no doubt, calls either a song or some musical instrument by the word sgyvn, shegiun. Yet some think that David bears testimony there to his own innocency; and that, as he was not conscious of having done wrong, his own innocency is alone signified by the title: but this is a strained view. The word is taken in this place, almost by common consent, for ignorances: and we know that the Hebrews denominate by ignorances all errors or falls which are not grievous, and such things as happen through inadvertence; and by this word they do not extenuate their faults, but acknowledge themselves to be inconsiderate when they offend.', false, false, 'sourced', 'published');
