-- Calvin commentary INSERT — Deuteronomy (batch 4, rows 31-34)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 31, 1, NULL, 'deuteronomy-31', 'John Calvin', 'Commentaries', E'9. And Moses wrote this law. It is unquestionable that Moses deposited the Book of the Law in the custody of the Levites, to enjoin upon them the duty of teaching; for although it is only related that they were commanded to recite the book before the people every seventh year, yet it is easy to gather that they were appointed the constant proclaimers of its doctrine. For it would have been absurd that the Law should lie buried for seven whole years, and that not a word should be heard of its instruction; besides, the difficulty of hearing in so great a multitude would be great, and the recollection of it would soon have vanished. In a word, very little would have been the use of the ceremony, if at all other times the Levites had been dumb, and nothing should have been heard throughout the land regarding the worship of God. This then was the object of the solemn promulgation of the Law, (Deuteronomy 31:10, etc.), which was made in the year of release, that the people should daily inquire the right way of serving God of the Levites, who were chosen to be as it were nomophulakes (guardians of the Law), that they might bring forward in due season whatever it was profitable to know. Here, then, is represented to us as in a mirror what Paul says, that the Church of God is "the pillar and ground of the truth," (1 Timothy 3:15;) because purity of doctrine is preserved unimpaired in the world, and propagated by the ministry of pastors, whilst piety would soon decay if the living preaching of doctrine should cease. Therefore Paul also elsewhere commands that the sound doctrine, of which he was a minister, should be committed by Timothy

"to faithful men, who should be able to teach others also." (2 Timothy 2:2.)

First, then, we must remember, that the Book of the Law was given in trust, as it were, to the Levites, that the people might learn from them what was right. The addition of "the elders" is not superfluous; for although the office of teaching was not committed to them, yet were they given as coadjutors to the Levites, in order that they might uphold the doctrine of the Law, and not suffer it to be scorned. We know how great is the insolence of the people in rejecting pious teachers, unless they are restrained by those in authority; nor do the latter indeed duly fulfill their duty, if they do not keep their subjects to the study of religion, who would be otherwise too much disposed to impiety.

Moses in this passage calls by the name of "the Law," not the Ten Commandments engraved on the two tables, but the interpretation of it contained in the four books. The circumstances took place thirty-nine years after God had spoken on Mount Sinai.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 32, 1, NULL, 'deuteronomy-32', 'John Calvin', 'Commentaries', E'1. Give ear, O ye heavens. Moses commences in a strain of magnificence, lest the people should disdain this song with their usual pride, or even reject it altogether, being exasperated by its severe censures and reproaches. For we well know how the world naturally longs to be flattered, and that no strain can be gratifying to it unless it tickles and soothes the ear with praise. But Moses here not only inveighs bitterly against the vices of the people, but with the utmost possible vehemence stigmatizes their perverse nature, their utterly corrupt morals, their obstinate ingratitude, and incorrigible contumacy. Moreover, he desired that these accusations, whereby he rendered their name detestable, should daily echo from their tongues; and thus they became still more offensive. It was, therefore, requisite that their impatience should be bridled, as it were, in order that they might patiently and humbly receive these just reproofs, however severe they might be. If, therefore, they should repudiate this song, or should turn a deaf ear to it, he declares at the outset that heaven and earth would be witnesses of their prodigious obtuseness; nay, he turns and addresses himself to heaven and earth, and thus signifies that it was worthy of the attention of all creatures, even although they were without intelligence or feeling. For it is a hyperbolical mode of expression, when he assigns the faculty of hearing, and being instructed, to the senseless elements; just as Isaiah, when he would intimate that he found none to give heed to him amongst the whole people, in like manner appeals to the heavens and the earth, and even summons them to bear witness to the prodigious iniquity, that there should be less of intelligence amongst the whole people than in oxen and asses. (Isaiah 1:2, 3.) For it is but a meager exposition, which some give of these words, that they are used, by metonymy, for angels and men.

2 My doctrine shall drop as the rain. Some, as I think improperly, here resolve the future tense into the optative mood, for in this splendid eulogium he rather celebrates, in order to commend his doctrine, the fruitfulness which is actually imparted to it by the Holy Spirit, than asks for it to be given to him; and my readers must at once perceive that such a request would have been by no means seasonable. He therefore compares his speech to rain or dew, as if he had said that, if only the people were like the soil in a state of softness and preparation, he would deliver doctrine to them which would irrigate them unto abundant fruitfulness.

Although this expression refers especially, and kat '' exochen to the Song, still its force and propriety extends to all divine teaching; for God never speaks except to render men fruitful in good works, just as, by instilling succulency and vigor into the earth by means of rain, He makes it fertile for the production of fruit.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 33, 1, NULL, 'deuteronomy-33', 'John Calvin', 'Commentaries', E'1. And this is the blessing. The bitterness of the Song was seasoned, as it were, by this palliative, wherein Moses left a testimony with respect to God''s future and perpetual grace, as if depositing an inestimable treasure in the hands of the people. For, as God, after the deliverance of His people, and the giving of the Law, renewed the covenant which Jacob had testified of and proclaimed, so Moses was, as it were, their second father, to ratify anew its blessings, lest the memory of them should ever be lost.

In order to beget confidence in his benedictions, he commences by magnifying his vocation before he proceeds to them; for, although the word benediction is equivalent to a prayer for success, yet must it be borne in mind that Moses does not here pray in the ordinary manner, like a private person, in such a way as fathers are wont to offer supplications for their children; but that, in the spirit of prophecy, he sets forth the blessings which were to be expected from God. This, then, is the reason why he extols the dignity and glory of his office as ruler in such lofty terms, viz., that the twelve tribes of Israel may be thoroughly assured that God is the author of these blessings. For the same reason he calls himself "the man of God:" that the people may receive what he is about to say as if it. proceeded from God, whose undoubted minister he is. Nor is the circumstance of time without its weight -- "before his death," or, "in his death," which adds to the prophecy the force of a testament.

2 And he said, The Lord came from, Sinai. In these words he reminds them that he is setting before them, a confirmation of the covenant, which God had made with them in this Law, and that it is nothing different from it; for this connection was of exceeding efficacy in establishing the certainty of the blessings, provided only the Law was duly honored; for nothing was better adapted to confirm the grace of God than the majesty which was displayed in the promulgation of the Law. Some, as I conceive improperly, translate it, -- "God comes to Sinai," whereas Moses rather means that he came from thence, when His brightness was made manifest. By way of ornament, the same thing is repeated with respect to Seir and Paran; and, since these three words are synonymous, therefore to go forth, to rise up, and to come, also represent the same thing, viz., that manifestation of the divine glory which should have ravished into admiration the minds of all; as though he had said that his blessings were to be received with the same reverence, as that which God had procured for His Law, when His face was conspicuously displayed on Mount Sinai.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 5, 34, 1, NULL, 'deuteronomy-34', 'John Calvin', 'Commentaries', E'5. So Moses the servant of the Lord died. Since it was mark of ignominy to die without the borders of the Holy Land, Moses is honored with high eulogy, in order that the Israelites might learn the more to tremble at the judgment of God, who did not spare even his most illustrious servant. And it is expressly added, "according to the word (or mouth) of the Lord," lest they should despise the threatenings which were accomplished in so memorable a manner. For, if God spared not His own distinguished Prophet, but at length executed upon him what He had threatened, how should the ordinary multitude escape?

What follows, "he buried him," some render passively, "he was buried;" and others transitively, "he buried himself;" but in both cases improperly; for, whilst they are afraid to assign this office to God, they labor to avoid an absurdity which does not exist; since it may be gathered from the end of the verse, that Moses was buried by divine means, for it is said that his sepulcher is unknown. It is likely that an effort to discover it was not omitted, or neglected to be made by the people; since it would have been barbarous for them not to discharge the last offices of humanity towards such, and so great a man. Since, therefore, no signs of his funeral, nor his body itself, were anywhere to be found, it might be inferred that he was hidden by God''s determinate counsel; whilst it is superfluous to discuss in what manner God buried him, inasmuch as all the elements are under His control. It was enough, therefore, for Him to signify (annuere) to the earth, that it was to receive the body of the holy man into its bosom: nor was there any necessity to call in the assistance of angels, as some think, since the earth would have instantly obeyed the command of its Creator. From the Epistle of Jude (Jude 9) we learn that it was a matter of no slight importance that the sepulcher of Moses should be concealed from the eyes of men, for he informs us that a dispute arose respecting it. between Michael the archangel, and Satan: and, although the cause of its concealment is not stated, still it appears to have been God''s intention to prevent superstition; for it was usual with the Jews, and it is a custom for which Christ reproves them, to kill the prophets, and then to pay reverence to their tombs. (Luke 11:47.) It would have, therefore, been probable that, in order to blot out the recollection of their ingratitude, they would have paid superstitious veneration to the holy prophet, and so have carried his corpse into the land, from which the sentence of God had excluded it. Timely precaution, then, was taken, lest in their inconsiderate zeal the people should attempt to subvert the decree of heaven.

7 And Moses was an hundred and twenty years old.', false, false, 'sourced', 'published');
