-- Calvin commentary INSERT — Isaiah (batch 3, rows 21-30)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 21, 1, NULL, 'isaiah-21', 'John Calvin', 'Commentaries', E'1. The burden of the desert of the sea. The Prophet, after having taught that their hope ought to be placed, not on the Egyptians, but on the mercy of God alone, and after having foretold that calamities would come on the nations on whose favor they relied, adds a consolation in order to encourage the hearts of the godly. He declares, that for the Chaldeans, to whom they will be captives, a reward is prepared; from which it follows, that God takes account of the injuries which they endure. By the desert he means Chaldea, not that it was deserted or thinly inhabited, but because the Jews had a desert on that side of them; just as if, instead of Italy, we should name "the Alps," because they are nearer to us, and because we must cross them on our road to Italy. This reason ought to be kept in view; for he does not describe the nature of the country, but forewarns the Jews that the destruction of the enemies, which he foretells, is near at hand, and is as certain as if the event had been before their eyes, as that desert was. Besides, the prophets sometimes spoke ambiguously about Babylon, that believers alone might understand the hidden mysteries, as Jeremiah changes the king''s name.

As storms from the south. He says from the south, because that wind is tempestuous, and produces storms and whirlwinds. When he adds that "it cometh from the desert," this tends to heighten the picture; for if any storm arise in a habitable and populous region, it excites less terror than those which spring up in deserts. In order to express the shocking nature of this calamity, he compares it to storms, which begin in the desert, and afterwards take a more impetuous course, and rush with greater violence.

Yet the Prophet appears to mean something else, namely, that as they burst forth like storms from that direction to lay Judea desolate, so another storm would soon afterwards arise to destroy them; and therefore he says that this burden will come from a terrible land. By this designation I understand Judea to be meant, for it was not enough to speak of the ruin of Babylon, if the Jews did not likewise understand that it came from God. Why he calls it "a terrible land" we have seen in our exposition of the eighteenth chapter. It was because, in consequence of so many displays of the wrath of God, its disfigured appearance might strike terror on all. The occasion on which the words are spoken does not allow us to suppose that it is called "terrible" on account of the astonishing power of God by which it was protected. Although therefore Babylon was taken and plundered by the Persians and Medes, Isaiah declares that its destruction will come from Judea; because in this manner God will revenge the injuries done to that nation of which he had promised to be the guardian.

2.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 22, 1, NULL, 'isaiah-22', 'John Calvin', 'Commentaries', E'1. The burden of the valley of vision. Isaiah again prophesies against Judea, which he calls the valley of vision. He gives this appellation to the whole of Judea rather than to Jerusalem, of which he afterwards speaks; but now in the preface he includes the whole of Judea. He appropriately calls it a "valley," for it was surrounded on all sides by mountains. It is a harsher view of the metaphor, which is adopted by some, that Jerusalem is called "a valley," because it was thrown down from its loftiness. The reason why he adds the words, of vision, is plain enough. The Lord enlightened the whole of Judea by his word; the prophets were continually employed in it, and that was the reason why they called them seers. (1 Samuel 9:9.) There is also an implied contrast here, for valleys have less light than open plains, because the height of the mountains intercepts the light of the sun. Now, this valley, he tells us, is more highly enlightened than those countries which were exposed on all sides to the sun. It was by the extraordinary goodness of God that this happened; for he means, that it was enlightened, not by the rays of the sun, but by the word of God.

Besides, the Prophet unquestionably intended to beat down that foolish confidence with which the Jews were puffed up, because God had distinguished them above others by remarkable gifts. They abused his word and prophecies, as if by means of them they had been protected against all danger, though they were disobedient and rebellious against God. He therefore declares that visions will not prevent God from punishing their ingratitude; and he even aggravates their guilt by this mark of ingratitude, that amidst such splendor of heavenly doctrine they still continued to stumble like the blind.

What hast thou here? or, What hast thou now? He now addresses Jerusalem; not that this defeat affects Jerusalem alone, but because the whole country thought it safe to take refuge under the shadow of the sanctuary which then existed, and to lead the Jews to reflect, since this befell a fortified city, what would become of other cities which had no means of defense. He asks in astonishment, "What does it mean that every person leaves his house and flies to the house-top for the purpose of saving his life?" Among the Jews the form of house-tops was different from what is now customary with us, and hence arose that saying of Christ,

"What you have heard in the ear proclaim on the housetops." (Matthew 10:27.)

When the inhabitants of Jerusalem fled to the house-tops, they left their houses open to be a prey to enemies, and this was a proof that they were exceedingly afraid.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 23, 1, NULL, 'isaiah-23', 'John Calvin', 'Commentaries', E'1. The burden of Tyre. Tyre was very wealthy, and highly celebrated, both on account of the variety and extent of its commercial intercourse with all nations, and on account of the flourishing colonies which sprang from it: Carthage, which was the rival of the Roman Empire, Utica, Leptis, Cadiz, and other towns, which also sent every year a present to Tyre, by which they acknowledged that they looked on Tyre as their mother. Isaiah threatens its destruction, because it had been hostile to the people of God, as we may infer from what is said by Ezekiel; for we ought carefully to attend to the cause of the destruction, because it was the design of the Prophet to shew that God testifies his fatherly regard to his people by opposing all her enemies. (Ezekiel 26:2.) Some think that this refers to the storming of Tyre by Alexander, who took it with great difficulty. But the argument on which they rely, that Isaiah mentions Chittim, has little force. By that name the Hebrew writers unquestionably denote the Macedonians, but under this word they likewise include other nations, such as the Greeks, and the countries that were beyond the sea. Nebuchadnezzar employed in that siege not only his own soldiers, but also foreigners, whom he brought from Greece and other places. It is for a reason altogether different, as we shall immediately see, that he mentions the Greeks, namely, that henceforth they will not take their ships to Tyre for the sake of carrying on merchandise.

But from the conclusion of this chapter I draw an argument for a contrary opinion, for Isaiah speaks of the restoration of Tyre, and it was never restored after having been stormed by Alexander. Besides, when I compare Ezekiel''s words with those of Isaiah, I think that I see one and the same prediction. Now, he does not speak of Alexander, but of Nebuchadnezzar; and I cannot doubt that it must be explained in that manner. Not only so, but in the days of Ezekiel and Isaiah that city was under the dominion of a king, but historians relate that, when it was stormed by Alexander, it had been brought to the form of a republic. And if we consider the object of the prophecy, we shall be sufficiently confirmed in this opinion, for his aim is to comfort the Jews by threatening that the inhabitants of Tyre, by whom they had been oppressed, will not pass unpunished. For it would have been highly inconsistent that the Lord should punish other nations, and that this nation, which had been not less hostile, should escape punishment altogether, or be punished five hundred years afterwards. Every conjecture, therefore, leads us to this conclusion, that we should expound this passage as relating to Nebuchadnezzar.

Howl, ye ships of Tarshish.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 24, 1, NULL, 'isaiah-24', 'John Calvin', 'Commentaries', E'1. Behold, Jehovah maketh the earth empty. This prophecy, so far as I can judge, is the conclusion of all the descriptions that have been given from the thirteenth chapter downwards, in which Isaiah foretold destruction not only to the Jews and to Israel, but to the Moabites, Assyrians, Egyptians, and other nations. In short, having, as it were, surveyed all the countries which were near the Jews and known to them, he gives a brief summary of the whole. Some view this as referring to Israel, and others to the Jews, and think that their destruction is foretold; but as he mentions the world, I can view it in no other light than as a comprehensive statement of all that he formerly said about each of them, and at different times. Nor is this view contradicted by the fact that he immediately mentions the priest, which might lead us to believe that these things relate to none but the people of God; for although he speaks of all the nations, yet because the Jews always hold the highest rank, Isaiah must have had them especially in his eye, for he was appointed to them. It may be said to have been accidental that he mentions other nations; and therefore we ought not to wonder if, after having made reference to them, he speaks particularly about his own people in a single word.

Others suppose that he means "the whole world," but think that he refers to the last day, which I consider to be an excessively forced interpretation; for, after having threatened the Jews and other nations, the Prophet afterwards adds a consolation, that the Lord will one day raise up his Church and make her more flourishing; which certainly cannot apply to the last judgment. But by the term the earth, I do not think that the Prophet means the whole world, but the countries well known to the Jews; just as in the present day, when we speak of what happens in the world, we almost never go beyond Europe, or think of what is passing in India; for this may be said to be our world. Thus, Isaiah speaks of "the earth" known to himself and to all whom he addressed, and of the people who inhabited the neighboring countries. In short, we may limit the term "World" to the Egyptians, Assyrians, Moabites, Tyrians, and such like; as if he had said, "Hitherto I have spoken of various calamities, which threatened many nations, and still in part threaten some of them; but I may sum up all by saying, The Lord will overturn and strip the face of the earth of all its ornaments.''"

And maketh it bare. Some translate vlqh, (bOlEkach,) he uncovereth the earth, that the enemies may have free entrance into it.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 25, 1, NULL, 'isaiah-25', 'John Calvin', 'Commentaries', E'1. O Lord, thou art my God. Hitherto Isaiah has prophesied about the judgments of God, which threatened not only a single nation, but almost the whole world. Now, it was impossible that the contemplation of calamities so dismal as those which he foresaw should not give him great uneasiness; for godly persons would desire that all mankind should be saved, and, while they honor God, they desire also to love all that belongs to him; and, in short, so far as any man sincerely fears God, he has a powerful and lively feeling of the divine judgments. While wicked men stand amazed at the judgments of God, and are not moved by any terror, godly men tremble at the slightest token of his anger. And if this be the case with us, what do we suppose was experienced by the Prophet, who had almost before his eyes those calamities which he foretold? For, in order that the ministers of the word might be convinced of the certainty of what they taught, it was necessary that they should be more powerfully impressed by it than the generality of men.

Since therefore the Lord held out to Isaiah, as in a picture, those dreadful calamities, he found it necessary, under the overpowering influence of grief and anxiety, to betake himself to the Lord; otherwise the confused emotions of his mind would have agitated him beyond measure. He therefore takes courage from the belief that, in the midst of these tempests, the Lord still determines to promote the advantage of his Church, and to bring into subjection to himself those who were formerly estranged. Isaiah therefore remains firm and steadfast in his calling, and does not allow himself to be drawn aside from his purpose, but continually relies on the expectation of mercy, and therefore perseveres in celebrating the praises of God. Thus we learn that this thanksgiving is connected with the former prophecies, and that Isaiah considers not only what he foretold, but why the Lord did it; that is, why the Lord afflicted so many nations with various calamities. It was, that he might subdue those who were formerly incorrigible, and who rushed forward with brutal eagerness, who had no fear of God, and no feeling of religion or godliness.

Thou art my God. Being as it were perplexed and confused, he suddenly raises his thoughts to God, as we have already said. Hence we ought to draw a very useful doctrine, namely, that when our minds are perplexed by a variety of uneasy thoughts on account of numerous distresses and afflictions which happen daily, we ought immediately to resort to God, and rely on his providence; for even the smallest calamities will overwhelm us, if we do not betake ourselves to him, and support our hearts by this doctrine.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 26, 1, NULL, 'isaiah-26', 'John Calvin', 'Commentaries', E'1. In that day shall a song be sung. Here the Prophet begins again to shew that, after the return of the people from captivity, they will be defended by God''s power and guardianship, and that under his protection Jerusalem will be as safe as if she had been surrounded by bulwarks, ramparts, a ditch, and a double wall, so that no enemy could find entrance.

It is proper to observe the time when "this song was sung." The Prophet had foretold the calamity that would befall the Church, which was not yet so near at hand, but happened a short time after his death. When the people were led into captivity, they would undoubtedly have despaired, if they had not been encouraged by such promises. That the Jews might cherish a hope that they would be delivered, and might behold life in the midst of death, the Prophet composed for them this song, even before the calamity occurred, that they might be better prepared for enduring it, and might hope for better things. I do not think that it was composed solely that, when they had been delivered, they might give thanks to God, but that even during their captivity, though they were like dead men, (Ezekiel 37:1,) they might strengthen their hearts with this confidence, and might also train up their children in this expectation, and hand down these promises, as it were, to posterity.

We have formerly seen the reason why these and other promises were put by Isaiah into the form of verse. It was, that, having been frequently sung, they might make a deeper impression on their memory. Though they mourned in Babylon, and were almost overwhelmed with sorrow, (hence these sounds, (Psalm 137:4,) "How can we sing the Lord''s song in a foreign land?") yet they must have hoped that at a future period, when they should have returned to Judea, they would give thanks to the Lord and sing his praises; and therefore the Prophet shews to them at a distance the day of deliverance, that they may take courage from the expectation of it.

We have a city of strength. By these words a full restoration of Jerusalem and of the people is promised, because God will not only deliver the captives and gather those that are scattered, but will also preserve them safe, after having brought them back to their country. But not long afterwards believers saw that Jerusalem was destroyed, (2 Kings 25:9,) and the Temple thrown down, (2 Chronicles 36:19,) and after their return nothing could meet their eye but hideous ruins; and all this Isaiah had previously foretold. It was therefore necessary that they should behold from the lofty watch-tower of faith this restoration of Jerusalem.

He hath made salvation to be walls and a bulwark. He now defines what will be "the strength of the city;" for the "salvation" of God will supply the place of a "wall," towers, ditches, and mounds.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 27, 1, NULL, 'isaiah-27', 'John Calvin', 'Commentaries', E'2. Sing to the vineyard of redness. He now shews that all this will promote the salvation of the Church; for the Lord attends to the interests of his people, whom he has taken under his guardianship and protection. In order, therefore, that the Church may be restored, Satan and all his kingdom shall be utterly destroyed. The object of all the vengeance which God takes on his enemies is to shew that he takes care of the Church; and although in this passage the Prophet does not name the Church, he shews plainly enough that he addresses her in this congratulation.

This figure conveys the meaning even more strongly than if he had spoken expressly of the people of Israel; for since the whole excellence of a vineyard depends partly on the soil in which it is planted, and partly on diligent cultivation, if the Church of God is a vineyard, we infer that its excellence is owing to nothing else than the undeserved favor of God and the uninterrupted continuance of his kindness. The same metaphor expresses also God''s astonishing love towards the Church, of which we spoke largely under the fifth chapter.

He calls it a vineyard of redness, that is, very excellent; for in Scripture, if we compare various passages, "red wine" denotes excellence. He says that this song may at that time be sung in the Church, and foretells that, though it would in the mean time be reduced to fearful ruin, and would lie desolate and waste, yet that afterwards it will be restored in such a manner as to yield fruit plentifully, and that this will furnish abundant materials for singing.

3. I Jehovah keep it. Here the Lord asserts his care and diligence in dressing and guarding the vine, as if he had said, that he left nothing undone that belonged to the duty of a provident and industrious householder. Not only does he testify what he will do, when the time for gladness and congratulation shall arrive, but he relates the blessings which the Jews had already received, that their hope for the future may be increased. Yet we must supply an implied contrast with the intermediate period, during which God appeared to have laid aside all care of it, so that at that time it differed little from a wilderness. This then is the reason why the Lord''s vineyard was plundered and laid waste; it was because the Lord forsook it, and gave it up as a prey to the enemy. Hence we infer that our condition will be ruined as soon as the Lord has departed from us; and if he assist, everything will go well.

I will water it every moment. He next mentions two instances of his diligence, that he "will water it every moment," and will defend it against the attacks of robbers and cattle and other annoyances. These are the two things chiefly required in preserving a vineyard, cultivation and protection.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 28, 1, NULL, 'isaiah-28', 'John Calvin', 'Commentaries', E'1. Woe to the crown of pride. Isaiah now enters on another and different subject from that which goes before it; for this discourse must be separated from the former one. He shews that the anger of the Lord will quickly overtake, first, Israel, and afterwards the Jews; for it is probable that the kingdom of Israel was still entire when the Prophet uttered these predictions, though nothing more can be affirmed with certainty than that there is good reason to believe that the ten tribes had not at that time been led into captivity.

Accordingly, the Prophet follows this order. First, he shews that the vengeance of God is not far from Israel, because various sins and corruption of every kind prevailed in it; for they were swelled with pride and insolence, had plunged into their luxuries and given way to every kind of licentiousness, and, consequently, had broken out into open contempt of God, as is usually the case when men take excessive liberties; for they quickly forget God. Secondly, he shews that God in some measure restrains his anger by sparing the tribe of Judah; for when the ten tribes, with the half tribe of Benjamin, had been carried into captivity, the Jews still remained entire and uninjured. Isaiah extols this compassion which God manifested, in not permitting his Church to perish, but preserving some remnant. At the same time he shews that the Jews are so depraved and corrupted that they do not permit God to exercise this compassion, and that, in consequence of the wickedness which prevailed among them, not less than in Israel, they too must feel the avenging hand of God. This order ought to be carefully observed; for many persons blunder in the exposition of this passage, because the Prophet has not expressly mentioned the name of Israel, though it is sufficiently known that Ephraim includes the ten tribes.

As to the words, since the particle hvy (hOi) very frequently denotes "wishing evil on a person," I was unwilling to depart from the ordinary opinion of commentators, more especially because the Prophet openly threatens in this passage; yet if the translation, Alas the crown! be preferred, I have no objection.

For the excellence of its glory shall be a fading flower The copulative v (vau) signifies for or because. He compares the "glory" and "excellence" of Israel to "a fading flower," as will afterwards be stated. In general, he pronounces a curse on the wealth of the Israelites; for by the word "Crown" he means nothing else than the wicked confidence with which they were puffed up, and which proceeded from the excess of their riches. These vices are almost always joined together, because abundance and fullness produce cruelty and pride; for we are elated by prosperity, and do not know how to use it with moderation. They inhabited a rich and fertile country, and on this account Amos (Amos 4:1) calls them "fat cows," which feed on the mountain of Samaria.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 29, 1, NULL, 'isaiah-29', 'John Calvin', 'Commentaries', E'1. This appears to be another discourse, in which Isaiah threatens the city of Jerusalem. He calls it "Altar," because the chief defense of the city was in the "Altar;" for although the citizens relied on other bulwarks, of which they had great abundance, still they placed more reliance on the Temple (Jeremiah 7:4) and the altar than on the other defences. While they thought that they were invincible in power and resources, they considered their strongest and most invincible fortress to consist in their being defended by the protection of God. They concluded that God was with them, so long as they enjoyed the altar and the sacrifices. Some think that the temple is here called "Ariel," from the resemblance which it bore to the shape of a lion, being broader in front and narrower behind; but I think it better to take it simply as denoting "the Altar," since Ezekiel also (Ezekiel 43:15) gives it this name. This prediction is indeed directed against the whole city, but we must look at the design of the Prophet; for he intended to strip the Jews of their foolish confidence in imagining that God would assist them, so long as the altar and the sacrifices could remain, in which they falsely gloried, and thought that they had fully discharged their duty, though their conduct was base and detestable.

The city where David dwelt. He now proceeds to the city, which he dignifies with the commendation of its high rank, on the ground of having been formerly inhabited by David, but intending, by this admission, to scatter the smoke of their vanity. Some understand by it the lesser Jerusalem, that is, the inner city, which also was surrounded by a wall; for there was a sort of two-fold Jerusalem, because it had increased, and had extended its walls beyond where they originally stood; but I think that this passage must be understood to relate to the whole city. He mentions David, because they gloried in his name, and boasted that the blessing of God continually dwelt in his palace; for the Lord had promised that "the kingdom of David would be for ever." (2 Samuel 7:13; Psalm 89:37.)

Hence we may infer how absurdly the Papists, in the present day, consider the Church to be bound to Peter''s chair, as if God could nowhere find a habitation in the whole world but in the See of Rome. We do not now dispute whether Peter was Bishop of the Church of Rome or not; but though we should admit that this is fully proved, was any promise made to Rome such as was made to Jerusalem? "This is my rest for ever: here will I dwell, for I have chosen it." (Psalm 132:14.) And if even this were granted, do not we see what Isaiah declares about Jerusalem? That God is driven from it, when there is no room for doctrine, when the worship of God is corrupted.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 23, 30, 1, NULL, 'isaiah-30', 'John Calvin', 'Commentaries', E'1. Woe to the rebellious children. The Prophet exclaims against the Jews, because, when they were unable to bear the burden, when they were hard pressed by the Assyrians and other enemies, they fled to Egypt for help. This reproof might appear to be excessively severe, were we merely to consider that weak and miserable men, especially when they are unjustly oppressed, have a right to ask assistance even from wicked persons; for it is a principle implanted in us by nature, that all human beings should willingly, and of their own accord, endeavour to assist each other. But when we come to the very sources, we shall find that no ordinary or inconsiderable guilt had been contracted by the people.

First, it is no light offense, but wicked obstinacy, to disregard and even despise God''s government, and follow their own inclinations. But God had strictly forbidden them to enter into any alliance or league with the Egyptians. (Exodus 13:17; Deuteronomy 17:16.) There were chiefly two causes of this prohibition. One was general, and related to alliances and leagues with other nations; for God did not wish that his people should be corrupted by the superstitions of the Gentiles. (Exodus 23:32; 34:15; Deuteronomy 7:2.) We are gradually infected, I know not how, by the vices of those with whom we have intercourse and familiarity; and as we are more prone by nature to copy vices than virtues, we easily become accustomed to corruptions, and, in short, the infection rapidly spreads from one person to another. This has happened to our own country, France, in consequence of having intercourse with many nations, which leads her too eagerly to imitate their vices, and has covered her with frightful pollution. This immoderate desire of forming alliances unlocked Asia to the Mahometans, and next laid Europe open to them; and though they still retain their moderation in eating and drinking, all that has been subdued by their arms has contracted nothing but filth and debasement. This is what we Frenchmen have also derived from our intercourse with other nations.

The second reason was special and peculiar to this nation; for, since the Lord had delivered the Jews out of Egypt, and commanded them to remember so remarkable a benefit, he forbade them to have any intercourse with the Egyptians. And if they had entered into an alliance with the Egyptians, the remembrance of that benefit might easily have been obliterated; for they would not have been at liberty to celebrate it in such a manner as had been commanded. (Exodus 13:3, 8,14.) It was excessively base to disregard the glory of God for the purpose of cultivating friendship with an irreligious and wicked nation. Since God intended also to testify to his people that he alone was more than sufficient to secure their safety, they ought to have valued that promise so highly as to exclude themselves willingly from other assistance.', false, false, 'sourced', 'published');
