-- Calvin commentary INSERT — Jeremiah (batch 3, rows 21-30)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 21, 1, NULL, 'jeremiah-21', 'John Calvin', 'Commentaries', E'7. And afterward, saith the LORD, I will deliver Zedekiah king of Judah, and his servants, and the people, and such as are left in this city from the pestilence, from the sword, and from the famine, into the hand of Nebuchadrezzar king of Babylon, and into the hand of their enemies, and into the hand of those that seek their life: and he shall smite them with the edge of the sword; he shall not spare them, neither have pity, nor have mercy. 7 Et post sic (postea) dicit Jehova, Tradam Zedekiam, regem Jehudah, et servos ejus, et populum, et qui residui erunt in urbe hae a peste, a gladio, et a fame, in manum Nebuehadrezer, regis Babylonis, et in manum inimieorum ipsorum, et in manum quaerentium animam ipsorum; et percuitet eos ore gladii; non parcet illis, neque ignoscet, neque miserabitur. Jeremiah goes on with the same discourse, even that God had resolved to destroy Jerusalem and the people, at least for a time. But he points out here what he intended to do, even that he would consume them by pestilence and famine, as long as they continued in the city; as though he had said, "Though these Chaldeans may not immediately take the city by means of a siege, yet its destruction shall be worse, for famine shall rage within and consume them." We now perceive the design of the Prophet. But we must keep in mind what I reminded you of yesterday, -- that God assumes to himself what might have been ascribed to the Chaldeans, for he makes himself the author of all these calamities; I will smite, he says, the inhabitants of this city, both man and beast; by a great pestilence shall they die This was the first kind of punishment; before the enemy rushed into the city the pestilence had consumed many of the people. Now there is a circumstance mentioned which shews how dreadful would be their state, for not only men would perish, but even brute animals. It was no wonder that God''s vengeance extended to horses, and oxen, and asses; for we know that all these were created for the use of man. Hence when God manifested his wrath as to these animals, His object was to fill men with greater terrors; for they thus saw oxen and asses, though innocent, involved in the same punishment with themselves. For how can we suppose that horses and asses deserved to perish by diseases, or through want of daily food? But God sets forth such a spectacle as this, that he may more effectually touch men; for they thus see that the whole world is exposed to a curse through their sins. They are indeed constrained to know how great their sinfulness is; for on this account it is that the earth becomes dry and barren, that the elements above and below perform not their offices, so that the sterility of the ground deprives animals of their food, and the infection', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 22, 1, NULL, 'jeremiah-22', 'John Calvin', 'Commentaries', E'1. Thus saith the LORD; Go down to the house of the king of Judah, and speak there this word, 1. Sic dicit Jehova, Descende in domum regis Jehudah, et loquere illic ser-monem hunc, 2. And say, Hear the word of the LORD, O king of Judah, that sittest upon the throne of David, thou, and thy servants, and thy people that enter in by these gates: 2. Et dices, Audi sermonem Jehova, rex Jehudah, qui sedes super solium Davidis, tu et servi tui, et populus tuus qui ingredimini per portas has: 3. Thus saith the LORD, Execute ye judgment and righteousness, and deliver the spoiled out of the hand of the oppressor: and do no wrong, do no violence to the stranger, the fatherless, nor the widow, neither shed innocent blood in this place. 3. Sic dicit Jehova, Facite judicium et justitiam, et eripite spoliatum e manu oppressoris; peregrinum, pupilum, et viduam ne fraudetis (Hieronymus hoc verbum ubique vertit, contristari, vel, tristitia afficere; significat autem potius inferre violentiam, aut fraudulenter nocere;) ne violentiam exerceatis (alii vertunt, rsmcht l'', et sanguinem innocentem ne fundatis in loco isto. The Prophet is again bidden to reprove the king and his counsellors; but the exhortation is at the same time extended to the whole people. It was necessary to begin with the head, that the common people might know that it was not a matter to be trifled with, as God would not spare, no, not even the king himself, and his courtiers; for a greater terror seized the lower orders, when they saw the highest laid prostrate. That what is here taught might then penetrate more effectually into the hearts of all, the Prophet is bid to address the king himself and his courtiers: he is afterwards bidden to include also the whole body of the people. And hence it appears, that there was some hope of favor yet remaining, provided the king and the whole people received the admonitions of the Prophet; provided their repentance and conversion were sincere, God was still ready to forgive them. We must at the same time observe, as I have already said, that they could not escape the calamity that was at hand; but exile would have been much milder, and also their return would have been more certain, and they would have found in various ways that they had not been rejected by God, though for a time chastised. As then we now say, that a hope of pardon was set before them, this is not to be so understood as that they could avert the destruction of the city; for it had once for all been determined by God to drive the people into a temporary exile, and also to put all end for a time to their sacrifices; for this dreadful desolation was to be a proof that the people had been extremely ungrateful to God, and especially that their obstinacy could not be endured in having so long despised the Prophets', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 23, 1, NULL, 'jeremiah-23', 'John Calvin', 'Commentaries', E'1. Woe be unto the pastors that destroy and scatter the sheep of my pasture! saith the LORD.

1. Vae Pastoribus qui perdunt et dissipant gregem pascuorum meorum! dicit Jehova.

2. Therefore thus saith the LORD God of Israel against the pastors that feed my people; Ye have scattered my flock, and driven them away, and have not visited them: behold, I will visit upon you the evil of your doings, saith the LORD.

2. Propterea sic dicit Jehova, Deus Israel, super Pastores pascentes populum meum, Vos dissipastis gregem meum et dispulistis, et non visitastis eos (vel, oves meas;) Ecce ego visitans (hoc est, visitabo) super vos malitiam actionum vestrarum, dicit Jehova:

3. And I will gather the remnant of my flock out of all countries whither I have driven them, and will bring them again to their folds; and they shall be fruitful and increase.

3. Ego autem colligam residuum ovium mearum ex omnibus terris, ad quas expulero eas, et reverti faciam eas ad caulas suas, et fructificabunt et multiplicabuntur.

Here the Prophet promises the restoration of the Church; but he reminds hypocrites that there was no reason for them on that account to flatter themselves, especially the king, his councillors, and the priests. Then this prophecy is a mixture of promises and threatenings, for God promises that he would be propitious to the miserable Jews, after having chastised them, so that the seed of Abraham might not be entirely cut off: he yet deprives hypocrites of vain confidence, so that they might not falsely apply to themselves the hope of salvation, from which they had excluded themselves by their impiety. And this is what ought to be noticed, for as soon as God''s mercy is offered, hypocrites apply to themselves whatever God promises, and become more and more insolent, as though they held him bound to them; for impunity leads them to take more liberty to sin. Hence it is that they boast that they are safe, for they consider themselves to be the people of God. The Prophet, therefore, teaches here that whatever God promises belongs to his elect, that it does not appertain indiscriminately to all, nor ought to be extended to hypocrites who falsely pretend his name, but that it peculiarly belongs to the elect, though they may be small in number, and though they may be despised.

He says first, Wo to the pastors who destroy, etc. Here are contrary things -- a pastor and a destroyer! But he concedes to them the name which was honorable; and yet he derides their false boasting, for they thought that they could hide their crimes under this shade, falsely claimed. Though then he calls them pastors, he yet removes the mask, and thus shews that they in vain boasted while they assumed the name of pastors.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 24, 1, NULL, 'jeremiah-24', 'John Calvin', 'Commentaries', E'1. The LORD shewed me, and, behold, two baskets of figs were set before the temple of the LORD, after that Nebuchadrezzar king of Babylon had carried away captive Jeconiah the son of Jehoiakim king of Judah, and the princes of Judah, with the carpenters and smiths, from Jerusalem, and had brought them to Babylon.

1. Videre me fecit (ostendit mihi visionem) Jehova, et ecce duo calathi ficuum positi coram Templo Jehovae, postquam transtulerat Nebuchadne-zer, rex Babylonis, Jechoniam, filium Joakim, regem Jehudah, et principes Jehudah, et artificem et inclusorem (vel, sculptorem) e Jerusalem, et ab-duxerat eos Babylonem:

2. One basket had very good figs, even like the figs that are first ripe: and the other basket had very naughty figs, which could not be eaten, they were so bad.

2. Calathus unus ficuum bonarum valde, sicuti sunt ficus praecoces; et alter calathus ficuum malarum valde, quae non comederentur propter malitiam (hoc est, adeo malae erant.)

The meaning of this vision is, that there was no reason for the ungodly to flatter themselves if they continued in their wickedness, though God did bear with them for a time. The King Jeconiah had been then carried away into exile, together with the chief men and artisans. The condition of the king and of the rest appeared indeed much worse than that of the people who remained in the country, for they still retained a hope that the royal dignity would again be restored, and that the city would flourish again and enjoy abundance of every blessing, though it was then nearly emptied; for everything precious had become a prey to the conqueror; and we indeed know how great was the avarice and rapacity of Nebuchadnezzar. The city then was at that time almost empty, and desolate in comparison with its former splendor. They however who remained might indeed have hoped for a better state of things, but those who had gone into exile were become like dead bodies. Hence miserable Jeconiah, who was banished and deprived of his kingdom, was apparently undergoing a most grievous punishment, together with his companions, who had been led away with him; and the Jews who remained at Jerusalem no doubt flattered themselves, as though God had dealt more kindly with them. Had they really repented, they would indeed have given thanks to God for having spared them; but as they had abused his forbearance, it was necessary to set before them what this chapter contains, even that they foolishly reasoned when they concluded, that God had been more propitious to them than to the rest.

But this is shewn by a vision: the Prophet saw two baskets or flaskets; and he saw them full of figs, and that before the temple of God; but the figs in one were sweet and savory; and the figs in the other were bitter, so that they could not be eaten.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 25, 1, NULL, 'jeremiah-25', 'John Calvin', 'Commentaries', E'1. The word that came to Jeremiah concerning all the people of Judah, in the fourth year of Jehoiakim the son of Josiah king of Judah, that was the first year of Nebuchadrezzar king of Babylon;

1. Sermo qui fuit ad Jeremiam, ad omnem populum Jehudah (sed l accipitur etiam hic diverso sensu: sermo enim directus fuit ad Jeremiam ut esset illius testis ac proeco, deinde ad populum ut tandem perveniret ex ore Jeremioe ad omnes Judoeos quod uni dictum fuerat) anno quarto Joakim filii Josiae regis Jehudah: hic est annus primus Nebuchadnezer regis Babel.

his prophecy no doubt preceded the vision which we have just explained, and which had just been presented to Jeremiah when Jehoiakim died, and when Zedekiah reigned in the place of Jeconiah; who, being the last king, was substituted for his nephew Jeconiah. But related now is the prophecy which Jeremiah was bidden to proclaim in the fourth year of Jehoiakim; and he reigned, as we shall hereafter see, eleven years. We hence conclude that his book is composed of various addresses, but that the order of time has not always been preserved. Now the sum of the whole is, that when God found that the people could not be amended and restored to a right mind by any warnings, he denounced final ruin both on the Jews and on all the neighboring nations: but why he included the heathens we shall hereafter see.

He then says, that this prophecy was committed to him in the fourth year of Jehoiakim; and he adds, that the same year was the first of King Nebuchadnezar This seems inconsistent with other places, where the third of Jehoiakim is mentioned for the fourth year; and hence a long time is allotted for the first year of Nebuchadnezar. But a solution of this is not difficult, if we consider that Nebuchadnezar suddenly returned into Chaldea to settle his affairs at home, when the report of his father''s death was brought to him; for he feared, lest in his absence a tumult should arise, as it often happened. He was therefore anxious to secure his own affairs; and having settled things at home, he brought Jehoiakim into subjection, and in the fourth year of his reign he compelled him to open his treasures, and also led away captive those whom he wished. And it was at this time that Daniel and his companions were led away into exile, and the precious vessels of the Temple were removed. As to the first year of Nebuchadnezar''s reign, he reigned first with his father; and then when he reigned alone, the beginning of a new reign is justly mentioned as the first year. Though then he was made king, yet as he did not exercise the chief power until his father''s death, it was not until that event that he was really king; this is the reason why mention is made of his first year.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 26, 1, NULL, 'jeremiah-26', 'John Calvin', 'Commentaries', E'1. In the beginning of the reign of Jehoiakim the son of Josiah king of Judah came this word from the LORD, saying, 1. Principio regni Joakim filii Josiae, regis Jehudah, fuit sermo hic a Jehova, dicendo, 2. Thus saith the LORD; Stand in the court of the LORD''S house, and speak unto all the cities of Judah, which come to worship in the LORD''S house, all the words that I command thee to speak unto them; diminish not a word: 2. Sic dicit Jehova, Sta in atrio templi Jehovae, et loquere ad omnes urbes Jehudah (id est, omnes cives urbium Jehudah) quae veniunt ad orandum in templum Jehovae hos omnes sermones quas mandavero tibi ad loquendum ad ipsos (hoc est, loquaris ipsis;) ne diminuas verbum. This chapter contains a remarkable history, to which a very useful doctrine is annexed, for Jeremiah speaks of repentance, which forms one of the main points of true religion, and he shews at the same time that the people were rejected by God, because they perversely despised all warnings, and could by no means be brought to a right mind. We shall find these two things in this chapter. He says that this word came to him at the beginning of the reign, of Jehoiakim, of which king we have spoken in other places, where Jeremiah related other discourses delivered in his reign. We hence conclude that this book was not put together in a regular order, but that the chapters were collected, and from them the volume was formed. The time, however, is not here repeated in vain, for we know that the miserable derive some hope from new events. When men have been long afflicted and well-nigh have rotted in their evils, they yet think, when a change takes place, that they shall be happy, and they promise themselves vain hopes. Such was probably the confidence of the people when Jehoiakim began to reign; for they might have thought that things would be restored by him to a better state. There is also another circumstance to be noticed; though their condition was nigh past hope, they yet hardened themselves against God, so that they obstinately resisted the prophets. It hence appears that the reprobate were become more and more exasperated by the scourges of God, and had never been truly and really humbled. This was the reason why Jeremiah, according to God''s command, spoke so sharply. I pass by other things and come to the words, that the word of Jehovah came to him. He thus arrogated nothing to himself; but he testifies how necessary it was, especially among a people so refractory, that he should bring nothing of his own, but announce a truth that came from heaven. A general subject might be here handled, which is, that God alone is to be heard in the Church, and also that no one ought to assume to himself the name of a prophet or teacher, except he whom the Lord has formed', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 27, 1, NULL, 'jeremiah-27', 'John Calvin', 'Commentaries', E'1. In the beginning of the reign of Jehoiakim the son of Josiah king of Judah, came this word unto Jeremiah from the LORD, saying,

1. Principio regni Jehoiakim filii Josiae regis Jehudah fuit sermo hic ad jeremiam a Jehova, dicendo,

2. Thus saith the LORD to me; Make thee bonds and yokes, and put them upon thy neck,

2. Sic dicit jehova ad me (mihi,) fac tibi vincula et juga, et pone ea super collum tuum;

3. And send them to the king of Edom, and to the king of Moab, and to the king of the Ammonites, and to the king of Tyrus, and to the king of Zidon, by the hand of the messengers which come to Jerusalem unto Zedekiah king of Judah;

3. Et mitte ad regem Edom, et ad regem Moab, et ad regem filiorum Ammon, et ad regem Tyri, et ad regem Sidonis, per manum nuntiorum, qui venient Jerusalem ad Zedechiam regem Jehudah;

4. And command them to say unto their masters, Thus saith the LORD of hosts, the God of Israel; Thus shall ye say unto your masters;

4. Et mandata dabis illis ad dominos suos, dicendo, Sic dicit Jehova exercituum, Deus Israel, Sic dicetis ad dominos vestros,

5. I have made the earth, the man and the beast that are upon the ground, by my great power and by my outstretched arm, and have given it unto whom it seemed meet unto me.

5. Ego feci terram, hominem et jumentum quod super faciem terrae est, in virtute mea magna, et brachio meo extento; et dedi eam illi qui placeret in oculis meis.

Jeremiah prefaces this prediction by saying, that it was delivered to him at the beginning of Jehoiakim''s reign. But this beginning, as we have said, extended to the whole of his reign while it was prosperous and entire. While, then, Jehoiakim enjoyed a quiet possession of the kingdom, Jeremiah was bidden to make known what had been committed to him, not to Jehoiakim himself, but, as we learn from the third verse, to Zedekiah who had not immediately succeeded him, but became at last king after various changes. God, then, committed this prophecy to his servant, but did not design it to be immediately promulgated. If it be asked, why God designed what he purposed to be made known to be concealed for so long a time? the answer is this, -- that it was done for the sake of the Prophet himself, in order that he might with more alacrity perform his office, knowing of a certainty that no one thought that it could ever happen, and certainly the thing was incredible.

God''s design then was to communicate this to his Prophet himself, that he might see afar off what no one, as I have just said, had thought could ever come to pass.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 28, 1, NULL, 'jeremiah-28', 'John Calvin', 'Commentaries', E'1. And it came to pass the same year, in the beginning of the reign of Zedekiah king of Judah, in the fourth year, and in the fifth month, that Hananiah the son of Azur the prophet, which was of Gibeon, spake unto me in the house of the LORD, in the presence of the priests, and of all the people, saying,

1. Factum est anno illo, principio regni Zedechiae, regis Jehudah, anno quarto, mense quinto, loquutus ad me Chananiah, filius Assur, propheta qui erat e Guibeon (oriundus e Guibeon) in Templo Jehovae, coram oculis sacerdotum et totius populi, dicendo,

2. Thus speaketh the LORD of hosts, the God of Israel, saying, I have broken the yoke of the king of Babylon.

2. Sic dicit Jehova exercituum, Deus Israel, confregi (aut contrivi) jugum regis Babylonis.

The Prophet relates here with what haughtiness, and even fury, the false prophet Hananiah came forward to deceive the people and to proclaim his trumperies, when yet he must have been conscious of his own wickedness. It hence clearly appears how great must be the madness of those who, being blinded by God, are carried away by a satanic impulse. The circumstances of the case especially shew how great a contempt of God was manifested by this impostor; for he came into the Temple, the priests were present, the people were there, and there before his eyes he had the sanctuary and the ark of the covenant; and we know that the ark of the covenant is everywhere represented as having the presence of God; for God was by that symbol in a manner visible, when he made evident the presence of his power and favor in the Temple. As Hananiah then stood before God''s eyes, how great must have been his stupidity to thrust himself forward and impudently to announce falsehood in the name of God himself! He had yet no doubt but that he falsely boasted that he was God''s prophet.

And he used the same words as Jeremiah did, Thus saith the Lord of hosts, the God of Israel Surely these words ought to have been like a thunderbolt to him, laying prostrate his perverseness, even had he been harder than iron; for what does Jehovah of hosts mean? This name expresses not only the eternal existence of God, but also his power, which diffuses itself through heaven and earth. Ought not Hananiah then to have trembled when any other had alleged God''s name? But now, though he derided and laughed to scorn the prophetic office as well as God''s holy name, he yet hesitated not to boast that God was the author of this prophecy, which was yet nothing but an imposture. And he added, the God of Israel, so that he might be in nothing inferior to Jeremiah. This was a grievous trial, calculated not only to discourage the people, but also to break down the firmness of the holy Prophet.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 29, 1, NULL, 'jeremiah-29', 'John Calvin', 'Commentaries', E'4 For thus saith Jehovah, -- Behold, I will make thee a terror To thyself and to all thy friends; And fall shall they by the sword of thine enemies, While thine eyes are looking on; And all Judah will I deliver Into the hand of the king of Babylon; And he shall carry them into Babylon, And shall smite them with the sword: 5 And I will give up all the strength of this city, And all its labor and its every precious thing; And all the treasures of the kings of Judah Will I give up into the hands of their enemies; And they shall spoil them and take them away, And they shall lead them into Babylon. 6 And thou, Pashur, and all the inhabitants of thy house, Go shall ye into captivity; Thou shalt come to Babylon, and there die, And there shalt thou be buried and thy friends, To whom thou hast falsely prophesied. 7 Thou hast deceived me, Jehovah, and I was deceived; Thou hast constrained me and didst prevail; I am become a scorn all the day, All make a mock of me; 8 For from the time I have spoken, I cried aloud against violence, And devastation have I proclaimed: Because the word of Jehovah became to me A reproach and derision all the day, 9 Therefore I said, I will not mention him, Nor speak any more in his name: But it became in my heart as a burning fire, Closed up in my bones; And I was wearied with forbearing, And I did not prevail. 10 For I heard the slander of many, Terror on every side, "Report ye, and we will report to him:" All my friends watch for my haltings -- "He may go astray, then we shall prevail against him, And take our revenge on him." 11 But Jehovah is with me as a terrible giant; Therefore my persecutors shall fall and not prevail; They shall be greatly ashamed, for they shall not succeed; It will be a perpetual reproach Which shall not be forgotten. 12 But thou, Jehovah of hosts, Art he who provest the righteous, Who seest the reins and the heart; I shall see thy vengeance on them, For to thee have I opened my cause. 13 Sing ye to Jehovah, praise ye Jehovah, For he has rescued the soul of the distressed From the hand of the wicked. 14 Cursed be the day on which I was born; The day on which my mother bare me, Let it not be blessed: 15 Cursed be the man who told my father, Saying, "Born to thee is a male child," Who with joy made him joyful; 16 And let that man be as the cities, Which Jehovah destroyed and repented not; And let him hear a cry in the morning, And a tumult at noontide. 17 Why hast thou not slain me from the womb? That my mother might be my grave, Or her womb', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 30, 1, NULL, 'jeremiah-30', 'John Calvin', 'Commentaries', E'1. The word that came to Jeremiah from the LORD, saying,

1. Sermo qui fuit ad Jeremiam a Jehova dicendo,

2. Thus speaketh the LORD God of Israel, saying, Write thee all the words that I have spoken unto thee in a book.

2. Sic dicit Jehova, Deus Israel, dicendo, Scribe tibi omnes sermones quos loquutus sum ad to in libro:

3. For, lo, the days come, saith the LORD, that I will bring again the captivity of my people Israel and Judah, saith the LORD: and I will cause them to return to the land that I gave to their fathers, and they shall possess it.

3. Quoniam ecce dies veniunt, dicit Jehova, et reducam captivitatem populi mei Israel et Jehudah, dicit Jehovah; et reducam eos in terram quam dedi patribus ipsorum et possidebunt cam.

This and the next chapter contain, as we shall see, a most profitable truth; and that the people might be the more attentive, God introduced these prophecies by a preface. Jeremiah spoke many things which afterwards, as it has elsewhere appeared, had been collected and inserted in one volume by the priests and Levites; but God reminds us in these words, that the prophecies which are to follow respecting the liberation of the people, were especially to be remembered.

There is, however, another circumstance to be noticed. We have seen that such was the stubbornness of the people, that Jeremiah spent his labor among them in vain, for he addressed the deaf, or rather stocks and stones, for they were so possessed by stupor that they understood nothing, for God had even blinded them, a judgment which they fully deserved. Such was the condition of the people. We must further bear in mind the comparison between the doctrine of Jeremiah and the fables of those who fed the miserable people with flatteries, by giving them the hope of a return after two years. God knew what would be the event; but the people ceased not to entertain hope and to boast of a return at the end of two years. Thus they despised God''s favor, for seventy years was a long period: "What! God indeed promises a return, but after seventy years who of us will be alive? Hardly one of us will be found then remaining, therefore so cold a promise is nothing to us." They, at the same time, as I have said, were filled with a false confidence, as with wind, and behaved insolently towards God and his prophets, as though they were to return sound and safe in a short time.

But profane men always run to extremes; at one time they are inflated with pride, that is, when things go on prosperously, or when a hope of prosperity appears, and they carry themselves proudly against God, as though nothing adverse could happen to them; then when hope and false conceit disappoint them, they are wholly disheartened, so that they will receive no comfort, but plunge into the abyss of despair.', false, false, 'sourced', 'published');
