-- Calvin commentary INSERT — Matthew (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 1, 1, NULL, 'matthew-1', 'John Calvin', 'Commentaries', E'1. The book of the generation of Jesus Christ, the son of David, the son of Abraham. 2. And Abraham began Isaac. And Issac begat Jacob. And Jacob begat Judah and his brethren. 3. And Judah begat Pharez and Zarah by Tamar. And Pharez begat Hezron. and Hezron begat Ram. 4. And Ram begat Amminadab. And Amminadab begat Nahshon. And Nahshon begat Salma. 5. And Salma begat Boaz by Rahab. And Boaz begat Obed by Ruth. And Obed begat Jesse. 6. And Jesse begat David the king. And David the king begat Solomon by her who had been the wife of Uriah. 7. And Solomon begat Rehoboam. And Rehoboam begat Abijah. And Abijah begat Asa. 8. And Asa begat Jehoshaphat. And Jehoshaphat begat Jorem. And Joram begat Uzziah. 9. And Uzziah begat Jotham. And Jotham begat Ahaz. And Ahaz begat Hezekiah. 10. And Hezekiah begat Manasseh. And Manasseh begat Amon. And Amon begat Josiah. 11. And Josiah begat Jeconiah and his brethren, about the Babylonish exile. 12. And after the Babylonish exile, Jeconiah begat Salathiel. And Salathiel begat Zerubbabel. 13. And Zerubbabel begat Abiud. And Abiud begat Eliakim. And Eliakim begat Azor. 14. And Azor begat Zadok. And Zadok begat Achim. And Achim begat Eliud. 15. And Eliud begat Eleazar. And Eleazar begat Matthan. And Matthan begat Jacob. 16. And Jacob begat Joseph, the husband of Mary, of whom was born Jesus, who is called Christ. 17. Therefore all the generations from Abraham till David are fourteen generations; and from David till the Babylonish migration are fourteen generations; and from the Babylonish migration till Christ are fourteen generations.

23. Jesus was supposed to be the son of Joseph, who was the son of Heli, 24. Who was the son of Matthat, who was the son of Levi, who was the son of Melchi, who was the son of Janna, who was the son of Joseph, 25. Who was the son of Matthias, who was the son of Amos, who was the son of Nahum, who was the son of Esli, who was the son of Nagge, 26. Who was the son of Maath, who was the son of Mattahtias, who was the son of Semei, who was the son of Joseph, who was the son of Judah, 27. Who was the son of Joanna, who was the son of Rhesa, who was the son of Zerubbabel, who was the son of Salathiel, who was the son of Neri, 28. Who was the son of Melchi, who was the son of Addi, who was the son of Cosam, who was the son of Elmodam, who was the son, of Er, 29. Who was the son of of Joses, who was the son of Eliezer, who was the son of Joriam, who was the son of Matthat, who was the son of Levi, 30. Who was the son of Simeon, who was the son of Judah, who was the son of Joseph, who was the son of Jonan, who was the son of Eliakim, 31.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 2, 1, NULL, 'matthew-2', 'John Calvin', 'Commentaries', E'1. Now when Jesus had been born How it came about that Jesus was born in Bethlehem, Matthew does not say. The Spirit of God, who had appointed the Evangelists to be his clerks, appears purposely to have regulated their style in such a manner, that they all wrote one and the same history, with the most perfect agreement, but in different ways. It was intended, that the truth of God should more clearly and strikingly appear, when it was manifest that his witnesses did not speak by a preconcerted plan, but that each of them separately, without paying any attention to another, wrote freely and honestly what the Holy Spirit dictated.

This is a very remarkable narrative. God brought Magi from Chaldea, to come to the land of Judea, for the purpose of adoring Christ, in the stable where he lay, amidst the tokens, not of honor, but of contempt. It was a truly wonderful purpose of God, that he caused the entrance of his Son into the world to be attended by deep meanness, and yet bestowed upon him illustrious ornaments, both of commendation and of other outward signs, that our faith might be supplied with everything necessary to prove his Divine Majesty.

A beautiful instance of real harmony, amidst apparent contradiction, is here exhibited. A star from heaven announces that he is a king, to whom a manger, intended for cattle, serves for a throne, because he is refused admittance among the lowest of the people. His majesty shines in the East, while in Judea it is so far from being acknowledged, that it is visited by many marks of dishonor. Why is this? The heavenly Father chose to appoint the star and the Magi as our guides, to lead directly to his Son: while he stripped him of all earthly splendor, for the purpose of informing us that his kingdom is spiritual. This history conveys profitable instruction, not only because God brought the Magi to his Son, as the first-fruits of the Gentiles, but also because he appointed the kingdom of his Son to receive their commendation, and that of the star, for the confirmation of our faith; that the wicked and malignant contempt of his nation might not render him less estimable in our eyes.

Magi is well known to be the name given by the Persians and Chaldees to astrologers and philosophers: and hence it may readily be conjectured that those men came from Persia. As the Evangelist does not state what was their number, it is better to be ignorant of it, than to affirm as certain what is doubtful. Papists have been led into a childish error, of supposing that they were three in number: because Matthew says, that they brought gold, frankincense, and myrrh, (verse 11.) But the historian does not say, that each of them separately presented his own gift. He rather says, that those three gifts were presented by them in common.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 3, 1, NULL, 'matthew-3', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 4, 1, NULL, 'matthew-4', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 5, 1, NULL, 'matthew-5', 'John Calvin', 'Commentaries', E'1. And when Jesus had seen the multitudes, he went up into a mountain, and when he had sat down, his disciples approached to him. 2. And opening his mouth, he taught them, saying, 3. Happy are the poor in spirit: for their is the kingdom of heaven. 4. Happy are they who mourn: for they shall receive consolation. 5. Happy are the meek: for they shall receive the earth by inheritance. 6. Happy are they who hunger and thirst after righteousness: for they shall be satisfied. 7. Happy are the merciful: for they shall obtain mercy. 8. Happy are those who are of a pure heart: for they shall see God. 9. Happy are the peace-makers: for they shall be called the children of God. 10. Happy are those who suffer persecution on account of righteousness: for theirs is the kingdom of heaven. 11. Happy are you, when they shall throw reproaches on you, and shall persecute you, and lying, shall speak every evil word against you on my account. 12. Rejoice ye, and leap for joy: for your reward is great in heaven: for so did they persecute the prophets who were before you.

20. And he, lifting up his eyes on the disciples, said, Happy (are ye) poor: for yours is the kingdom of God. 21. Happy are ye who hunger now: for ye shall be satisfied. Happy are ye who weep now: for ye shall laugh. 22. Happy shall ye be when men shall hate you, and shall separate you, and shall load you with reproaches, and shall cast out your name as evil, on account of the Son of Man. 23. Rejoice ye in that day, and leap for joy: for, lo, your reward is great in heaven: for according to these things their fathers did to the prophets. 24. But woe to you (who are) rich: for you have your consolation. 25. Woe to you who are filled: for you shall hunger. Woe to you who laugh now: for ye shall mourn and weep. 26. Woe to you, when all men shall applaud you: for according to these things their fathers did to the false prophets.

Matthew 5:1. He went up into a mountain. Those who think that Christ''s sermon, which is here related, is different from the sermon contained in the sixth chapter of Luke''s Gospel, rest their opinion on a very light and frivolous argument. Matthew states, that Christ spoke to his disciples on a mountain, while Luke seems to say, that the discourse was delivered on a plain. But it is a mistake to read the words of Luke, he went down with them, and stood in the plain, (Luke 6:17,) as immediately connected with the statement that, lifting up his eyes on the disciples, he spoke thus. For the design of both Evangelists was, to collect into one place the leading points of the doctrine of Christ, which related to a devout and holy life.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 6, 1, NULL, 'matthew-6', 'John Calvin', 'Commentaries', E'1. Beware In this passage, Christ exhorts his people to devote themselves sincerely to good works; that is, to endeavor, with simplicity, to do what is right before God, and not to make a parade before men. A very necessary admonition; for in all virtues the entrance of ambition is to be dreaded, and there is no work so laudable, as not to be in many instances corrupted and polluted by it. Under one class he lays down, by a synecdoche, a general doctrine: for he speaks of alms only, as he speaks shortly afterwards about prayers: though some copies, instead of eleemosunen, alms, read dikaiosunen, righteousness, which is also the rendering of the old translator. But the difference is of little moment: for in either way there is no room to doubt, that the design is, to correct the disease of ambition, when, in doing what is right, we seek glory from men.

2. When thou doest alms He expressly reproves a long established custom, in which the desire of fame might not only be perceived by the eye, but felt by the hands. In places where streets or roads met, and in public situations, where large assemblies were wont to be held, they distributed alms to the poor. There was evident ostentation in that practice: for they sought crowded places, that they might be seen by multitudes, and, not satisfied with this, added even the sound of trumpets. They pretended, no doubt, that it was to call the poor, as apologies are never wanting: but it was perfectly obvious, that they were hunting for applause and commendation. Now, when our service is rendered to the eyes of men, we do not submit our life to the judgment and approbation of God. Justly, therefore, does Christ say, that those persons, who exhibit themselves in this manner, have their reward: for they whose eyes are held by such vanity cannot look upon God.

For the same reason, all who are desirous of vain-glory are called hypocrites. Profane authors gave the name of hupokritai, hypocrites, to those who personated assumed characters in plays and on the stage; and Scripture has applied this term to men who are double in heart and insincere. There are various kinds of hypocrites. Some, though conscious of being very wicked, impudently give themselves out for good men before the world, and endeavor to conceal their vices, of which they have an inward conviction. Others allow themselves to proceed to such a pitch of audacity, that they venture to claim even perfect righteousness before God. Others do good, not from a desire to do what is right, nor on account of the glory of God, but only to obtain for themselves fame and a reputation for holiness.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 7, 1, NULL, 'matthew-7', 'John Calvin', 'Commentaries', E'1. Judge not, that you may not be judged. 2. For with what judgment you judge you shall be judged, and with what measure you measure, it shall be measured to you again. 3. And why seest thou the straw, which is in thy brother''s eye, and perceivest not the beam which is in thine eye? 4. Or how shall thou say to thy brother, Allow me to pull the straw out of thine eye, and, behold, a beam is in thine eye? 5. Hypocrites, cast out first the beam out of thine eye, and then thou shall see clearly, that thou mayest pull out the straw from they brother''s eye.

24 With what measure you measure, the same shall be measured to you.

37. Judge not, and you shall not be judged: condemn not, and you shall not be condemned: forgive, and it shall be forgiven to you. 38. Give, and it shall be given to you. Good measure, and pressed down, and shaken together, and running over, shall they give into your bosom: for the same measure, with which you measure, shall be measured again to you. (Again.) 41. And why seest thou a straw in thy brother''s eye, and perceivest not a beam which is in thine own eye? 42. Or how will thou be able to say to thy brother, Brother, allow me to pull out the straw which is in thine eye, while thou seest not the beam which is in thine eye? Hypocrite, cast out first the beam out of thine eye, and then thou shalt see clearly, that thou mayest cast out the straw which is in thy brother''s eye.

Matthew 7:1. Judge not These words of Christ do not contain an absolute prohibition from judging, but are intended to cure a disease, which appears to be natural to us all. We see how all flatter themselves, and every man passes a severe censure on others. This vice is attended by some strange enjoyment: for there is hardly any person who is not tickled with the desire of inquiring into other people''s faults. All acknowledge, indeed, that it is an intolerable evil, that those who overlook their own vices are so inveterate against their brethren. The Heathens, too, in ancient times, condemned it in many proverbs. Yet it has existed in all ages, and exists, too, in the present day. Nay, it is accompanied by another and a worse plague: for the greater part of men think that, when they condemn others, they acquire a greater liberty of sinning.

This depraved eagerness for biting, censuring, and slandering, is restrained by Christ, when he says, Judge not. It is not necessary that believers should become blind, and perceive nothing, but only that they should refrain from an undue eagerness to judge: for otherwise the proper bounds of rigor will be exceeded by every man who desires to pass sentence on his brethren.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 8, 1, NULL, 'matthew-8', 'John Calvin', 'Commentaries', E'1. And when he had come down from the mountain, great multitudes followed him. 2. And, lo, a leper, approaching, worshipped him, saying, Lord, if thou art willing, thou art able to cleanse me. 3. And Jesus, having stretched out his hand, touched him, saying, I am willing; be thou clean: and immediately his leprosy was cleansed. 4. And Jesus saith to him, See that thou do not tell it to any man: but go, show thyself to the priest, and present the offering which Moses commanded, for a testimony to them.

40. And a leper came to him, beseeaching him, and kneeling down to him, and saying to him, If thou art willing, thou art able to cleanse me. 41. And Jesus, having compassion, stretched out his hand, and touched him, and said to him, I am willing; be thou clean. 42. And when he had spoken, immediately the leprosy departed from him, and he was cleansed. 43. And threatening him, he immediately sent him away; 44. And he said to him, See that thou say nothing to any man: but go, show thyself to the priest, and present for thy cleansing those things which Moses commanded, for a testimony to them. 45. But he, having gone out, began to publish many things, and to blaze abroad the matter, so that Jesus could no longer enter openly into cities, but was without in desert places: and they came to him from every quarter.

12. And it happened, while he was in a certain city, lo, a man full of leprosy: and when he had seen Jesus, he fell down on his face, and besought Jesus, saying, Lord, if thou art willing, thou art able to cleanse me. 13. And having stretched out his hand, he touched him, saying, I am willing; be thou clean: and immediately the leprosy departed from him. 14. And he commanded him that he should not tell it to any man, but saith, Go, show thyself to the priest, and present for thy cleansing as Moses commanded, for a testimony to them. 15. But still more did the report spread about him, and great multitudes assembled, to hear him, and to be healed by him of their infirmities. 16. And he sought retirement in the deserts, and prayed.

Matthew 8:1. And when he had come down from the mountain Matthew now returns to the course of the history. He had formerly said, that Christ went up into a mountain, (verse 1) then he threw, as it were, into one heap, many leading points of the doctrine of Christ; and now he adds that, about the time when he preached on the mountain, he healed a certain leper The same event is related by Mark and Luke, though they do not mention the time. It was a striking display of the divine power of Christ, that, by his word alone and a touch of his hand, he suddenly cleansed the man''s leprosy.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 9, 1, NULL, 'matthew-9', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 40, 10, 1, NULL, 'matthew-10', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published');
