-- Calvin commentary INSERT — Exodus (batch 4, rows 31-40)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 31, 1, NULL, 'exodus-31', 'John Calvin', 'Commentaries', E'13. Speak thou also unto the children of Israel. He inculcates the same things as before, with the addition of a few words, such as "for it is holiness unto you;" by which expression he exhorts them to observe this rite as most sacred and inviolable, since by its neglect religion would fall And therefore he denounces capital punishment against any who should work on that day. Hence, again, we gather the dignity and excellency of the mystery, when God deemed an apparently light transgression of it worthy of death. Still this was an act of by no means excusable contempt, to overthrow professedly, as it were, what God would have to be a mark of distinction between His people and heathen nations. The passages which follow have the same tendency, which it would have been superfluous to repeat, unless because the people were thus reminded that it was a matter of the utmost importance. By prohibiting them from lighting a fire, He anticipates all the glosses which they would have been ready enough to invent; for they would have alleged that if the pot had been put on the fire the day before, the Sabbath would not have been violated by lighting the fire. What, then, would have been more allowable than anything else God excludes, viz., that they should not employ themselves in the preparation of their food, or undertake any other earthly work, however venial. When He calls it a "perpetual" or eternal "covenant," the Jews rest on it as a ground of their obstinacy, and wantonly rave against Christ as a covenant-breaker, because He abrogated the Sabbath. I will not contend with them as to the word gvlm, gnolam, which sometimes means a long time, and not perpetuity: I will simply insist on the thing itself. Whatever was spoken of under the Law as eternal, I maintain to have had reference to the new state of things which came to pass at the coming of Christ; and thus the eternity of the Law must not be extended beyond the fullness of time, when the truth of its shadows was manifested, and God''s covenant assumed a different form. If the Jews cry out that what is perpetual, and what is temporary, are contraries to each other, we must deny it in various respects, since assuredly what was peculiar to the Law could not continue to exist beyond the day of Jesus Christ. Besides, the Sabbath, although its external observation is not now in use, still remains eternal in its reality, like circumcision. Thus the stability of both was best confirmed by their abrogation; since, if God now required the same of Christians, it would be putting a veil over the death and resurrection of His Son; and hence the more carefully the Jews persevere in the keeping the festival, the more do they derogate from its sanctity.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 32, 1, NULL, 'exodus-32', 'John Calvin', 'Commentaries', E'1 And when the people saw that Moses. In this narrative we perceive the detestable impiety of the people, their worse than base ingratitude, and their monstrous madness, mixed with stupidity. For their sakes Moses had been carried up above the state of terrestrial life, that he might receive the injunctions of his mission, and that his authority might be beyond the reach of controversy. They perversely declare that they know not what has become of him, nay, they speak contemptuously of him as of a person unknown to them. It is for this that Stephen severely blames them, This is that Moses (he says) whom your fathers rejected, though he was the minister of their salvation. (Acts 7:35.) They confess that he had been their deliverer, yet they cannot tolerate his absence for a little time, nor are they affected with any reverence towards him, unless they have him before their eyes. Moreover, although God offered Himself as if present with them by day and by night in the pillar of fire, and in the cloud, they still despised so illustrious and lively an image of His glory and power, and desire to have Him represented to them in the shape of a dead idol. For what could they mean by saying, "make us gods which shall go before us?" Could they not see the pillar of fire and the cloud? Was not God''s paternal solicitude abundantly conspicuous every day in the manna? Was he not near them in ways innumerable

Yet, accounting as nothing all these true, and sure, and manifest tokens of God''s presence, they desire to have a figure which may satisfy their vanity. And this was the original source of idolatry, that men supposed that they could not otherwise possess God, unless by subjecting Him to their own imagination. Nothing, however, can be more preposterous; for since the minds of men and all their senses sink far below the loftiness of God, when they try to bring Him down to the measure of their own weak capacity, they travesty Him. In a word, whatever man''s reason conceives of Him is mere falsehood; and nevertheless, this depraved longing can hardly be repressed, so fiercely does it burst out. They are also influenced by pride and presumption, when they do not hesitate to drag down His glory as it were from heaven, and to subject it to earthly elements. We now understand what motive chiefly impelled the Israelites to this madness in demanding that a figure of God should be set before them, viz., because they measured Him by their own senses. Wonderful indeed was their stupidity, to desire that a God should be made by mortal men, as if he could be a god, or could deserve to be accounted such who obtains his divinity at the caprice of men.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 33, 1, NULL, 'exodus-33', 'John Calvin', 'Commentaries', E'1. Depart, and go up hence, thou and the people I have used the pluperfect tense; for the reason is here given, whereby Moses was stirred up to such vehemence in prayer, viz., because, although God had not altogether abandoned the care of the people, still He had renounced His covenant, and had proclaimed to them that, after He had once performed His engagement of giving them possession of the land, He would have no more to do with them. Wherefore, what is here related, preceded, in order of time, the prayer of Moses; for, being astonished at the sad and almost fatal message, he burst forth into that confused and wild request, that he might be blotted out of the book of life.

Let us now endeavor to elicit the true meaning of the passage. It is plain, that when God bids Moses depart with the people, He utterly renounces the charge which He Himself had hitherto sustained. He only promises that He will cause them to attain the promised inheritance, and not that He will preside over them, will there preserve them in safety, and even cherish them, as a father does his children; in fact, that he will merely fulfill the promise He had made to their fathers. And thus He anticipates their complaints; for they might reply, that consequently His promise would be rendered vain and ineffectual; but by way of anticipation, He says, that although He should renounce them, still He should maintain this truth, because He will cast out the inhabitants of the land of Canaan, so that their abode would be vacant for them. In sum, He repudiates them, that they may no longer count themselves to be His peculiar people, or expect more from Him, than as if they were strangers, He mentions His oath, lest they should accuse Him of faithlessness; as if He had said that He should be discharged from His engagement when they had obtained the land. And thus, whilst depriving them of the hope of salvation, and the grace of adoption, He still asserts the stability and stedfastness of His covenant. I, therefore, understand the word angel in a different sense from that which it has just before, and in many other passages of this book; for, when mention was before made of the angel, the familiar presence of God was denoted by it, nay, it was used interchangeably with the name of God itself. But here God is said to be so about to send the angel, as to separate Himself from the people. "I will not go up (He says) in the midst of thee;" and the reason is subjoined, viz., because it could not be that He could endure any longer their perverse spirits. Again He uses a similitude taken from refractory oxen, which cannot be broken to bear the yoke. The sum is, that because they are so intractable, God cannot perform the office of their guide without straightway destroying them.

4.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 34, 1, NULL, 'exodus-34', 'John Calvin', 'Commentaries', E'1. And it shall be when thou art come. The Israelites are commanded to offer their first-fruits, for the same reason that they were to pay the tribute for every soul; viz., that they might confess that they themselves, and all that they had, belonged to God. This was the only distinction, that the tribute was a symbol of their emancipation, that they might acknowledge themselves to be free, as having been redeemed by the special mercy of God; but by the firstfruits they testified that the land was tributary to God, and that they were masters of it by no other title than as tenants at will, so that the direct sovereignty and property of it remained with God alone. This, then, was the object of the first-fruits, that they might renew every year the recollection of their adoption; because the land of Canaan was given to them as their peculiar inheritance, in which they were to worship God in piety and holiness, and at the same time reflect that they were not fed promiscuously, like the Gentiles, by God, but like children; whence also their food was sacred. But we shall have to speak again elsewhere of the first-fruits, in as much as they were a part of the oblations; yet it was necessary to insert here their main object, that we might know that they were appointed to be offered by the people, in pious acknowledgment that their food was received from God, and to shew that, being separated from other nations, they were dependent upon the God of Israel alone.

2. That thou shalt take of the first. We know that in the first-fruits the whole produce of the year was consecrated to God. The people, therefore, bore in them a testimony of their piety to Him, whom they daily experienced to be their preserver, and the giver of their food. This typical rite has now, indeed, ceased, but Paul tells us that the true observation of it still remains, where he exhorts us, whether we eat or drink, to do all to the glory of God. (1 Corinthians 10:31.) As to the place where the first-fruits were to be offered, and why God is said to have placed His name there, we shall hereafter consider, when we come to the sacrifices; I now only briefly touch upon what concerns the present subject.

I profess this day. In these words the Israelites confess that they had not gained dominion of the land either by their own strength or good fortune, but by the free gift of God, and that according to His promise. There are, therefore, two clauses in this sentence; first, that God had gratuitously promised to grant that land to Abraham as the inheritance of his descendants; and, secondly, that He had performed His promise, not only when He had brought the children of Abraham into possession, but by adding'' to His grace by their peaceful enjoyment of it.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 35, 1, NULL, 'exodus-35', 'John Calvin', 'Commentaries', E'12. Six days thou shalt do thy work. In this passage the incidental use of the Sabbath is again referred to, although it is no inherent part of its original institution, viz., that by its means the family also and the cattle shall be benefited. There is no impropriety in reckoning this amongst the other blessings which enhance the value of the Sabbath, although it is a portion of the Second Table. And we know that this rude people required to be attracted by every possible means to present cheerfully to God the worship due to Him. The sum therefore is, that they were thus to testify not only their piety towards God, but also their kindness towards their servants. I have already shewn that their authority as masters was to be exercised in moderation by them, if they were mindful of their former condition:, since they also had been servants in Egypt. If any one should suppose that the argument does not hold good, because; they were oppressed by cruel and dreadful tyranny, the reply is easy, that so much the better could they determine from their own feelings how detestable and intolerable a thing cruelty is. __________________________________________________________________', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 36, 1, NULL, 'exodus-36', 'John Calvin', 'Commentaries', E'1. Then wrought Bezaleel and Aholiab. Although Moses might have seemed to be unnecessarily prolix in recording the injunctions which God gave respecting the building of the tabernacle, yet he repeats the same narrative here almost in the same words; and this he does with the best design, and for very good reasons. For it was of much importance that it might be seen by actual comparison how exactly the artificers had conformed everything to the pattern laid down by God: and this, not only in commendation of their obedience, but because it behooved that there should be nothing human in the structure; for although they might each of them have exerted themselves strenuously in the work, still it was not lawful for them to give the slightest scope to their own inventions; nay, this would have been a profanation of the sacred edifice, not to follow in every part what had been so carefully dictated to Moses. And this might avail as a restraint upon them in future times, so that they might not violate God''s commands by any change or innovation. They did not indeed understand the reason of everything either in reference to number or measure; but it became them to be assured that God had commanded nothing without a purpose. Hence, also, their minds should have been elevated to the heavenly pattern, so as reverently to look up to the mysteries, obscure as they were, which it contained, until its full manifestation. This verbal repetition, then, reminds us how accurately the labor and art of men in the building corresponded with the command of God.

2. And Moses called Bezaleel and Aholiab. It is not without reason that Moses so often exalts the grace of God''s Spirit in the ingenuity and artistic skill of the workmen. In the first place he speaks of them as skillful architects, and then, by way of correction, adds that they were furnished from above with such intelligence. Thus the absurdity of the Papists is refuted, who, in order to prove free-will, think it sufficient to drag forward the passages in which rectitude of will is commended: whereas, even though men may will aright, it is foolish to infer that therefore they are possessed of free-will, unless it be proved that the will proceeds from themselves. Consequently, what follows in the text, -- that every one contributed either of his labor or his substance to the building of the tabernacle, according as their hearts stirred them up, -- does not so make men the authors of pious affections, as to defraud God of His praise. It is true that men understand -- are willing -- encourage themselves to holy endeavors; but the question is, from whence comes their intelligence, their will, and their zeal in well-doing? Scripture decides that they are the gifts of God and the Spirit: the Papists improperly arrogate them to themselves.

3. And they received of Moses all the offering.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 37, 1, NULL, 'exodus-37', 'John Calvin', 'Commentaries', E'1. And Bezaleel made the ark of shittim-wood: two cubits and a half was the length of it, and a cubit and a half the breadth of it, and a cubit and a half the height of it.

1. Fecit etiam Beseleel arcam e lignis sittim: duorum cubitorum et dimidii longitudo ejus: cubiti et dimidii latitudo ejus: cubiti quoque et dimidii altitudo ejus.

2. And he overlaid it with pure gold within and without, and made a crown of gold to it round about.

2. Et texit eam auro mundo intrinsecus, et extrinsecus: fecitque ei coronam auream in circuitu.

3. And he cast for it four rings of gold, to be set by the four corners of it; even two rings upon the one side of it, and two rings upon the other side of it.

3. Et fudit ei quatuor annulos aureos ad quatuor angulos ejus, duos videlicet annulos in latere ejus uno, et duos annulos in latere ejus altero.

4. And he made staves of shittim-wood, and overlaid them with gold.

4. Fecit et vectes e lignis sittim, et texit eos auro.

5. And he put the staves into the rings by the sides of the ark, to bear the ark.

5. Induxitque vectes in annulos in lateribus arcae ad portandum arcam.

6. And he made the mercy-seat of pure gold: two cubits and a half was the length thereof, and one cubit and a half the breadth thereof.

6. Fecit et propitiatorium ex auro mundo: duorum cubitorum et dimidii longitudo ejus, cubiti et dimidii latitudo ejus.

7. And he made two cherubims of gold, beaten out of one piece made he them, on the two ends of the mercy-seat;

7. Fecit quoque duos Cherubim ex auro, ductiles fecit eos in duabus extremitatibus propitiatorii.

8. One cherub on the end on this side, and another cherub on the other end on that side: out of the mercy-seat made he the cherubims on the two ends thereof.

8. Cherub unum ab extremo hinc, et cherub alterum ab extremo inde: ex propitiatorio fecit cherubim in duabus extremitatibus ejus.

9. And the cherubims spread out their wings on high, and covered with their wings over the mercy-seat, with their faces one to another; even to the mercy-seat-ward were the faces of the cherubims.

9. Cherubim autem extendebant alas sursum versus, tegentes alis suis propitiatorium et facies eorum altera ad alteram: ad propitiatorium facies Cherubim.

10. And he made the table of shittim-wood: two cubits was the length thereof, and a cubit the breadth thereof, and a cubit and a half the height thereof.

10. Fecit et mensam e liguis sittim: duorum cubitorum longitudo ejus, et cubiti latitudo ejus, cubiti autem et dimidii altitudo ejus.

11. And he overlaid it with pure gold, and made thereunto a crown of gold round about.

11. Et texit eam auro puro, fecitque ei coronam auream in circuitu.

12.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 38, 1, NULL, 'exodus-38', 'John Calvin', 'Commentaries', E'1. And he made the altar of burnt-offering. The purport of this chapter is the same as that of the last, except that the order of some parts of it is transposed, though not a word is changed. He begins with the altar of burnt-offering, which he states to have been made of the materials and the form prescribed by God, in order that the people might there offer with surer confidence their sacrifices for the expiation of sin, and for thanksgiving. One thing which had not been mentioned before, is here added respecting the laver of brass, or cauldron (concha,) from whence they took the water of sprinkling for expiation, viz., that this laver was ornamented with the mirrors of the women. Some explain this, that the vessel was so bright that it might be easily discovered on every side whether there was any scandalous, or wanton, or indelicate act committed; for we know that impure and ungodly men sometimes conceal their iniquities under the cover of religion, even as it; is written that the women who frequented the tabernacle for religious exercises were defiled by the sons of Eli, the priests. (1 Samuel 2:22.) But there is another conjecture equally probable, that these mirrors were dedicated by holy women for the ornament of the Temple, and for sacred purposes; for, whereas women are only too much given to outward adornment and finery, they have been always very fond of mirrors, both for the purpose of painting their cheeks and arranging their hair, so that not a single hair should be out of place. Isaiah, therefore, (3:23,) enumerates mirrors amongst the luxuries of the female world. Some, then, think that women, being devoted to God''s service, laid aside this vanity, and consecrated their mirrors in testimony of their repentance. It might, however, have been that, amongst the other gifts before spoken of, they offered mirrors also, which were mounted as embossments in this brasen laver. Others suppose that they were carvings, by which the portraits of females were depicted, as if seen in mirrors. The simple notion is most approved by me, that they were votive offerings, wherewith pious women had desired to decorate the sanctuary, and that they had been applied to this use by the advice of the artificers; for he does not speak generally of all the women, but of those who warred or assembled by troops at the door of the tabernacle; for translators variously explain this word tsv'', tzaba, both in this passage and that from Samuel which I have just quoted. It is also applied to the Levites, who are said "to war the warfare" of the sanctuary, whilst performing their appointed work. (Numbers 4:3; 8:24.) Indeed this metaphor is by no means unsuitable to watchings and long-continued prayers. The sum is, that the laver was cast of their materials, or, as I rather suppose, embossed with these mirrors, in order that it might be more splendid.

21.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 39, 1, NULL, 'exodus-39', 'John Calvin', 'Commentaries', E'1. And of the blue, and purple, and scarlet. The description of the sacerdotal garments, which is repeated in this chapter, is more accurate than it would have been had he been speaking of some unimportant matter. And assuredly, since Christ was vividly represented in the person of the high priest, this was a most important part of the legal service. We have elsewhere set forth how far it was from being an empty pomp, as when the Popish sacrificers now-a-days, in order to acquire dignity, dazzle the eyes of the simple by the splendor of their vestments, and their magnificent paraphernalia; but that rather it was for the purpose of placing before men''s eyes all that faith ought to consider in Jesus Christ. We have especially seen how great mysteries were contained in the mitre, which was Holiness to the Lord: and in the ephod, in which shone forth the light of truth and integrity of life, and in which were the symbols of the ten tribes, so that the priest bore the people itself upon his shoulders and before his breast, in such a manner that in the person of one all might be presented familiarly before God. For this reason he repeats seven times the clause, "as the Lord commanded Moses;" which certainly has the effect of awakening attention.

32. Thus was all the work of the tabernacle. A brief summary is now subjoined, whereby he indicates that in no part was there the least defect, and also declares that the children of Israel had so obeyed God''s commands, that the work itself varied in no respect from its pattern. "The children of Israel," he says, "did according to all that the Lord commanded Moses, so did they;" whence we gather that no part of the building was impaired by any admixture. Afterwards it is added, that the tabernacle with its utensils and furniture was brought before Moses, and that all things were approved of by his judgment; for he is said to have "blessed them," because they had duly and faithfully obeyed God''s command. This, however, was not a simple prayer, as of a private individual; but it was a promise of reward, such as might awaken confidence in the minds of the people, when they heard from the mouth ("D''un tel Prophete;" of such a Prophet. -- Fr.) of this excellent and unimpeachable witness that their labor was pleasing to God. __________________________________________________________________', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 2, 40, 1, NULL, 'exodus-40', 'John Calvin', 'Commentaries', E'9. And thou shalt take the anointing oil There was by no means any virtue or efficacy for sanctification in the oil, except in so far as it was a type of the Spirit, from whom as its only source all holiness emanates. Assuredly the oil, as being a corruptible fluid, neither penetrates into the soul, nor would by itself at all avail unto spiritual service. It appears, however, from many pnssages of Scripture, that it was a symbol of all the gifts of the Holy Spirit. This figure, therefore, clearly shews that nothing pleases God, that nothing is pure or holy in His sight, except what has been purged, and duly consecrated by the influence and grace of the Holy Spirit. Moreover, God would have all the vessels of the sanctuary set apart by this sacred anointing from common use, in order that the Israelites might distinguish between things sacred and profane, and thus that God''s service might receive its due reverence, so that none should intrude the pollutions of the flesh into that place, the purity of which had been signalized by that sacred symbol. A question, however, here arises why he dignifies the altar of burnt-offering with a more exalted title; for, after having called the tabernacle itself with its vessels simply holy, He calls the altar "holy of holies," which I have rendered sacrosanctum. I doubt not but that it acquired this name from the sacrifices, which are also so called on account of the expiation made by them, as we have seen elsewhere. The children of Israel, therefore, were instructed that God is truly reconciled by holocausts and burnt-offerings, since "the holiness of holinesses" resided on the altar itself.

12. And thou shalt bring Aaron and his sons I have already expounded all that might seem to be profitable with respect to the garments and the mode of anointing; only let; my readers remember that the priest, who had been before appointed, is now at length inaugurated, in order that he may begin the discharge of his office. At the same time, let them also bear in mind that this oil was consecrated by God. Hence it appears how foolishly the Popish bishops, as it were, ape Moses, when, in imitation of him, they sprinkle their priests and altars and other rubbish with stinking oil, since it is abundantly clear that this ceremony of anointing, belonging as it did to the ancient shadows of the Law, ceased at the coming of Christ. What Augustine reminds us of is also worthy of observation, that Moses, who is commissioned to anoint the others, was never consecrated himself by any visible symbol, in order that we may understand that outward signs are not to be estimated by the dignity of the minister, but only by the ordinance of God; and again, that invisible grace has profited some without visible sacraments, whilst visible sanctification may be imparted, but cannot profit, without invisible.

17.', false, false, 'sourced', 'published');
