-- Calvin commentary INSERT — Mark (batch 2, rows 11-16)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 11, 1, NULL, 'mark-11', 'John Calvin', 'Commentaries', E'16. Moreover, when you shall fast, be not, like the hypocrites, dejected: for they disfigure their faces, that it may be evident to men that they fast. Verily I say to you, they have their reward. 17. But thou, when thou fastest, anoint thy head, and wash thy face, 18. That it may not appear to men that thou fastest, but to thy Father, who is in secret, and thy Father, who seeth in secret, will reward thee openly.

He again returns to the former doctrine: for, having begun to rebuke vain ostentation in alms and prayer, he laid down, before proceeding farther, the rule for praying in a right manner. The same injunction is now given to his disciples about fasting, which he had formerly given about prayers and alms, not to be too solicitous to obtain the applause of spectators, but to have God as the witness of their actions. When he bids them anoint their head, and wash their face, his language is hyperbolical: for Christ does not withdraw us from one kind of hypocrisy, to lead us into another. He does not enjoin us to counterfeit splendor, or exhort us to temperance in food in such a manner, as to encourage the luxuries of ointments and of dress: but merely exhorts us to preserve moderation, without any thing new or affected;--in short, that the fastings, in which we engage, should make no change in our accustomed way of living.

Thy Father will reward thee When he promises a reward from God to fastings, this mode of expression, as we said a little before with respect to prayer, is not strictly accurate. There is a wide difference, indeed, between prayer and fastings Prayer holds the first rank among the antics of piety: but fasting is a doubtful operation, and does not, like alms, belong to the class of those actions which God requires and approves. It is pleasing to God, only so far as it is directed to another object: and that is, to train us to abstinence, to subdue the lust of the flesh, to excite us to earnestness in prayer, and to testify our repentance, when we are affected by the view of the tribunal of God. The meaning of Christ''s words is: "God will one day show that he was pleased with those good works, which appeared to be lost, because they were concealed from the eyes of men." __________________________________________________________________

"D''un regard triste, ou, visage chagrin;" -- "of a sad look, or, distressed countenance "

"C''est une facon de parler hyperbolique, c''est a dire, excessive." -- "It is a hyperbolical, that is, an exaggerated way of speaking."

"Pour nous faire retomber en 1''autre;" -- "to make us fall into the other." __________________________________________________________________

MATTHEW 6:19-21; LUKE 12:33-34

19. Lay not up for yourselves treasures on the earth, where rust and the moth consume, where theives break through and steal. 20.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 12, 1, NULL, 'mark-12', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 13, 1, NULL, 'mark-13', 'John Calvin', 'Commentaries', E'1. And while he was going out of the temple, one of his disciples saith to him, Master, see what stones and what buildings! 2. And Jesus answering saith to him, Seest thou these vast, buildings? There shall not be left one stone upon another that shall not be thrown down. 3. And while he was sitting on the mountain of Olives, opposite to the temple, Peter, and James, and John, and Andrew, asked him privately, 4. Tell us, when will these things be, and what is the sign when all these things shall be accomplished? 5. And Jesus answering began to say to them, Take heed that no man deceive you. 6. For many will come in my name, saying, I am Christ, and will deceive many. 7. And when you shall hear of wars and rumors of wars, be not troubled; for these things must be, but the end is not yet. 8. For nation will rise against nation, and kingdom against kingdom; and there will be earthquakes in various places. These things are the beginnings of sorrows.

5. And while some were saying concerning the temple, that it was adorned with beautiful stones and gifts, he said, 6. The days will come, when of those things which you see there shall not be left one stone upon another which shall not be thrown down. 7. And they asked him, saying, Master, when shall these things be? and what is the sign when those things shall begin to take place? 8. And he said, Take heed that you be not deceived; for many will come in my name, saying, It is I; and the time approaches: do not therefore follow them. 9. But when you shall hear of wars and seditions, be not terrified: for these things must first take place; but the end is not immediately. 10. Then he said to them, Nation will rise against nation, and kingdom against kingdom; 11. And there will be great earthquakes in various places, and famines, and pestilences; and there will be frightful appearances and great signs from heaven.

Matthew 24:1. And Jesus went out. The disciples undoubtedly perceived that Christ was paying, as it were, his last adieu to the temple. It remained, therefor that he should erect a new temple far more magnificent, and that he should produce a more flourishing condition of the kingdom, as had been foretold by the Prophets; for he had nothing to do with that temple, in which every thing was opposed to him. But again, the disciples could not believe that the magnificent splendor of the temple would give way to Christ. And it ought to be carefully observed that, owing to the prodigious costliness of the temple, their eyes were so dazzled by the splendor of its present aspect, that they could scarcely entertain the hope that the kingdom of Christ would arise.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 14, 1, NULL, 'mark-14', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 15, 1, NULL, 'mark-15', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 16, 1, NULL, 'mark-16', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published');
