-- Calvin commentary INSERT — Jeremiah (batch 4, rows 31-40)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 31, 1, NULL, 'jeremiah-31', 'John Calvin', 'Commentaries', E'1. At the same time, saith the LORD, will I be the God of all the families of Israel, and they shall be my people. 1. In tempore illo, dicit Jehova, ero in Deum cunctis cognationibus Israel; et ipsi mihi in populum. 2. Thus saith the LORD, The people which were left of the sword found grace in the wilderness; even Israel, when I went to cause him to rest. 2. Sic dicit Jehova, Invenit gratiam in deserto populus qui evaserant a gladio, proficiscendo donec quietem daret ipsi Israeli (vel profectus est Israel, donec se ad quietem conferret) I omit here any remarks on the first verse; for it was explained in connection, with the 22d verse of the last chapter (Jeremiah 30:22). The verb hlvk eluk, in the second verse, is in the infinitive mood, but it is to be taken as a preterite, and in this interpreters agree. But some apply it to God, that he is a leader to his people, until he brings them to rest; and as the verb, lhrgyv, laeregiou, to rest him, so to speak, is in Hiphil, it seems that this ought to be ascribed to God. But we may take the words more simply, "until he betakes himself to rest;" added afterwards is the word "Israel;" and thus we may render the pronoun "himself," and not "him," -- until then he betook himself to rest Let us now come to the truth which the Prophet handles: he reminds the people, no doubt, of the ancient benefits of God, in order that the miserable exiles might entertain hope, and not doubt but that God would be their deliverer, though they were drowned, as it were, in Chaldea, and overwhelmed with a deluge of evils. This is the reason why he mentions the desert, and why Jeremiah also adds, that they who were then preserved had escaped from the sword For the people, though they dwelt in a pleasant and fertile country, were in a manner in a desert, when compared with their own country. As then the Israelites had been driven far away into foreign lands, all the regions where they then inhabited are compared to a desert. A similar mode of speaking is adopted by Isaiah when he says, "A voice crying in the desert, Prepare ye the way of Jehovah, make straight paths in the wilderness." (Isaiah 40:3) What did he understand then by desert? even the most fertile regions, Chaldea, Assyria, and other neighboring countries. But with regard to the people, he thus calls these countries, because their exile was always sorrowful and miserable. So then in this place the Prophet, in order to animate the exiles with hope, says, that though they had been sent away to unknown regions, yet distance, or anything else which might seem opposed to their liberation, could not prevent God to restore them; for he formerly liberated their fathers when they were in Egypt.; Now as the Jews might again object and say,', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 32, 1, NULL, 'jeremiah-32', 'John Calvin', 'Commentaries', E'1. The word that came to Jeremiah from the LORD in the tenth year of Zedekiah king of Judah, which was the eighteenth year of Nebuehadrezzar.

1. Sermo qui datus fait Jeremiae a Jehova anno decimo Zedechiae regis Jehudah; hic annus est decimus octavus Nabuchadnezer:

2. For then the king of Babylon''s army besieged Jerusalem: and Jeremiah the prophet was shut up in the court of the prison, which was in the king of Judah''s house.

2. Et tunc exercitus regis Babylonii obsidebat Jerosolymam, et Jeremias propheta erat indusus in atrio custodiae qum est in palatio regis Jehudah;

3. For Zedekiah king of Judah had shut him up, saying, Wherefore dost thou prophesy, and say, Thus saith the LORD, Behold, I will give this city into the hand of the king of Babylon, and he shall take it;

3. Quia incluserat ipsum Zedechias rex Jehudab, dicendo, Quare tu prophetizas dicendo, sic dicit Jehova, Ecce ego trado urbem hanc in manum regis Babylonii, et capiet eam.

The Prophet here declares, that though he was shut up in prison, the Word of God was not bound, and that he himself was not less loose and free in his confinement than if he rambled through the whole city and visited all the lanes and the streets. He then did not desist from his office as a Prophet, though he was cast into prison. And thus we see that the course of heavenly truth cannot be impeded, how much soever the world may rage against all its ministers, and bind them in order to make them mute: and then also we see here that the constancy of the Prophet was invincible, because he was not cast down with fear, though he was a captive and not beyond the reach of danger; for we find that even then he proceeded in the discharge of his office.

He points out then the circumstances of that time, and not without reason, when he says, that he was then shut up in prison, and also mentions the year, even the tenth of Zedekiah and the eighteenth of king Nebuchadnezar. It was about the end of the ninth year that the army of Nebuchadnezar came up to Jerusalem; the city was besieged for two months in that year. The tenth year followed, in which this vision was given to the Prophet. The siege continued for a year and a half; but there was some interruption; for the Egyptians came to its aid. Thus for a short time, while the Chaldeans went to meet them, it had some liberty. But the Egyptians, as we shall hereafter see, were forced to retire in disgrace, and afterwards suffered punishment for their audacity and rashness. It was then about the middle of the siege that God, as we shall see, foretold to the Prophet the future return of the people.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 33, 1, NULL, 'jeremiah-33', 'John Calvin', 'Commentaries', E'1. Moreover, the word of the LORD came unto Jeremiah the second time, while he was yet shut up in the court of the prison, saying, 1. Et fuit sermo Jehovae ad Jeremiam secundo, cum ipse adhuc captivus esset in atrio custodiae, dicendo, 2. Thus saith the LORD the maker thereof, the LORD that formed it, to establish it; The LORD is his name; 2. Sic dicit Jehova, faciens ipsam, Jehova formans ipsam, ad stabiliendum ipsam; Jehova nomen ejus; 3. Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not. 3. Clama ad me, et respondebo tibi, et annunciabo tibi res magnificas et reconditas, quas non novisti: 4. For thus saith the LORD, the God of Israel, concerning the houses of this city, and concerning the houses of the kings of Judah, which are thrown down by the mounts, and by the sword; 4. Quia sic dicit Jehova, Deus Israel, super domibus urbis hujus, super domibus regum Jehudah, quae dirutae fuerunt catapultis (vel, balistis, vel, machinis aliis) et gladio, (alii autem vertunt, ad catapultas, vel, balistas, vel, alias munitiones, et ad gladium; dicemus postea de sensu: hoec omnia legenda sunt uno contextu) 5. They come to fight with the Chaldeans, but it is to fill them with the dead bodies of men, whom I have slain in mine anger and in my fury, and for all whose wickedness I have hid my face from this city. 5. Venerunt ad praeliandum cum Chaldaeis, et ad replendas ipsas (domos) cadaveribus hominum, quos percussi in ira mea et indignatione mea, et quia abscondi faciam meam ab hac urbe propter universam malitiam ipsorum; 6. Behold, I will bring it health and cure, and I will cure them, and will reveal unto them the abundance of peace and truth. 6. Ecce ego adduco illi restitutionem et sanationem, et sanabo eos, et aperiam ipsis multitudinem pacis et veritatis (alii vertunt, orationem) This prophecy refers to the same subject; nor was it to be wondered at, that God spoke so much of the same thing, for it was necessary to render the Jews inexcusable, as they always pretended ignorance, except God made frequent repetitions. And this was also the reason why Paul said, that by the mouth of two or three witnesses everything should be established, when he said that he would come the second and the third time to Corinth. (2 Corinthians 13:1) He intimated that his coming would not be useless, for except they repented they could not have escaped by pretending ignorance, as hypocrites are wont to do. It was, then, God''s purpose to confirm by many prophecies what he had once testified respecting the restoration of the people; but he had an especial care for the faithful, that they might not grow faint and succumb under those many trials which remained for so long a time; for as some died in exile, they might have forgotten the covenant of God, and thus the soul', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 34, 1, NULL, 'jeremiah-34', 'John Calvin', 'Commentaries', E'1. The word which came unto Jeremiah from the LORD, when Nebuchadnezzar king of Babylon, and all his army, and all the kingdoms of the earth of his dominion, and all the people, fought against Jerusalem, and against all the cities thereof, saying,

1. Sermo qui fuit ad Jeremiam a Jehova, cum Nebuchadnezer rex Babylonis et totus excreitus ejus et omnia regna terrae, quae sub dominatione marius ejus erant, et omnes populi pugnarent contra Jerusalem (hoc est, oppugnarent Jerosolymam) et cunctas urbes, dicendo,

2. Thus saith the LORD, the God of Israel; Go and speak to Zedekiah king of Judah, and tell him, Thus saith the LORD; Behold, I will give this city into the hand of the king of Babylon, and he shall burn it with fire:

2. Sic dicit Jehova, Deus Israel, Vade et dices Zedechiae regi Jehudah, dices, inquam, illi, Sic dicit Jehova, Ecce ego trado urbem hanc in manum regis Babylonis, et incendet eam igni.

It is no wonder, nor ought it to be deemed useless, that the Prophet so often repeats the same things, for we know how great was the hardness of the people with whom he had to do. Here, then, he tells us that he was sent to King Zedekiah when the city was besieged by Nebuchadnezzar and his whole army. The Prophet mentions the circumstances, by which we may understand how formidable that siege was, for Nebuchadnezzar had not brought a small force, but had armed many and various people. Hence the Prophet here expressly mentions the kingdoms of the earth and the nations who were, under his dominion

Zedekiah was then the king at Jerusalem, and there remained two other cities safe, as we shall hereafter see; but it is evident how unequal he must have been to contend with an army so large and powerful. Nebuchadnezzar was a monarch; the kingdom of Israel had been cut off, which far exceeded in number the kingdom of Judah; and he had subdued all the neighboring nations. Such a siege then ought to have immediately taken away from the Jews every hope of deliverance; and yet the Prophet shews that the king was as yet resolute, and there was still a greater obstinacy among the people. But Zedekiah was not overbearing; we find that he was not so proud and so cruel as tyrants are wont to be: as then he was not of a ferocious disposition, we hence see how great must have been the pride of the whole people, and also their perverseness against God, when they made the king to be so angry with the Prophet. Yet the state of things as described ought to have subdued his passion; for as ungodly men are elevated by prosperity, so they ought to be humbled when oppressed with adversity.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 35, 1, NULL, 'jeremiah-35', 'John Calvin', 'Commentaries', E'1. The word which came unto Jeremiah from the LORD in the days of Jehoiakim the son of Josiah king of Judah, saying,

1. Sermo qui factus fuit ad Jeremiam a Jehova diebus Jehoiakim filii Joziae regis Jehudah, dicendo,

2. Go unto the house of the Rechabites, and speak unto them, and bring them into the house of the LORD, into one of the chambers, and give them wine to drink.

2. Vade ad domum Rechabitarum, et dices illis, (et loquere cum ipsis) et adducas eos in domum Jehovae ad unum cubiculorum, et popina illis vinum.

3. Then I took Jaazaniah the son of Jeremiah, the son of Habaziniah, and his brethren, and all his sons, and the whole house of the Rechabites;

3. Et sumpsi Jaazaniah filium Jeremiae, filii Habazaniiae, et fratres ejus, (hoc est, cognatos) et omnes filios ejus, totam domum Rechabitarum;

4. And I brought them into the house of the LORD, into the chamber of the sons of Hanan, the son of Igdaliah, a man of God, which was by the chamber of the princes, which was above the chamber of Maaseiah the son of Shallum, the keeper of the door:

4. Et adduxi eos in domum Jehovae ad cubiculum filiorum Chanan filii Igdaliae, viri Dei, quod erat juxta cubiculum principum, quod erat e super cubiculo Maassaiae filii Selum custodis thesauri (alii vertunt, liminis, sed sine ratione, ut milhividetur)-

5. And I set before the sons of the house of the Rechabites pots full of wine, and cups, and I said unto them, Drink ye wine.

5. Et posui in conspectu filiorum domus Rechabitarum (vel, coram filiis domus Rechabitarum) scyphos plenos vino, et calices, et dixi, Bibite vinum.

6. But they said, We will drink no wine: for Jonadab the son of Rechab our father commanded us, saying, Ye shall drink no wine, neither ye, nor your sons for ever:

6. Et dixerunt, Non bibimus vinum, quia Jonadab filius Rechab, pater noster (vel, patris nostri) praecepit nobis, dicendo, Non bibetis vinum, vos et filii vestri, usque in seculum;

7. Neither shall ye build house, nor sow seed, nor plant vineyard, nor have any: but all your days ye shall dwell in tents; that ye may live many days in the land where ye be strangers.

7. Et domos non aedificabitia, et semen non seretis, et vitem non plantabitis, et non erit vobis quicquam, quia (hoc est, quin potius) habitabitis in tabernaculis, cunctis diebus vestris, ut vivatis dies multos in superficie terrae in qua vos peregrini estis.

It must be first observed, that the order of time in which the prophecies were written has not been retained. In history the regular succession of days and years ought to be preserved, but in prophetic writings this is not so necessary, as I have already reminded you.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 36, 1, NULL, 'jeremiah-36', 'John Calvin', 'Commentaries', E'1. And it came to pass in the fourth year of Jehoiakim the son of Josiah king of Judah, that this word came unto Jeremiah from the LORD, saying, 1. Et fuit anno quarto Joakim filii Josiae regis Jehudah (fuit inquam) sermo hic ad Jeremiam a Jehova, dicendo, 2. Take thee a roll of a book, and write therein all the words that I have spoken unto thee against Israel, and against Judah, and against all the nations, from the day I spake unto thee, from the days of Josiah, even unto this day. 2. Sume tibi volumen libri, et scribe in eo cunctos sermones quos loquutus sum ad to contra Israel et contra Jehudah, et contra eunctos gentes a die quo loquutus sum ad to, a diebus scilicet Josiae usque ad hunc diem. The Prophet relates in this chapter a history worthy of being remembered, and very useful to us; for he says that he wrote down by God''s command what he had previously taught in the Temple, and also that he sent that summary by Baruch to be recited in the Temple, that the report of this spread, and that the king''s counsellors called to them Baruch, and that when they heard what was written in the volume, they brought word to the king, having, however, first admonished Baruch to conceal himself, together with Jeremiah, lest the king should be exasperated against them. And so it happened, for the king, being instantly filled with indignation, ordered Jeremiah and Baruch to be taken, that they might be put to death; but they were hidden and protected through God''s favor. We shall hereafter see what the king by his obduracy had effected, even to cause the Prophet to speak more boldly against him. The Prophet then says at the beginning, that the word of Jehovah came, by which he was ordered to write in a volume of a book whatever he had previously spoken By the volume of a book he means the volume in which he was to write; for sphr sepher, does not here mean a written book, for the volume was without any writing. Then the Prophet must have dictated to his servant Baruch. And this mode of speaking occurs also elsewhere, as in Psalm 40:7. But the Hebrews, according to an ancient custom, called a volume mglh, megele; for they had no books in a compact form, such as we have in the present day, but had volumes or rolls; and the same word, volume, is also used in Latin. For as the Hebrews called what is folded up mglh, megele, which comes from gll, gelal, to fold up, or to roll; so the Latins also have derived it from a verb (volvo) which means to roll, and we call it rolle; and in Gaul they used the same form of writing; for all ancient documents and also judicial proceedings were wont formerly to be written on rolls, and in the old archieves there is nothing', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 37, 1, NULL, 'jeremiah-37', 'John Calvin', 'Commentaries', E'1. And king Zedekiah the son of Josiah reigned instead of Coniah the son of Jehoiakim, whom Nebuchadrezzar king of Babylon made king in the land of Judah.

1. Et regnavit rex Zedechias, filius Josiae, pro Choniah (Jechania) filio Joiakim, quem constituit regem Nebuchadnezer, rex Babylonis, in terra Jehudah:

2. But neither he, nor his servants, nor the people of the land, did hearken unto the words of the LORD, which he spake by the prophet Jeremiah.

2. Et non audivit, neque servi ejus, neque populus terrae sermones Jehovae, quos loquutus est per manum Jeremiae Prophetae.

The Prophet tells us here, that after Jeconiah the king had been led into exile, the Jews had not on that account repented, though God had as it were forced them to return to him; for it was so severe a chastisement, that to become worse was an evidence of monstrous stupidity. Jeremiah, however, says that they were not reformed by that punishment; for Zedekiah, who had succeeded Jeconiah, rejected sound doctrine, and did not obey the counsel of the Prophet.

But we must bear in mind the history of that time, that we may understand the meaning of the Prophet: the Jews made Jeconiah king in the place of his father, but in the third month the army of the king of Babylon came. Then Jeconiah surrendered himself to them of his own accord. Now the Prophet had said, that there would be no legitimate successor to Jehoiakim; and this was fulfilled, though his son was set on the throne, for a three months'' reign was so unimportant that it was deemed as nothing. And when Nebuchadnezzar saw that the people could hardly be kept in order without a king, he made Mattaniah king, whom he called Zedekiah. And he immediately revolted to the Egyptians and made a treaty with them, in order that he might shake off the yoke of the king of Babylon. Hence the Prophet says, that though Zedekiah had been taught by the example of Jehoiakim and of his nephew Jeconiah, he yet became nothing the better, he does not shnply blame his ingratitude: it is indeed certain that he had been severely reproved by the Prophet for having acted perfidiously towards the King Nebuchadnezzar, for he ought to have kept faith with him to the last. He feigned a reason of his own for revolting from him; no new cause had occurred; but it was only that he might be exempt from tribute, and also lest the malevolent should object to him that he reigned by permission, and that. he was the slave of another king. As, then, he saw that his reign would be exposed to many reproaches, except he revolted from the king of Babylon, he made a treaty with the Egyptians.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 38, 1, NULL, 'jeremiah-38', 'John Calvin', 'Commentaries', E'1. Then Shephatiah the son of Mattan, and Gedaliah the son of Pashur, and Jucal the son of Shelemiah, and Pashur the son of Malchiah, heard the words that Jeremiah had spoken unto all the people, saying,

1. Et audivit Saphatias fillus Matthew tam, et Guadalias filius Passhur, et Juchal filius Selemiae et Passhur filius Malchiae, sermones quos Jere-mias loquutus fuerat ad toturm popu-lum, dicendo,

2. Thus saith the LORD, He that remaineth in this city shall die by the sword, by the famine, and by the pestilence: but he that goeth forth to the Chaldeans shall live; for he shall have his life for a prey, and shall live.

2. Sic dicit Jehova, Qui manebit in urbe hac morietur gladio, fame et peste; qui autem egressus fuerit ad Chaldaeos, rivet et erit ei anima sua in spolium et vivet.

3. Thus saith the LORD, This city shall surely be given into the hand of the king of Babylon''s army, which shall take it.

3. Sic dicit Jehova, Ecce tradendo tradetur haec urbs in manum exer-citus regis Babylonis, et capiet eam.

4. Therefore the princes said unto the king, We beseech thee, let this man be put to death: for thus he weakeneth the hands of the men of war that remain in this city, and the hands of all the people, in speaking such words unto them: for this man seeketh not the welfare of this people, but the hurt.

4. Et dixeunt principes ad regem, Moriatur nunc (vel, agedum, est hor-tantis particula n'') vir iste, quoni-am propterea (vel, hoc modo) solvit manus virorum bellicosorum, qui residui sunt in urbe hac, et manus totius populi, loquendo ad ipsos se-cundum istos sermones; quoniam hic vir non quaerit pacem (hoc est, non spectat ad pacem) populo huic (populi hujus) quin potius ad malum.

The Prophet now shews that he was again dragged from the court of the prison to the inner part, which was dark, filthy, and like a grave. The cause of this he states: it was because four of the princes had heard his words. It is probable that many of the people had come there for the purpose of hearing the Prophet, and that he, having received a message, delivered it to every one that came to him. Though then he was shut up in prison, yet the word of God could not be bound, as Paul says, who gloried in the fact, that though he was in chains, yet the truth spread far and wide. (2 Timothy 2:9.) Such was the case as to Jeremiah; though he was retained as a prisoner, he yet ceased not to discharge his office; and yet there is no doubt but that the purpose of the king was in this way to restrain him. The prison was, as it were, the captivity of prophetic truth.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 39, 1, NULL, 'jeremiah-39', 'John Calvin', 'Commentaries', E'1. In the ninth year of Zedekiah king of Judah, in the tenth month, came Nebuchadrezzar king of Babylon and all his army against Jerusalem, and they besieged it.

1. Anno nono Zedechiae regis Jehudah, mense decimo venit Nebuchadnezer rex Babylonis et totus exercitus ejus Jerosolymam, et obsiderunt eam.

2 And in the eleventh year of Zedekiah, in the fourth month, the ninth day of the month, the city was broken up.

2. In undecimo anno Zedechiae, mense quarto, nona mensis, disrupta fuit urbs.

Jeremiah seems here indeed to undertake the office of an historian rather than that of a Prophet; but he seals his previous prophecies, and at the same time shews that he had brought forward nothing rashly or thoughtlessly. There is, then, here a proof of all his former doctrine; he brings before us the reality, and shews that whatever he had predicted was accomplished by God''s hand, and in a manner almost incredible. We now understand what this chapter contains.

he says that King Nebuchadnezzar came, though he soon departed from the siege, for, as we shall presently see, he went to Riblah, which, as some think, was the Antioch of Syria; but of this we shall speak in its proper place. When, therefore, the king came with his army, he soon departed, and his purpose was to live at leisure, and in the enjoyment of pleasures as long as the city was besieged, he was not disposed to undertake the trouble and weariness of a long warfare; but yet, in order to spread more terror, he came himself to the City and gave instructions to his army.

We must notice the time: he came in the ninth year, in the tenth month, that is about the end of the year. Zedekiah, no doubt, entertained a good hope, though reports were flying as to the coming of the Chaldean army; for the king had not so soon prepared for the war as he ought to have done. he thought that his revolt from the king of Babylon would be passed by unpunished. But the Prophet here reminds us that it was a false confidence; for though God spared him for a time and suspended his judgment, he yet at length punished the impiety of his revolt, to which was also added ingratitude, as it has been before stated. Thus much as to the ninth year and the tenth month

It then follows, In the eleventh year, in the fourth month, the city was broken up We hence see that the city was besieged for a year and half; for there was the whole of the tenth year, and then added must be two months of the ninth year and four months of the eleventh year; and thus a year and half was the whole time.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 24, 40, 1, NULL, 'jeremiah-40', 'John Calvin', 'Commentaries', E'1. The word that came to Jeremiah from the LORD, after that Nebuzaradan the captain of the guard had let him go from Ramah, when he had taken him being bound in chains among all that were carried away captive of Jerusalem and Judah, which were carried away captive unto Babylon.

1. Sermo qui fuit ad Jeremiam a Jehova, postquam dimisit eum Nabuzardan, princeps interfectorum, e Ramah, quum sustulisset ipsum: et ipse vinctus erat cathenis (vel, manicis,) in medio captivitatis (hoc est, multitudinis captivae) Jerusalem et Jehudah, qui transferebantur Babylonem.

2. And the captain of the guard took Jeremiah, and said unto him, The LORD thy God hath pronounced this evil upon this place.

2. Et sumpsit princeps interfectorum Jeremiam, et dixit ad eum, Jehova Deus tuus loquutus est malum hoc super locum hunc;

3. Now the LORD hath brought it, and done according as he hath said: because ye have sinned against the LORD, and have not obeyed his voice, therefore this thing is come upon you.

3. Et adduxit et fecit Jehova sicut loquutus fuerat, quia peccastis Jehovae, et non audiistis vocem ejus; et fuit vobis res haec (hoc est, accidit vobis haec res.)

4. And now, behold, I loose thee this day from the chains which were upon thine hand. If it seem good unto thee to come with me into Babylon, come; and I will look well unto thee: but if it seem ill unto thee to come with me into Babylon, forbear: behold, all the land is before thee: whither it seemeth good and convenient for thee to go, thither go.

4. Et tu ecce (hoc est, quantum ad te,) ego ecce solvi te hodie a manicis (vel, cathenis, sed potius, a manicis, quoniam addit) quae erant super manus tuas (ideo perperam alii, vertunt, compedes, quia non ligantur compedibus;) si bonum in oculis tuis fecerit, ut venias (hoc est, si tibi placuerit venire) Babylonem, venias; ego autem ponam oculum meum super te; si autem malum in oculis tuis fuerit, ut venias Babylonem, desine (cessa, veI, supersedeas:) ecce tota regio coram facie tua est, ad bonum et rectum in oculis tuis, ad proficiscendum (hoc est, quod fuerit bonum et rectum in oculis tuis,) ut illic eas, eas.

Here Jeremiah pursues more at large what he had briefly touched upon before; for the Hebrews were wont, in a few words, to state the substance of the whole, and then to explain more diffusely what, they had briefly said. Jeremiah had before told us that some of the Babylonian generals had been sent to release him from prison; and he added that he had been committed to the care of Gedaliah, who had been set over the poor of the land. He now tells us, that he, as yet bound with chains, had been brought forth to Ramah in that miserable condition. These things appear inconsistent, but, as I have said, we must bear in mind, that there is an omission in that summary, which we have noticed.', false, false, 'sourced', 'published');
