-- Calvin commentary INSERT — Jude (batch 1, rows 1-1)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 65, 1, 1, NULL, 'jude-1', 'John Calvin', 'Commentaries', E'1 Jude the servant of Jesus Christ. He calls himself the servant of Christ, not as the name applies to all the godly, but with respect to his apostleship; for they were deemed peculiarly the servants of Christ, who had some public office committed to them. And we know why the apostles were wont to give themselves this honorable name. Whosoever is not called, arrogates to himself presumptuously the right and authority of teaching. Then their calling was an evidence to the apostles, that they did not thrust themselves into their office through their own will. It was not, however, of itself sufficient to be appointed to their office, except they faithfully discharged it. And, no doubt, he who declares himself to be the servant of God, includes both these things, that is, that God is the bestower of the office which he exercises, and that he faithfully performs what has been committed to him. Many act falsely, and falsely boast to be what they are very far from being: we ought always to examine whether the reality corresponds with the profession.

And brother of James. He mentions a name more celebrated than his own, and more known to the churches. For though faithfulness of doctrine and authority do not depend on the names of mortal men, yet it is a confirmation to the faith, when the integrity of the man who undertakes the office of a teacher is made certain to us. Besides, the authority of James is not here brought forward as that of a private individual, but because he was counted by all the Church as one of the chief apostles of Christ. He was the son of Alpheus, as I have said elsewhere. Nay, this very passage is a sufficient proof to me against Eusebius and others, who say, that he was a disciple, named Oblias, [James,] mentioned by Luke, in Acts 15:13; Acts 21:18, who was more eminent than the apostles in the Church. But there is no doubt but that Jude mentions here his own brother, because he was eminent among the apostles. It is, then, probable, that he was the person to whom the chief honor was conceded by the rest, according to what Luke relates.

To them that are sanctified by God the Father, or, to the called who are sanctified, etc. By this expression, "the called," he denotes all the faithful, because the Lord has separated them for himself. But as calling is nothing else but the effect of eternal election, it is sometimes taken for it. In this place it makes but little difference in which way you take it; for he, no doubt, commends the grace of God, by which he has been pleased to choose them as his peculiar treasure.', false, false, 'sourced', 'published');
