-- Calvin commentary INSERT — Zechariah (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 1, 1, NULL, 'zechariah-1', 'John Calvin', 'Commentaries', E'1. 1 In the eighth month, in the second year of Darius, came the word of the Lord unto Zechariah, the son of Berechiah, the son of Iddo the prophet, saying,

1. Mense octavo, anno secundo Darii, fuit sermo Iehovae ad Zachariam, filium Barachiae, filii Addo (Iddo, ad verbum) prophetae, (vel, prophetam,) dicendo,

2. The Lord hath been sore displeased with your fathers.

2. Iratus est Iehova erga patres vestros ira.

3. Therefore say thou unto them, Thus saith the Lord of hosts; Turn ye unto me, saith the Lord of hosts, and I will turn unto you, saith the Lord of hosts.

3. Dices igitur ad eos, Sic dicit Iehova exercituum, Revertimini ad me, dicit Iehova exercituum; et revertar ad vos, dicit Iehova exercituum.

We here learn what we have already stated, -- that Haggai and Zechariah were by God joined together, that they might confirm each other''s doctrine, for they had to do with a refractory people: besides, the people had to endure hard and arduous trials, so that they needed more than a common testimony to confirm them. Haggai commenced the work of his office in the sixth month; Zechariah shortly followed him, in the eighth month of the same year. It has already been shown who was the Darius mentioned here; though some interpreters dissent, we may yet learn from certain and indubitable proofs, that he was the son of Hystaspes. We shall again speak of this Darius, when a better occasion will offer itself: I wished only in passing to say thus much.

The word of Jehovah came to Zechariah. We have already said that the word of God comes in two ways to men. God addresses all from the least to the greatest; but in the first place he sends his word especially to his Prophets, to whom he commits the office of teaching. The word of God thus comes to private individuals, and it comes also to teachers, who sustain a public character, and become God''s interpreters or messengers. It was thus that God''s word came to Zechariah, not that he might keep to himself what God had said, but that he might be a faithful dispenser of his truth.

With regard to Zechariah, they are mistaken who regard him as the son of Jehoiadah, they are mistaken by Christ in Matthew 23:35. Zechariah is indeed said there to have been killed between the temple and the altar, and he is called the son of Barachiah: but the counting of years will easily prove their mistake, who would have him to be the same Zechariah. The former, who is called in sacred history the son of Jehoiadah the priest, was slain under Joash. Let us now see how many kings succeeded him, and also how many years he reigned. That Zechariah must have been almost two hundred years old at the Babylonian exile, if he was alive, had be been a boy when he was stoned.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 2, 1, NULL, 'zechariah-2', 'John Calvin', 'Commentaries', E'1. I lifted up mine eyes again, and looked, and behold a man with a measuring line in his hand.

1. Et sustuli oculos meos et vidi; et ecce vir in ejus manu funiculus mensurae.

2. Then said I, Whither goest thou? And he said unto me, To measure Jerusalem, to see what is the breadth thereof, and what is the length thereof.

2. Et dixi, Quo tu vadis? et dixit mihi, Ad metiendum Ierusalem, ut videam quanta latitudo ejus, et quanta longitudo ejus.

3. And, behold, the angel that talked with me went forth, and another angel went out to meet him,

3. Et ecce angelus qui loquebatur mecum egressus est, et alter angelus egressus est in occursum ejus;

4. And said unto him, Run, speak to this young man, saying, Jerusalem shall be inhabited as towns without walls for the multitude of men and cattle therein:

4. Et dixit ad eum, Curre, dic puero huic, dicendo, In villis (vel, pagis) habitabitur Ierusalem prae multitudine hominis et pecoris (id est, honinum et pecorum) in medio ejus.

Added now is another vision for the same end; not that the former was difficult to be understood, but because there was need of confirmation in a state of things so disturbed; for though the return of the people was no common evidence of the goodness and favor of God yet as Jerusalem was not flourishing as formerly, as the temple was like a cottage as there was no form of a kingdom and no grandeur, it was difficult to believe what had been already exhibited. This is the reason why God confirms by many proofs the same thing; for we know how difficult the contest is, owing to the infirmity of the flesh, when grievous and sharp trials assail us.

Hence Zechariah says, that he saw in the hand of a man a measuring line. He calls him a man, who appeared in the form of man; and it is well known, and a common thing, that angels are called men. For though they put on a human form only for a time, yet as it was the Lord''s will that they should be seen in that form, they are called men, though with no propriety. If it be asked, whether angels did really put on human nature? the obvious answer is, that they never, strictly speaking, became really men. But we know that God treats us as children; and there is the same reason for the expression as for the thing itself. How was it that angels appeared in human form? even that their access to men might be easier. Hence God calls them men as in this place. Zechariah then says, that an angel appeared to him in the form of a man, having in his hand a measuring line.

He then asks him where he was going; the answer given is, to measure Jerusalem, to see what was its breadth and its length.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 3, 1, NULL, 'zechariah-3', 'John Calvin', 'Commentaries', E'10. In that day, saith the LORD of hosts, shall ye call every man his neighbour under the vine and under the fig tree.

10. In illo die, dicit Iehova exercituum, vocabitis quisque proximum suum sub vite et sub ficu.

We see from this verse that a particular time is signified by one day; for the Prophet wished to inspire the Jews with confidence, lest they should think that their misery would continue, because God had hitherto treated them with rigor and severity. Here then is shown to them a sudden change. He therefore adds, In that day, ye shall call every one his neighbor under his vine and under his fig-tree; that is, "Ye shall dwell secure, beyond the reach of fear or of danger; for no one will be incensed against you." This kind of expression signifies a safe and quiet state, that is, when it is said; that neighbors meet together under the vine and under the fig-tree. For they who fear, either remain inclosed in cities, or seek, when in the country, some fortified place and difficult of access, or watch their own doors that they may not be exposed to injuries; but they who joyfully meet together under the vine or under the fig-tree, show that they are free from every anxiety and fear.

The sum of the whole then is, -- that when God shall openly make himself the guardian of his Church, the faithful shall be relieved from every fear, and shall cheerfully enjoy their freedom, so that they shall venture to have their repast under the vine and under the fig-tree, that is, in the open air and on the public road, as there will be none to terrify them. But as this promise is to be extended to the whole kingdom of Christ, what is said ought to be applied to that spiritual peace which we enjoy, when we are fully persuaded that God is reconciled to us; for then also us become reconciled among ourselves, so that we no longer seek to injure one another, according to what we have observed in Micah, (Micah 4:4,) and according to what Isaiah says in the second chapter Isaiah 2:1. Let us now proceed- __________________________________________________________________ __________________________________________________________________

Chapter 4. __________________________________________________________________', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 4, 1, NULL, 'zechariah-4', 'John Calvin', 'Commentaries', E'1. And the angel that talked with me came again, and waked me, as a man that is wakened out of his sleep, 1. Et reversus et angelus, qui loquebatur mecum, et excitavit me, quasi virum qui excitatur (vel, evigilat) a somno suo. 2. And said unto me, What seest thou? And I said, I have looked, and behold a candlestick all of gold, with a bowl upon the top of it, and his seven lamps thereon, and seven pipes to the seven lamps, which are upon the top thereof: 2. Et dixit ad me, Quid tu vides? et dixit, Video, et ecce candelabrum ex auro totum (hoc est, ex solido auro,) et pelvis super caput ejus; et septem lucernae super ipsum; septem et septem infusoria lucernis, quae sunt super caput ejus; 3. And two olive trees by it, one upon the right side of the bowl, and the other upon the left side thereof. 3. Et duae oleae super ipsum, una a dextera pelvis, et una ad sinistram ejus. 4. So I answered and spake to the angel that talked with me, saying, What are these, my lord? 4. Et respondit et dixi angelo, qui loquebatur mecum, dicendo, Quid ista, Domine mi? 5. Then the angel that talked with me answered and said unto me, Knowest thou not what these be? And I said, No, my lord. 5. Et respondit angelus, qui loquebatur mecum, et dixit mihi, Annon cognoscis quid sint haec? Et dixi, Non, Domine mi. 6. Then he answered and spake unto me, saying, This is the word of the Lord unto Zerubbabel, saying, Not by might, nor by power, but by my spirit, saith the Lord of hosts. 6. Et respondit et dixit mihi dicendo, Hic sermo Iehovae ad Zerubbabel, dicendo, Non in exercitu, et non in fortitudine, sed in Spiritu meo, dicit Iehova exercituum. Another vision is narrated here, -- that a candlestick was shown to the Prophet, on which there were seven lights. He says that the candlestick was formed all of gold: and he says that to the seven lamps there were as many cruses, (infusoria -- pourers,) or, as some think, there were seven cruses to each lamp: but the former view is what I mostly approve, that is, that every lamp had its own cruse. He further says, that there were two olive-trees, one on the right, the other on the left hand, so that there was no deficiency of oil, as the olive-trees were full of fruit. Since then there was a great abundance of berries, the oil would not fail; and the lamps were continually burning. This is the vision, and the explanation is immediately added, for God declares that his Spirit was sufficient to preserve the Church without any earthly helps, that is, that his grace would always shine bright, and could never be extinguished. There is, moreover, no doubt but that God set forth to Zechariah a figure and an image suitable to the capacities of the', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 5, 1, NULL, 'zechariah-5', 'John Calvin', 'Commentaries', E'1. Then I turned, and lifted up mine eyes, and looked, and behold a flying roll.

1. Et reversus sum et extuli oculos meos, et aspexi, et ecce volumen volans.

2. And he said unto me, What seest thou? And I answered, I see a flying roll; the length thereof is twenty cubits, and the breadth thereof ten cubits.

2. Et dixit mihi, Quid tu vides? Et dixit, ego video volumen volans; longitudo ejus viginti in cubito (hoc est, ad viginti cubitos,) et latitudo ejus decem in cubito (hoc est, ad decem cubitos.)

3. Then said he unto me, This is the curse that goeth forth over the face of the whole earth: for every one that stealeth shall be cut off as on this side according to it; and every one that sweareth shall be cut off as on that side according to it.

3. Et dixit mihi, Haec est maledictio, quiae egreditur super faciem universae terrae; quia quisquis furatur, ex hac sicut illa punietur; et quisquis pejerat, ex hac sicut illa punietur.

4. I will bring it forth, saith the LORD of hosts, and it shall enter into the house of the thief, and into the house of him that sweareth falsely by my name: and it shall remain in the midst of his house, and shall consume it with the timber thereof and the stones thereof.

4. Emittam (vel, producam) eam, dicit Iehova exercituum; et veniet ad domum furantis, et ad domum jurantis in nomine meo fallaciter; et residebit in medio domus ejus, et consumet eam et ligna et lapides ejus.

The angel shows in this chapter, that whatever evils the Jews had suffered, proceeded from the righteous judgment Of God; and then he adds a consolation -- that the Lord would at length alleviate or put an end to their evils, when he had removed afar off their iniquity. Interpreters have touched neither heaven nor earth in their explanation of this prophecy, for they have not regarded the design of the Holy Spirit. Some think that by the volume are to be understood false and perverted glosses, by which the purity of doctrine had been vitiated; but this view can by no means be received. There is no doubt but that God intended to show to Zechariah, that the Jews were justly punished, because the whole land was full of thefts and perjuries. As then religion had been despised, as well as equity and justice, he shows that it was no wonder that a curse had prevailed through the whole land, the Jews leaving by their impiety and other sins extremely provoked the wrath of God. This is the import of the first part. And, then, as this vision was terrible, there is added some alleviation by representing iniquity in a measure, and the mouth of the measure closed, and afterwards carried to the land of Shinar, that is, into Chaldea, that it might not remain in Judea.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 6, 1, NULL, 'zechariah-6', 'John Calvin', 'Commentaries', E'1. And I turned, and lifted up mine eyes, and looked, and, behold, there came four chariots out from between two mountains; and the mountains were mountains of brass.

1. Et conversus sum, et levavi oculos meos, et aspexi; et ecce quatuor quadrigae egressae e mdio duorum montium; et montes illi, montes aenei.

2. In the first chariot were red horses; and in the second chariot black horses;

2. In quadriga prima equi rufi, et in quadriga secunda equi nigri,

3. And in the third chariot white horses; and in the fourth chariot grisled and bay horses.

3. Et in quiadriga tertia equi albi, et in quadriga quarta equi grandinei. (vel, varii; mytsvm'', robusti, sed potius subscribo eorum sententiae qui vertunt subrufos.)

Here we have another vision; and the Prophet distinguishes it from the former visions by saying, that he turned, as though he had said, that there had been some intervening time. They were not then continued visions, but he turned himself elsewhere, and then he raised up his eyes, and the Lord revealed to him what he now relates. But as the vision is obscure, interpreters have given it different meanings. They who think that the four Gospels are designated by the four chariots, give a very frigid view. I have elsewhere reminded you, that we are to avoid these futile refinements which of themselves vanish away. Allegories, I know, delight many; but we ought reverently and soberly to interpret the prophetic writings, and not to fly in the clouds, but ever to fix our foot on solid ground. Others think that those changes are meant which we know happened in Chaldea and Assyria. As Nineveh was overthrown that Babylon might be the seat of the empire, they suppose that this is meant by the first chariot, the horses of which were red. Then they think that the Persian empire is intended by the second chariot, as the Jews had at the beginning suffered many grievous evils. Afterwards by the white horses are signified, as they suppose, the Macedonian power, as Alexander treated the Jews with humanity and kindness. By the fourth chariot they understand the Roman Empire, and think that the horses are of different colors, because some of the Caesars raged cruelly against the Jews and the Church of God, and some of them showed more lenity. But I know not whether these things are well founded.

We see that the fourth chariot went to the south, and wandered through various regions, and almost through the whole world. As then this cannot be applied to Chaldea, the simpler view seems to be -- that the four chariots signify the various changes which happened not only in Chaldea and among the Babylonians, but also in Judea and among other nations: and this may be easily gathered from the context. But as all these things cannot be stated at the same time, we shall treat them in the order in which the Prophet relates them.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 7, 1, NULL, 'zechariah-7', 'John Calvin', 'Commentaries', E'1. And it came to pass in the fourth year of king Darius, that the word of the LORD came unto Zechariah in the fourth day of the ninth month, even in Chisleu; 1. Et factus est (datus est,) anno quarto Darii regis, sermo Iehovae ad Zachariam, quarta die mensis noni Chisleu; 2. When they had sent unto the house of God Sherezer and Regemmelech, and their men, to pray before the LORD, 2. Nam miserat in domum Dei (hoc est, Templum) Sareezer et Regem-melech et viros ejus ad deprecandam faciem Iehovae (aut, Miserat in domum Dei Sareezer et Regem-melech, in nominativo casu, et viri ejus ad deprecandam faciem Iehovae:) 3. And to speak unto the priests which were in the house of the LORD of hosts, and to the prophets, saying, Should I weep in the fifth month, separating myself, as I have done these so many years? 3. Ad dicendum sacerdotibus qui erant in domo Iehovae exercituum, et Prophetis, dicendo, An flebo mense, quinto? Separabo me? quemadmodum feci his annis? (est turbata series verborum, quemadmodum solitus sum facere his annis?) There is no vision here, but the answer which Zechariah was commanded to give to the messengers of the captives: for he says that some had been sent from Chaldea to offer sacrifices to God, and at the same time to inquire whether the fast, which they had appointed when the city was taken and destroyed, was to be observed. But there is some ambiguity in the words of the Prophet, for it is doubtful whether the two whom he names, even Sherezer and Regem-melech, together with the others, had sent the messengers of whom mention is made, or they themselves came and brought the message from the captives. But this is a matter of no great moment. As to the question itself, I am disposed to adopt their view, who think that these two came with their associates to Jerusalem, and in the name of them all inquired respecting the fast, as we shall hereafter see. The Jews think that these were Persian princes; but this opinion is frivolous. They are thus accustomed to draw whatever occurs to the glory of their own nation without any discretion or judgment, as though it had been an object much desired by the Jews, that two Persian should go up to the temple. But there is no need here of a long discussion; for if we regard the Prophet''s design, we may easily conclude that these were Jews who had been sent by the exiles, both to offer gifts and to inquire about the fast, as the Prophet tells us. The sum of the whole then is, that Sherezer and Regem-melech, and their companions, came to the temple, and that they also asked counsel of the priests and Prophets, whether the fast of the fifth month was still to be observed. It must first be observed, that though all had not so much courage as to return to their own', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 8, 1, NULL, 'zechariah-8', 'John Calvin', 'Commentaries', E'23. Thus saith the Lord of hosts; In those days it shall come to pass, that ten men shall take hold out of all languages of the nations, even shall take hold of the skirt of him that is a Jew, saying, We will go with you: for we have heard that God is with you. 23. Sic dicit Iehova exercituum, In diebus isitis fiet ut apprehendant decem homines ex cunctis linguis gentium, apprehendant alam viri Judaei, dicendo, Ambulabimus (vel, ambulemus) vobiscum, quia audivimus quod Deus sit vobiscum. He pursues the same subject in this verse; for as he had before said, that the nations would willingly come to worship God, and that each would encourage his brother to undertake this pious and holy expedition, so he now adds, that ten men would lay hold on the border of a Jew''s garment: Ten men shall then take hold of the skirt of a Jew. He shows here more clearly what I have briefly referred to -- that there would be no need of arms, or of any compulsion, in order to draw or compel the nations to engage in God''s service; for even ten would of themselves accompany one Jew; and it is a proof of a very great readiness when ten surrender themselves to be ruled by one. As one Jew could not be sufficient to draw so many nations, the Prophet declares that there would be everywhere a union of faith, so that those, before wholly alienated from God, would desire to join themselves as friends, or rather as companions to the Jews. He says, From all languages. By these words he amplifies the miracle; for there cannot be a union between men far distant, especially when they are of different languages, as they are barbarians to one another. When the Prophet then says that they would come from all languages, and unite together, it more fully appears to be God''s work; for there is nothing here to be ascribed to human contrivances. It must then be that the hearts of those who cannot express their minds, and can hardly give a sign, are united together by the hidden power of the Spirit. We now perceive the Prophet''s object in this verse. But he uses in the last clause a phrase different from the one he employed before -- Let us go with you, for we have heard that with you is God. He had said, "Let us go to seek Jehovah, and to entreat his face;" but now he says "Let us go with you." But yet he handles and confirms the same thing; for the nations could not have sought God without following the Jews going before them. For when any one separates himself from others, it so happens that he is led astray, and feeds on much that is very absurd, as we see to be the case with proud and morose men, who invent strange and monstrous things; for they shun society, and seem', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 9, 1, NULL, 'zechariah-9', 'John Calvin', 'Commentaries', E'1. The burden of the word of the Lord in the land of Hadrach, and Damascus shall be the rest thereof: when the eyes of man, as of all the tribes of Israel, shall be toward the Lord 1. Onus sermonis Iehovae in terra Chadrak, et Damascus quies ejus; quia ad Iehovam oculus hominis et omnium tribuum Israel. One thing had escaped my notice in the words of the Prophet -- that great people and strong nations would come. We have said that "great" rather than "many" ought to be adopted. The latter meaning may indeed be allowed that the worshipers of God would come from various cities; but as the word tsvmym, otsumim properly signifies strong, and as it is certain that the Prophet means the same thing by the two words, it is more probable that he speaks of strong and valiant people, as they are not so easily subdued; for the more any one excels in prowess, the more stiff is his neck to undertake the yoke. As then the strong and the brave, and such as are eminent in the world, are not so easily brought to submit to God, the Prophet expressly says, that they shall become teachable, and be made willing, so that pride, as it is usually the case, shall not be a hindrance to them. I come now to the passage in which the Prophet announces a heavy burden, or a severe and fearful prophecy respecting Syria and other neighboring nations. I prefer to retain the word "burden," rather than to render it prophecy, as many expositors have done; for though ms'', mesha, is sometimes taken simply for prophecy, yet there is here, as it appears to me, something particular intended; for the Prophet denounces God''s judgment both on Syria and on the surrounding countries, and the word prophecy is not suitable; for to say "the prophecy of the word," would be strange and without meaning. But when he says, The burden of the word of God, the sentence is full, and flows well; for he reminds us that his word would not be ineffectual, but full of effect, as it would lie as a burden on Syria and on other countries, which they should not be able to shake off. The burden then of the word of Jehovah; that is, "I have now a prediction which will be grievous and severe to those heathens who now disturb the Jews, the chosen people." But this doctrine contains consolation to the godly; for they may hence know that they are safe under God''s protection, as he carries on war with their enemies; nay, his vengeance was now prepared against all those who harassed the Jews. As then he had before promised that incredible favor of God which we have noticed, so now he declares that the Church would be safe under the protection of God, inasmuch as vengeance was in readiness for all the ungodly. But the Prophet mentions here only the cities', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 38, 10, 1, NULL, 'zechariah-10', 'John Calvin', 'Commentaries', E'1. Ask ye of the Lord rain in the time of the latter rain; so the Lord shall make bright clouds, and give them showers of rain, to every one grass in the field.

1. Petite a Iehova pluviam tempore serotino (vertunt;) Iehova faciet nubes, et pluvium imbrem dabit illis, cuique herbam in agro.

Zechariah, after having shown that God would be bountiful towards the Jews, so that nothing necessary to render life happy and blessed should be wanting, now reproves them for their unbelief, because they did not expect from the Lord what he was ready fully to bestow on them. As then it depended on them only, that they did not enjoy abundance of all blessings, he charges them with ingratitude: for though he exhorts them to prayer, there is yet an implied reproof. One by merely reading over the words may think that a new subject is here introduced, that the Jews are directed to ask of the Lord what he had previously promised them; but he who will more minutely consider the whole context, will easily find that what I have stated is true -- that the Jews are here condemned, and on this account, because they closed the door against God''s favor; for they were straitened in themselves, as all the unbelieving are, who cannot embrace the promises of God; nor is it at all doubtful but that many made great complaints, when they found themselves disappointed of their wishes. They had indeed hoped for a most abundant supply of corn and wine, and had also promised to themselves all kinds of blessings, yet the Lord, as we have seen in the book of Haggai, had begun to withdraw his hand, so that they labored under want of provisions; and when mine and thirst oppressed them, they thought that they had been in a manlier deceived by God. On this ground the Prophet expostulates with them; they thrust from themselves, by their want of faith, the favor which had been prepared for them. We now then understand the Prophet''s meaning.

He bids them to ask rain of Jehovah. They ought indeed to have done this of themselves without being reminded; for though Christ has delivered to his Church a form of prayer, it ought yet to be as it were the dictate of nature to seek of God our daily bread; and it is not without reason that he claims to himself the name of a Father. The Prophet then does here reprove the Jews for their brutal stupidity -- that they did not ask rain of the Lord. He adds, at the late season, that is, at spring time; for rains at two seasons were necessary for the corn, after sowing and before harvest, and whenever Scripture speaks of fruitfulness or of a large produce, it mentions rain at these two seasons.', false, false, 'sourced', 'published');
