-- Calvin commentary INSERT — Daniel (batch 2, rows 11-12)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 27, 11, 1, NULL, 'daniel-11', 'John Calvin', 'Commentaries', E'1. Also I in the first year of Darius the Mede, even I, stood to confirm and to strengthen him.

1. Et ego anno primo Darii medi steti in roboratorem, et auxilium illi.

Interpreters explain this verse in various ways. Some think the angel fought for the Persian king, and follow up their opinion, because he did not for the first time begin now to defend that monarchy in favor of the chosen people, but had done so from the very beginning. Others refer this to Michael, as the angel declares that he introduced the assistance of Michael. But that is forced and cold. I do not hesitate to state the argument to be from the greater to the less, and we have an instance of this in a tragedy of Ovid''s. I have been able to preserve you; do you ask whether I can destroy you? Thus the angel says, I have erected the Persian monarchy; I have not the slightest doubt of my present power to restrain these kings, lest they should pour forth their fury upon the people. The full meaning is this, the king of the Persians is nothing, and can do nothing except through me. I was God''s servant in transferring the monarchy of the Medes and Chaldeans to the Persians, as well as that of the Babylonians to the Medes. God, says he, entrusted me with that office, and so I placed Darius upon the throne. You now see how completely I have him in my power, and how I can prevent him from injuring my people should he be so inclined. When the angel boasts of his standing forward to help Darius, he claims nothing to himself, but speaks as it were in the person of God. For angels have no power distinct from God''s when he uses their agency and assistance. There is no reason for any inquiry whether the angel ought to use this boastful language and claim anything for himself. For he does not claim anything as really his own, but he skews himself to have been an agent in the change of dynasty when Babylon was subdued by the Medes, and the empire transferred to Darius. For although, as we have previously shewn, Cyrus obtained the victory, yet he transferred the honors of government to his uncle Cyaxares. The Hebrews are accustomed to consider him as king for the first two years; Cyrus began to reign after this period; and now, when the angel appears to Daniel, the third year had arrived, as we saw at the beginning of the chapter. __________________________________________________________________

That is, I stood by to strengthen and assist him. -- Calvin. __________________________________________________________________

Grant, Almighty God, as thou daily and familiarly deignest to grant us the light of heavenly doctrine, that we may come to thy school with true humility and modesty. May our docility be really apparent; may we receive with reverence whatever proceeds from thy lips, and may thy majesty be conspicuous among us.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 27, 12, 1, NULL, 'daniel-12', 'John Calvin', 'Commentaries', E'1. And at that time shall Michael stand up, the great prince which standeth for the children of thy people: and there shall be a time of trouble, such as never was since there was a nation even to that same time: and at that time thy people shall be delivered, every one that shall be found written in the book.

1. Et tempore illo stabit Michael princeps, magnus stans pro filiis populi tui, et erit tempus afflictionis, quale non fuit abesse gentem, hoc est, ex quo coeperunt esse gentes, ad tempus illud usque: et tempore illo servabitur populus tuus quicunque inventus fuerit scriptus in libro.

The angel no longer relates future occurrences specially, but proclaims God to be in general the guardian of his Church, so as to preserve it wonderfully amidst many difficulties and dreadful commotion''s, as well as in the profound darkness of disaster and death. This is the meaning of this sentence. This verse consists of two parts: the first relates to that most wretched period which should be full of various and almost numberless calamities; and the second assures us of God''s never-failing protection and preservation of his Church by his own innate power. In this second part the promise is restricted to the elect, and thus a third clause may be distinguished, but it is only an addition to the second just mentioned. At the close of the verse, the angel presents us with a definition of the Church, as many professed to be God''s people who were not really so. He says, Michael, the prince of the people, should stand up Then he states the reason, The calamities of that period should be such as were never witnessed from the beginning of the world As he addresses Daniel, he says, sons of thy people; for he was one of the sons of Abraham, and the nation from which Daniel sprang was in that sense "his." From this it follows that the calamities of which he will by and bye treat, belong to the true Church, and not to the profane nations. The singular aid of Michael would not have been needed, unless the Church had been oppressed with the most disastrous distresses. We perceive, then, the angel''s meaning to be according to my explanation. The Church should be subject to most numerous and grievous calamities until the advent of Christ, but yet it should feel God''s propitious disposition, ensuring its own safety under his aid and protection. By Michael many agree in understanding Christ as the head of the Church. But if it seems better to understand Michael as the archangel, this sense will prove suitable, for under Christ as the head, angels are the guardians of the Church. Whichever be the true meaning, God was the preserver of his Church by the hand of his only-begotten Son, and because the angels are under the government of Christ, he might entrust this duty to Michael.', false, false, 'sourced', 'published');
