-- Calvin commentary INSERT — Hebrews (batch 2, rows 11-13)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 58, 11, 1, NULL, 'hebrews-11', 'John Calvin', 'Commentaries', E'1. Now faith, etc. Whoever made this the beginning of the eleventh chapter, has unwisely disjointed the context; for the object of the Apostle was to prove what he had already said that there is need of patience. He had quoted the testimony of Habakkuk, who says that the just lives by faith; he now shows what remained to be proved -- that faith can be no more separated from patience than from itself. The order then of what he says is this, -- "We shall not reach the goal of salvation except we have patience, for the Prophet declares that the just lives by faith; but faith directs us to things afar off which we do not as yet enjoy; it then necessarily includes patience." Therefore the minor proposition in the argument is this, Faith is the substance of things hoped for, etc. It is hence also evident, that greatly mistaken are they who think that an exact definition of faith is given here; for the Apostle does not speak here of the whole of what faith is, but selects that part of it which was suitable to his purpose, even that it has patience ever connected with it. Let us now consider the words. He calls faith the hypostasis, the substance of things hoped for. We indeed know that what we hope for is not what we have as it were in hand, but what is as yet hid from us, or at least the enjoyment of which is delayed to another time. The Apostle now teaches us the same thing with what we find in Romans 8:24; where it is said that what is hoped for is not seen, and hence the inference is drawn, that it is to be waited for in patience. So the Apostle here reminds us, that faith regards not present things, but such as are waited for. Nor is this kind of contradiction without its force and beauty: Faith, he says, is the hypostasis, the prop, or the foundation on which we plant our foot, -- the prop of what? Of things absent, which are so far from being really possessed by us, that they are far beyond the reach of our understanding. The same view is to be taken of the second clause, when he calls faith the evidence or demonstration of things not seen; for demonstration makes things to appear or to be seen; and it is commonly applied to what is subject to our senses. Then these two things, though apparently inconsistent, do yet perfectly harmonize when we speak of faith; for the Spirit of God shows to us hidden things, the knowledge of which cannot reach our senses: Promised to us is eternal life, but it is promised to the dead; we are assured of a happy resurrection, but we are as yet involved in corruption; we are pronounced just, as yet sin dwells in us; we hear that we are happy, but we are as yet in', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 58, 12, 1, NULL, 'hebrews-12', 'John Calvin', 'Commentaries', E'1. Wherefore, seeing we also, etc. This conclusion is, as it were, an epilogue to the former chapter, by which he shows the end for which he gave a catalogue of the saints who excelled in faith under the Law, even that every one should be prepared to imitate them; and he calls a large multitude metaphorically a cloud, for he sets what is dense in opposition to what is thinly scattered. Had they been a few in number, yet they ought to have roused us by their example; but as they were a vast throng, they ought more powerfully to stimulate us.

He says that we are so surrounded by this dense throng, that wherever we turn our eyes many examples of faith immediately meet us. The word witnesses I do not take in a general sense, as though he called them the martyrs of God, and I apply it to the case before us, as though he had said that faith is sufficiently proved by their testimony, so that no doubt ought to be entertained; for the virtues of the saints are so many testimonies to confirm us, that we, relying on them as our guides and associates, ought to go onward to God with more alacrity.

Let us lay aside every weight, or every burden, etc. As he refers to the likeness of a race, he bids us to be lightly equipped; for nothing more prevents haste than to be encumbered with burdens. Now there are various burdens which delay and impede our spiritual course, such as the love of this present life, the pleasures of the world, the lusts of the flesh, worldly cares, riches also and honors, and other things of this kind. Whosoever, then, would run in the course prescribed by Christ, must first disentangle himself from all these impediments, for we are already of ourselves more tardy than we ought to be, so no other causes of delay should be added.

We are not however bidden to cast away riches or other blessings of this life, except so far as they retard our course for Satan by these as by toils retains and impedes us.

Now, the metaphor of a race is often to be found in Scripture; but here it means not any kind of race, but a running contest, which is wont to call forth the greatest exertions. The import of what is said then is, that we are engaged in a contest, even in a race the most celebrated, that many witnesses stand around us, that the Son of God is the umpire who invites and exhorts us to secure the prize, and that therefore it would be most disgraceful for us to grow weary or inactive in the midst of our course.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 58, 13, 1, NULL, 'hebrews-13', 'John Calvin', 'Commentaries', E'1. Let brotherly love, etc. Probably he gave this command respecting brotherly love, because a secret hatred arising from the haughtiness of the Jews was threatening to rend the Churches. But still this precept is generally very needful, for nothing flows away so easily as love; when everyone thinks of himself more than he ought, he will allow to others less than he ought; and then many offenses happen daily which cause separations. He calls love brotherly, not only to teach us that we ought to be mutually united together by a peculiar and an inward feeling of love, but also that we may remember that we cannot be Christians without being brethren; for he speaks of the love which the household of faith ought to cultivate one towards another inasmuch as the Lord has bound them closer together by the common bond of adoption. It was therefore a good custom in the primitive Church for Christians to call one another brothers; but now the name as well as the thing itself is become almost obsolete, except that the monks have appropriated to themselves the use of it when neglected by others, while at the same time they show by their discords and intestine factions that they are the children of the evil one. 2. Be not forgetful to entertain strangers, etc. This office of humanity has also nearly ceased to be properly observed among men; for the ancient hospitality, celebrated in histories, is unknown to us, and Inns now supply the place of accommodations for strangers. But he speaks not so much of the practice of hospitality as observed then by the rich; but he rather commends the miserable and the needy to be entertained, as at that time many were fugitives who left their homes for the name of Christ. And that he might commend this duty the more, he adds, that angels had sometimes been entertained by those who thought that they received only men. I doubt not but that this is to be understood of Abraham and Lot; for having been in the habit of showing hospitality, they without knowing and thinking of any such thing, entertained angels; thus their houses were in no common way honored. And doubtless God proved that hospitality was especially acceptable to him, when he rendered such a reward to Abraham and to Lot. Were any one to object and say, that this rarely happened; to this the obvious answer is, -- That not mere angels are received, but Christ himself, when we receive the poor in his name. In the words in Greek there is a beautiful alliteration which cannot be set forth in Latin. 3. Remember them that are in bonds, or, Be mindful of the bound, etc. There is nothing that can give us a more genuine feeling of compassion than to put ourselves in the place of those who are in distress; hence he says, that we ought to think of those in bonds as though we', false, false, 'sourced', 'published');
