-- Calvin commentary INSERT — Jonah (batch 1, rows 1-4)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 32, 1, 1, NULL, 'jonah-1', 'John Calvin', 'Commentaries', E'1. Now the word of the LORD came unto Jonah the son of Amittai, saying,

1. Et fuit sermo Jehovae ad Ionam, filium Amittai, dicendo,

2. Arise, go to Nineveh, that great city, and cry against it; for their wickedness is come up before me.

2. Surge, vade Niniveh, ad urbem magnam, et clama contra eam; quia ascendit malitia eorum coram facie mea.

As I have before observed, Jonah seems here indirectly to intimate, that he had been previously called to the office of a teacher; for it is the same as though he had said, that he framed this history as a part of his ordinary function. The word of God then was not for the first time communicated to Jonah, when he was sent to Nineveh; but it pleased God, when he was already a Prophet, to employ him among other nations. It might have been then, that he was sent to Nineveh, that the Lord, being wearied with the obstinacy of his own people, might afford an example of pious docility on the part of a heathen and uncircumcised nation, in order to render the Israelites more inexcusable. They made a profession of true religion, they boasted that they were a holy people; circumcision was also to them a symbol and a pledge of God''s covenant; yet they despised all the Prophets, so that their teaching among them was wholly useless. It is then probable that this Prophet was taken away from them, that the Ninevites by their example might increase the sin of Israel, for in three days they turned to God, after Jonah had preached to them: but among the Israelites and their kindred he had, during a long time, effected nothing, when yet his authority had been sufficiently ratified, and thus, as we have already said, in their favor: for Jonah had predicted, that the kingdom of Israel would as yet stand; and however much they deserved to perish, yet the Lord fulfilled what he had promised by the mouth at his servant. They ought then to have embraced his doctrine, not only because it was divine, but especially because the Lord had been pleased to show his love to them.

I do not indeed doubt, but that the ingratitude of the people was in this manner arraigned, since the Ninevites repented at the preaching of Jonah, and that for a short time, while the Israelites ever hardened themselves in their obstinacy. And hence some have refinedly expounded that passage in Matthew 12:39-41, This perverse generation seeketh a sign, and a sign shall not be given to it, except the sign of Jonah the Prophet,'' as though this intimated, that the Gospel was to be preached to the Gentiles, inasmuch as Jonah was taken away from his own nation, and was given as a teacher to foreign and heathen nations.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 32, 2, 1, NULL, 'jonah-2', 'John Calvin', 'Commentaries', E'1. Then Jonah prayed unto the Lord his God out of the fish''s belly,

1. Et oravit Jonas ad Jehovam Deum suum e ventre piscis;

2. And said, I cried by reason of mine affliction unto the Lord, and he heard me; out of the belly of hell cried I, and thou heardest my voice.

2. Et dixit clamavi in angustia mea ad Jehovam, et exaudit me (vel, respondit mihi;) e ventre sepulchri vociferatus sum, audivisti vocem meam.

When Jonah says that he prayed from the bowels of the fish, he shows first with what courage of mind he was endued. He had then put on a new heart; for when he was at liberty he thought that he could in a manner escape from God, he became a fugitive from the Lord: but now while inclosed within narrow bounds, he begins to pray, and of his own accord sets himself in God''s presence.

This is a change worthy of being noticed: and hence we may learn how much it profits us to be drawn back often as it were by cords, or to be held tied up with fetters because when we are free we go astray here and there beyond all limits. Jonah, when he was at liberty, became, as we have seen, wanton; but now finding himself restrained by the mighty hand of God, he receives a new mind, and prays from the bowels of the fish . But how was it that he directed his petitions then to God, by whose hand he saw that he was so heavily pressed? For God most rigidly handled him; Jonah was in a manner doomed to eternal ruin; the bowels of the fish, as we shall hereafter see, were indeed to him as it were hell or the grave. But in this state of despair Jonah even gathered courage, and was able to retake himself directly to God. It was a wonderful and almost incredible example of faith. Let us then learn to weigh well what is here said; for when the Lord heavily afflicts us, it is then a legitimate and seasonable time for prayer. But we know that the greater part despond, and do not usually offer their prayers freely to God, except their minds be in a calm state; and yet God then especially invites us to himself when we are reduced to extremities. Let this, then, which Jonah declares of himself, come to our minds, -- that he cried to God from hell itself: and, at the same time, he assures us that his prayer proceeded from true faith; for he does not simply say that he prayed to Jehovah, but he adds that he was his God; and he speaks with a serious and deeply-reflective mind. Though Jonah then was not only like one dead, but also on the confines of perdition, he yet believed that God would be merciful if he fled to him.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 32, 3, 1, NULL, 'jonah-3', 'John Calvin', 'Commentaries', E'1. And the word of the LORD came unto Jonah the second time, saying,

1. Et factum fuit verbum Jehovae ad Jonam secundo, dicendo, --

2. Arise, go unto Nineveh, that great city, and preach unto it the preaching that I bid thee.

2. Surge, proficiscere Nineven in urbem magnam, et praedica ad eam praedicationem quam ego mando tibi.

There is here set before us a remarkable proof of God''s grace, -- that he was pleased to bestow on Jonah his former dignity and honor. He was indeed unworthy of the common light, but God not only restored him to life, but favored him again with the office and honor of a prophet. This, as I have said, Jonah obtained through the wonderful and singular favor of God. As he had previously fled, and by disobedience deprived himself in a manner of all God''s favor, the recovery of his prophetic office was certainly not obtained through his own merit.

It must, in the first place, be observed, that this phrase, The word of Jehovah came the second time, ought to be noticed; for the word of God comes to men in different ways. God indeed addresses each of us individually; but he spoke to his Prophets in a special manner; for he designed them to be witnesses and heralds of his will. Hence, whenever God sets a man in some peculiar office, his word is said to come to him: as the word of God is addressed to magistrates because they are commanded to exercise the power committed to them; so also the word of God ever came to the Prophets, because it was not lawful for them to thrust in themselves without being called.

The command now follows, Arise, go to Nineveh, to that great city, and preach there the preaching which I command thee. God again repeats what we have observed at the be ginning, -- that Nineveh was a great city, that Jonah might provide himself with an invincible courage of mind, and come there well prepared: for it often happens, that many boldly undertake an office, but soon fail, because difficulties had not been sufficiently foreseen by them. Hence, when men find more hardships than they thought of at the beginning, they nearly faint, at least they despond. The Lord, therefore, expressly foretold Jonah how difficult would be his employment; as though he said, "I send thee, a man unknown, and of no rank, and a stranger, to denounce ruin on men, not a few in number, but on a vast multitude, and to carry on a contest with the noblest city, and so populous, that it may seem to be a region of itself."

We now then understand why this character of the city was added; it was, that Jonah might gird up himself for the contest, that he might not afterwards fail in the middle of his course.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 32, 4, 1, NULL, 'jonah-4', 'John Calvin', 'Commentaries', E'1. But it displeased Jonah exceedingly, and he was very angry.

1. Et displicuit Jonae dolore magno, et succensuit apud se.

Jerome commends this grief of Jonah, and compares it to the holy zeal of Paul when he wished himself to be an anathema for his brethren, (Romans 9:3:) for he denies that he grieved because God had showed mercy to so illustrious a city; but because the conversion of the Gentiles was a certain presage of the destruction of the chosen people. As then Jonah perceived as in a mirror the near ruin of Israel, he on this account grieved, if we believe Jerome: but this notion is extremely frivolous; for, immediately after, God reproved Jonah. What then will the foolish and puerile apology of Jerome avail the Prophet, since God has declared that he acted perversely in grieving? Nay, the dullness of Jerome is thus become evident; (thus indeed do I speak of a man, who, though learned and laborious, has yet deprived himself of that praise, which otherwise he might have justly earned.) His wayward disposition everywhere betrayed itself; and he is evidently disproved in this very context, where Jonah shows clearly that the cause of his grief was another, even this, -- that he was unwilling to be deemed a false or a lying prophet: hence was his great grief and his bitterness. And this we see, had God not expressed his mind, was unjust and inconsistent with every reason.

We may then conclude that Jonah was influenced by false zeal when he could not with resignation bear that the city of Nineveh should have been delivered from destruction: and he also himself amplifies the greatness of his sin. He might have said, in one word, that it displeased Jonah; but not satisfied with this simple form, he adds, that he felt great displeasure or grief; and he afterwards adds, that he was very angry. Though the beginning may not have been wrong, yet excess was sinful. But he confesses that there was excess, and want of moderation in his grief: since then he accuses himself in plain words what good is it, by false and invented pretenses, to cover what we clearly see cannot be excused? But that it may be more evident why the deliverance of the city of Nineveh displeased Jonah, let us go on with the context -- __________________________________________________________________

The two verbs used here are evidently to be construed as impersonals. The most literal rendering would be thus, -- "And it was an evil to Jonah, a great evil; and wrath was to him," or, "he was wroth." Evil means often grief or distress, and so it is here: but the verb chrh, properly rendered in our version, "very angry," seldom if ever, means grief. It is sometimes rendered "grieved" in our version; but in every instance that I can find, it means the grief of anger or displeasure.', false, false, 'sourced', 'published');
