-- Calvin commentary INSERT — James (batch 1, rows 1-5)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 59, 1, 1, NULL, 'james-1', 'John Calvin', 'Commentaries', E'1 To the twelve tribes. When the ten tribes were banished, the Assyrian king placed them in different parts. Afterwards, as it usually happens in the revolutions of kingdoms (such as then took place,) it is very probable that they moved here and there in all directions. And the Jews had been scattered almost unto all quarters of the world. He then wrote and exhorted all those whom he could not personally address, because they had been scattered far and wide. But that he speaks not of the grace of Christ and of faith in him, the reason seems to be this, because he addressed those who had already been rightly taught by others; so that they had need, not so much of doctrine, as of the goads of exhortations. 2 All joy. The first exhortation is, to bear trials with a cheerful mind. And it was especially necessary at that time to comfort the Jews, almost overwhelmed as they were with troubles. For the very name of the nation was so infamous, that they were hated and despised by all people wherever they went; and their condition as Christians rendered them still more miserable, because they held their own nation as their most inveterate enemies. At the same time, this consolation was not so suited to one time, but that it is always useful to believers, whose life is a constant warfare on earth. But that we may know more fully what he means, we must doubtless take temptations or trials as including all adverse things; and they are so called, because they are the tests of our obedience to God. He bids the faithful, while exercised with these, to rejoice; and that not only when they fall into one temptation, but into many, not only of one kind, but of various kinds. And doubtless, since they serve to mortify our flesh, as the vices of the flesh continually shoot up in us, so they must necessarily be often repeated. Besides, as we labor under diseases, so it is no wonder that different remedies are applied to remove them. The Lord then afflicts us in various ways, because ambition, avarice, envy, gluttony, intemperance, excessive love of the world, and the innumerable lusts in which we abound, cannot be cured by the same medicine. When he bids us to count it all joy, it is the same as though he had said, that temptations ought to be so deemed as gain, as to be regarded as occasions of joy. He means, in short, that there is nothing in afflictions which ought to disturb our joy. And thus, he not only commands us to bear adversities calmly, and with an even mind, but shews us that this is a reason why the faithful should rejoice when pressed down by them. It is, indeed, certain, that all the senses of our nature are so formed, that every trial produces in us grief and sorrow; and no one of us can so far', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 59, 2, 1, NULL, 'james-2', 'John Calvin', 'Commentaries', E'1 Have not the faith, etc., with respect of persons. He means that the respect of persons is inconsistent with the faith of Christ, so that they cannot be united together, and rightly so; for we are by faith united into one body, in which Christ holds the primacy. When therefore the pomps of the world become preeminent so as to cover over what Christ is, it is evident that faith hath but little vigor.

In rendering tos doxes, "on account of esteem," (ex opinione,) I have followed Erasmus; though the old interpreter cannot be blamed, who has rendered it "glory," for the word means both; and it may be fitly applied to Christ, and that according to the drift of the passage. For so great is the brightness of Christ, that it easily extinguishes all the glories of the world, if indeed it irradiates our eyes. It hence follows, that Christ is little esteemed by us, when the admiration of worldly glory lays hold on us. But the other exposition is also very suitable, for when the esteem or value of riches or of honors dazzles our eyes, the truth is suppressed, which ought alone to prevail. To sit becomingly means to sit honorably.

4 Are ye not then partial in yourselves? or, are ye not condemned in yourselves. This may be read affirmatively as well as interrogatively, but the sense would be the same, for he amplifies the fault by this, that they took delight and indulged themselves in so great a wickedness. If it be read interrogatively, the meaning is, "Does not your own conscience hold you convicted, so that you need no other judge?" If the affirmative be preferred, it is the same as though he had said, "This evil also happens, that ye think not that ye sin, nor know that your thoughts are so wicked as they are." __________________________________________________________________

It is commonly admitted to be an interrogatory sentence: "And do ye not make a difference among (or, in) yourselves, and become judges, having evil thoughts?" literally, "judges of evil thoughts," it being, as they say, the genitive case of possession. Or the words may be rendered, "and become judges of evil (or, false) reasonings?" or as Beza renders the sentence, "and become judges, reasoning falsely," concluding that the rich man was good and the poor man bad. It is said by Beza and others, that diakrinomai never means to be judged or condemned, but to distinguish, to discriminate, to make a difference, and also to contend and to doubt. The difference made here was the respect of persons that was shewn, and they made this difference in themselves, in their own minds, through the perverse or false thoughts or reasonings which they entertained. But it appears that these preferences were shewn, not to the members of the Church, but to such strangers as might happen to come to their assemblies.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 59, 3, 1, NULL, 'james-3', 'John Calvin', 'Commentaries', E'1 Be not many masters. The common and almost universal interpretation of this passage is, that the Apostle discourages the desire for the office of teaching, and for this reason, because it is dangerous, and exposes one to a heavier judgment, in case he transgresses: and they think that he said, Be not many masters, because there ought to have been some. But I take masters not to be those who performed a public duty in the Church, but such as took upon them the right of passing judgment upon others: for such reprovers sought to be accounted as masters of morals. And it has a mode of speaking usual among the Greeks as well as Latins, that they were called masters who superciliously animadverted on others.

And that he forbade them to be many, it was done for this reason, because many everywhere did thrust in themselves; for it is, as it were, an innate disease in mankind to seek reputation by blaming others. And, in this respect, a twofold vice prevails -- though few excel in wisdom, yet all intrude indiscriminately into the office of masters; and then few are influenced by a right feeling, for hypocrisy and ambition stimulate them, and not a care for the salvation of their brethren. For it is to be observed, that James does not discourage those brotherly admonitions, which the Spirit so often and so much recommends to us, but that immoderate desire to condemn, which proceeds from ambition and pride, when any one exalts himself against his neighbor, slanders, carps, bites, and malignantly seeks for what he may turn to a sinister purpose: for this is usually done when impertinent censors of this kind insolently boast themselves in the work of exposing the vices of others.

From this outrage and annoyance James recalls us; and he adds a reason, because they who are thus severe towards others shall undergo a heavier judgment: for he imposes a hard law on himself, who tries the words and deeds of others according to the rule of extreme rigor; nor does he deserve pardon, who will pardon none. This truth ought to be carefully observed, that they who are too rigid towards their brethren, provoke against themselves the severity of God.

2 For in many things we offend all. This may be taken as having been said by way of concession, as though he had said, "Be it that thou findest what is blamable in thy brethren, for no one is free from sins; but dost thou think that thou art perfect who usest a slanderous and virulent tongue?" But James seems to me to exhort us by this argument to meekness, since we are ourselves also surrounded with many infirmities; for he acts unjustly who denies to others the pardon he needs himself.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 59, 4, 1, NULL, 'james-4', 'John Calvin', 'Commentaries', E'1 From whence come wars. As he had spoken of peace, and had reminded them that vices are to be exterminated in such a way as to preserve peace, he now comes to their contentions, by which they created confusion among themselves; and he shews that these arose from their invidious desires and lusts, rather than from a zeal for what was just and right; for if every one observed moderation, they would not have disturbed and annoyed one another. They had their hot conflicts, because their lusts were allowed to prevail unchecked.

It hence appears, that greater peace would have been among them, had every one abstained from doing wrong to others; but the vices which prevailed among them were so many attendants armed to excite contentions. He calls our faculties members. He takes lusts as designating all illicit and lustful desires or propensities which cannot be satisfied without doing injury to others.

2 Ye lust, or covet, and have not. He seems to intimate that the soul of man is insatiable, when he indulges wicked lusts; and truly it is so; for he who suffers his sinful propensities to rule uncontrolled, will know no end to his lust. Were even the world given to him, he would wish other worlds to be created for him. It thus happens, that men seek torments which exceed the cruelty of all executioners. For that saying of Horace is true:

The tyrants of Sicily found no torment greater than envy.

Some copies have phoneuete, "ye kill;" but I doubt not but that we ought to read, phthoneite, "ye envy," as I have rendered it; for the verb, to kill, does in no way suit the context. Ye fight: he does not mean those wars and fightings, which men engage in with drawn swords, but the violent contentions which prevailed among them. They derived no benefit from contentions of this kind, for he affirms that they received the punishment of their own wickedness. God, indeed, whom they owned not as the author of blessings, justly disappointed them. For when they contended in ways so unlawful, they sought to be enriched through the favor of Satan rather than through the favor of God. One by fraud, another by violence, one by calumnies, and all by some evil or wicked arts, strove for happiness. They then sought to be happy, but not through God. It was therefore no wonder that they were frustrated in their efforts, since no success can be expected except through the blessings of God alone.

3 Ye seek and receive not. He goes farther: though they sought, yet they were deservedly denied; because they wished to make God the minister of their own lusts. For they set no bounds to their wishes, as he had commanded; but gave unbridled license to themselves, so as to ask those things of which man, conscious of what is right, ought especially to be ashamed.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 59, 5, 1, NULL, 'james-5', 'John Calvin', 'Commentaries', E'1 Go to now. They are mistaken, as I think, who consider that James here exhorts the rich to repentance. It seems to me to be a simple denunciation of God''s judgment, by which he meant to terrify them without giving them any hope of pardon; for all that he says tends only to despair. He, therefore, does not address them in order to invite them to repentance; but, on the contrary, he has a regard to the faithful, that they, hearing of the miserable and of the rich, might not envy their fortune, and also that knowing that God would be the avenger of the wrongs they suffered, they might with a calm and resigned mind bear them. But he does not speak of the rich indiscriminately, but of those who, being immersed in pleasures and inflated with pride, thought of nothing but of the world, and who, like inexhaustible gulfs, devoured everything; for they, by their tyranny, oppressed others, as it appears from the whole passage. Weep and howl, or, Lament, howling. Repentance has indeed its weeping, but being mixed with consolation, it does not proceed to howling. Then James intimates that the heaviness of God''s vengeance will be so horrible and severe on the rich, that they will be constrained to break forth into howling, as though he had said briefly to them, "Woe to you!" But it is a prophetic mode of speaking: the ungodly have the punishment which awaits them set before them, and they are represented as already enduring it. As, then, they were now flattering themselves, and promising to themselves that the prosperity in which they thought themselves happy would be perpetual, he declared that the most grievous miseries were nigh at hand. 2 Your riches. The meaning may be twofold: -- that he ridicules their foolish confidence, because the riches in which they placed their happiness, were wholly fading, yea, that they could be reduced to nothing by one blast from God -- or that he condemns as their insatiable avarice, because they heaped together wealth only for this, that they might perish without any benefit. This latter meaning is the most suitable. It is, indeed, true that those rich men are insane who glory in things so fading as garments, gold, silver, and such things, since it is nothing else than to make their glory subject to rust and moths; and well known is that saying "What is ill got is soon lost;" because the curse of God consumes it all, for it is not right that the ungodly or their heirs should enjoy riches which they have snatched, as it were, by violence from the hand of God. But as James enumerates the vices of which the rich brought on themselves the calamity which he mentions, the context requires, as I think, that we should say, that what he condemns here is the extreme rapacity of the rich, in retaining everything they could lay hold on, that it might rot', false, false, 'sourced', 'published');
