-- Calvin commentary INSERT — Joshua (batch 2, rows 11-20)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 11, 1, NULL, 'joshua-11', 'John Calvin', 'Commentaries', E'1. And it came to pass when Jabin, etc In this new league also we have a bright manifestation of the more than paternal care of God, in warding off dangers from his people, and also in assisting their weakness by kindness and indulgence. Had Jabin, with the confederates of whom mention is now made, openly declared himself the ally of the neighboring kings, a much more formidable war would have broken out against the Israelites, and greater solicitude and anxiety must have seized their minds. It would, indeed, have been easy for the Lord, as well to put all their forces at once to the rout, as to dissipate all fear and dread of them. He was unwilling, however, to press beyond measure his own people, who were otherwise feeble, lest the excessive numbers of the enemy should strike them with terror, and drive them to despair. He therefore kept the many nations, whose interest it was to have rushed hastily to arms, in a state of lethargy and amazement, until the chosen people had been animated by signal victories, to carry on the wars which still remained. They pillage and devastate a large territory, and leave it destitute of inhabitants and stript of resources. None of the neighboring powers, who were afterwards to act on the offensive, makes the least movement. The Israelites revisit their wives and children in safety. When they had gathered courage, and were ready for a new war, suddenly a very large army appears, composed of different nations, who had hitherto, by remaining quiet, furnished opportunity for victory. Their coming thus forward at a later period, was the same as if they had entered into a truce. Thus God not only fought for his chosen people, but by dividing the enemy, increased their strength manifold.

How formidable must the onset have been, had not the Israelites been gradually trained to confidence in battle, and at the same time experienced the manifest assistance of God? First, their numbers are compared to the sand of the sea, and then they have horses and chariots. As the Israelites were altogether destitute of cavalry, it is strange that they were not terrified at this array. Therefore they were gradually brought forward till they were able to bear it. For, in their former battles, he had only exercised them by a kind of pleasing preludes. It may be added, that the Lord had, by several victories, ever and anon borne testimony to his power, that they might not think more lightly of it than was meet. Had all their enemies been routed at once, they might, indeed, have magnificently celebrated the praises of God, but they might also have easily lost the remembrance of them. It was necessary, therefore, that repeated proofs distinct and apart from each other, should be held forth to their view, lest they might attribute one victory to a stroke of fortune.

6.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 12, 1, NULL, 'joshua-12', 'John Calvin', 'Commentaries', E'1. NOW these are the kings, etc This chapter does not need a lengthened exposition, as it only enumerates the kings of whose territories the Israelites gained possession. Two of them are beyond the Jordan, Og and Sihon, whose rule was extensive; in the land of Canaan there are thirty-one. But though each of those now summarily mentioned was previously given more in detail, there is very good reason for here placing before our eyes as it were a living picture of the goodness of God, proving that there had been a complete ratification and performance of the covenant made with Abraham as given in the words, "Unto thy seed will I give this land." (Genesis 12:7; Genesis 13:15; Genesis 15:18) This living image of the grace of God is here set before us as if the reality were actually present. Joshua was eighty years of age when he entered the land. In this aged man how could there be so much vigor as to fit him for carrying on so many wars and enduring the fatigues of warfare, had not celestial virtue furnished him with more than mortal strength? And were not his uninterrupted career of victory, his success under all circumstances, the ease, free from doubt and uncertainty, with which he stormed cities, the rapidity of his movements, and his inflexible firmness -- were not all these clear evidences of the hand of God, just as if it had appeared from heaven?

The object of defining the countries by their boundaries was to give a better display of the divine power by setting forth their extent; but this of course was only for those to whom their site was known. Hence, for any one not acquainted with the geography to dwell upon the names, would be vain and foolish curiosity. I admit, indeed, that it is useful to pay attention to the places with which, from their being often mentioned in Scripture, our knowledge ought to be somewhat more familiar, as when the boundaries are fixed by the brook Jabok, in the district of Lebanon and the lake of Gennesaret, here called the Sea of Cineroth, and elsewhere Cinereth. For a slight attention will help us to understand the narrative. If we cannot go farther, let us leave those who are better skilled to give a more searching discussion of what is beyond our reach. But although the dominions of these petty kings were narrow and not very populous, we shall however see that many towns were annexed to their principal cities; their number may be ascertained especially from what is said of the lot of the Levites. On the other hand, if we reflect how one small territory could receive and maintain old men, women, and children, nay, a great part of the people with their domestic animals, we cannot fail to admire the inestimable goodness of God which prevented all things from being thrown into complete and irremediable confusion.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 13, 1, NULL, 'joshua-13', 'John Calvin', 'Commentaries', E'1. Now Joshua was old, etc Since we have seen above that the land was pacified by the subjugation of thirty-one kings, it is probable that some cessation now took place for the purpose of resting from their fatigues, lest the people should be worn out by continual service. Nor could that justly be blamed, provided they rested only for a time and continued always intent on the goal set before them. But lest that intermission which was given for the purpose of recruiting new vigor might prove an occasion of sloth, the Lord employs a new stimulus to urge them to proceed. For he orders the whole inheritance to be divided into tribes, and the whole line of the Mediterranean coast which was possessed by the enemy to be put into the lot. A division of this kind might indeed seem absurd and ludicrous, nay, a complete mockery, seeing they were dealing among themselves with the property of others just as if it had been their own. But the Lord so appointed for the best of reasons. First, they might have cast away the hope of the promise and been contented with their present state. Nay, although after the lot was cast they had security in full for all that God had promised, they by their own cowardice, as far as in them lay, destroyed the credit of his words. Nor was it owing to any merit of theirs that his veracity did not lie curtailed and mutilated. The allocation by lot must therefore have been to them an earnest of certain possession so as to keep them always in readiness for it. Secondly, Those who happened to have their portion assigned in an enemy''s country, inasmuch as they were living in the meanwhile as strangers on precarious hospitality beyond their own inheritance, must have acted like a kind of task-masters spurring on the others. And it surely implied excessive stupor to neglect and abandon what had been divinely assigned to them. We now see to what intent the whole land behooved to be divided by lot, and the seat of each tribe allocated. It was also necessary that this should be done while Joshua was alive, because after his death the Israelites would have been less inclined to obedience, for none of his successors possessed authority sufficient for the execution of so difficult a task. Moreover, as God had already by the mouth of Moses commanded it to be done, had he not performed the business thus committed to him, the whole work might have gone to wreck when the lawful minister was removed. Although the exact time is not stated, still it is probable that as there was no hope that while Joshua continued alive the people would again take up arms with the view of giving a wider extent to their boundaries, he then only attempted to divide the land, as if he were proclaiming and promising, by a solemn attestation, that the distribution would certainly', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 14, 1, NULL, 'joshua-14', 'John Calvin', 'Commentaries', E'1. And these are the countries, etc He now proceeds to the land of Canaan, from which nine tribes and a half were to obtain their lots. And he will immediately break off the thread of the narrative, as we shall see. Yet the transition is seasonably made from that region whose situation was different, to let the reader know that the discourse was to be concerning the land of Canaan, which was to be divided by lot. We have said that Joshua and Eleazar not only divided what the Israelites had already acquired, but trusting in the promise of God, confidently included whatever he had promised to his people, just as if they had been in actual possession of it. We shall see, indeed, that the division was not all at once made complete, but when the first lot turned up in favor of Judah, the turns of the others were left in hope. Here a difficult question arises. How can it be said that the distribution of the land was made by Joshua, Eleazar, and the princes, if lots were cast? For the lot is not regulated by the opinion or the will or the authority of man. Should any one answer, that they took charge and prevented any fraud from being committed, the difficulty is not removed, nay, this evasion will be refuted from the context. It is to be known, therefore, that they were not selected simply to divide the land by lot, but also afterwards to enlarge or restrict the boundaries of the tribes by giving to each its due proportion. That this business could not be accomplished by a naked lot is very apparent. For while, according to human ideas, nothing is more fortuitous than the result of a lot, it was not known whether God might choose to place the half tribe of Manasseh where the tribe of Judah obtained its settlement, or whether Zebulun might not occupy the place of Ephraim. Therefore they were not at liberty at the outset to proceed farther than to divide the land into ten districts or provinces. In this way, however, the space belonging to each would remain indefinite. For had an option been given to each, some would have chosen to fix themselves in the center, others would have preferred a quiet locality, while others would have been guided in their choice by the fertility of the soil, or the climate and beauty of the scenery. But the lot placed the tribe of Judah, as it were, at the head, while it sent that of Zebulun away to the seashore, placed the tribe of Benjamin adjacent to that of Judah, and removed that of Ephraim to a greater distance. In short, the effect of the lot was that ten divisions fell out from Egypt towards Syria, and from the north quarter to the Mediterranean Sea, making some neighbors to the Egyptians, and giving to others maritime positions, to others hilly districts, to others intervening valleys.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 15, 1, NULL, 'joshua-15', 'John Calvin', 'Commentaries', E'1. I have already premised, that I would not be very exact in delineating the site of places, and in discussing names, partly because I admit that I am not well acquainted with topographical or chorographic science, and partly because great labor would produce little fruit to the reader; nay, perhaps the greater part of readers would toil and perplex themselves without receiving any benefit. With regard to the subject in hand, it is to be observed, that the lot of the tribe of Judah not only falls on elevated ground, the very elevation of the territory, indicating the dignity of the future kingdom, but a similar presage is given by its being the first lot that turns up. What had already been obtained by arms, they begin to divide. The names of the ten tribes are cast into the urn. Judah is preferred to all the others. Who does not see that it is raised to the highest rank, in order that the prophecy of Jacob may be fulfilled? Then within the limits here laid down, it is well known that there were rich pastures, and vineyards celebrated for their productiveness and the excellence of their wines. In this way, while the lot corresponds with the prophecy of Jacob, it is perfectly clear that it did not so happen by chance; the holy patriarch had only uttered what was dictated by the Spirit. If any are better skilled in places, a more minute investigation will be pleasant and useful to them. But lest those who are less informed feel it irksome to read unknown names, let them consider that they have obtained knowledge of no small value, provided they bear in mind the facts to which I have briefly and summarily adverted -- that the tribe of Judah was placed on elevated ground, that it might be more conspicuous than the others, until the scepter should arise from it -- and that a region of fruitful vineyards and rich pastures was assigned to his posterity -- and, finally, all this was done, in order that the whole people might recognize that there was nothing of the nature of chance in the turning up of a lot, which had been foretold three centuries before. Besides, it is easy for the unlearned to infer from the long circuit described, that the territory thus allocated to one tribe was of great extent. For although some diminution afterwards took place, its dominions always continued to be the largest. It is necessary, however, to bear in mind what I formerly observed, that nothing else was determined by the lot than that the boundary of the children of Judah was to be contiguous to the land of Edom and the children of Sin, and that their boundary, in another direction, was to be the river of Egypt and the Mediterranean Sea -- that those who had been selected to divide the country proceeded according to the best of their judgment, in proportioning the quantity of', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 16, 1, NULL, 'joshua-16', 'John Calvin', 'Commentaries', E'1. And the lot of the children of Joseph fell, etc The sacred writer first states what the lot was which fell to the two children of Joseph, and then describes the lot of Ephraim. It is strange, however, that when the half of the tribe of Manasseh had already been settled beyond the Jordan, more words are employed in describing the remaining half than in describing the whole of the inheritance of the tribe of Ephraim, though the latter was the more populous, and justly claimed for itself a larger territory. But the longer detail given concerning the posterity of Manasseh is owing to particular circumstances. First, the writer repeats how a settlement had been given them without lot in the country of Basan. Secondly, he mentions the ratification by Joshua of the command which Moses had given by divine authority in regard to the daughters of Selophead. Seeing, then, there was no doubt in regard to the boundaries of Ephraim, and there was no danger of dispute, their allocation is only briefly glanced at.

But here a new question arises. When the right of primogeniture had passed from Manasseh to Ephraim, how did the posterity of that tribe which had precedence in rank obtain their cities among the children of Manasseh? For theirs seems in this way to have been the inferior condition. My explanation is this, When the portion of Manasseh was too extensive in proportion to the amount of population, a calculation was made, and certain cities were deducted to complete the just share of the tribe of Ephraim; not that they were mixed up with the children of Manasseh, to hold their dwellings among them by a precarious tenure, but their boundaries were merely extended in the direction of the Manassites whom a narrower possession might suffice.

In the end of the chapter, Ephraim is severely censured for his effeminacy in not having expelled the Canaanites from Gezer. For had they proceeded in a manly and hearty manner to make good their right to the land which had fallen to them by lot, the victory was in their hands. There would have been no temerity in the attempt, since the decision of the lot was as valid as if the Lord himself had stretched forth his hand from heaven. But their disgraceful sloth is more clearly expressed and their culpability greatly heightened by the fact, that they made tributaries of those with whom it was not lawful to enter into any kind of arrangement. Seeing, then, God had distinctly forbidden his people to transact business of any kind with those nations, and least of all to enter into pactions with them, stipulating for their pardon and safety, the Ephraimites sinned much more grievously in exacting tribute than if they had tolerated them without paction.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 17, 1, NULL, 'joshua-17', 'John Calvin', 'Commentaries', E'5. And there fell ten portions to Manasseh, etc The children of Manasseh are in this passage classed under seven stems. Machir, the first-born, is placed apart; the other six follow. Here the question arises, How was the inheritance divided into ten parts? Some expositors cunningly disguise the difficulty; others, because they are unable to solve it, indulge in the merest trifling. It is certainly very absurd that four portions should be given to five daughters; and it is not a whit more congruous that their share should be doubled because their father was the first-born. It is beyond all controversy, that Gilead, son of Machir, and great-grandfather of the females of whom we are now speaking, chose his settlement in mount Gilead and Bashan. Therefore, seeing he had already obtained an inheritance by privilege without lot, he ought not to have obtained one by lot in the land of Canaan, unless perhaps he settled only a part of his family beyond the Jordan. For Hepher was one of his sons, but not the only one; and likewise the offspring of five other brothers might be distinguished into several heads according to the number of which the allocation by lot might be made. For it is not known in what degree families whose portion fell in the land of Canaan were taken. And all we read here is, that ten lots were east among the sons of Manasseh in addition to the country which they had formerly acquired for themselves beyond the Jordan. It is thus vain to dispute concerning the number, which cannot be ascertained with certainty from the present narrative, because the first thing necessary to be known is the exact number of families to whom the division was common. Nay, it is not impossible that the daughters of Selophead obtained their patrimony there. They are said, indeed, to have dwelt among the brethren of their father; but the place is not given. Be this as it may, I have no doubt that mutual equity was observed, and that after provision was made for others, the land which had been submitted to lot was distributed among ten families whose names are here omitted. __________________________________________________________________

Latin, "Quidam astute hunc scrupulum dissimulant." French, "Aucuns y vent a la finesse ne faisans nulle mention de ceste difficulte;" "Some have recourse to finesse, making no mention of this difficulty." -- Ed. __________________________________________________________________

11. And Manasseh had in Issachar and in Asher Bethshean and her towns, and Ibleam and her towns, and the inhabitants of Dor and her towns, and the inhabitants of Endor and her towns, and the inhabitants of Taanach and her towns, and the inhabitants of Megiddo and her towns, even three countries.

11. Fuitque ipsi Manasse in Issachar, et in Aser, Beth-sean, et oppida ejus: et Ibleam, et oppida ejus: et habitatores Dor, et oppida ejus: et habitatores Endor, et oppida ejus: et habitatores Thaanach, et oppida ejus: et habitatores Magiddo, et oppida ejus, tres regiones.

12.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 18, 1, NULL, 'joshua-18', 'John Calvin', 'Commentaries', E'1. And the whole congregation of the children of Israel, etc Here we have a narrative of the celebrated convention held in Shiloh, where it was deliberated, as to the casting of the remaining lots. For although with pious zeal they had attempted the casting of lots, yet the proceeding had been interrupted, as if victory behooved to precede the distribution which depended solely on the mouth of God. They assemble, therefore, in Shiloh to determine what was necessary to be done in future. And there is no doubt that Joshua summoned this meeting in order to raise them from their lethargy. For they do not come forward spontaneously with any proposal, but he begins with upbraiding them with having been sluggish and remiss in entering on the inheritance which God had bestowed upon them. It is easy to infer from his speech that they had shown great alacrity at the outset, but that there had been no perseverance.

And yet that obedience, which shortly after grew languid, was honored with the approbation of the Holy Spirit. It is to be observed that the people are blamed, not for neglecting to proceed to the lot, but for not occupying the inheritance divinely offered to them. And, certainly, as the distribution by lot was a sign of confidence, so each district which fell out to each was a sure and faithful pledge of future possession; for the Lord was by no means deluding them in assigning to each his portion.

The word dphh, which I have translated "to cease," signifies also to be remiss or feeble. He charges them, therefore, with base heartlessness, in that while the full time for routing the enemy had arrived, they by their delays retard and suspend the effect of the divine goodness. For had they been contented with the bare lot, and faithfully embraced the results which it gave, they would doubtless have been prompt and expeditious in carrying on the war, nay, would have hastened like conquerors to a triumph.

The ark is said to have been stationed at Shiloh, not only that the consultation might be graver and more sacred, as held in the presence of God, but because it was a completely subjugated place, and safe from all external violence and injury. For it behooved to be their special care to prevent its exposure to sudden assault. No doubt the hand of God would have been stretched to ward off attacks of the enemy from any quarter; still, however, though God dwelt among them, they were to be regarded as its guardians and attendants.

But although a station for the ark was then chosen, it was not a perpetual abode, but only a temporary lodging. For it was not left to the will or suffrages of the people to fix the seat where God should dwell, but they behooved to wait for the period so often referred to in the Law, when he was to establish the memorial of his name elsewhere.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 19, 1, NULL, 'joshua-19', 'John Calvin', 'Commentaries', E'9. Out of the portion of the children of Judah, etc The praise of moderation is due to the tribe of Judah for not contending that the abstraction of any part of the inheritance already assigned to them was unjust. They might easily have obtruded the name of God, and asserted that it was only by his authority they had obtained that settlement. But as it is decided by the common consent of all the tribes that more has been given to them than they can possess without loss and injury to the others, they immediately desist from all pretext for disputing the matter. And it is certain that if they had alleged the authority of God, it would have been falsely and wickedly, inasmuch as though their lot had been determined by him in regard to its situation, an error had taken place with regard to its extent, their limits having been fixed by human judgment wider than they ought. Therefore, acknowledging that it would have been wrong to give them what would occasion loss to others, they willingly resign it, and give a welcome reception to their brethren, who must otherwise have remained without inheritance, nay, submit to go shares with them in that which they supposed they had acquired beyond controversy. __________________________________________________________________

10. And the third lot came up for the children of Zebulun according to their families: and the border of their inheritance was unto Sarid:

10. Ascendit autem sors tertia filiis Zabulon per familias suas: et fuit terminus haereditatis eorum usque ad Sarid.

11. And their border went up toward the sea, and Maralah, and reached to Dabbasheth, and reached to the river that is before Jokneam;

11. Ascenditque terminus eorum ad mare: et Maralah, et pertingit ad Dabbaseth: pervenitque ad flumen quod est e regione Jocneam.

12. And turned from Sarid eastward toward the sunrising unto the border of Chislothtabor, and then goeth out to Daberath, and goeth up to Japhia,

12. Revertiturque a Sarid ad orientem, id est, ad ortum solis, ad terminum Chisloth-Thabor, et illinc egreditur ad Dobrath, et ascendit in Japhia.

13. And from thence passes on along on the east to Gittahhepher, to Ittahkazin, and goeth out to Remmonmethoar to Neah;

13. Inde praeterea transit ad orientem, ad ortum, ad Githah-Hepher, et ad Ihtah-casin: et illinc exit in Rimmon, et gyrat ad Neah:

14. And the border compasseth it on the north side to Hannathon: and the outgoings thereof are in the valley of Jiphthahel:

14. Gyrat item idem terminus ab aquilone ad Hannathon: suntque egressus ejus ad vallem Iphthael.

15. And Kattath, and Nahallal, and Shimron, and Idalah, and Bethlehem: twelve cities with their villages.

15. Et Catthath, et Nahalal, et Simron, et Idalah, et Bethlehem: urbes duodecim, et villae earum.

16. This is the inheritance of the children of Zebulun according to their families, these cities with their villages.

16. Haec est haereditas filiorum Zabulon per familias suas: urbes istae, et villae earum.

17.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 6, 20, 1, NULL, 'joshua-20', 'John Calvin', 'Commentaries', E'1. The Lord also spoke unto Joshua, etc In the fact of its not having occurred to their own minds, to designate the cities of refuge, till they were again reminded of it, their sluggishness appears to be indirectly censured. The divine command to that effect had been given beyond the Jordan. When the reason for it remained always equally valid, why do they wait? Why do they not give full effect to that which they had rightly begun? We may add, how important it was that there should be places of refuge for the innocent, in order that the land might not be polluted with blood. For if that remedy had not been provided, the kindred of those who had been killed would have doubled the evil, by proceeding without discrimination to avenge their death. It certainly did not become the people to be idle in guarding the land from stain and taint. Hence we perceive how tardy men are, not only to perform their duty, but to provide for their own safety, unless the Lord frequently urge them, and prick them forward by the stimulus of exhortation. But that they sinned only from thoughtlessness, is apparent from this, that they are forthwith ready to obey, neither procrastinating nor creating obstacles or delays to a necessary matter, by disputing the propriety of it.

The nature of the asylum afforded by the cities of refuge has been already explained. It gave no impunity to voluntary murder, but if any one, by mistake, had slain a man, with whom he was not at enmity, he found a safe refuge by fleeing to one of these cities destined for that purpose. Thus God assisted the unfortunate, and prevented their suffering the punishment of an atrocious deed, when they had not been guilty of it. Meanwhile respect was so far paid to the feelings of the brethren and kindred of the deceased, that their sorrow was not increased by the constant presence of the persons who had caused their bereavement. Lastly, the people were accustomed to detest murder, since homicide, even when not culpable, was followed by exile from country and home, till the death of the high priest. For that temporary exile clearly showed how precious human blood is in the sight of God. Thus the law was just, equitable, and useful, as well in a public as in a private point of view. But it is to be briefly observed, that everything is not here mentioned in order. For one who had accidentally killed a man might have remained in safety, by sisting himself before the court to plead his cause, and obtaining an acquittal, after due and thorough investigation, as we explained more fully in the books of Moses, when treating of this matter.

7. And they appointed Kedesh, etc The Hebrew word Kedesh here used, signifies also to fit and consecrate. Accordingly, I interpret, that cities were selected according as common use required.', false, false, 'sourced', 'published');
