-- Calvin commentary INSERT — Luke (batch 2, rows 11-20)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 11, 1, NULL, 'luke-11', 'John Calvin', 'Commentaries', E'9. Pray ye therefore thus: Our Father who art in heaven, may thy name be sanctified. 10. May thy kingdom come. May thy will be done, as in heaven, so also in the earth. 11. Give us to-day our daily bread. 12. And forgive us our debts, as we also forgive our debtors. 13. And lead us not into temptation, but deliver us from evil. For thine is the kingdom, and the power, and the glory for ever. Amen.

1. And it happened, while he was praying in a certain place, when he ceased, one of his disciples said to him, Lord, teach us to pray, as John also taught his disciples. 2. And he saith to them, When you pray, say, Our Father who art in heaven, may thy name be sanctified. May thy kingdom come. May thy will be done, as in heaven, so also in the earth. 3. Give us to.day our daily bread. 4. And forgive us our sins, as we also forgive every one who owes us. And lead us not into temptation, but deliver us from evil.

It is uncertain whether this form was once only or twice delivered by Christ to his disciples. Some think that the latter is more probable; because Luke says that he was requested to do it, while Matthew represents him as teaching it of his own accord. But as we have said, that Matthew collects all the leading points of doctrine, in order that the whole amount of them may be more clearly perceived by the readers when they are placed in close succession, it is possible that Matthew may have omitted to mention the occasion which is related by Luke. On this subject, however, I am unwilling to debate with any person.

Luke 11:1 As John also taught his diciples. John delivered to his disciples a particular form of prayer; and he did so, in my opinion, because the time required it. The state of affairs among the Jews was, at that time, exceedingly corrupted. Every thing connected with religion had so miserably fallen, that we need not be surprised to find few among them, by whom prayer was offered in a proper manner. Besides, it was proper, that the minds of believers should be excited, by prayer, to hope and desire the promised redemption, which was at hand. John might, therefore, have collected, out of various passages of Scripture, a certain prayer adapted to the time, and approaching more nearly to the spiritual kingdom of Christ, which had already begun to be revealed.

Matthew 6:9 Do ye therefore pray thus Instead of this Luke says, when ye pray, say: though Christ does not enjoin his people to pray in a prepared form of words, but only points out what ought to be the object of all our wishes and prayers. He embraces, therefore, in six petitions what we are at liberty to ask from God. Nothing is more advantageous to us than such instruction.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 12, 1, NULL, 'luke-12', 'John Calvin', 'Commentaries', E'23. Therefore, if thou shalt bring thy gift to the altar, and there shalt remember that thy brother hath anything against thee, 24. Leave there thy gift before the altar, and go away: first be reconciled to thy brother, and then come and offer thy gift. 25. Be agreed with thy adversary quickly, while thou art in the way with him: lest at any time the adversary deliver thee to the judge, and the judge deliver thee to the officer, and thou be thrown into prison. 26. Verily I say to thee, Thou shalt not depart thence, till thou shalt have paid the last farthing.

58. Now, when thou goest with thy adversary to the magistrate, do thy endeavor, while thou art in the way, to be delivered from him: lest perhaps he drag thee to the judge, and the judge deliver thee to the officer, and the officer throw thee into prison. 59. I say to thee, Thou shalt no depart thence, until thou pay even the last mite.

Matthew 5:23. Therefore, if thou shalt bring thy gift This clause confirms, and at the same time explains, the preceding doctrine. It amounts to this, that the precept of the law, which forbids murder, (Exodus 20:13,) is obeyed, when we maintain agreement and brotherly kindness, with our neighbor. To impress this more strongly upon us, Christ declares, that even the duties of religion are displeasing to God, and are rejected by him, if we are at variance with each other. When he commands those who have injured any of their brethren, to be reconciled to him, before they offer their gift, his meaning is, that, so long as a difference with our neighbor is kept up by our fault, we have no access to God. But if the worship, which men render to God, is polluted and corrupted by their resentments, this enables us to conclude, in what estimation he holds mutual agreement among ourselves.

Here a question may be put. Is it not absurd, that the duties of charity should be esteemed more highly than the worship of God? We shall then be forced to say, that the order of the law is improper, or that the first table of the law must be preferred to the second. The answer is easy: for the words of Christ mean nothing more than this, that it is a false and empty profession of worshipping God, which is made by those who, after acting unjustly towards their brethren, treat them with haughty disdain. By a synecdoche he takes a single class to express the outward exercises of divine worship, which in many men are rather the pretenses, than the true expressions, of godliness. It ought to be observed that Christ, adapting his discourse to that age, speaks of sacrifices.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 13, 1, NULL, 'luke-13', 'John Calvin', 'Commentaries', E'25. And when the master of the house shall have arisen, and shall have shut the door, and you shall begin to stand without and to knock at the door, saying, Lord, Lord, open to us: and he answering shall say to you, I know not whence you are: 26. Then you shall begin to say, We have eaten and drunk in thy presence, and thou hast taught in our streets. 27. And he shall say, I say to you, I know not whence you are: depart from me, all who work iniquity. 28. Weeping and gnashing of teeth shall be there, when you shall see Abraham, and Isaac, and Jacob, and all the prophets, in the kingdom of God, and yourselves shut out. 29. And they shall come from the east and west, and north and south, and shall sit down in the kingdom of God. 30. And, lo, they are last who shall be first, and they are first who shall be last.

Luke 13:25. And when the master of the house shall have arisen Though these words, as I hinted a little before, were spoken on a different and later occasion, I have chosen to pay more regard to the doctrine than to the time: for it is no slight assistance to the understanding to read, in immediate connection, those passages which are closely related in meaning. As Christ had declared that to many, who shall desire to enter into heaven, the door will not be open, he now asserts, that they gain nothing by occupying a place in the church because God will at length arise in judgment, and shut out from his kingdom those who now lay claim to a place in his family. He employs the comparison of the master of a house, who, having learned that some wicked and dissolute persons among his own domestics steal out unperceived during the night, and expose the house to thieves, rises and shuts the door, and does not allow those night-prowlers to enter, who have been wandering through the public streets at unseasonable hours. By these words he warns us, that we must avail ourselves of the opportunity, while it is offered: for so long as the Lord invites us to himself, the door is, as it were, open, that we may enter into the kingdom of heaven: but the greater part do not deign to move a step. Christ therefore threatens, that the door will at length be shut, and that those who are looking for companions are in danger of being refused admission.

26. Thou hast taught in our streets Christ expressly states, that it will be of no advantage to the Jews, that he approached near to them, and permitted them to enjoy familiar intercourse with him, if, when called, they do not answer at the appointed day.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 14, 1, NULL, 'luke-14', 'John Calvin', 'Commentaries', E'13. Ye are the salt of the earth: but if salt shall become tasteless, with what shall it be salted? It is good for nothing farther, than to be thrown out and trodden down by men. 14. Ye are the light of the world: a city placed upon a mountain cannot be hid. 15. Neither do men light a candle, and put it upon a bushel but upon a candlestick, and it gives light to all who are in the house. 16. Let your light shine before men, so that they may see your good works, and may glorify your Father who is in heaven. 49. For every (man) shall be salted with fire, and every sacrifice shall be salted with salt. 50. Salt is a good thing: but if salt shall become tasteless, with what shall it be seasoned? Have salt in yourselves, and cultivate peace with one another. 21. And he said to them, Is a candle lighted, that it may be put under a bushel, or under a bed? Is it not that it may be put on a candlestick? 34. Salt is good: but if salt shall have become tasteless, with what shall it be seasoned? 35. It is not useful either for the land or for the dunghill: they throw it out. He who hath ears to hear, let him hear. 16. And no man, when he hath lighted a candle, covered it with a vessel, or putteth it under a bed, but putteth it on a candlestick, that those who enter may see the light. 33. No man lighteth a candle, and putteth it in a hidden place, nor under a bushel, but on a candlestick, that those who enter may see the light. Matthew 5:13. Ye are the salt of the earth. What belongs to doctrine is applied to the persons to whom the administration of it has been committed. When Christ calls the apostles the salt of the earth, he means, that it is their office to salt the earth: because men have nothing in them but what is tasteless, till they have been seasoned with the salt of heavenly doctrine. After having reminded them to what they are called, he pronounces against them a heavy and dreadful judgment, if they do not fulfill their duty. The doctrine, which has been entrusted to them, is shown to be so closely connected with a good conscience and a devout and upright life, that the corruption, which might be tolerated in others, would in them be detestable and monstrous. "If other men are tasteless in the sight of God, to you shall be given the salt which imparts a relish to them: but if you have lost your taste, where shall you obtain the remedy which you ought to supply to others?" Our Lord skillfully pursues his metaphor, by saying, that other things when they lose their original qualities, are still useful after they have become corrupted: but that salt becomes even hurtful, and', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 15, 1, NULL, 'luke-15', 'John Calvin', 'Commentaries', E'11. For the Son of man is come to save that which was lost. 12. What think you? If a man shall have a hundred sheep, and one of them shall go astray, doth he not leave the ninety-nine, and go to the mountains, and seek that which had gone astray? 13. And if he happen to find it, verily, I say to you, he rejoiceth more on account of that sheep than on account of the ninety-nine which had gone astray. 14. So it is not the will of your Father who is in heaven, that one of those little ones should perish.

1. And all the publicans and sinners drew near to him to hear him. 2. And the Pharisees and scribes murmured, saying, This man receiveth sinners, and eateth with them. 3. And he spoke to them a parable, saying, 4. What man is there among you, who hath a hundred sheep, and, if he shall lose one of them, doth not leave the ninety-nine in the wilderness, and go after that which was lost, till he find it? 5. And when he hath found it, he layeth it on his shoulders, rejoicing: 6. And coming home, he calleth his friends and neighbors, saying to them, Rejoice with me; for I have found the sheep which was lost. 7. I say to you, that in like manner there will be greater joy in heaven over one repenting sinner, than over ninety-nine righteous persons who do not need repentance. 8. Or what woman having ten pieces of money, if she shall lose one piece, doth not light a candle, and sweep the house, and seek diligently until she find it? 9. And when she hath found it, she calleth together her friends and neighbors, saying, Rejoice with me, for I have found the piece which I had lost. 10. In like manner, I tell you, there will be joy in the presence of the angels of God over one repenting sinner.

Matthew 18:11. For the Son of man cometh. Christ now employs his own example in persuading his disciples to honor even weak and despised brethren; for he came down from heaven to save not them only, but even the dead who were lost. It is in the highest degree unreasonable that we should disdainfully reject those whom the Son of God has so highly esteemed. And even if the weak labor under imperfections which may expose them to contempt, our pride is not on that account to be excused; for we ought to esteem them not for the value of their virtues, but for the sake of Christ; and he who will not conform himself to Christ''s example is too saucy and proud.

12. What think you? Luke carries the occasion of this parable still farther back, as having arisen from the murmurings of the Pharisees and scribes against our Lord, whom they saw conversing daily with sinners.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 16, 1, NULL, 'luke-16', 'John Calvin', 'Commentaries', E'33. Thou shalt not perjure thyself This also is not a correction of the law, but a true interpretation of it. For God condemned in the law not only acts of perjury, but lightness in swearing, which lessens the reverence for his name. The man who perjures himself is not the only person who takes the name of God in vain, (Exodus 20:7.) He does so, who idly and contemptuously pronounces the name of God on trivial occasions, or in ordinary conversation. While the law condemns every kind of profanation of the name of God the Jews imagined, that the guilt of it lay entirely in acts of perjury. Christ reproves this gross error of supposing that they might, without danger, abuse the name of God, provided they did not swear falsely. We are, no doubt, strictly enjoined to perform to the Lord what we have sworn: for he who, after employing the name of God, cheats and deceives his neighbors, does an injury to God as well as to man. But it is improper to confine to a single part that which has a wider reference. Some consider the word perform as applying to vows, when any thing has been promised to God on account of religion. But this mode of expression applies very well to all promises and engagements, which have been sanctioned by the use of the name of God: for in such cases God is appealed to as guarantee between the parties, to secure their fidelity. 34. Swear not at all Many have been led by the phrase, not at all, to adopt the false notion, that every kind of swearing is condemned by Christ. Some good men have been driven to this extreme rigor by observing the unbridled licentiousness of swearing, which prevailed in the world. The Anabaptists, too, have blustered a great deal, on the ground, that Christ appears to give no liberty to swear on any occasion, because he commands, Swear not at all But we need not go beyond the immediate context to obtain the exposition: for he immediately adds, neither by heaven, nor by the earth Who does not see that those kinds of swearing were added by way of exposition, to explain the former clause more fully by specifying a number of cases? The Jews had circuitous or indirect ways of swearing: and when they swore by heaven, or by earth, or by the altar, (Matthew 23:18,) they reckoned it to be next to nothing; and, as one vice springs from another, they defended, under this pretense, any profanation of the name of God that was not openly avowed. To meet this crime, our Lord declares that they must not swear at all, either in this or that way, either by heaven, or by the earth Hence we conclude, that the particle, at all, relates not to the substance, but to the form, and means, "neither directly nor indirectly." It would otherwise have been superfluous to enumerate those kinds: and', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 17, 1, NULL, 'luke-17', 'John Calvin', 'Commentaries', E'6. But whosoever shall offend one of those little ones who believe in me, it were better for him that a millstone were hanged about his neck, and that he were sunk to the bottom of the sea. 7. Woe to the world on account of offenses! for offenses must come; but woe to the man by whom the offense cometh! 8. But if thy hand or thy foot offend thee, cut it off, and cast it from thee; for it is better for thee to enter lame or maimed into life, than that, having two hands or two feet, thou shouldst be cast into the everlasting fire. 9. And if thine eye offend thee, pluck it out, and cast it from thee; for it is better that thou shouldst enter into life having one eye, than that, having two eyes, thou shouldst be cast into hell-fire. 10. Beware of despising one of these little ones; for I say to you, That their angels always behold the face of my Father who is in heaven.

42. And whosoever shall offend one of the little ones who believe in me, it were better for him that a millstone were hung around his neck, and that he were thrown into the sea. 43. And if thy hand shall offend thee, cut it off; for it were better for thee to enter lame into life, than that, having two hands, thou shouldst go into hell, into the unquenchable fire: 44. Where their worm dieth not, and their fire is not quenched. 45. And if thy foot shall offend thee, cut if off; for it were better for thee to enter lame into life, than that, having two feet, thou shouldst be cast into hell, into the unquenchable fire: 46. Where their worm dieth not, and their fire is not quenched. 47. And if thine eye offend thee, pluck it out; for it were better for thee to enter with one eye into the kingdom of God than that, having two eyes, thou shouldst be cast into hell-fire: 48. Where their worm dieth not, and their fire is not quenched.

1. And he said to his disciples, It is impossible but that offenses will come; but woe to him by whom they come! 2. It were better for him that a millstone were hung around his neck, and that he were thrown into the sea, than that he should offend one of these little ones.

Matthew 18:6. But whosoever shall offend one of those little ones. This appears to be added for the consolation of the godly, that they may not be rendered uneasy by their condition, if they are despised by the world. It is a powerful obstruction to the voluntary exercise of modesty, when they imagine, that by so doing they expose themselves to contempt; and it is hard to be not only treated disdainfully, but almost trodden under foot, by haughty men.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 18, 1, NULL, 'luke-18', 'John Calvin', 'Commentaries', E'1. And he spake also a parable to them, that they ought always to pray, and not to grow weary: 2. Saying, There was a judge in a city, who neither feared God, nor regarded man. 3. And there was a widow in that city, who came to him, saying, Do me justice on my adversary. 4. And he refused for some time, but afterwards said within himself, Though I neither fear God, nor regard man, 5. Yet because this widow is troublesome to me, I will do her justice, lest by coming perpetually she weary me out. 6. And the Lord said, Hear what the unjust judge saith. 7. And will not God avenge his elect, who cry to him night and day, even though he forbear with respect to them? 8. I tell you that he will speedily avenge them. But when the Son of man shall come, will he find faith on the earth?

We know that perseverance in prayer is a rare and difficult attainment; and it is a manifestation of our unbelief that, when our first prayers are not successful, we immediately throw away not only hope, but all the ardor of prayer. But it is an undoubted evidence of our Faith, if we are disappointed of our wish, and yet do not lose courage. Most properly, therefore, does Christ recommend to his disciples to persevere in praying.

The parable which he employs, though apparently harsh, was admirably fitted to instruct his disciples, that they ought to be importunate in their prayers to God the Father, till they at length draw from him what He would otherwise appear to be unwilling to give. Not that by our prayers we gain a victory over God, and bend him slowly and reluctantly to compassion, but because the actual facts do not all at once make it evident that he graciously listens to our prayers. In the parable Christ describes to us a widow, who obtained what she wanted from an unjust and cruel judge, because she did not cease to make earnest demands. The leading truth conveyed is, that God does not all at once grant assistance to his people, because he chooses to be, as it were, wearied out by prayers; and that, however wretched and despicable may be the condition of those who pray to him, yet if they do not desist from the uninterrupted exercise of prayer, he will at length regard them and relieve their necessities.

The parties between whom the comparison is drawn are, indeed, by no means equal; for there is a wide difference between a wicked and cruel man and God, who is naturally inclined to mercy. But Christ intended to assure believers that they have no reason to fear lest their persevering entreaties to the Father of mercy should be refused, since by importunate supplication they prevail on men who are given to cruelty.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 19, 1, NULL, 'luke-19', 'John Calvin', 'Commentaries', E'1. And having entered, he passeth through Jericho. 2. And, lo, a man named Zaccheus, and he was chief of the publicans, and was rich. 3. And he sought to see Jesus who he was, and could not on account of the multitude; for he was of small stature. 4. And running before, he climbed up into a sycamore tree to see him; for he was to pass that way. 5. And when Jesus came to the place, he looked up, and saw him, and said to him, Zaccheus, make haste, and come down; for today I must abide at thy house. 6. And he made haste, and came down, and received him joyfully. 7. And when they saw it, they all murmured, saying, That he had gone to lodge with a man who is a sinner. 8. And Zaccheus stood, and said to the Lord, Lo, O Lord, the half of my goods I give to the poor; and if I have defrauded any man in any thing, I restore fourfold. 9. Jesus said to him, Today is salvation come to this house, inasmuch as he also is a son of Abraham. 10. For the Son of man came to seek and save what was lost.

This shows how little attention Luke paid to observing the order of dates; for, after having detailed the miracle, he now relates what happened in the city of Jericho He tells us that, while Christ presented himself to the view of all, as he went along the streets, Zaccheus alone was very desirous to see him. For it was an evidence of intense desire that he climbed up a tree; since rich men are, for the most part, haughty, and plume themselves on affected gravity. It is possible, indeed, that others entertained the same wish, but this man was most properly singled out by Luke, both on account of his rank, and on account of his wonderful conversion, which took place suddenly. Now, though faith was not yet formed in Zaccheus, yet this was a sort of preparation for it; for it was not without a heavenly inspiration that he desired so earnestly to get a sight of Christ; I mean, in reference to that design which immediately appeared. Some were led, no doubt, by vain curiosity to run even from distant places, for the purpose of seeing Christ, but the event showed that the mind of Zaccheus contained some seed of piety. In this manner, before revealing himself to men, the Lord frequently communicates to them a secret desire, by which they are led to Him, while he is still concealed and unknown; and, though they have no fixed object in view, He does not disappoint them, but manifests himself in due time.

5. Zaccheus, make haste, and come down. It is a remarkable instance of favor, that the Lord anticipates Zaccheus, and does not wait for his invitation, but of his own accord asks lodging at his house.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 20, 1, NULL, 'luke-20', 'John Calvin', 'Commentaries', E'23. And when he was come into the temple, the chief priests and elders of the people came to him, saying By what authority doest thou these things? and who gave thee that authority? 24. And Jesus answering said to them, I also will ask you something, which if you shall tell me, I also will tell you by what authority I do these things. 25. Whence was the baptism of John? From heaven, or from men? But they thought within themselves saying, If we shall say, From heaven, he will say to us, Why then did you not believe him? 26. But if we shall say, From men, we dread the multitude, for they all hold John for a prophet. 27. And answering Jesus, they said, We do not know. And he saith to them, Neither do I tell you by what authority I do these things.

27. And they come again to Jerusalem; and while he was walking in the temple, the chief priests, and scribes, and elders, come to him. 28. And they say to him, By what authority doest thou these things? and who gave thee that authority to do these things? 29. And Jesus answering said to them, I will also ask you something, and answer me, and I will tell you by what authority I do these things. 30. Whether was the baptism of John from heaven or from men? Answer me. 31. And they thought within themselves, saying, If we shall say, From heaven, he will say, Why then did you not believe him? 32. But if we say, From men, they dreaded the people; for all reckoned John that he was truly a prophet. 33. And they answering say to Jesus, We do not know. And Jesus answering saith to them, Neither will I tell you by what authority I do these things.

1. And it happened on one of those days, while he was teaching the people in the temple, and preaching the gospel, the chief priests, and scribes, with the elders, came upon him, 2. And spoke to him saying, Tell us, by what authority doest thou these things? or who is he that gave thee that authority? 3. And Jesus answering said to them, I will also ask you something, and answer me. 4. Was the baptism of John from heaven, or from men? 5. But they reasoned within themselves, saying, If we shall say, From heaven, he will say, Why then did you not believe him? 6. But if we shall say, From men, all the people will stone us; for they are convinced that John is a prophet. 7. And they answered, That they did not know whence it was. 8. And Jesus said to them, Neither do I tell you by what authority I do these things.

Matthew 21:23. By what authority doest thou these things.', false, false, 'sourced', 'published');
