-- Calvin commentary INSERT — Galatians (batch 1, rows 1-6)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 48, 1, 1, NULL, 'galatians-1', 'John Calvin', 'Commentaries', E'1. Paul, an apostle. In the salutations with which he commenced his Epistles, Paul was accustomed to claim the title of "an Apostle." His object in doing so, as we have remarked on former occasions, was to employ the authority of his station, for the purpose of enforcing his doctrine. This authority depends not on the judgment or opinion of men, but exclusively on the calling of God; and therefore he demands a hearing on the ground of his being "an Apostle." Let us always bear this in mind, that in the church we ought to listen to God alone, and to Jesus Christ, whom he has appointed to be our teacher. Whoever assumes a right to instruct us, must speak in the name of God or of Christ. But as the calling of Paul was more vehemently disputed among the Galatians, he asserts it more strongly in his address to that church, than in his other Epistles; for he does not simply affirm that he was called by God, but states expressly that it was not either from men or by men. This statement, be it observed, applies not to the office which he held in common with other pastors, but to the apostleship. The authors of the calumnies which he has in his eye did not venture to deprive him altogether of the honor of the Christian ministry. They merely refused to allow him the name and rank of an apostle. We are now speaking of the apostleship in the strictest sense; for the word is employed in two different ways. Sometimes, it denotes preachers of the Gospel, to whatever class they might belong; but here it bears a distinct reference to the highest rank in the church; so that Paul is equal to Peter and to the other twelve. The first clause, that he was called not from men, he had in common with all the true ministers of Christ. As no man ought to "take this honor unto himself," (Hebrews 5:4,) so it is not in the power of men to bestow it on whomsoever they choose. It belongs to God alone to govern his church; and therefore the calling cannot be lawful, unless it proceed from Him. So far as the church is concerned, a man who has been led to the ministry, not by a good conscience, but by ungodly motives, may happen to be regularly called. But Paul is here speaking of a call ascertained in so perfect, a manner, that nothing farther can be desired. It will, perhaps, be objected -- Do not the false apostles frequently indulge in the same kind of boasting? I admit they do, and in a more haughty and disdainful style than the servants of the Lord venture to employ; but they want that actual call from Heaven to which Paul was entitled to lay claim. The second clause, that he was called not by man, belonged in a peculiar manner to the apostles; for in an', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 48, 2, 1, NULL, 'galatians-2', 'John Calvin', 'Commentaries', E'1. Fourteen years after. This cannot with certainty be affirmed to be the same journey mentioned by Luke. (Acts 15:2.) The connection of the history leads us rather to an opposite conclusion. We find that Paul performed four journeys to Jerusalem. Of the first we have already spoken. The second took place when, in company with Barnabas, he brought the charitable contributions of the Greek and Asiatic Churches. (Acts 15:25.) My belief that this second journey is referred to in the present passage rests on various grounds. On any other supposition, the statements of Paul and Luke cannot be reconciled. Besides, there is ground for conjecturing that the rebuke was administered to Peter at Antioch while Paul was residing there. Now, this happened before he was sent to Jerusalem by the Churches to settle the dispute which had arisen about ceremonial observances. (Acts 15:2.) It is not reasonable to suppose that Peter would have used such dissimulation, if that controversy had been settled and the decree of the Apostles published. But Paul writes that he came to Jerusalem, and afterwards adds that he had rebuked Peter for an act of dissimulation, an act which Peter certainly would not have committed except in matters that were doubtful.

Besides, he would scarcely have alluded, at any time, to that journey undertaken with the consent of all the believers, without mentioning the occasion of it, and the memorable decision which was passed. It is not even certain at what time the Epistle was written, only that the Greeks conjecture that it was sent from Rome, and the Latins from Ephesus. For my own part, I think that it was written, not only before Paul had seen Rome, but before that consultation had been held, and the decision of the Apostles given about ceremonial observances. While his opponents were falsely pleading the name of the apostles, and earnestly striving to ruin the reputation of Paul, what carelessness would it have angered in him to pass by the decree universally circulated among them, which struck at those very persons! Undoubtedly, this one word would have shut their mouth: "You bring against me the authority of the apostles, but who does not know their decision? and therefore I hold you convicted of unblushing falsehood. In their name, you oblige the Gentiles to keep the law, but I appeal to their own writing, which sets the consciences of men at liberty."

We may likewise observe, that, in the commencement of the Epistle, he reproved the Galatians for having so soon revolted from the gospel which had been delivered to them. But we may readily conclude, that, after they had been brought to believe the gospel, some time must have elapsed before that dispute about the ceremonial law arose. I consider, therefore, that the fourteen years are to be reckoned, not from one journey to another, but from Paul''s conversion. The space of time between the two journeys was eleven years.

2. And I went up according to revelation.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 48, 3, 1, NULL, 'galatians-3', 'John Calvin', 'Commentaries', E'1. O foolish Galatians. An expostulation is here interwoven -- I should rather say, inserted -- amidst his doctrinal statements. Some will wonder that he did not delay it to the close of the Epistle, but the very serious nature of the errors which he has brought forward unquestionably roused him to a burst of passion. When we hear that the Son of God, with all his benefits, is rejected, that his death is esteemed as nothing, what pious mind would not break out into indignation? He therefore declares that those who allowed themselves to be involved in so heinous a crime must have been anoetoi, that is, "disordered in mind." He accuses them not only of having suffered themselves to be deceived, but of having been carried away by some sort of magical enchantment, which is a still more serious charge. He insinuates that their fall partook more of madness than of folly.

Some think that Paul refers to the temper of the nation, that, being sprung from barbarians, it was more difficult to train them; but I rather think that he refers to the subject itself. It looks like something supernatural, that, after enjoying the gospel in such clearness, they should be affected by the delusions of Satan. He does not merely say that they were "bewitched" and "disordered in mind," because they did not obey the truth; but because, after having received instruction so clear, so full, so tender, and so powerful, they immediately fell away. Erasmus has chosen to interpret the words, "that ye should not believe the truth." I am not quite prepared to set aside that rendering, but would prefer the word obey, because Paul does not charge them with having, from the outset, rejected the gospel, but with not having persevered in obedience.

Before whose eyes. This is intended, as I have already hinted, to express an aggravation; for, the better opportunities they had of knowing Christ, the more heinous was the criminality of forsaking him. Such, he tells them, was the clearness of his doctrine, that it was not naked doctrine, but the express, living image of Christ. They had known Christ in such a manner, that they might be almost said to have seen him.

Jesus Christ hath been evidently set forth. Augustine''s interpretation of the word proegraphe, ("hath been set forth,") is harsh, and inconsistent with Paul''s design. He makes it to signify that Christ was to be thrust out from possession. Others propose a different phrase, (proscriptus,) which, if used in the sense of "openly proclaimed," would not be inapplicable. The Greeks, accordingly, borrow from this verb the word programmata, to denote boards on which property intended to be sold was published, so as to be exposed to the view of all. But the participle, painted, is less ambiguous, and, in my own opinion, is exceedingly appropriate.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 48, 4, 1, NULL, 'galatians-4', 'John Calvin', 'Commentaries', E'1. Now I say. Whoever made the division into chapters has improperly separated this paragraph from the preceding, as it is nothing else than the concluding section, (epexergasia,) in which Paul explains and illustrates the difference that exists between us and the ancient people. He does so by introducing a third comparison, drawn from the relation which a person under age bears to his tutor. The young man, though he is free, though he is lord of all his father''s family, still resembles a slave; for he is under the government of tutors. But the period of guardianship lasts only "until the time appointed by the father" after which he enjoys his freedom. In this respect the fathers under the Old Testament, being the sons of God, were free; but they were not in possession of freedom, while the law held the place of their tutor, and kept them under its yoke. That slavery of the law lasted as long as it pleased God, who put an end to it at the coming of Christ. Lawyers enumerate various methods by which the tutelage or guardianship is brought to a close; but of all these methods, the only one adapted to this comparison is that which Paul has selected, "the appointment of the father."

Let us now examine the separate clauses. Some apply the comparison in a different manner to the case of any man whatever, whereas Paul is speaking of two nations. What they say, I acknowledge, is true; but it has nothing to do with the present passage. The elect, though they are the children of God from the womb, yet, until by faith they come to the possession of freedom, remain like slaves under the law; but, from the time that they have known Christ, they no longer require this kind of tutelage. Granting all this, I deny that Paul here treats of individuals, or draws a distinction between the time of unbelief and the calling by faith. The matters in dispute were these. Since the church of God is one, how comes it that our condition is different from that of the Israelites? Since we are free by faith, how comes it that they, who had faith in common with us, were not partakers with us of the same freedom? Since we are all equally the children of God, how comes it that we at this day are exempt from a yoke which they were forced to bear? On these points the controversy turned, and not on the manner in which the law reigns over each of us before we are freed by faith from its slavery. Let this point be first of all settled, that Paul here compares the Israelitish church, which existed under the Old Testament, with the Christian church, that thus we may perceive in what points we agree and in what we differ.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 48, 5, 1, NULL, 'galatians-5', 'John Calvin', 'Commentaries', E'1. Stand fast therefore. After having told them that they are the children of the free woman, he now reminds them that they ought not lightly to despise a freedom so precious. And certainly it is an invaluable blessing, in defense of which it is our duty to fight, even to death; since not only the highest temporal considerations, but our eternal interests also, animate us to the contest. Many persons, having never viewed the subject in this light, charge us with excessive zeal, when they see us so warmly and earnestly contending for freedom of faith as to outward matters, in opposition to the tyranny of the Pope. Under this cloak, our adversaries raise a prejudice against us among ignorant people, as if the whole object of our pursuit were licentiousness, which is the relaxation of all discipline. But wise and skillful persons are aware that this is one of the most important doctrines connected with salvation. This is not a question whether you shall eat this or that food, -- whether you shall observe or neglect a particular day, (which is the foolish notion entertained by many, and the slander uttered by some,) but what is your positive duty before God, what is necessary to salvation, and what cannot be omitted without sin. In short, the controversy relates to the liberty of conscience, when placed before the tribunal of God.

The liberty of which Paul speaks is exemption from the ceremonies of the law, the observance of which was demanded by the false apostles as necessary. But let the reader, at the same time, remember, that such liberty is only a part of that which Christ has procured for us: for how small a matter would it be, if he had only freed us from ceremonies? This is but a stream, which must be traced to a higher source. It is because

"Christ was made a curse, that he might redeem us from the curse of the law," (Galatians 3:13;)

because he has revolted the power of the law" so far as it held us liable to the judgment of God under the penalty of eternal death; because, in a word, he has rescued us from the tyranny of sin, Satan, and death. Thus, under one department is included the whole class; but on this subject we shall speak more fully on the Epistle to the Colossians.

This liberty was procured for us by Christ on the cross: the fruit and possession of it are bestowed upon us through the Gospel. Well does Paul, then, warn the Galatians, not to be entangled again with the yoke of bondage, -- that is, not to allow a snare to be laid for their consciences. For if men lay upon our shoulders an unjust burden, it may be borne; but if they endeavor to bring our consciences into bondage, we must resist valiantly, even to death.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 48, 6, 1, NULL, 'galatians-6', 'John Calvin', 'Commentaries', E'1. Brethren, if a man be overtaken in any fault Ambition is a serious and alarming evil. But hardly less injury is frequently done by unseasonable and excessive severity, which, under the plausible name of zeal, springs in many instances from pride, and from dislike and contempt of the brethren. Most men seize on the faults of brethren as an occasion of insulting them, and of using reproachful and cruel language. Were the pleasure they take in upbraiding equalled by their desire to produce amendment, they would act in a different manner. Reproof, and often sharp and severe reproof, must be administered to offenders. But while we must not shrink from a faithful testimony against sin, neither must we omit to mix oil with the vinegar.

We are here taught to correct the faults of brethren in a mild manner, and to consider no rebukes as partaking a religious and Christian character which do not breathe the spirit of meekness. To gain this object, he explains the design of pious reproofs, which is, to restore him who is fallen, to place him in his former condition. That design will never be accomplished by violence, or by a disposition to accuse, or by fierceness of manner or language; and consequently, we must display a gentle and meek spirit, if we intend to heal our brother. And lest any man should satisfy himself with assuming the outward form, he demands the spirit of meekness; for no man is prepared for chastising a brother till he has succeeded in acquiring a gentle spirit.

Another argument for gentleness in correcting brethren is contained in the expression, "if a man be overtaken." If he has been carried away through want of consideration, or through the cunning arts of a deceiver, it would be cruel to treat such a man with harshness. Now, we know that the devil is always lying in wait, and has a thousand ways of leading us astray. When we perceive a brother to have transgressed, let us consider that he has fallen into the snares of Satan; let us be moved with compassion, and prepare our minds to exercise forgiveness. But offenses and falls of this description must undoubtedly be distinguished from deep seated crimes, accompanied by deliberate and obstinate disregard of the authority of God. Such a display of wicked and perverse disobedience to God must be visited with greater severity, for what advantage would be gained by gentle treatment? The particle if also, (ea`n kai,) implies that not only the weak who have been tempted, but those who have yielded to temptation, shall receive forbearance.

Ye who are spiritual. This is not spoken in irony; for, however spiritual they might be, still they were not wholly filled with the Spirit. It belongs to such persons to raise up the fallen.', false, false, 'sourced', 'published');
