-- Calvin commentary INSERT — Lamentations (batch 1, rows 1-5)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 25, 1, 1, NULL, 'lamentations-1', 'John Calvin', 'Commentaries', E'1. How doth the city sit solitary that was full of people! how is she become as a widow! she that was great among the nations, and princess among the provinces, how is she become tributary! 1. Quomodo sedet solitaria civitas, quae abundavit populo! facta est tanquam vidua, quae magna fuit in gentibus! Quae dominataest in provinciis, redacta est ad tributum! The Prophet could not sufficiently express the greatness of the calamity, except by expressing his astonishment. He then assumes the person of one who on seeing something new and unexpected is filled with amazement. It was indeed a thing incredible; for as it was a place chosen for God to dwell in, and as the city Jerusalem was not only the royal throne of God, but also as it were his earthly sanctuary, the city might have been thought exempted from all danger. Since it had been said, "Here is my rest for ever, here will I dwell," (Psalm 132:14,) God seemed to have raised that city above the clouds, and to have rendered it free from all earthly changes. We indeed know that there is nothing fixed and certain in the world, and that the greatest empires have been reduced to nothing; but, the state of Jerusalem did not depend on human protection, nor on the extent of its dominion, nor on the abundance of men, nor on any other defenses whatever, but it was founded by a celestial decree, by the promise of God, which is not subject to any mutations. When, therefore, the city fell, uprooted from its foundations, so that nothing remained, when the Temple was disgracefully plundered and then burnt by enemies, and further, when the king was driven into exile, his children slain in his presence, and also the princes, and when the people were scattered here and there, exposed to every contumely and reproach, was it not, a horrible and monstrous thing? It was not, then, without reason that the Prophet exclaimed, How! for no one could have ever thought that such a thing would have happened; and then, after the event, no one with a calm mind could have looked on such a spectacle, for innumerable temptations must have come to their minds; and this thought especially must have upset the faith of all -- "What does God mean? How is it that, he has promised that this city would be perpetual? and now there is no appearance of a city, and no hope of restoration in future." As, then, this so sad a spectacle might not only disturb pious minds, but also upset them and sink them in the depths of despair, the Prophet exclaims, How! and then says, How sits the city solitary, which had much people! Here, by a comparison, he amplifies the indignity of the fact; for, on the one hand, he refers to the flourishing state of Jerusalem before the calamity, and, on the other hand, he shews how the place had in a manner been', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 25, 2, 1, NULL, 'lamentations-2', 'John Calvin', 'Commentaries', E'1. How hath the Lord covered the daughter of Zion with a cloud in his anger, and cast down from heaven unto the earth the beauty of Israel, and remembered not his footstool in the day of his anger!

1. Quomodo obnubilavit in iracundia sua Dominus filiam Sion, projecit a coelo in terram decorem Israel, et non recordatus est scabelli pedum suorum in dic iracundiae!

The Prophet again exclaims in wonder, that an incredible thing had happened, which was like a prodigy; for at the first sight it seemed very unreasonable, that a people whom God had not only received into favor, but with whom he had made a perpetual covenant, should thus be forsaken by him. For though men were a hundred times perfidious, yet God never changes, but remains unchangeable in his faithfulness; and we know that his covenant was not made to depend on the merits of men. Whatsoever, then, the people might be, yet it behooved God to continue in his purpose, and not to annul the promise made to Abraham. Now, when Jerusalem was reduced to desolation, there was as it were all abolition of God''s covenant. There is, then, no wonder that the Prophet here exclaims, as on account of some prodigy, How can it be that God hath clouded or darkened, etc.

We must, however, observe at the same time, that the Prophet did not mean here to invalidate the fidelity or constancy of God, but thus to rouse the attention of his own nation, who had become torpid in their sloth; for though they were pressed down under a load of evils, yet they had become hardened in their perverseness. But it was impossible that any one should really call on God, except he was humbled in mind, and brought the sacrifice of which we have spoken, even a humble and contrite spirit. (Psalm 51:19.) It was, then, the Prophet''s object to soften the hardness which he knew prevailed in almost the whole people. This was the reason why he exclaimed, in a kind of astonishment, How has God clouded, etc.

Some render the words, "How has God raised up," etc., which may be allowed, provided it be not taken in a good sense, for it is said, in his wrath; but in this case the words to raise up and to cast down ought to be read conjointly; for when one wishes to break in pieces an earthen vessel, he not only casts it on the ground, but he raises it up, that it may be thrown down with greater force. We may, then, take this meaning, that God, in order that he might with greater violence break in pieces his people, had raised them up, not to honor them, but in order to dash them more violently on the ground.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 25, 3, 1, NULL, 'lamentations-3', 'John Calvin', 'Commentaries', E'1. I am the man that hath seen affliction by the rod of his wrath.

1. Ego vir videns afflictionem in virga Indignationis ejus.

The word, vrh obere, properly means assault, passing over limits; but what is peculiar to man is often in Scripture ascribed to God. Here also he changes the person, for he spoke before of the people under the person of a woman, as it is often done; but now the Prophet himself comes before us. At the same time there is no doubt but that by his own example he exhorted all others to lamentation, which was to be connected with true repentance. And this chapter, as we shall see, is full of rich instruction, for it contains remarkable sentiments which we shall consider in their proper places.

Some think that this Lamentation was written by Jeremiah when he was cast into prison; but this opinion seems not probable to me; and the contents of the chapter sufficiently shew that this ode was composed to set forth the common calamity of the whole people. Jeremiah, then, does not here plead his own private cause, but shews to his own nation what remedy there was for them in such a state of despair, even to have an immediate recourse to God, and on the one hand to consider their sins, and on the other to look to the mercy of God, so that they might entertain hope, and exercise themselves in prayer. All these things we shall see in their due order.

The Prophet then says that he was an afflicted man, or a man who saw affliction. This mode of speaking, we know, is common in Scripture -- to see affliction -- to see good and evil -- to see life and death. He then says that he had experienced many afflictions, and not only so, but that he had been given up as it were to miseries, -- how? by the rod of his fury. He does not mention the name of God, but Jeremiah speaks of him as of one well known, using only a pronoun. Now, then, at the very beginning, he acknowledges that whatever he suffered had been inflicted by God''s hand. And as all the godly ought to be convinced of this, that God is never angry without just reasons, there is included in the word wrath a brief confession, especially when it is added, by the rod, or staff. In short, the Prophet says that he was very miserable, and he also expresses the cause, for he had been severely chastised by an angry God. __________________________________________________________________

2. He hath led me, and brought me into darkness, but not into light.

2. Me deduxit et proficisci fecit in tenebras, et non in lucem.

The letters of the alphabet are tripled in this chapter, which I had omitted to mention.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 25, 4, 1, NULL, 'lamentations-4', 'John Calvin', 'Commentaries', E'1. How is the gold become dim! how is the most fine gold changed! the stones of the sanctuary are poured out in the top of every street.

1. Quomodo obscuratum est aurum! Mutatum est aurum bonum! Effusi sunt (vel, projecti) lapides sanctuarii in capite omnium platearum.

Here Jeremiah, following the order of the alphabet the fourth time, deplores the ruin of the city, and the destruction of the priesthood and of the kingdom. For they are mistaken who think that the death of Josiah is here lamented; for there are here many things, which we shall see as we proceed, which do not suit that event. There is no doubt but that this mournful song refers to the destruction of the Temple and city; but when Josiah was killed, the enemy had not come to the city, and the stones of the Temple were not then east forth into the streets and the public roads. There are also other things which we shall see, which did not then happen. It follows then that here is described the terrible vengeance of God, which we have had already to consider.

He begins by expressing his astonishment, How obscured is the gold! and the precious gold! for ktm, catam, is properly the best gold, though the word good,htvv ethub, is added to it. We may hence conclude that it generally denotes gold only. He mentions, then, gold twice, but they are two different words in Hebrew, zhv, zaeb, and ktm catam. Now he speaks figuratively in the former part of the verse; but there is no doubt but that by the gold, and the finest gold, as it is rendered, he means the splendor of the Temple; for God had designed the Temple to be built, as it is well known, in a very magnificent manner. Hence he calls what was ornamental in the Temple gold.

He then speaks without a figure, and says, that the stones were thrown here and there in all directions. Some, indeed, think that these words refer to the sacred vessels, of which there was a large quantity, we know, in the Temple. But this opinion is not probable, for the Prophet does not complain that the gold was taken away, but that it was obscured, and changed. It is then, no doubt, a metaphorical expression. But he afterwards explains himself when he says that the stones of the sanctuary were cast forth here and there along all the streets. It was indeed a sad spectacle; for God had consecrated that temple to himself, that he might dwell in it. When therefore the stones of the sanctuary were thus disgracefully scattered, it must have grievously wounded the minds of all the godly; for they saw that God''s name was thus exposed to reproaches. Nor is there a doubt but that the Chaldeans vomited forth many reproaches against God when they thus scattered the stones of the temple.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 25, 5, 1, NULL, 'lamentations-5', 'John Calvin', 'Commentaries', E'19 Behold, as a lion from the swelling of Jordan, Will he ascend to the habitation of strength: After having made him to rest, I will make him flee from her; And who is the chosen one whom I shall set over her? For who is as I am? And who will protest against me? And who is the shepherd that before me will stand? 20 Therefore, hear ye the counsel of Jehovah, Which he hath counseled against Edom, And his thoughts which he hath thought Against the inhabitants of Teman; Surely draw them forth shall the least of the flock, Surely destroyed over them shall be their dwellings. 21 At the sound of their fall, tremble shall the earth, The cry of their voice shall at the Red Sea be heard. 22 Behold, as an eagle will he ascend and fly, And will spread his wings over Bozrah; And the heart of the valiant men of Edom in that day Shall be like the heart of a sorrowful woman. 23 Concerning Damascus: Ashamed is Hamath and Arpad; Because they heard a bad report, they melt away, Like a turbulent sea which cannot rest. 24 Weakened is Damascus, she turns to flight, Terror hath laid hold on her, Anguish and pangs have seized her, As a woman in travail. 25 How is not forsaken the city of praise -- The city of my joy? 26 Yet fall shall her young men in her streets, And all the men of war shall be cut off In that day, saith Jehovah of Hosts. 27 For I will kindle a fire in the wall of Damascus, And it shall consume the palaces of Ben-hadad. 28 Concerning Kedar, and the kingdoms of Hazor, which Nebuchadnezzar, the king of Babylon, had smitten: Thus saith Jehovah, -- Arise ye, ascend against Kedar, And destroy the children of the east. 29 Their tents and their flocks shall they take away, And their curtains and all their vessels; Their camels also shall they take to themselves, And they shall cry to them, "Terror is on every side." 30 Flee ye, depart far away, (Though deep have they made to dwell The inhabitants of Hazor, saith Jehovah;) For consulted against you hath Nebuchadnezzar, The king of Babylon, a counsel, And he hath purposed against you a purpose. 31 Arise ye, ascend against a secure nation, That dwelleth in confidence, saith Jehovah; It hath neither gates nor bars, it dwelleth alone. 32 And their camels shall became a prey, And the abundance of their cattle a plunder; And I will scatter them to every wind, Even the utmost corners; And from all the sides thereof Will I bring their destruction, saith Jehovah. 33 And Hazor shall be the habitation of dragons, A perpetual desolation; Dwell there shall no man, Nor shall a son of man abide in her. 34 The word which came to Jeremiah, the prophet, against Elam, at the beginning of the reign of Zedekiah, the king of', false, false, 'sourced', 'published');
