-- Calvin commentary INSERT — Ephesians (batch 1, rows 1-6)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 49, 1, 1, NULL, 'ephesians-1', 'John Calvin', 'Commentaries', E'1. Paul, an apostle. As the same form of salutation, or at least very little varied, is found in all the Epistles, it would be superfluous to repeat here the observations which we have formerly made. He calls himself "an apostle of Jesus Christ;" for all to whom has been given the ministry of reconciliation are his ambassadors. The word Apostle, indeed, carries something more; for it is not every minister of the gospel, as we shall afterwards see, (Ephesians 4:11,) that can be called an apostle. But this subject has been explained more fully in my remarks on the Epistle to the Galatians. (See Calvin on "Galatians 1:1")

He adds, by the will of God; for "no man ought to take this honor unto himself," (Hebrews 5:4,) but every man ought to wait for the calling of God, which alone makes lawful ministers. He thus meets the jeers of wicked men by holding out the authority of God, and removes every occasion of inconsiderate strife.

To all the saints. He gives the name of saints to those whom he afterwards denominates faithful in Christ Jesus. No man, therefore, is a believer who is not also a saint; and, on the other hand, no man is a saint who is not a believer. Most of the Greek copies want the word all; but I was unwilling to strike it out, because it must, at all events, be understood.

3. Blessed be the God and Father of our Lord Jesus Christ. The lofty terms in which he extolls the grace of God toward the Ephesians, are intended to rouse their hearts to gratitude, to set them all on flame, to fill them even to overflowing with this thought. They who perceive in themselves discoveries of the Divine goodness, so full and absolutely perfect, and who make them the subject of earnest meditation, will never embrace new doctrines, by which the very grace which they feel so powerfully in themselves is thrown into the shade. The design of the apostle, therefore, in asserting the riches of divine grace toward the Ephesians, was to protect them against having their faith shaken by the false apostles, as if their calling were doubtful, or salvation were to be sought in some other way. He shews, at the same time, that the full certainty of future happiness rests on the revelation of his love to us in Christ, which God makes in the gospel. But to confirm the matter more fully, he rises to the first cause, to the fountain, -- the eternal election of God, by which, ere we are born, (Romans 9:11,) we are adopted as sons. This makes it evident that their salvation was accomplished, not by any accidental or unlooked-for occurrence, but by the eternal and unchangeable decree of God.

The word bless is here used in more than one sense, as referring to God, and as referring to men. I find in Scripture four different significations of this word. 1.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 49, 2, 1, NULL, 'ephesians-2', 'John Calvin', 'Commentaries', E'1. And you who were dead. This is an epexergasia of the former statements, that is, an exposition accompanied by an illustration. To bring home more effectually to the Ephesians the general doctrine of Divine grace, he reminds them of their former condition. This application consists of two parts. "Ye were formerly lost; but now God, by his grace, has rescued you from destruction." And here we must observe, that, in laboring to give an impressive view of both of these parts, the apostle makes a break in the style by (huperbaton) a transposition. There is some perplexity in the language; but, if we attend carefully to what the apostle says about those two parts, the meaning is clear. As to the first, he says that they were dead; and states, at the same time, the cause of the death -- trespasses and sins. He does not mean simply that they were in danger of death; but he declares that it was a real and present death under which they labored. As spiritual death is nothing else than the alienation of the soul from God, we are all born as dead men, and we live as dead men, until we are made partakers of the life of Christ, -- agreeably to the words of our Lord,

"The hour is coming, and now is, when the dead shall hear the voice of the Son of God, and they that hear shall live." (John 5:25)

The Papists, who are eager to seize every opportunity of undervaluing the grace of God, say, that while we are out of Christ, we are half dead. But we are not at liberty to set aside the declarations of our Lord and of the Apostle Paul, that, while we remain in Adam, we are entirely devoid of life; and that regeneration is a new life of the soul, by which it rises from the dead. Some kind of life, I acknowledge, does remain in us, while we are still at a distance from Christ; for unbelief does not altogether destroy the outward senses, or the will, or the other faculties of the soul. But what has this to do with the kingdom of God? What has it to do with a happy life, so long as every sentiment of the mind, and every act of the will, is death? Let this, then, be held as a fixed principle, that the union of our soul with God is the true and only life; and that out of Christ we are altogether dead, because sin, the cause of death, reigns in us.

2. In which for some time ye walked. From the effects or fruits, he draws a proof that sin formerly reigned in them; for, until sin displays itself in outward acts, men are not sufficiently aware of its power.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 49, 3, 1, NULL, 'ephesians-3', 'John Calvin', 'Commentaries', E'1. For this cause. Paul''s imprisonment, which ought to have been held as a confirmation of his apostleship, was undoubtedly presented by his adversaries in an opposite light. He therefore points out to the Ephesians that his chains served to prove and to declare his calling; and that the only reason why he had been imprisoned was, that he had preached the gospel to the Gentiles. His unshaken firmness was no small additional proof that he had discharged his office in a proper manner.

The prisoner of Jesus Christ. To strengthen his authority still more, he speaks in lofty terms of his prison. In the presence of the world and of wicked men, this might have appeared to be foolish boasting; but, in addressing godly persons, it was a dignified and faithful manner. The glory of Christ not only overcomes the ignominy of the chains, but converts what was in itself a reproach into the highest honor. If he had merely said, "I am a prisoner," this would not have conveyed the idea of his being an ambassador. Imprisonment alone has no claim to this honor, being usually the mark of wickedness and crime. But the crowns and sceptres of kings, to say nothing of the imposing splendor of an ambassador, are less honorable than the chains of a prisoner of Jesus Christ. Men might think otherwise, but it is our duty to judge of the reasons. So highly ought the name of Christ to be revered by us, that what men consider to be the greatest reproach, ought to be viewed by us as the greatest honour.

For you Gentiles. Another circumstance greatly fitted to interest the Ephesians was, that the persecutions of Paul were endured for the Gentiles, -- that his troubles and dangers were on their account.

2. If ye have heard. There is reason to believe, that, while Paul was at Ephesus, he had said nothing on these subjects, no necessity for doing so having arisen; for no controversy had taken place among them about the calling of the Gentiles. If he had made any mention of them in his discourses, he would have reminded the Ephesians of his former statements, instead of referring generally, as he now does, to common report and to his own Epistle. He did not, of his own accord, raise unnecessary disputes. It was only when the wickedness of his adversaries made it necessary, that he reluctantly undertook the defense of his ministry. Dispensation (oikonomia) means here a divine order or command, or, as it is generally expressed, a commission

3. That by revelation. Some might imagine, that, in attempting to discharge the office of an apostle, he had acted rashly, and was now paying the penalty of his rashness. It was this that made him so earnest in pleading the Divine authority for all his transactions. The present instance, on account of its novelty, had few supporters; and therefore he calls it a mystery.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 49, 4, 1, NULL, 'ephesians-4', 'John Calvin', 'Commentaries', E'1. I therefore, the prisoner of the Lord. His imprisonment, which might have been supposed more likely to render him despised, is appealed to, as we have already seen, for a confirmation of his authority. It was the seal of that embassy with which he had been honored. Whatever belongs to Christ, though in the eyes of men it may be attended by ignominy, ought to be viewed by us with the highest regard. The apostle''s prison is more truly venerable than the splendid retinue or triumphal chariot of kings.

That ye may walk worthy. This is a general sentiment, a sort of preface, on which all the following statements are founded. He had formerly illustrated the calling with which they were called, and now reminds them that they must live in obedience to God, in order that they may not be unworthy of such distinguished grace.

2. With all humility. He now descends to particulars, and first of all he mentions humility The reason is, that he was about to enter on the subject of Unity, to which humility is the first step. This again produces meekness, which disposes us to bear with our brethren, and thus to preserve that unity which would otherwise be broken a hundred times in a day. Let us remember, therefore, that, in cultivating brotherly kindness, we must begin with humility. Whence come rudeness, pride, and disdainful language towards brethren? Whence come quarrels, insults, and reproaches? Come they not from this, that every one carries his love of himself, and his regard to his own interests, to excess? By laying aside haughtiness and a desire of pleasing ourselves, we shall become meek and gentle, and acquire that moderation of temper which will overlook and forgive many things in the conduct of our brethren. Let us carefully observe the order and arrangement of these exhortations. It will be to no purpose that we inculcate forbearance till the natural fierceness has been subdued, and mildness acquired; and it will be equally vain to discourse of meekness, till we have begun with humility.

Forbearing one another in love. This agrees with what is elsewhere taught, that "love suffereth long and is kind." (1 Corinthians 13:4.) Where love is strong and prevalent, we shall perform many acts of mutual forbearance.

3. Endeavoring to keep the unity of the Spirit. With good reason does he recommend forbearance, as tending to promote the unity of the Spirit. Innumerable offenses arise daily, which might produce quarrels, particularly when we consider the extreme bitterness of man''s natural temper. Some consider the unity of the Spirit to mean that spiritual unity which is produced in us by the Spirit of God. There can be no doubt that He alone makes us "of one accord, of one mind," (Philippians 2:2,) and thus makes us one; but I think it more natural to understand the words as denoting harmony of views.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 49, 5, 1, NULL, 'ephesians-5', 'John Calvin', 'Commentaries', E'1. Be ye therefore followers. The same principle is followed out and enforced by the consideration that children ought to be like their father. He reminds us that we are the children of God, and that therefore we ought, as far as possible, to resemble Him in acts of kindness. It is impossible not to perceive, that the division of chapters, in the present instance, is particularly unhappy, as it has made a separation between parts of the subject which are very closely related. If, then, we are the children of God, we ought to be followers of God. Christ also declares, that, unless we shew kindness to the unworthy, we cannot be the children of our heavenly Father.

"Love your enemies, bless them that curse you, do good to them that hate you, and pray for them who despitefully use you and persecute you; that ye may be the children of your Father which is in heaven; for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust." (Matthew 5:44,45.)

2. And walk in love as Christ also hath loved us. Having called on us to imitate God, he now calls on us to imitate Christ, who is our true model. We ought to embrace each other with that love with which Christ has embraced us, for what we perceive in Christ is our true guide.

And gave himself for us. This was a remarkable proof of the highest love. Forgetful, as it were, of himself, Christ spared not his own life, that he might redeem us from death. If we desire to be partakers of this benefit, we must cultivate similar affections toward our neighbors. Not that any of us has reached such high perfection, but all must aim and strive according to the measure of their ability.

An offering and a sacrifice to God of a sweet smelling savor. While this statement leads us to admire the grace of Christ, it bears directly on the present subject. No language, indeed, can fully represent the consequences and efficacy of Christ''s death. This is the only price by which we are reconciled to God. The doctrine of faith on this subject holds the highest rank. But the more extraordinary the discoveries which have reached us of the Redeemer''s kindness, the more strongly are we bound to his service. Besides, we may infer from Paul''s words, that, unless we love one another, none of our duties will be acceptable in the sight of God. If the reconciliation of men, effected by Christ, was a sacrifice of a sweet smelling savor, we, too, shall be "unto God a sweet savor," (2 Corinthians 2:15,) when this holy perfume is spread over us.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 49, 6, 1, NULL, 'ephesians-6', 'John Calvin', 'Commentaries', E'1. Children, obey. Why does the apostle use the word obey instead of honor, which has a greater extent of meaning? It is because Obedience is the evidence of that honor which children owe to their parents, and is therefore more earnestly enforced. It is likewise more difficult; for the human mind recoils from the idea of subjection, and with difficulty allows itself to be placed under the control of another. Experience shews how rare this virtue is; for do we find one among a thousand that is obedient to his parents? By a figure of speech, a part is here put for the whole, but it is the most important part, and is necessarily accompanied by all the others.

In the Lord. Besides the law of nature, which is acknowledged by all nations, the obedience of children is enforced by the authority of God. Hence it follows, that parents are to be obeyed, so far only as is consistent with piety to God, which comes first in order. If the command of God is the rule by which the submission of children is to be regulated, it would be foolish to suppose that the performance of this duty could lead away from God himself.

For this is right. This is added in order to restrain the fierceness which, we have already said, appears to be natural to almost all men. He proves it to be right, because God has commanded it; for we are not at liberty to dispute, or call in question, the appointment of him whose will is the unerring rule of goodness and righteousness. That honor should be represented as including obedience is not surprising; for mere ceremony is of no value in the sight of God. The precept, honor thy father and mother, comprehends all the duties by which the sincere affection and respect of children to their parents can be expressed.

2. Which is the first commandment with promise. The promises annexed to the commandments are intended to excite our hopes, and to impart a greater cheerfulness to our obedience; and therefore Paul uses this as a kind of seasoning to render the submission, which he enjoins on children, more pleasant and agreeable. He does not merely say, that God has offered a reward to him who obeys his father and mother, but that such an offer is peculiar to this commandment. If each of the commandments had its own promises, there would have been no ground for the commendation bestowed in the present instance. But this is the first commandment, Paul tells us, which God has been pleased, as it were, to seal by a remarkable promise. There is some difficulty here; for the second commandment likewise contains a promise,

"I am the Lord thy God, who shew mercy unto thousands of them that love me, and keep my commandments." (Exodus 20:5,6.)

But this is universal, applying indiscriminately to the whole law, and cannot be said to be annexed to that commandment.', false, false, 'sourced', 'published');
