-- Calvin commentary INSERT — 1 John (batch 1, rows 1-5)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 62, 1, 1, NULL, '1-john-1', 'John Calvin', 'Commentaries', E'1 That which was from the beginning As the passage is abrupt and involved, that the sense may be made clearer, the words may be thus arranged; "We announce to you the word of life, which was from the beginning and really testified to us in all manner of ways, that life has been manifested in him;" or, if you prefer, the meaning may be thus given, "What we announce to you respecting the word of life, has been from the beginning, and has been openly shewed to us, that life was manifested in him." But the words, That which was from the beginning, refer doubtless to the divinity of Christ, for God manifested in the flesh was not from the beginning; but he who always was life and the eternal Word of God, appeared in the fullness of time as man. Again, what follows as to the looking on and the handling of the hands, refers to his human nature. But as the two natures constitute but one person, and Christ is one, because he came forth from the Father that he might put on our flesh, the Apostle rightly declares that he is the same, and had been invisible, and afterwards became visible.

Hereby the senseless cavil of Servetus is disproved, that the nature and essence of Deity became one with the flesh, and that thus the Word was transformed into flesh, because the life-giving Word was seen in the flesh.

Let us then bear in mind, that this doctrine of the Gospel is here declared, that he who in the flesh really proved himself to be the Son of God, and was acknowledged to be the Son of God, was always God''s invisible Word, for he does not refer here to the beginning of the world, but ascends much higher.

Which we have heard, which we have seen. It was not the hearing of a report, to which little credit is usually given, but John means, that he had faithfully learnt from his Master those things which he taught, so that he alleged nothing thoughtlessly and rashly. And, doubtless, no one is a fit teacher in the Church, who has not been the disciple of the Son of God, and rightly instructed in his school, since his authority alone ought to prevail.

When he says, we have seen with our eyes, it is no redundancy, but a fuller expression for the sake of amplifying; nay, he was not satisfied with seeing only, but added, which we have looked upon, and our hands have handled By these words he shews that he taught nothing but what had been really made known to him.

It may seem, however, that the evidence of the senses little availed on the present subject, for the power of Christ could not be perceived by the eyes nor felt by the hands.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 62, 2, 1, NULL, '1-john-2', 'John Calvin', 'Commentaries', E'1. My little children. It is not only the sum and substance of the preceding doctrine, but the meaning of almost the whole gospel, that we are to depart from sin; and yet, though we are always exposed to God''s judgment, we are certain that Christ so intercedes by the sacrifice of his death, that the Father is propitious to us. In the meantime, he also anticipates an objection, lest any one should think that he gave license to sin when he spoke of God''s mercy, and shewed that it is presented to us all. He then joins together two parts of the gospel, which unreasonable men separate, and thus lacerate and mutilate. Besides, the doctrine of grace has always been calumniated by the ungodly. When the expiation of sins by Christ is set forth, they boastingly say that a license is given to sin.

To obviate these calumnies, the Apostle testifies first that the design of his doctrine was to keep men from sinning; for when he says, that ye sin not, his meaning only is, that they, according to the measure of human infirmity, should abstain from sins. And to the same purpose is what I have already said respecting fellowship with God, that we are to be conformable to him. He is not, however, silent as to the gratuitous remission of sins; for though heaven should fall and all things be confounded, yet this part of truth ought never to be omitted; but, on the contrary, what Christ is ought to be preached clearly and distinctly.

So ought we also to do at this day. As the flesh is inclined to wantonness, men ought to be carefully warned, that righteousness and salvation are provided in Christ for this end, that we may become the holy possession of God. Yet whenever it happens that men wantonly abuse the mercy of God, there are many snarlish men who load us with calumny, as though we gave loose reins to vices. We ought still boldly to go on and proclaim the grace of Christ, in which especially shines forth the glory of God, and in which consists the whole salvation of men. These barkings of the ungodly ought, I repeat it, to be wholly disregarded; for we see that the apostles were also by these barkings assailed.

For this reason he immediately adds the second clause, that when we sin we have an advocate By these words he confirms what we have already said, that we are very far from being perfectly righteous, nay, that we contract new guilt daily, and that yet there is a remedy for reconciling us to God, if we flee to Christ; and this is alone that in which consciences call acquiesce, in which is included the righteousness of men, in which is founded the hope of salvation.

The conditional particle, if, ought to be viewed as causal; for it cannot be but that we sin.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 62, 3, 1, NULL, '1-john-3', 'John Calvin', 'Commentaries', E'1 Behold The second argument is from the dignity and excellency of our calling; for it was not common honor, he says, that the heavenly Father bestowed on us, when he adopted us as his children. This being so great a favor, the desire for purity ought to be kindled in us, so as to be conformed to his image; nor, indeed, can it be otherwise, but that he who acknowledges himself to be one of God''s children should purify himself. And to make this exhortation more forcible, he amplifies the favor of God; for when he says, that love has been bestowed, he means that it is from mere bounty and benevolence that God makes us his children; for whence comes to us such a dignity, except from the love of God? Love, then, is declared here to be gratuitous. There is, indeed, an impropriety in the language; but the Apostle preferred speaking thus rather than not to express what was necessary to be known. He, in short, means that the more abundantly God''s goodness has been manifested towards us, the greater are our obligations to him, according to the teaching of Paul, when he besought the Romans by the mercies of God to present themselves as pure sacrifices to him. (Romans 12:1.) We are at the same time taught, as I have said, that the adoption of all the godly is gratuitous, and does not depend on any regard to works.

What the sophists say, that God foresees those who are worthy to be adopted, is plainly refuted by these words, for, in this way the gift would not be gratuitous. It behooves us especially to understand this doctrine; for since the only cause of our salvation is adoption, and since the Apostle testifies that this flows from the mere love of God alone, there is nothing left to our worthiness or to the merits of works. For why are we sons? Even because God began to love us freely, when we deserved hatred rather than love. And as the Spirit is a pledge of our adoption, it hence follows, that if there be any good in us, it ought not to be set up in opposition to the grace of God, but, on the contrary, to be ascribed to him.

When he says that we are called, or named, the expression is not without its meaning; for it is God who with his own mouth declares us to be sons, as he gave a name to Abraham according to what he was.

Therefore the world It is a trial that grievously assaults our faith, that we are not so much regarded as God''s children, or that no mark of so great an excellency appears in us, but that, on the contrary, almost the whole world treats us with ridicule and contempt.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 62, 4, 1, NULL, '1-john-4', 'John Calvin', 'Commentaries', E'1 Believe not every spirit When the Church is disturbed by discords and contentions, many, as it has been said, being frightened, depart from the Gospel. But the Spirit prescribes to us a far different remedy, that is, that the faithful should not receive any doctrine thoughtlessly and without discrimination. We ought, then, to take heed lest, being offended at the variety of opinions, we should discard teachers, and, together with them, the word of God. But this precaution is sufficient, that all are not to be heard indiscriminately.

The word spirit I take metonymically, as signifying him who boasts that he is endowed with the gift of the Spirit to perform his office as a prophet. For as it was not permitted to any one to speak in his own name, nor was credit given to speakers but as far as they were the organs of the Holy Spirit, in order that prophets might have more authority, God honored them with this name, as though he had separated them from mankind in general. Those, then, were called spirits, who, giving only a language to the oracles of the Holy Spirit, in a manner represented him. They brought nothing of their own, nor came they forth in their own name, but the design of this honorable title was, that God''s word should not lose the respect due to it through the humble condition of the minister. For God would have his word to be always received from the mouth of man no otherwise than if he himself had appeared from heaven.

Here Satan interposed, and having sent false teachers to adulterate God''s word, he gave them also this name, that they might more easily deceive. Thus false prophets have always been wont superciliously and boldly to claim for themselves whatever honor God had bestowed on his own servants. But the Apostle designedly made use of this name, lest they who falsely pretend God''s name should deceive us by their masks, as we see at this day; for many are so dazzled by the mere name of a Church, that they prefer, to their eternal ruin, to cleave to the Pope, than to deny him the least part of his authority.

We ought, therefore, to notice this concession: for the Apostle might have said that every sort of men ought not to be believed; but as false teachers claimed the Spirit, so he left them to do so, having at the same time reminded them that their claim was frivolous and nugatory, except they really exhibited what they professed, and that those were foolish who, being astonished at the very sound of so honorable a name, dared not to make any inquiry on the subject.

Try the spirits As all were not true prophets, the Apostle here declares that they ought to have been examined and tried.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 62, 5, 1, NULL, '1-john-5', 'John Calvin', 'Commentaries', E'2 By this we know He briefly shows in these words what true love is, even that which is towards God. He has hitherto taught us that there is never a true love to God, except when our brethren are also loved; for this is ever its effect. But he now teaches us that men are rightly and duly loved, when God holds the primacy. And it is a necessary definition; for it often happens, that we love men apart from God, as unholy and carnal friendships regard only private advantages or some other vanishing objects. As, then, he had referred first to the effect, so he now refers to the cause; for his purpose is to shew that mutual love ought to be in such a way cultivated that God may be honored.

To the love of God he joins the keeping of the law, and justly so; for when we love God as our Father and Lord, reverence must necessarily be connected with love. Besides, God cannot be separated from himself. As, then, he is the fountain of all righteousness and equity, he who loves him must necessarily have his heart prepared to render obedience to righteousness. The love of God, then, is not idle or inactive.

But from this passage we also learn what is the keeping of the law. For if, when constrained only by fear, we obey God by keeping his commandments, we are very far off from true obedience. Then, the first thing is, that our hearts should be devoted to God in willing reverence, and then, that our life should be formed according to the rule of the law. This is what Moses meant when, in giving a summary of the law, he said,

"O Israel, what does the Lord thy God require of thee, but to love him and to obey him?" (Deuteronomy 10:12.)

3 His commandments are not grievous This has been added, lest difficulties, as it is usually the case, should damp or lessen our zeal. For they who with a cheerful mind and great ardor have pursued a godly and holy life, afterwards grow weary, finding their strength inadequate. Therefore John, in order to rouse our efforts, says that God''s commandments are not grievous.

But it may, on the other hand, be objected and said that we have found it far otherwise by experience, and that Scripture testifies that the yoke of the law is insupportable. (Acts 15:2.) The reason also is evident, for as the denial of self is, as it were, a prelude to the keeping of the law, can we say that it is easy for a man to deny himself? nay, since the law is spiritual, as Paul, in Romans 7:14, teaches us, and we are nothing but flesh, there must be a great discord between us and the law of God.', false, false, 'sourced', 'published');
