-- Calvin commentary INSERT — 2 Timothy (batch 1, rows 1-4)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 55, 1, 1, NULL, '2-timothy-1', 'John Calvin', 'Commentaries', E'1 Paul an Apostle From the very preface we already perceive that Paul had not in view Timothy alone; other wise he would not have employed such lofty titles in asserting his apostleship; for what purpose would it have served to employ these ornaments of language in writing to one who was fully convinced of the fact? He, therefore, lays claim to that authority over all which belonged to his public character and he does this the more diligently, because, being near death, he wishes to secure the approbation of the whole course of his ministry, and to seal his doctrine which he had labored so hard to teach, that it may be held sacred by posterity, and to leave a true portrait of it in Timothy.

Of Jesus Christ by the will of God First, according to his custom, he calls himself an "Apostle of Christ." Hence it follows, that he does not speak as a private person, and must not be heard slightly, and for form''s sake, like a man, but as one who is a representative of Christ. But because the dignity of the office is too great to belong to any man, except by the special gift and election of God, he at the same time pronounces a eulogy on his calling, by adding that he was ordained by the will of God His apostleship, therefore, having God for its author and defender, is beyond all dispute.

According to the promise of life That his calling may be the more certain, he connects it with the promises of eternal life; as if he had said, "As from the beginning God promised eternal life in Christ, so now he has appointed me to be the minister for proclaiming that promise." Thus also he points out the design of his apostleship, namely, to bring men to Christ, that in him they may find life.

Which is in Christ Jesus He speaks with great accuracy, when he mentions that "the promise of life" was indeed given, in ancient times, to the fathers. (Acts 26:6.) But yet he declares that this life is in Christ, in order to inform us that the faith of those who lived under the Law must nevertheless have looked towards Christ; and that life, which was contained in promises, was, in some respects, suspended, till it was exhibited in Christ.

2 My beloved son By this designation he not only testifies his love of Timothy, but procures respect and submission to him; because he wishes to be acknowledged in him, as one who may justly be called his son, The reason of the appellation is, that he had begotten him in Christ; for, although this honor belongs to God alone, yet it is also transferred to ministers, whose agency he employs for regenerating us.

Grace, mercy The word mercy, which he employs here, is commonly left out by him in his ordinary salutations.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 55, 2, 1, NULL, '2-timothy-2', 'John Calvin', 'Commentaries', E'1 Be strong in the grace As he had formerly commanded him to keep, by the Spirit, that which was committed to him, so now he likewise enjoins him "to be strengthened in grace." By this expression he intends to shake off sloth and indifference; for the flesh is so sluggish, that even those who are endued with eminent gifts are found to slacken in the midst of their course, if they be not frequently aroused. Some will say: "Of what use is it to exhort a man to be strong in grace,'' unless free-will have something to do in cooperation?" I reply, what God demands from us by his word he likewise bestows by his Spirit, so that we are strengthened in the grace which he has given to us. And yet the exhortations are not superfluous, because the Spirit of God, teaching us inwardly, causes that they shall not sound in our ears fruitlessly and to no purpose. Whoever, therefore, shall acknowledge that the present exhortation could not have been fruitful without the secret power of the Spirit, will never support free-will by means of it. Which is in Christ Jesus. This is added for two reasons; to shew that the grace comes from Christ alone, and from no other, and that no Christian will be destitute of it; for, since there is one Christ common to all, it follows that all are partakers of his grace, which is said to be in Christ, because all who belong to Christ must have it. My son. This kind appellation, which he employs, tends much to gain the affections, that the doctrine may more effectually obtain admission into the heart. 2 And which thou hast heard from me. He again shews how earnestly desirous he is to transmit sound doctrine to posterity; and he exhorts Timothy, not only to preserve its shape and features, (as he formerly did,) but likewise to hand it down to godly teachers, that, being widely spread, it may take root in the hearts of many; for he saw that it would quickly perish if it were not soon scattered by the ministry of many persons. And, indeed, we see what Satan did, not long after the death of the Apostles; for, just as if preaching had been buried for some centuries, he brought in innumerable reveries, which, by their monstrous absurdity, surpassed the superstitions of all the heathens. We need not wonder, therefore, if Paul, in order to guard against an evil of such a nature and of such magnitude, earnestly desires that his doctrines shall be committed to all godly ministers, who shall be qualified to teach it. As if he had said, -- "See that after my death there may remain a sure attestation of my doctrine; and this will be, if thou not only teach faithfully what thou hast learned from me, but take care that it be more widely published by others; therefore, whomsoever thou shalt see fitted for that work,', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 55, 3, 1, NULL, '2-timothy-3', 'John Calvin', 'Commentaries', E'1 But know this By this prediction he intended still more to sharpen his diligence; for, when matters go on to our wish, we become more careless; but necessity urges us keenly. Paul, therefore informs him, that the Church will be subject to terrible diseases, which will require in the pastors uncommon fidelity, diligence, watchfulness, prudence, and unwearied constancy; as if he enjoined Timothy to prepare for arduous and deeply anxious contests which awaited him. And hence we learn, that, so far from giving way, or being terrified, on account of any difficulties whatsoever, we ought, on the contrary. to arouse our hearts for resistance.

In the last days Under "the last days," he includes the universal condition of the Christian Church. Nor does he compare his own age with ours, but, on the contrary, informs Timothy what will be the future condition of the kingdom of Christ; for many imagined some sort of condition that would be absolutely peaceful, and free from any annoyance. In short, he means that there will not be, even under the gospel, such a state of perfection, that all vices shall be banished, and virtues of every kind shall flourish; and that therefore the pastors of the Christian Church will have quite as much to do with wicked and ungodly men as the prophets and godly priests had in ancient times. Hence it follows, that there is no time for idleness or for repose.

2 For men will be It is proper to remark, first, in what he makes the hardship of those "dangerous" or "troublesome" times to consist; not in war, nor in famine, nor in diseases, nor in any calamities or inconveniences to which the body is incident, but in the wicked and depraved actions of men. And, indeed, nothing is so distressingly painful to godly men, and to those who truly fear God, as to behold such corruptions of morals; for, as there is nothing which they value more highly than the glory of God, so they cannot but suffer grievous anguish when it is attacked or despised.

Secondly, it ought to be remarked, who are the persons of whom he speaks. They whom he briefly describes are not external enemies, who openly assail the name of Christ, but domestics, who wish to be reckoned among the members of the Church; for God wishes to try his Church to such an extent as to carry within her bosom such plagues, though she abhors to entertain them. So then, if in the present day many whom we justly abhor are mingled within us, let us learn to groan patiently under that burden, when we are informed that this is the lot of the Christian Church.

Next, it is wonderful that those persons, whom Paul pronounces to be guilty of so many and so aggravated acts of wickedness, can keep up the appearance of piety, as he also declares.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 55, 4, 1, NULL, '2-timothy-4', 'John Calvin', 'Commentaries', E'1 I charge thee, therefore, before God and the Lord Jesus Christ It is proper to observe carefully the word therefore, by means of which he appropriately connects Scripture with preaching. This also refutes certain fanatics, who haughtily boast that they no longer need the aid of teachers, because the reading of scripture is abundantly sufficient. But Paul, after having spoken of the usefulness of Scripture, infers not only that all ought to read it, but that teachers ought to administer it, which is the duty enjoined on them. Accordingly, as all our wisdom is contained in the Scriptures, and neither ought we to learn, nor teachers to draw their instructions, from any other source; so he who, neglecting the assistance of the living voice, shall satisfy himself with the silent Scripture, will find how grievous an evil it is to disregard that way of learning which has been enjoined by God and Christ. Let us remember, I say, that the reading of Scripture is recommended to us in such a manner as not to hinder, in the smallest degree, the ministry of pastors; and, therefore, let believers endeavor to profit both in reading and in hearing; for not in vain hath God ordained both of them.

Here, as in a very weighty matter, Paul adds a solemn charge, exhibiting to Timothy, God as the avenger, and Christ as the judge, if he shall cease to discharge his office of teaching. And, indeed, in like manner as God showed by an inestimable pledge, when he spared not his only-begotten Son, how great is the care which he has for the Church, so he will not suffer to remain unpunished the negligence of pastors, through whom souls, which he hath redeemed at so costly a price, perish or are exposed as a prey.

Who shall judge the living and the dead More especially the Apostle fixes attention on the judgment of Christ; because, as we are his representatives, so he will demand a more strict account of evil administration. By "the living and the dead" are meant those whom he shall find still alive at his coming, and likewise those who shall have died. There will therefore be none that escape his judgment.

The appearance of Christ and his kingdom mean the same thing; for although he now reigns in heaven and earth, yet hitherto his reign is not clearly manifested, but, on the contrary, is obscurely hidden under the cross, and is violently assailed by enemies. His kingdom will therefore be established at that time when, having vanquished his enemies, and either removed or reduced to nothing every opposing power, he shall display his majesty.

2 Be instant in season, out of season By these words he recommends not only constancy, but likewise earnestness, so as to overcome all hindrances and difficulties; for, being, by nature, exceedingly effeminate or slothful, we easily yield to the slightest opposition, and sometimes we gladly seek apologies for our slothfulness.', false, false, 'sourced', 'published');
