-- Calvin commentary INSERT — Ezekiel (batch 2, rows 11-20)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 11, 1, NULL, 'ezekiel-11', 'John Calvin', 'Commentaries', E'1. Moreover, the Spirit lifted me up, and brought me unto the east gate of the LORD''S house, which looketh eastward: and behold at the door of the gate five and twenty men; among whom I saw Jaazaniah the son of Azur, and Pelatiah the son of Benaiah, princes of the people.

1. Et sustulit me Spiritus et introduxit me ad portam domus Iehovae orientalera: et ecce in limine portae vigintiquinque viri: et aspexi in medio ipsorum Iaazaniah filium Azur, et Pelthiah filium Benaiah, principes populi.

2. Then said he unto me, Son of man, these are the men that devise mischief, and give wicked counsel in this city:

2. Et dixit ad me, Fili hominis, isti homines cogitant vanitatem, et consultant consilium perversum in urbe hae.

Here the Prophet admonishes the people that perverse leaders would be the cause of their destruction. For if the blind lead the blind both will fall into the ditch (Matthew 15:14; Luke 6:39.) Since, therefore, the elders of the city were such wicked apostates, they drew with them the whole body of the people into the same ruin. Now, therefore, the Prophet shows that the state of the city was so corrupt that no hope of pardon remained, since those who ought to be the eyes of the whole people were involved in darkness. But he names the five and twenty seniors Whence it is probable, that this number was chosen in the midst of confusion, or that a definite number is put for an indefinite; and I rather embrace this second view. Whatever it is, it implies that those who held the reins of government were impious despisers of God, and hence it is not surprising that impiety and defection from God and his law had begun to increase among the whole people. But we must remark the Prophet''s intention. For common soldiers are accustomed to consider their commanders as a shield, as we this day see in the Papacy. For this is their last refuge, since they think themselves guilty of no fault when they obey their holy Mother Church. Such also formerly was the obstinacy of the people.

Lastly, men always throw off all blame from themselves, under pretense of error or ignorance. Hence the Prophet now shows that the city was not free from God''s wrath, since it was corrupted by its leaders and rulers; nay, that this was a cause of its destruction, since the people were too easily led astray by perverse examples. Meanwhile, we must notice the Prophet''s freedom, because he here fearlessly attacks the most noble princes. He was, indeed, out of danger, because he was an exile: but it seems that he was at Jerusalem when he uttered this prophecy. He shows, therefore, his strength of mind, since he does not spare the nobles. Hence this useful doctrine is collected, that those who excel in reputation and rank are not free from blame if they conduct themselves wickedly, as we see happens in the Papacy.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 12, 1, NULL, 'ezekiel-12', 'John Calvin', 'Commentaries', E'1. The word of the LORD also came unto me, saying,

1. Et fuit sermo Iehovae ad me dicendo,

2. Son of man, thou dwellest in the midst of a rebellious house, which have eyes to see, and see not; they have ears to hear, and hear not: for they are a rebellious house.

2. Fili hominis, in medio domus rebellis tu habitas, oculi illis ad videndum, et non vident: aures illis ad audiendum, et non audiunt: quia domus rebellis ipsi.

Because God was about to give a command to his servant, he wished to inspire him with fortitude of mind, lest, when he saw that he was consuming his labor in vain, he should withdraw from his course. For we know how severe is that temptation to God''s servants when they speak to the deaf, and not only is their doctrine rejected but even refused with ignominy. They think, therefore, that nothing is better than silence, because where their word is so despised it only exposes the name of God to the reproaches of the impious. Now then we understand for what purpose God admonishes his Prophet about the contumacy of the nation. The Prophet had tried enough, and more than enough, how unmanageable the Israelites were, but God confirms by his judgment what the Prophet had discovered sufficiently in practice. Then we must observe another reason, for God not only commanded his Prophet what to say, but he added an outward symbol, as we shall see. But the Prophet might object, that it would be ridiculous to take a staff, and scrip, and hat, as a traveler about to commence a journey. Nor is it doubtful that the Israelites derided through perverseness what he was doing, as a boyish amusement.

Lest, therefore, the Prophet should think what he was commanded to do absurd, God instructs him, and gives him the reason of his plan. He says, therefore, the house of Israel is rebellious, and then he expresses the greatness of their contumacy, namely, that they are deaf, though endued with ears: that they are blind, and yet do not want eyes God here shows that the Israelites could not defend their error, as if they had sinned without consideration; but he assigns their neither hearing nor seeing to their obstinacy. And this must be diligently remarked, because hypocrites, when convicted, catch as much as possible at this excuse, that they fell through error or ignorance. But God on the contrary here pronounces that the Israelites were blind and deaf, and shows that their blindness was voluntary. When, therefore, unbelievers pretend that they have not been illuminated by the Lord, it may be conceded to them that they are blind and deaf: but we must often proceed beyond this, since their own obstinacy is the fountain of their blindness and deafness: and God blinds them, because they will not admit the light offered them, but stop their ears.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 13, 1, NULL, 'ezekiel-13', 'John Calvin', 'Commentaries', E'1. And the word of the LORD came unto me, saying,

1. Et fuit sermo Iehovae ad me, dicendo,

2. Son of man, prophesy against the prophets of Israel that prophesy, and say you unto them that prophesy out of their own hearts, Hear you the word of the LORD;

2. Fili hominis, prophetiza contra prophetas Israel prophetizantes, et dic prophetizantibus ex corde suo, Audite sermonem Iehovah.

3. Thus says the Lord GOD, Woe unto the foolish prophets, that follow their own spirit, and have seen nothing!

3. Sic dicit Dominator Iehovah, Vae super prophetas stultos qui ambulant post spiritum suum: et non viderunt.

He speaks of the exiled prophets, as will be evident from the context: for among the captives there were those who assumed the name of God, boasting themselves endowed with the prophetic spirit: but meanwhile they intruded into the office, and then vainly boasted in their deceptions. But the end which they proposed to themselves was to promise the people a speedy return, and so to will the favor of the multitude. For the captives were already almost broken-hearted by weariness: and seventy years was a long period. When therefore they heard of returning after three years, they easily suffered themselves to be deceived by such blandishments. But although God is so vehemently enraged against those impostors, it does not therefore follow that when he charges them with their crime, he absolves the people, or even extenuates their fault. Nor could the people object that they were deceived by those falsehoods, since they willingly and knowingly threw themselves into the snare. They were not destitute of true prophets; and God had distinguished his servants from false prophets by well-known marks, so that no one could mistake except willfully. (Deuteronomy 13:3.) But in the midst of light they blinded themselves, and so God suffered them to be deceived. But that was the just reward of their pride, since they could not be subject to God and his servants. Then when they thought enticements, as is evident from many passages, God also gave the reins to Satan, that there should be a lying spirit in the mouth of all the prophets. Micah reproves them because they desired prophets to be given them who should promise large grape-gatherings and a plentiful harvest, (Micah 2:11;) meanwhile, when God chastised them severely, they roared and were tumultuous. We see, therefore, that while God inveighs so sharply against false prophets, the people''s fault was not diminished; but rather each thought thus to reason with himself -- if God spares not our prophets, what better have we to hope for?

When therefore the Prophet turns his discourse to the false prophets, there is no doubt of his intention to reprove the whole people for attending to such fallacies while they despised the true doctrine, and not only so, but even rejected it with fury. Say therefore to the prophets of Israel while prophesying, say to those prophesying out of their own hearts.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 14, 1, NULL, 'ezekiel-14', 'John Calvin', 'Commentaries', E'1. Then came certain of the elders of Israel unto me, and sat before me.

1. Et venerunt ad me viri ex senioribus Israel, et sederunt coram facie mea.

2. And the word of the LORD came unto me, saying,

2. Et fuit sermo Iehovae ad me, dicendo,

3. Son of man, these men have set up their idols in their heart, and put the stumblingblock of their iniquity before their face: should I be inquired of at all by them?

3. Fili hominis, viri isti ascendere fecerunt idola sua super cor suum, et offendiculum iniquitatis suae posuerunt coram facie sua. An quaerendo quaerar ipsis?

Here Ezekiel relates an event worthy of notice. For this was not a mere vision, but a real transaction, since some of the elders of Israel came to him for the sake of consultation. He says that he sat, as men who are perplexed and astonished by evils are accustomed to do, when they see no remedy. The gesture then which the Prophet describes was a sign of anxiety and despair. A person wishing for an answer is said to sit before another; but since it is probable that they disputed among themselves about beginning, and did not immediately discover how they should commence, hence they became anxious to consult the Prophet. Ezekiel, indeed, might be touched and softened by pity when he saw them seeking God in this way. For this was a sign of repentance when they turned to the true and faithful servant of God. But since they had no sincerity, the Prophet is warned in time against supposing them to come with cordiality. Hence God instructs his servant not to give way with too much facility when he sees old men coming to be disciples. But he shows their hypocrisy, because superstition still reigned in their hearts; nay, they desired openly to violate God''s law, and they did not disguise this feeling whenever occasion offered. First, he says they have set up idols in their hearts; by which words he means that they were addicted to superstition, so that idols obtained a high rank in their hearts; as Paul exhorts the faithful, that the peace of God which passes all understanding may obtain the rule in their hearts (Philippians 4:7; Colossians 3:15); so on the other hand the Prophet says that these men had given supreme sway to idols. And again an implied comparison must be remarked between God and idols. For God has erected the seat of his empire in our hearts: but when we set up idols, we necessarily endeavor to overthrow God''s throne, and to reduce his power to nothing. Hence the most heinous crime of sacrilege is here shown in those old men who caused idols to rise above their hearts. For hence it follows that all their senses were drowned in their superstitions.

He adds, they placed the stumblingblock of their iniquity before his face.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 15, 1, NULL, 'ezekiel-15', 'John Calvin', 'Commentaries', E'1. And the word of the LORD came unto me, saying,

1. Et fuit sermo Iehovae ad me dicendo,

2. Son of man, What is the vine-tree more than any tree, or than a branch which is among the trees of the forest?

2. Fili hominis, quid erit lignum vitis prae omni arbore rami quae est inter arbores sylvae?

3. Shall wood be taken thereof to do any work? or will men take a pin of it to hang any vessel thereon?

3. An sumetur ex eo lignum ad formandum, ut sit opus, vel an sument, ex eo paxillum, ut suspendatur in eo omne vas?

4. Behold, it is cast into the fire for fuel; the fire devoureth both the ends of it, and the midst of it is burned. Is it meet for any work?

4. Ecce in ignem traditur ad consumptionem, duas extremitates ejus consumpsit ignis, et medium ejus exustum est, an utile erit ad opus?

5. Behold, when it was whole, it was meet for no work: how much less shall it be meet yet for any work, when the fire hath devoured it, and it is burned?

5. Ecce, cum esset integrum non factum fuit ut esset opus: quanto magis postquam ignis consumpsit ipsum et exaruit formabitur adhuc ut sit opus?

The Prophet''s intention is to humble the foolish confidence of the people, who boasted of the gratuitous kindness of God, as if they were naturally excellent: hence, also, their obstinacy against his threats was so great. For when the prophets reprove them sharply, they boasted against them the remarkable gifts by which they were divinely adorned: as if they had been so armed by God''s benefits to resist his power, for we know that they were so blinded. Since, then, that disease had attacked the people, it is not surprising that the prophets in many places refute such folly. But the Prophet here uses a simile to show the Jews that they were not intrinsically but only accidentally excellent, since God had treated them as worthy of remarkable benefits. Since it is so, their arrogance is easily refuted, when they oppose their superiority to God, as if it were peculiar to them, and not God''s special gift. But we must understand the simile which Ezekiel uses: what is the vine more than other trees of the woods? It is certain that the vine produces very good fruit, and therefore is preferred to other trees: the very flower of the vine has a most, delicious scent; but the fruit which it produces proves its excellence. For the wood of the vine is without elegance and shapeless: it does not attain to any thickness; it is slender, pliable, and twisted. In looking at a vine, it. seems scarcely worth numbering among shrubs: if compared with trees, it clearly has no value; but in the excellency of trees something is easily acknowledged which surpasses all vines.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 16, 1, NULL, 'ezekiel-16', 'John Calvin', 'Commentaries', E'The allegory which runs through this chapter is by no means an unusual one in the Prophets. The beginning of Ezekiel 16:3 has occasioned some variety of remark. OEcolampadius takes mkvrh, mekoreh, meaning "birth," "origin," for mgvrh, megoreh, meaning "dwelling;" as Calvin translates it habitationes. Houbigant derives it from krh, kereh, "to dig," which Newcome prefers: it may come from mkr, meker, "to sell," and thus means "dealings;" but this is not so appropriate here. Rosenmuller reviews these derivations, adding as another, viz. formationes; but approves of the sense "origin," effossione, from kvr, cor, "to dig." This is clearly the best, the Jews having constantly before them the digging out of a rock -- as in Isaiah 51:1. Both Theodoret and Jerome explain Ezekiel 16:3 with precision'' the former has -- arais gar ho Chanaan hupeblethe kai douleian hupo tou propatoros Noe katedikasthe; the latter writes -- Cham quippe, pater Chanaan, princeps fuit gentis Aegvptiae... radicem Ierusalem terram AEgypti esse dicemus. In Ezekiel 16:4 the salting and swaddling the body is said to represent the Almighty''s care of the people when under Egyptian bondage. The custom of throwing the skirt over the female is alluded to by Theocritus Idyll. 18:19; and a fragment of Euripides preserved by Stobaeus. This cleansing from pollution is explained by the Chaldee paraphrast to mean the deliverance from Egypt. Those who are curious in the various articles of clothing in Ezekiel 16:10 to 14 may consult Schroeder de Vestitu Mul., chapter 14 page 221; Bochart Hieroz., part 1 lib. 3.; Jablonskii Opuscula, t. 1 p 290, etc.; and J. D. Michaelis in Suppl., page 1565. "The images of men," (Ezekiel 16:17,) Jerome interprets of the idols of Bel, Chemosh, and Ashtoreth, which were made out of the sacred gold and silver of the temple. The passing through the fire, (Ezekiel 16:21,) the Vulgate renders consecrans illos; but Aquila, Synmachus, and Theodotion take the same view as Calvin. Theodoret interprets the 26th verse of the grossness of the Egyptian idolatry in worshipping the ibis, the cow and the crocodile. The punishment of the Jews (Ezekiel 16:36-43) is figuratively predicted by similar language, which Theodoret clearly illustrates -- ou gunaikas tas gunaikas onomazei alla tropikos tas poleis outo kalei epaide kai auten polin ousan diken gunaikos eis to dikasterion eisagei The comment of OEcolampadius on Ezekiel 16:20 and Ezekiel 16: 23 is copious and instructive.

b CAPTIVE ISRAEL AND PAPAL ROME.

In commenting on this verse, Calvin draws a striking comparison between the Jews of Ezekiel''s day and the Romanists of his own. And as the controversy with Rome is at present a subject of absorbing interest, it is very important to ascertain the exact views of the Reformers as to that giant apostacy. The parallel between them seems to our Reformer most complete. He allows both to be true Churches, while he condemns them as breakers of God''s covenant.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 17, 1, NULL, 'ezekiel-17', 'John Calvin', 'Commentaries', E'1. And the word of the LORD came unto me, saying,

1. Et fuit sermo Iehovae ad me, dicendo,

2. Son of man, put forth a riddle, and speak a parable unto the house of Israel;

2. Fili hominis, aenigmatisa aenigma, et proverbia proverbium ad domum Israel.

In this chapter the Prophet shows that the Jews were utterly foolish in thinking themselves safe, since they had God as their adversary. At the end of the chapter he promises indeed the restoration of the Church, and heralds the kingdom of Christ: but the principal part of the chapter is consumed with this teaching, that the Jews were utterly foolish in promising themselves safety for the city, the temple, and their kingdom: for, as it now appeared, they had violated the covenant of God and he had rejected them. When deprived of God''s help, what could they do? This was egregious folly to hope for a prosperous state of their kingdom when their power was diminished and cut off, and they were reduced almost to the very last straits. But since the Prophet''s discourse came be understood without a knowledge of the history, I shall therefore make a beginning: When Nebuchadnezzar appointed Zedekiah king, he also made him tributary to himself. He was made king at the will or rather by the lust of the king of Babylon, when Jeconiah was led captive. (2 Kings 24:15-17; 2 Chronicles 36:10; Jeremiah 37:1.) Jeconiah had not sinned greatly, but when he saw himself unable to resist, he surrendered himself with his mother and children; he was carried away to Babylon, and there was treated humanely and even splendidly, although not royally. Nebuchadnezzar, foreseeing much trouble if he set any of his satraps over Judea, and fearing daily tumults, appointed Mattaniah king, to whom he gave the name Zedekiah; this was the last king: already, as I have said, the royal dignity was greatly diminished: it was tributary to Nebuchadnezzar, and Zedekiah''s sway was but precarious. His position depended on the will of his conqueror, and he who placed him on the throne could remove him as often as he pleased. A little while afterwards, when he saw that Nebuchadnezzar was at a distance, he made an agreement with the king of Egypt, and thought he should have sufficient help if Nebuchadnezzar were to return again with an army. And the Egyptians, as we have elsewhere said, were sufficiently desirous of this treaty. For they saw the Babylonian monarchy gradually increasing, and it was probable that, when the Jews were utterly subdued, Nebuchadnezzar would not be content with those boundaries, but would attack Egypt in like manner, and absorb that kingdom, as he had done others. Hence a reason for their entering into the treaty was at hand, since the king of Egypt thought that Judea would be a defense if Nebuchadnezzar should come down with his army: and certainly the Jews must receive the assault first.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 18, 1, NULL, 'ezekiel-18', 'John Calvin', 'Commentaries', E'1. The word of the LORD came unto me again, saying,

1. Et fuit sermo Iehova, ad me, dicendo,

2. What mean ye, that ye use this proverb concerning the land of Israel, saying, The fathers have eaten sour grapes, and the children''s teeth are set on edge?

2. Quid vobis? vos proverbiantes proverbium super terram Israel, dicendo, Patres comederunt omphacem, et dentes filiorum obstupescunt.

3. As I live, saith the Lord GOD, ye shall not have occasion any more to use this proverb in Israel.

3. Vivo ego, dicit Dominator Iehovah, Si erit vobis amplius qui utatur hoc dicterio in Israele.

4. Behold, all souls are mine; as the soul of the father, so also the soul of the son is mine: the soul that shineth, it shall die.

4. Ecce omnes animae mihi, sicut anima patris sic anima filii mihi. Anima quae peccaverit ipsa morietur.

We may collect from this rebuke that the Jews were perverse interpreters of the best teaching; yea, they purposely reviled the Prophet''s expression, and drew it to a contrary meaning. For it, is far commoner than it ought to be among unbelievers, always to take occasion of turning backwards, twisting, distorting, and tearing the teaching of heaven. And at this time we see this impudence increasing greatly in the world. For the world is full of buffoons and other deceivers, who wickedly sport with God, and seek material for joking from the law and the gospel: and so also it appears to have been in the Prophet''s time; for although they listened to the wrath of God hanging over them, they did not cease to provoke him, and that too for many years. And not only were their own iniquities set forth against them, but also those of their fathers: hence the occasion for cavil when they heard -- For so many ages you do not cease your warfare against God: he has borne with you patiently unto this day. Do you think that you can carry on your audacity with impunity? God wished hitherto to tame you by his forbearance; but your obstinacy is not to be subdued. Since, therefore, not only for one or two generations, but for four and five, your obstinacy has wrestled with God''s goodness, he cannot any longer pardon you. Since the prophets thus gathered up the iniquities of their fathers, impious men scattered abroad their witticisms -- then we are to pay the penalty of our fathers'' sins: they provoked God, but we suffer the punishment which they deserved. The Prophet now convinces them of this unfairness, and shows that they had no reason for transferring their faults to others, or to thrust them away from themselves, since God was just in taking vengeance on them. We know that men willingly shuffle so as to free themselves from blame, and then afterwards accuse God of cruel injustice.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 19, 1, NULL, 'ezekiel-19', 'John Calvin', 'Commentaries', E'1. Moreover take you up a lamentation for the princes of Israel,

1. Et tu tolle lamentu super principes Israel,

2. And say, What is thy mother? A lioness: she lay down among lions, she nourished her whelps among young lions.

2. Et dices, Quare mater vestra leaena inter leones occubuit? in medio leonum educavit catulos suos.

3. And she brought up one of her whelps: it became a young lion, and it learned to catch the prey; it devoured men.

3. Et sustulit unum e catulis suis, leo factus est, et didicit praedari praedam, homines comedit.

4. The nations also heard of him; he was taken in their pit, and they brought him with chains unto the land of Egypt.

4. Et audierunt de ipso Gentes, in fovea ipsarum captus est; et abduxerunt in cathenis in terram AEgypti.

Here the Prophet, under the image of a lion, informs us that whatever evils happened to the Israelites could not be imputed to others. We must understand then his intention: it is not surprising that the Spirit of God insists on a matter not very obscure, since nothing is more obstinate than the pride of men, especially when God chastises them, although they pretend to humility and modesty, yet they swell with pride and are full of bitterness, and, lastly, they can scarcely be induced to confess God to be just, and that they deserve chastisement at his hand. For this reason, therefore, Ezekiel confirms what we formerly saw, that the Jews were not afflicted without deserving it. But he uses, as I have said, a simile taken from lions. He calls the nation itself a lioness: for when he treats of the mother of the people, we know that the offspring is considered. He says, therefore, that the people was full of insolence. The comparison to a lion is sometimes taken in a good sense, as when Moses uses it of the tribe of Judea, as a lion''s whelp shall he lie down, (Genesis 49:9,) a, phrase used in a good sense. But here Ezekiel denotes cruelty, as if he had said that all the Jews were fierce and savage beasts. For under the name of mother, as I said, he embraces the whole nation. At the beginning he orders his Prophet to take up a mournful wailing: for thus I interpret the word qynh, kineh, but there is in my judgment an indirect opposition between this lamentation which God dictated to them by his Prophet, and the common complaints which sounded constantly from their tongues. For when their condition was not only ruinous, but utterly deplorable, they made many groanings and bewailings. But at the same time no one extended his thoughts beyond the pressure of present evils they all exclaimed that they were wretched, but no one was anxious to inquire why they were so or whence their miseries arose; nay, they avoided this contemplation.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 26, 20, 1, NULL, 'ezekiel-20', 'John Calvin', 'Commentaries', E'1. And it came to pass in the seventh year, in the fifth month, the tenth day of the month, that certain of the elders of Israel came to inquire of the LORD, and sat before me.

1. Et fuit anno septimo, quinto mense, decimo mensis venerunt viri e senioribus Israel ad consulendum Jehovam: et sederunt coram facie mea.

Here he does not narrate a vision but an event which really happened. It is a simple historical narrative, that some of the elders of Israel were chosen to interrogate him. We know this to be customary, and when God separates His people from the profane nations, he opposes his prophets to the soothsayers and magi, augurs and astrologers. For he says that the Gentiles inquire what concerns them in various ways, and so interrogate their deities; but that he prescribes to the chosen people but one method: I will raise for them a prophet from the midst of their brethren, says Moses, (Deuteronomy 18:18;) that is, they need not wander about, like the wretched gentiles, destitute of counsel, first to their soothsayers, then to magi, and then to astrologers: there is no end to them'' but I will meet them, says he, by my prophets, who shall always exist among the people. In this sense Ezekiel says that the elders of Israel came to consult God. The verb, drs, deresh, properly signifies "to seek" but it is here received for "to consult" or "inquire into," as in many other places. Now it is not surprising that the elders came by public consent to the Prophet: for the Israelites were already worn out by long weariness, and thought that they had almost perished through their long exile. But there was another reason, since false prophets, as we saw, tickled the ears of the simple by offering them daily some new hope. Since therefore they were agitated between hope and fear, and the devil scattered false prophecies which distracted the minds of the vulgar, it is probable that the elders of Israel came and were sent to inquire concerning either the prosperous or disastrous event of their captivity. They come therefore to the prophets; he says it happened in the seventh year, that is, after the captivity of Jehoiakim. They reckoned the years from that change, and deservedly so: for so remarkable an act of God''s vengeance ought to be kept constantly in remembrance. There was also another reason, since God gave some hope of restoration. The reckoning of the years, then, which the Israelites dated from Jehoiakim''s exile, had a twofold use and end, first, that God''s judgment might remain fixed in their minds, and next, that they might nevertheless refresh their spirits by the hope of good. Hence as often as they dated the first year or the second, it was just as if they kept before their eyes that slaughter by which God testified himself grievously offended.', false, false, 'sourced', 'published');
