-- Calvin commentary INSERT — Leviticus (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 1, 1, NULL, 'leviticus-1', 'John Calvin', 'Commentaries', E'1. And the Lord called unto Moses. In these seven chapters Moses will treat generally of the sacrifices. But since we read of many things here, the use of which has passed away, and others, the grounds of which I do not understand, I intend to content myself with a brief summary, from whence, however, the reader may fully perceive that whatever has been left to us relative to the legal sacrifices is even now profitable, provided we are not too curious. Let those who choose to hunt for allegories receive the praise they covet; my object is only to profit my readers, and it will suffice briefly to sum up what I think useful to be known. Although in this chapter burnt-offerings only are treated of, yet the rule which is laid down respecting them has a more extensive application, since Moses teaches what animals God would have offered to Him, so as that they may be acceptable, and also by whom and with what ceremonies they are to be offered. He enumerates three kinds, of the herd, of the flocks, and of fowls; for the case of the red heifer, from which the ashes of atonement were made, was different and peculiar; and here the question is as to the ordinary sacrifices, by which private individuals used either to atone for their sins or to testify their piety. He commands, therefore, that the cattle as well as the lambs and kids should be males, and also perfect and free from all blemish. We see, then, that only clean animals were chosen for the sacrifices, and again that all clean animals did not please God, but only domestic ones, such as allow themselves to be directed by the hand and will of men. For, though deer and roes are sometimes tamed, yet God did not admit them to His altar. This, then, was the first rule of obedience, that men should not offer promiscuously this or that victim, but bulls or bull-calves of their herds, and male lambs or kids of their flocks. Freedom from blemish is required for two reasons; for, since the sacrifices were types of Christ, it behooved that in all of them should be represented that complete perfection of His whereby His heavenly Father was to be propitiated; and, secondly, the Israelites were reminded that all uncleanness was repudiated by God lest his service should be polluted by their impurity. But whilst God exhorted them to study true sincerity, so he abundantly taught them that unless they directed their faith to Christ, whatsoever came from them would be rejected; for neither would the purity of a brute animal have satisfied Him if it had not represented something better. In the second place, it is prescribed that whosoever presented a burnt-offering should lay his hand on its head, after he had come near the door of the tabernacle.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 2, 1, NULL, 'leviticus-2', 'John Calvin', 'Commentaries', E'1. And when any will offer. In this chapter Moses prescribes the rules for those offerings to which the name of minha is peculiarly given. They were not bloody sacrifices, nor offerings of animals, but only of cakes and oil. If any one would offer plain flour, he is commanded to season it with frankincense and oil, and also to choose fine flour, that the oblation may not be defiled by the bran. Thus here, as in all the service of God, the rule is laid down that nothing but what is pure should be offered; besides, by the oil its savor is improved, and by the frankincense a fragrant odor is imparted to it. We know that God is not attracted either by sweetness of taste nor by pleasant scents; but it was useful to teach a rude people by these symbols, lest they should corrupt God''s service by their own foolish inventions. Moses afterwards commands, that whatever is consecrated to God should be delivered into the hand of the priest, as we have before seen that private persons were excluded from this honor so that Christ''s peculiar dignity should remain to Him, i.e., that by Him alone access should be sought to God, and that all men might know that no worship pleases God except what He sanctifies. The substance of this type is shewn by the words of the Apostle, when he says that "by him" we now "offer the sacrifice of praise to God continually, that is, the fruit of our lips giving thanks to His name." (Hebrews 13:15.) But when the priest had burnt a handful of the flour with the oil and frankincense, what remained was left for his own use; for, as we have elsewhere seen, the holy of holies of the burnt-offerings were given to the priests. Other kinds are then spoken of, viz., cakes, baken in the oven; then such as were fried in a pan; and thirdly, on a gridiron: for God would have the minha offered Him of every kind of cake, so that the Israelites might learn to look to Him in all their food, since nothing is clean to us except what He consecrates by His blessing. This is the reason why Moses accurately distinguishes between the cakes which were cooked either in the oven, or the frying-pan, or on the gridiron.

11. No meat-offering, which ye shall bring. God here forbids leavened cakes to be offered to Him, by which rite the ancients were taught that God''s service is corrupted if any strange invention be mingled with it. Nor can it be doubted but that. Christ alluded to this when He warned His disciples to "beware of the leaven of the Pharisees," (Matthew 16:11;) understanding by that word the fictions whereby they had corrupted religion.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 3, 1, NULL, 'leviticus-3', 'John Calvin', 'Commentaries', E'1. And if his oblation be a sacrifice. He now proceeds to a different class, viz., to the sacrifices, which were testimonies of gratitude in celebration of God''s blessings; part of which was burnt with fire, part was claimed by the priests, and the rest remained to the offerers themselves. As to the word slmym, shelomim, I have briefly given my opinion elsewhere; the common translation of it is certainly unsuitable, "the sacrifices of peace-offerings:" and the statement of others is far-fetched, that they are called "sacrifices of perfections," because it was unlawful for the unclean to touch them. Since, however, the Hebrews include in the word "peace," safety, and all good success, I have thought that its plural number might aptly be translated "prosperities:" on which account, David calls the libation which used to be made in this sacrifice, "the cup of salvations:" (Psalm 116:13,) nor do I doubt but that by this outward sign he designates thanksgiving. I admit indeed that this sacrifice was not only offered in acknowledgment of gratitude, but also when they sought of God peace and good success; yet still the epithet will always admirably suit it, because they confessed by it that God was the author of all good things, so as to attribute all their prosperity to Him. First, however, he commands all the sacrifices to be brought to the tabernacle, which is what he means by "the face of God;" else would altars have been everywhere erected in their cities and villages, and by this license God''s service would have been mangled, and religion undermined. Wherefore, in order to keep the people in the unity of the faith, he bids them all be content with a single altar. But He would be worshipped and honored in that place, which He had dedicated to Himself, lest they should be scattered abroad after strange gods; and then He prescribes the mode of offering, whether the victim were of the herd or the flock. That such exact injunctions should be given as to trifles, might seem to be an unnecessary particularity, and even a superfluous repetition, inasmuch as the same thing is often inculcated, in precisely similar words: if it were not that this earnestness reminded the people that something higher was enwrapped in the ceremonies, whilst it restrained them from allowing themselves wantonly to add or change the smallest point. This very scrupulous observance, then, ought to have led them by the hand, as it were, to the things signified; so that under the external image the spiritual truth might meet their eyes; secondly, it ought to have held them bound, as it were, to the word of God, lest they should do anything in sacred matters from the dictates of their own reason.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 5, 1, NULL, 'leviticus-5', 'John Calvin', 'Commentaries', E'1. And if a soul sin. The three kinds of offense, to which Moses refers in the beginning of the chapter, seem to differ much from each other; for the first, when a person concealed a matter which he knew, could not arise from error, yet I include this concealment of which he treats under the head of error, by supposing it to have been when a person should be induced by shame or fear to connive at any crime or offense respecting which he might be interrogated, and so, without any design of perjuring himself, but by blinding himself, should withhold what he would have said, if he had duly examined the matter. Yet these words must be more narrowly discussed, respecting the meaning of which men are not well agreed. Some think that the word ''lh, alah, is put for "execration," as though it were said, if any shall have heard a misdoing or detestable crime worthy of execration; yet their gloss is contradicted by what immediately follows, "Whether he hath seen or known it." Others indeed interpret it to mean an oath, yet improperly confine it to perjury, as if Moses stated that he was guilty who had heard a man perjuring himself, and had not opposed him, but had rather covered the perjury by his own connivance or silence. I rather subscribe, then, to their opinion who expound it as meaning "adjuration;" for the words will thus combine very well, "If any one, being summoned as a witness, shall have heard the voice of adjuration, whereby he shall be required in God''s name to answer truly as to the matter proposed, and from favor, or good nature, or any other false pretext, as if he were enveloped in a cloud of error, shall conceal what, if he had paid diligent attention, he well knew, he shall be guilty." We must then here render the disjunctive particle as the conditional. Literally it is, "If any shall have heard the voice of adjuration, and (is) himself a witness." But wherefore should he say, "if he hath been a witness," and then add, "or have known it," as if he referred to different things? What I have said squares very well, that a person becomes himself guilty, who, when summoned as a witness, does not answer to a matter of which he is cognizant. Now, what does hearing the voice of adjuration mean, unless you understand that he is adjured by the mouth of a judge? We must observe, too, that the three kinds of sin which are first enumerated have a connection with each other, since they speak of sinners who are infected by the uncleanness of others; for, after Moses had commanded generally that offenses committed in error should be expiated, he now adds what had not been stated explicitly enough, that those also required atonement who had been polluted by the defilements of others.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 6, 1, NULL, 'leviticus-6', 'John Calvin', 'Commentaries', E'1. And the Lord spake unto Moses. Moses now no longer treats of the means of expiating errors when the sinner is guilty through thoughtlessness; but he prescribes the mode of reconciliation, when any one shall have wilfully and designedly offended God. And this is well worthy of notice, lest those who may have been guilty of voluntary sin should doubt whether God will be propitiated towards them, provided they make application to the one sacrifice of Christ, in which consists the entire substance of the shadows of the Law. We must indeed beware lest we indulge ourselves under the cover of God''s clemency and readiness to pardon, -- for the lust of the flesh provokes us to sin more than enough, without the addition of this snare, -- nor is it less than a blasphemous insult to God to take occasion and license for sin, from the fact of His willingness to pardon. Let then the fear of God reign in us, which will repress our wicked desires like a rein, so that we should not wilfully fall into sin; and let His mercy rather engender the hatred and detestation of sin in our hearts, than incite us to audacity. Yet, at the same time, we must prudently take heed, lest if we imagine God to be inexorable to our voluntary sins, this excessive severity should overthrow the hope of salvation even in those who are the holiest. For even now-a-days there are some madmen who deny pardon to all who may have chanted to fall through the infirmity of the flesh, since to morose men this severity has its charms, and by this hallucination Novatus greatly troubled the Church of old. But if we all honestly examine ourselves, it will plainly appear that those rigid censors, who affect the reputation of sanctity by immoderate asperity, are the grossest hypocrites. For if they would abandon their pride, and examine into their lives, which of them would find himself free from concupiscence? and whose conscience must not often smite him?

It is then monstrous blindness to exalt men, clothed in human flesh, to such a pitch of perfection, as that their conscience should not convict them of any fault or blame. And nothing is more pestilent than this imposture of the devil, excluding from the hope of pardon those who knowingly and willingly have sinned; since there is not one even of God''s best servants, in whom the corrupt affections of the flesh do not sometimes prevail; for although they be neither adulterers, nor thieves, nor murderers, yet there is none whom the last Commandment of the Law -- "Thou shalt not covet," -- does not convict of sin. And assuredly the more advance one has made in endeavors after purity, the more he feels and acknowledges that he is still very far from reaching its goal.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 7, 1, NULL, 'leviticus-7', 'John Calvin', 'Commentaries', E'1. Likewise this is the law. I have just confessed that I do not sufficiently understand how these two words, cht''h, chateah, and ''sm, asham, differ from each other; and I have therefore followed the sense which is commonly received, and called them the sin and the trespass-offering, (hostiam pro peccato vel pro delicto.) Although in this second kind of offering he commands the same ceremony to be observed as in the former one, yet he mentions some things which he had before omitted, such as the sprinkling of blood around the altar, the offering of the fat, kidneys, etc., which had not been before expressed. The sum amounts to this, that they were to sacrifice in the same manner, and with the same rites for sin as for trespass, and make not the smallest alteration in the rule laid down for them. __________________________________________________________________

11. And this is the law of the sacrifice of peace offerings, which he shall offer unto the LORD.

11. Haec autem est lex sacrificii prosperitatum, quod offerer Jehovae.

12. If he offer it for a thanksgiving, then he shall offer with the sacrifice of thanksgiving unleavened cakes mingled with oil, and unleavened wafers anointed with oil, and cakes mingled with oil, of fine flour, fried.

12. Si pro gratiarum actione obtulerit illud, tune offerer pro sacrificio gratiaram actionis, placentas infermentatas versatas in oleo, et lagana infermentata uncta oleo, et similam frictam una cum placentis illis versaris in oleo.

13. Besides the cakes, he shall offer for his offering leavened bread with the sacrifice of thanksgiving of his peace offerings.

13. Cron placentis panis fermentati offeret oblationem suam pro sacrificio gratiarum actionis prosperitatum suarum.

14. And of it he shall offer one out of the whole oblation for an heave offering unto the LORD, and it shall be the priest''s that sprinkleth the blood of the peace offerings.

14. Offeretque ex eo unum panem, ex omni oblatione oblationem Jehovae.

15. And the flesh of the sacrifice of his peace offerings for thanksgiving shall be eaten the same day that it is offered; he shall not leave any of it until the morning.

15. Caro autem hostiae gratiarum actionis prosperitatum ejus, in die oblationis ejus comedetur: non relinquet ex eo usque mane.

16. But if the sacrifice of his offering be a vow, or a voluntary offering, it shall be eaten the same day that he offereth his sacrifice: and on the morrow also the remainder of it shall be eaten:

16. Quod si votum, vel spontaneum fuerit sacrificium oblationis ejus, die quo ille obtulerit sacrificium suum, comedetur, et sequenti die comedetur quod superfuerit ex co.

17. But the remainder of the flesh of the sacrifice on the third day shall be burnt with fire.

17. Quodvero superfuerit de carne sacrificii die tertia, igni comburetur.

18.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 8, 1, NULL, 'leviticus-8', 'John Calvin', 'Commentaries', E'1. And the Lord spake. It is well known that in conjunction with the sacrifices there was an offering, which they call minha, but we shall elsewhere see that this was also used separately; for it was lawful without a victim to offer either plain meal, or cakes, or wafers seasoned with oil. Therefore, besides the sacrifice of consecration, of which Moses has already treated, this second offering is required from the priest, that he should present at his inauguration a cake fried in a pan, and cut in pieces. The reason of this appears to have been, that he might thence become the legitimate minister of all the people, and might duly offer in the name of others, when he had done what was right for himself. But a distinction is drawn between the demand upon the priest and that, upon the people, viz., that it should be "wholly burnt;" the reason for which, since it will be explained elsewhere, it will be now sufficient to advert to in a single word. The fact was that God was unwilling that the priests should indulge themselves in vain ostentation, which might have been easily the case, if the oblation had been preserved for their use, like the minha of the people which remained in their hands. __________________________________________________________________

Numbers 8:5-19, 23-26

5. And the LORD spake unto Moses, saying,

5. Loquutusque est praeterea Jehova ipsi Mosi, dicendo:

6. Take the Levites from among the children of Israel, and cleanse them.

6. Cape Levitas e medio filiorum Israel, et purifices illos.

7. And thus shalt thou do unto them, to cleanse them: Sprinkle water of purifying upon them, and let them shave all their flesh, and let them wash their clothes, and so make themselves clean.

7. Sic autem facies illis ut purifices illos: sparge super eos aquam purificationis, et transire faciant novaculam super totam carnem suam, laventque vestimenta sua, et purificentur.

8. Then let them take a young bullock with his meat offering, even. fine flour mingled with oil, and another young bullock shalt thou take for a sin offering.

8. Postea capient juvencum filium bovis, et minham ejus similam conspersam oleo: et juvencum alterura filium bovis capies in sacrificium pro peccato.

9. And thou shalt bring the Levites before the tabernacle of the congregation: and thou shalt gather the whole assembly of the children of Israel together.

9. Tunc offeres Levitas coram tabernaculo conventionis: et congregabis omnem coetum filiorum Israel.

10. And thou shalt bring the Levites before the LORD: and the children of Israel shall put their hands upon the Levites:

10. Offeres inquam Levitas eoram Jehova, et conjungent filii Israel marius suas super Levitas.

11. And Aaron shall offer the Levites before the LORD for an offering of the children of Israel, that they may execute the service of the LORD.

11. Offeretque Aharon Levitas in oblationem coram Jehova a filiis Israel, et ministrabunt in ministerio Jehovae.

12.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 9, 1, NULL, 'leviticus-9', 'John Calvin', 'Commentaries', E'1. And it came to pass on the eighth day We have here related how Aaron and his sons, after the time of their consecration was fulfilled, began to execute their office. It was necessary that He should be his brother''s disciple, in order to follow the pattern laid down by God. And we must bear in mind that Moses, who was not appointed priest by a solemn rite, sanctified the others, in order that the authority and the efficacy of the outward sign should rest in God alone. This, therefore, is contained in the earlier portion of the chapter, how, after Aaron had been initiated in the priest''s office for seven days, He commenced the work entrusted to him by God''s command: the second part shews how the sacrifices were approved by a divine miracle, in ratification of the priesthood which God had instituted. But, first of all, He enumerates the ordinary kinds of sacrifice, viz., for sin, the burnt-offering; and for thanksgiving, the sacrifice with the meat-offering (minha) and the sprinkling: that in every respect Aaron might be accounted the lawful priest of God.

6. And Moses said, This is the thing which the Lord commanded He seems, indeed, to address himself to the whole people, to whom also the promise belonged; but in the word "do ye," He specially speaks to the sons of Aaron; and he promises what, at the end of the chapter, he will state to have been fulfilled, that the glory of God should be manifested in approbation of the priesthood, in order that they may set about their duties more cheerfully. For this was no common aid to their faith and assurance, that their office should be thus, as it were, sealed by God.

7. And Moses said unto Aaron, Go unto the altar Here is repeated what was stated elsewhere, that the priest, as being himself a sinner, must first make entreaty for himself, before he propitiates God towards others. Hence the Apostle justly infers that the legal priesthood was weak and merely typical. (Hebrews 5:1.) For none can be a true peace-maker, except he, who, in reliance on his perfect innocence, presents himself before God to obtain pardon for others, and, being pure from every blemish, requires no expiation for himself. All else to the end of the chapter I pass over, because Moses only records how Aaron sacrificed according to God''s command and the legal ritual.

22. And Aaron lifted up his hand toward the people This was a kind of application of the sacrifice, in order that the people might know that God was reconciled to them through the priest as their mediator and surety. The form of benediction has been already expoundled; at present let this one point suffice, that, when by the lifting up of their hands the priests testified of God''s paternal favor to the people, their commission was ratified and efficacious.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 10, 1, NULL, 'leviticus-10', 'John Calvin', 'Commentaries', E'9. Do not drink wine, nor strong drink. The second cleanness required in the priests is that they should abstain from wine, and strong drink; in which word Jerome says that everything intoxicating is included; and this I admit to be true; but the definition would be more correct, that all liquors espressed from fruits are denoted by it, in whose sweetness there is nearly as much to tempt men as in wine. Even in these days the Orientals compose of dates as well as of other fruits, liquors, which are exceedingly sweet and delicious. The same rule is, therefore, here prescribed for the priests, whilst in the performance of their duties, as for the Nazarites. Both were allowed freely to eat of all the richest foods; but God commanded them to be content with water, because abstinence in drinks very greatly conduces to frugality of living. For few are intemperate in eating, who do not also love wine; besides, an abundance of food generally satisfies the appetite, whilst there is no limit to drinking, where the love of wine prevails. Therefore, abstinence from wines was enjoined upon the priest, not only that they might beware of drunkenness, but that they might be temperate in eating, and not luxuriate in their abundance. But, inasmuch as sobriety is the main point in moderate living, God especially limited His priests in this respect, lest the rigor of their minds, and rectitude, and integrity of judgment, should be impaired by drinking. Hence it appears how great is man''s proneness to all defilements. Wine is very wholesome as one of our means of nutriment; but by the too free use of it many enervate their strength, becloud their understanding, and almost stupify all their senses so as to make themselves inactive. Some, too, degrade themselves into foul and brutish stupidity, or are driven by it to madness. Thus a pleasure, which ought to have incited them to give God thanks, is taken away from them on account of their vicious excess; and not without disgrace, because they know not how to enjoy God''s good gifts in moderation. He afterwards confirms the fact, that He interdicted wine to the priests when exercising their office, that they may distinguish "between clean and unclean," and be sound and faithful interpreters of the Law. On this score it became them to be abstemious throughout their whole life, because they were always appointed to be masters to instruct the people; but lest immoderate strictness should tend to disgust them, so that they might be less disposed for the willing performance of the rest of their duty, God deemed it sufficient to admonish them by this temporary abstinence, that they should study to be sober at other times. Thus, then, it must be concluded that none are fit to teach who are given to gluttony, which corrupts the soundness of the mind, and destroys its rigor.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 3, 11, 1, NULL, 'leviticus-11', 'John Calvin', 'Commentaries', E'2. These are the beasts which ye shall eat. The holy fathers, before the birth of Moses, knew what animals were unclean; of which fact Noah afforded a manifest proof, when, by God''s command, he took into the ark seven pairs of the clean animals, and offered of them his sacrifice of thanksgiving to God. Certainly he could not have obeyed the command of God, unless he had either been taught by secret inspiration, or unless this tradition had descended to him from his forefathers. But there is nothing absurd in the notion that God, desiring to confirm the traditional distinction, appointed certain marks of difference whereby its observation might be more scrupulously attended to, and lest any transgression of it should creep in through ignorance. For God also consecrated the Sabbath to Himself from the creation of the world, and desired it to be observed by the people before the promulgation of the Law; and yet afterwards the peculiar holiness of the day was more distinctly expressed. Besides, the clean animals are here distinguished from the unclean, by name as well as by signs. The proper names, which are recited, are of little service to us now-a-days; because many species which are common in the East, are unknown elsewhere; and it was therefore easy for Jews who were born and had lived in distant countries, to fall into error about them; whilst, on the other hand, the more bold they are in their conjectures, the less are they to be trusted. As to many of them, I acknowledge that there is no ambiguity, especially as to the tame animals, or those that are to be found everywhere, or that have plain descriptions of them given in the Bible. A positive knowledge then is only to be sought from the signs which are here laid down; viz., that the animals which have cloven hoofs, and which ruminate, are clean: and that those are unclean in which either of these two things is wanting; that either sea or river fish, which have fins and scales, are clean. No such distinction as to birds is given, but only the unclean are named, which it was sinful to eat. Lastly, mention is made of reptiles. As to details, if there be anything worthy of observation, the place to consider them will be further on; let us now remember, in general, what I have before touched upon, viz., that whilst the Gentiles might eat every kind of food, many were forbidden to the Jews, in order that they might learn in their very food to cultivate purity; and this was the object of their separation from ordinary customs. Hence it arose that they use the word chll, chalal both for "to make common," and to "contaminate;" and the word, chvl, chol, signifies "polluted," because it is opposed to anything holy or set apart.', false, false, 'sourced', 'published');
