-- Calvin commentary INSERT — Mark (batch 1, rows 1-10)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 1, 1, NULL, 'mark-1', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 2, 1, NULL, 'mark-2', 'John Calvin', 'Commentaries', E'1. And again he entered into Capernaum after some days; and it was reported that he was in the house. 2. And immediately many were assembled, so that the places which were around the door did not now contain them, and he preached the word to them. 3. And they come to him, bringing a paralytic, who was carried by four persons. 4. And when they could not approach him on account of the crowd, they uncovered the roof of the house in which he was, and having made an opening in the roof, they lower the couch on which the paralytic lay. 5. And when Jesus saw their faith, he said to the paralytic, Son, thy sins are forgiven thee. 6. And some of the scribes were sitting there, and thinking in their hearts, 7. Why does this man thus speak blasphemies? Who can forgive sins but God alone? 8. And immediately when Jesus knew by his Spirit that they thought thus within themselves, he said to them, Why do you think those things in your hearts? 9. Whether it is easier to say to the paralytic, Thy sins are forgiven thee; or to say, Rise, and take up thy bed, and walk? 10. But that you may know that the Son of man hath authority on earth to forgive sins, (he saith to the paralytic,) 11. I say to thee, Arise, take up thy bed, and go away to thy house. 12. And immediately he arose, and having taken up the bed, went out in the presence of all, so that all were astonished, and glorified God, saying, We never saw such a thing.

17. And it happened on a certain day, and he was teaching: and Pharisees and doctors of the law were sitting, who had come out of every village of Galilee and Judea, and from Jerusalem; and the power of the Lord was present to heal them. 18. And, lo, men carrying on a bed, a man who was a paralytic, and they sought to bring him in, and to place him before him. 19. And not finding a way by which they could bring him in on account of the crowd, they went up to the roof, and lowered him by cords with the bed into the midst before Jesus. 20. And when he saw their faith, he said to him, Man, thy sins are forgiven thee. 21. And the scribes and Pharisees began to think, saying, Who is this that speaketh blasphemies? Who can forgive sins but God alone? 22. And when Jesus knew their thoughts, he answering said to them, What do you think in your hearts? 23. Whether it is easier to say, Thy sins are forgiven thee, or to say, Arise, and walk? 24. But that you may know that the Son of man hath authority on earth, (he saith to the paralytic,) I say to thee, Arise, take up thy bed, and go to thy house. 25.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 3, 1, NULL, 'mark-3', 'John Calvin', 'Commentaries', E'13. And he went up into a mountain, and called to him whom he would: and they came to him. 14. And he appointed twelve to be with him, and send them forth to preach, 15. And to have powers of healing diseases, and of casting out devils. 16. And to Simon he gave the name Peter. 17. And James th son of Zebedee, and John, the brother of James: and he gave them the names of Boanerges, which is, The sons of thunder. 18. And Andrew, and Philip, and Bartholomew, and Matthew, and Thomas, and James (son) of Alpheus, and Thaddeus, and Simon the Canaanite, 19. And Judas Iscariot, who also betrayed him.

12. And it happened in those days, he went out into a mountain to pray, and he spent the whole night in prayer to God. 13. And when it was day, he called his disciples, and chose twelve from among them, whom he also called Apostles: 14. Simon, whom he also called Peter, and Andrew his brother, James and John, Philip and Bartholomew, 15. Matthew and Thomas, James (son) of Alpheus, and Simon, who is called Zelotes, 16. And Judas (brother) of James, and Judas Iscariot, who also was the traitor. 17. And going down with them, he stood in a plain, and a multitude of his disciples, and a very great multitude of people out of all Judea and Jerusalem, and from the sea coast of Tyre and Sidon. 18. Who had come to hear him, and to be healed from their diseases, and those who were tormented by unclean spirits were healed. 19. And the whole multitude sought to touch him, for virtue went out of him, and healed all.

Mark 3:13. And he went up into a mountain. By this election he does not yet ordain them to be Apostles, to enter immediately into the discharge of their office, but merely admits them to enjoy his private instructions with a view to the apostleship. Commentators have fallen into a mistake here, by confounding those passages with the tenth chapter of the Gospel by Matthew. For the plain meaning of the words is, that they are only destined to a future commission, the bestowal of which is recorded by Matthew; and Mark and Luke will be found afterwards relating, in its proper place, the mission which Matthew there describes. And we need not wonder, if their heavenly Master chose to train and accustom them gradually to so arduous an employment: for, even by a long course of instruction, their ignorance could not be corrected.

Both the Evangelists say, that Christ went up into a mountain. Luke explains the cause to have been, that he might pray with greater freedom in his retirement, which he was accustomed to do frequently, as is evident from other passages.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 4, 1, NULL, 'mark-4', 'John Calvin', 'Commentaries', E'23. And when he had entered into the ship, his disciples followed him. 24. And, lo, there was a great swell in the sea, so that the ship was covered with the billows: and he was asleep. 25. And his disiples approached and awoke him, saying, Lord, save us, we perish. 26. And he saith to them, Why are you timid, O men of little faith? Then he arose, and rebuked the winds and the sea: and there was a great calm. 27. But the men wondered, saying, What sort of man is this: for the winds and the sea obey him?

35. And the same day, when it was evening, he said to them, Let us cross to the opposite side. 36. And having sent away the multitude, they take him even as he was, in the ship. But there were also other ships along with him. 37. Then ariseth a great storm of wind: and the billows dashed into the ship, so that it was now filled. 38. And he was at the stern, sleeping upon a pillow: and they awake him, and say to him, Master, hast thou no care that we perish? 39. And he arose, and rebuked the wind, and said to the sea, Silence, be still. And the wind was hushed, and there was a great calm. 40. And he said to them, Why are you so timid? How have you not confidence? 41. And they feared with a great fear, and said among themselves, Who is this: for even the wind and the sea obey him?

22. And it happened on a certain day, that he went into a ship with his disciples. And he saith to them, Let us cross to the opposite side of the lake: and they set sail. 23. And while they were sailing, he fell asleep, and a tempest of wind arose in the lake, and they were filled with water, and were in danger. 24. And they approached and awoke him, saying, Master, Master, we perish. But he arose, and rebuked the wind and the tempest of the water; and they ceased, and there was a calm. 25. And he said to them, Where is your faith? And they were afraid, and wondered, saying among themselves, Who is this? for he commands even the winds and the water, and they obey him.

As we shall soon meet again with the mention of a lake, where it is said (Matthew 8:33) that the swine were carried into it with violence, it is not universally agreed whether one and the same lake is mentioned in both places. The waters of Gennesareth, all admit, were pleasant and healthful to drink: but the Gadarene lake, Strabo tells us, was so unwholesome and pestilential, that the cattle which drank of it often lost their hair and their hoofs. There is therefore no doubt that there were two separate lakes, and that they were at a considerable distance from each other.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 5, 1, NULL, 'mark-5', 'John Calvin', 'Commentaries', E'28. And when he had come to the opposite bank, into the country of the Gergesenes, two demoniacs, who had come from among the tombs, met him: and they were fierce beyond measure, so that no man could pass along that road. 29. And, lo, they cried out, saying, What have we to do with thee, Jesus, Son of God? Hast thou come hither before the time to torment us? 30. And at a distance from them there was a herd of many swine feeding. 31. And the devils entreated him, saying, If thou cast us out, permit us to remove into the herd of swine. 32. And he said to them, Go. And when they had gone out, they went away into the heard of swine. And, lo, the whole herd was carried headlong into the sea, and perished in the waters. 33. And those who had the charge of them fled; and going away into the city, they related all things, and what had happened to the demoniacs, 34. And, lo, the whole city went out to meet Jesus; and when they saw him, they entreated him, that he would depart from their territories.

1. And having crossed the sea, they came into the country of Gaderanes. 2. And when he left the ship, immediately there met him out of the tombs a man possessed by an unclean spirit, 3. Who had a dwelling among the tombs, and no man could bind him, not even with chains: 4. Because frequently, when he had been bound with fetters and chains, the chains were torn asunder by him, and the fetters were broken in pieces, so that no man could tame him. 5. And always, day and night, he was in the mountains, and among the tombs, crying, and cutting himself with stones. 6. And when he saw Jesus at a distance, he ran and worshipped him: 7. And, crying with a loud voice, he said, What have I to do with thee, Jesus, Son of the Most High God? I adjure thee by God, that thou do not torment me. 8. For he said to him, Go out of the man, unclean spirit. 9. And he asked him, What is thy name? And he answered, saying to him, My name is Legion: for there are many. 10. And he entreated him earnestly, that he would not send him out of the country. 11. And there was there, near the mountains, a great herd of swine feeding. 12. And all the devils besought him, saying, Send us into the swine, that we may enter into them. 13. And immediately Jesus permitted them. And the unclean spirit having gone out, entered into the swine, and the herd was carried headlong into the sea: and they were about two thousand, and were choked in the sea. 14. Then those who tended the swine fled, and told it in the city and in the fields.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 6, 1, NULL, 'mark-6', 'John Calvin', 'Commentaries', E'9. Do not provide gold, nor silver, nor brass in your purses, 10. Nor scrip for the journey, nor two coats, nor shoes, nor staff: for the laborer is worthy of his food. 11. But into whatsoever city or village you shall enter, inquire what person in it is worthy, and remain there till you depart. 12. And when you shall enter a house, salute it. 13. And if the house shall be worthy, may your peace come upon it: but if it shall not be worthy, may your peace return to you. 14. And whosoever shall not receive you, or hear your words, when you go out of that house or city, shake off the dust of your feet. 15. Verily I say to you, It shall be more tolerable for the land of Sodom and of Gomorrah in the day of judgment than for that city. 8. And commanded them to take nothing for the journey, but a staff only; not a scrip, nor bread, nor money in their girdle: 9. But to be shod with sandals, and not to wear two coats. 10. And he said to them, Whenever you shall enter a house, remain there till you depart thence. 11. And whoever shall not receive you or hear you, when you go out of that place, shake off the dust which is under your feet for a testimony to them. Verily I say to you, It shall be more tolerable for Sodom and Gomorroah in the day of judgment than for that city. 3. And he said to them, Carry nothing for the journey, neither a staff, nor a scrip, nor bread, nor money; and do not have two coats each. 4. And into whatsoever house you shall enter, remain there, and depart thence. 5. And whoever will not receive you, when you go out of that city, shake off even the dust from your feet for a testimony against them. Matthew 10:9. Do not provide. As the embassy was of such a nature, that Christ wished the disciples to traverse the whole of Judea within a few days, and immediately to return to him, he forbids to carry luggage with them, by which this speed may be retarded. Some have ignorantly supposed that the rule here laid down for the ministers of the word, or for the apostles, is perpetual. We shall presently meet with a few sentences which have a more extensive reference: but the present injunctions not to carry baggage must undoubtedly be restricted to that temporary commission of which I have already spoken. The whole of the prohibition of gold, silver, a scrip, and two coats, which is given by Matthew, must be read in immediate connection, as is evident from the other two Evangelists. I have therefore chosen to translate ue ktesesthe, do not provide: for our Lord simply intended to forbid them to take any thing for the journey They might have scrips, and shoes, and a change of coats,', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 7, 1, NULL, 'mark-7', 'John Calvin', 'Commentaries', E'1. And the Pharisees, and some of the scribes, who had come from Jerusalem, assemble to him. 2. And when they saw some of his disciples eat bread with common, that is to say, with unwashen hands, they found fault. 3. For the Pharisees. and all the Jews, do not take food without frequently washing their hands, holding the traditions of the elders; 4. And returning from market, they eat not till they have washed; and many other things are there which they have undertaken to keep, namely, the washings of cups, and pots, and brazen vessels, and beds. 5. Then the Pharisees and scribes ask him, saying, Why do not thy disciples walk according to the tradition of the elders, but eat bread with unwashen hands? 6. And he answering said to them, Well hath Isaiah prophesied concerning you hypocrites, as it is written, This people honor me with the lips, but their heart is far from me. 7. But in vain do they worship me, teaching doctrines, commandments of men. 8. For, laying aside the commandments of God, you keep a tradition of men, the washings of pots and cups, and many other things similar to these you do. 9. And he said to them, Well do you reject the commandment of God, that you may keep your own tradition. 10. For Moses said, Honor thy father and mother; and, He that curseth father or mother, dying let him die. 11. But you say, If a man shall say to his father and mother, Every Corban (that is, gift) that cometh from me shall profit thee. 12. And you do not permit him to do any thing more to his father or his mother. 13. Annulling the word of God by your tradition, which you have delivered; and many things similar to this you do.

Matthew 15:1. Then scribes and Pharisees. As the fault that is here corrected is not only common but highly dangerous, the passage is particularly worthy of our attention. We see the extraordinary insolence that is displayed by men as to the form and manner of worshipping God; for they are perpetually contriving new modes of worship, and when any one wishes to be thought wiser than others, he displays his ingenuity on this subject. I speak not of foreigners, but of the very domestics of the Church, on whom God has conferred the peculiar honor of declaring with their lips the rule of godliness. God has laid down the manner in which he wishes that we should worship him, and has included in his law the perfection of holiness. Yet a vast number of men, as if it were a light and trivial matter to obey God and to keep what he enjoins, collect for themselves, on every hand, many additions. Those who occupy places of authority bring forward their inventions for this purpose, as if they were in possession of something more perfect than the word of the Lord.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 8, 1, NULL, 'mark-8', 'John Calvin', 'Commentaries', E'32. Whosoever therefore shall confess me before men, him will I also confess before my Father, who is in heaven. 33. And whosoever shall deny me before men, him will I also deny before my Father, who is in heaven. 34. Think not that I came to send peace on the earth: I came not to send peace, but a sword. 35. For I have come to set a man at variance against his father, and a daughter against her mother, and a daughter-in-law against her mother-in-law. And the persons of a man''s household shall be his enemies.

38. For whosoever shall be ashamed of me and of my words in this adulterous and sinful generation, of him will the Son of man be ashamed, when he shall come in the glory of his Father with the holy angels.

26. For whosoever shall be ashamed of me, and of my words, of him will the Son of man be ashamed, when he shall come in his own glory, and [in the glory] of the Father, and of the holy angels.

8. And I say to you, Whosoever shall confess me before men, him will the Son of man also confess before the angels of God. 9. And he who shall deny me before men, will be denied before the angels of God.--(Same chapter.) 51. Do you suppose that I came to send peace on earth? I tell you no; but division. 52. For henceforth there will be five in one house divided, three against two, and two against three. 53. The father will be divided against the son, and the son against the father: the mother against the daughter, and the daughter against the mother: the mother-in-law against her daughter-in-law, and the daughter-in-law against her mother-in-law.

Matthew 10:32. Whosoever therefore shall confess me He now applies to his present subject what he formerly said in a general manner about contempt of death: for we must struggle against the dread of death, that it may not keep us back from an open confession of faith, which God strictly demands, and which the world cannot endure. For this purpose the disciples of Christ must be bold and courageous, that they may be always ready for martyrdom. Now confession of Christ, though it is regarded by the greater part of men as a trifling matter, is here represented to be a main part of divine worship, and a distinguished exercise of godliness. And justly is it so represented: for if earthly princes, in order to enlarge and protect their glory, and to increase their wealth, call their subjects to arms, why should not believers maintain, at least in language, the glory of their heavenly King?

It is therefore certain that those persons extinguish faith, (as far as lies in their powers) who inwardly suppress it, as if the outward profession of it were unnecessary. With good reason does Christ here call us his witnesses, by whose mouth his name shall be celebrated in the world.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 9, 1, NULL, 'mark-9', 'John Calvin', 'Commentaries', E'', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 41, 10, 1, NULL, 'mark-10', 'John Calvin', 'Commentaries', E'49. And John answering said, Master, we saw one casting out devils in thy name; and we forbade him, because he followeth not with us. 50. And Jesus said to him, Forbid him not; for he who is not against us is for us. 51. And it happened, when the days of his being received up were in course of being fulfilled, and he set his face steadfastly to go to Jerusalem. 52. And he sent messengers before his face; and they went and entered into a town of the Samaritans, to make ready for him: 53. And they did not receive him, because his face was as if he were going to Jerusalem. 54. And when his disciples James and John saw it, they said, Lord, wilt thou that we command fire to come down from heaven, and consume them, even as Elijah did? 55. And Jesus, turning, rebuked them, saying, You know not of what spirit you are. 56. For the Son of man is not come to destroy men''s lives, but to save them. And they went into another village.

Mark 9:38. Master, we saw one. Hence it is evident that the name of Christ was at that time so celebrated, that persons who were not of the number of his intimate disciples used that name, or perhaps even abused it, for I will not venture to avouch any thing on this point as certain. It is possible that he who is here mentioned had embraced the doctrine of Christ, and betaken himself to the performance of miracles with no bad intention; but as Christ bestowed this power on none but those whom he had chosen to be heralds of his Gospel, I think that he had rashly taken, or rather seized upon, this office. Now though he was wrong in making this attempt, and in venturing to imitate the disciples without receiving a command to do so, yet his boldness was not without success: for the Lord was pleased, in this way also, to throw luster around his name, as he sometimes does by means of those of whose ministry he does not approve as lawful. It is not inconsistent with this to say, that one who was endued with special faith followed a blind impulse, and thus proceeded inconsiderately to work miracles.

I now come to John and his companions. They say that they forbade a man to work miracles Why did they not first ask whether or not he was authorized? For now being in a state of doubt and suspense, they ask the opinion of their Master. Hence it follows, that they had rashly taken on themselves the right to forbid; and therefore every man who undertakes more than he knows that he is permitted to do by the word of God is chargeable with rashness. Besides, there is reason to suspect the disciples of Christ of ambition, because they are anxious to maintain their privilege and honor.', false, false, 'sourced', 'published');
