-- Calvin commentary INSERT — Philippians (batch 1, rows 1-4)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 50, 1, 1, NULL, 'philippians-1', 'John Calvin', 'Commentaries', E'1 Paul and Timotheus, servants of Jesus Christ While Paul is accustomed, in the inscription of his epistles, to employ titles of distinction, with the view of procuring credit for himself and his ministry, there was no need of lengthened commendations in writing to the Philippians, who had known him by experience as a true Apostle of Christ, and still acknowledged him as such beyond all controversy. For they had persevered in the calling of God steadfastly, and in an even tenor.

Bishops He names the pastors separately, for the sake of honor. We may, however, infer from this, that the name of bishop is common to all the ministers of the Word, inasmuch as he assigns several bishops to one Church. The titles, therefore, of bishop and pastor, are synonymous. And this is one of the passages which Jerome quotes for proving this in his epistle to Evagrius, and in his exposition of the Epistle to Titus. Afterwards there crept in the custom of applying the name of bishop exclusively to the person whom the presbyters in each church appointed over their company. It originated, however, in a human custom, and rests on no Scripture authority. I acknowledge, indeed, that, as the minds and manners of men are, there cannot be order maintained among the ministers of the word, without one presiding over the others. I speak of particular bodies, not of whole provinces, much less of the whole world. Now, although we must not contend for words, it were at the same time better for us in speaking to follow the Holy Spirit, the author of tongues, than to change for the worse forms of speech which are dictated to us by Him. For from the corrupted signification of the word this evil has resulted, that, as if all the presbyters were not colleagues, called to the same office, one of them, under the pretext of a new appellation, usurped dominion over the others.

Deacons. This term may be taken in two ways -- either as meaning administrators, and curators of the poor, or for elders, who were appointed for the regulation of morals. As, however, it is more generally made use of by Paul in the former sense, I understand it rather as meaning stewards, who superintended the distributing and receiving of alms. On the other points consult the preceding commentaries.

3 I give thanks. He begins with thanksgiving on two accounts -- first, that he may by this token shew his love to the Philippians; and secondly, that, by commending them as to the past, he may exhort them, also, to perseverance in time to come. He adduces, also, another evidence of his love -- the anxiety which he exercised in supplications. It is to be observed, however, that, whenever he makes mention of things that are joyful, he immediately breaks forth into thanksgiving -- a practice with which we ought also to be familiar.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 50, 2, 1, NULL, 'philippians-2', 'John Calvin', 'Commentaries', E'1 If there is therefore any consolation. There is an extraordinary tenderness in this exhortation, in which he entreats by all means the Philippians mutually to cherish harmony among themselves, lest, in the event of their being torn asunder by intestine contentions, they should expose themselves to the impostures of the false apostles. For when there are disagreements, there is invariably a door opened for Satan to disseminate impious doctrines, while agreement is the best bulwark for repelling them.

As the term parakleseos is often taken to mean exhortation, the commencement of the passage might be explained in this manner: "If an exhortation which is delivered in the name and by the authority of Christ, has any weight with you." The other meaning, however, corresponds better with the context: "If there is among you any consolation of Christ," by means of which you may alleviate my griefs, and if you would afford me any consolation and relief, which you assuredly owe me in the exercise of love; if you take into view that fellowship of the Spirit, which ought to make us all one; if any feeling of humanity and mercy resides in you, which might stir you up to alleviate my miseries, fulfill ye my joy, etc. From this we may infer, how great a blessing unity in the Church is, and with what eagerness pastors should endeavor to secure it. We must also at the same time take notice, how he humbles himself by beseechingly imploring their pity, while he might have availed himself of his paternal authority, so as to demand respect from them as his sons. He knew how to exercise authority when it was necessary, but at present he prefers to use entreaties, because he knew that these would be better fitted to gain an entrance into their affections, and because he was aware that he had to do with persons who were docile and compliant. In this manner the pastor must have no hesitation to assume different aspects for the sake of the Church.

2 Fulfil ye my joy. Here again we may see how little anxiety he had as to himself, provided only it went well with the Church of Christ. He was kept shut up in prison, and bound with chains; he was reckoned worthy of capital punishment -- before his view were tortures -- near at hand was the executioner; yet all these things do not prevent his experiencing unmingled joy, provided he sees that the Churches are in a good condition. Now what he reckons the chief indication of a prosperous condition of the Church is -- when mutual agreement prevails in it, and brotherly harmony. Thus the 137th Psalm teaches us in like manner, that our crowning joy is the remembrance of Jerusalem.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 50, 3, 1, NULL, 'philippians-3', 'John Calvin', 'Commentaries', E'1 Rejoice in the Lord This is a conclusion from what goes before, for as Satan never ceased to distress them with daily rumors, he bids them divest themselves of anxiety and be of good courage. In this way he exhorts them to constancy, that they may not fall back from the doctrine which they have once received. The phrase henceforward denotes a continued course, that, in the midst of many hinderances, they may not cease to exercise holy joy. It is a rare excellence when Satan endeavors to exasperate us by means of the bitterness of the cross, so as to make God''s name unpleasant , to take such satisfaction in the simple tasting of God''s grace, that all annoyances, sorrows, anxieties, and griefs are sweetened.

To write the same thing to you. Here he begins to speak of the false Apostles, with whom, however, he does not fight hand to hand, as in the Epistle to the Galatians, but in a few words severely exposes them, as far as was sufficient. For as they had simply made an attempt upon the Philippians, and had not made an inroad upon them, it was not so necessary to enter into any regular disputation with the view of refuting errors, to which they had never lent an ear. Hence he simply admonishes them to be diligent and attentive in detecting impostors and guarding against them.

In the first place, however, he calls them dogs; the metaphor being grounded upon this -- that, for the sake of filling their belly, they assailed true doctrine with their impure barking. Accordingly, it is as though he had said, -- impure or profane persons; for I do not agree with those who think that they are so called on the ground of envying others, or biting them

In the second place, he calls them evil workers, meaning, that, under the pretext of building up the Church, they did nothing but ruin and destroy everything; for many are busily occupied who would do better to remain idle. As the public crier on being asked by Gracchus in mockery, on the ground of his sitting idle, what he was doing? had his answer ready, "Nay, but what are you doing?" for he was the ringleader of a ruinous sedition. Hence Paul would have a distinction made among workers, that believers may be on their guard against those that are evil.

In the third term employed, there is an elegant (prosonomasia) play upon words. They boasted that they were the circumcision: he turns aside this boasting by calling them the concision , inasmuch as they tore asunder the unity of the Church. In this we have an instance tending to shew that the Holy Spirit in his organs has not in every case avoided wit and humor, yet so as at the same time to keep at a distance from such pleasantry as were unworthy of his majesty.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 50, 4, 1, NULL, 'philippians-4', 'John Calvin', 'Commentaries', E'1. Therefore, my brethren He concludes his doctrine, as he is wont, with most urgent exhortations, that he may fix it the more firmly in the minds of men. He also insinuates himself into their affections by endearing appellations , which at the same time are not dictated by flattery, but by sincere affection. He calls them his joy and crown; because, delighted to see those who had been gained over through his instrumentality persevering in the faith , he hoped to attain that triumph, of which we have spoken , when the Lord will reward with a crown those things which have been accomplished under his guidance.

When he bids them so stand fast in the Lord, he means that their condition is approved of by him. At the same time, the particle so might be taken as referring to the doctrine going before; but the former view is more suitable, so that, by praising their present condition, he exhorts them to perseverance. They had already, it is true, given some evidence of their constancy. Paul, however, well knowing human weakness, reckons that they have need of confirmation for the future.

2. I exhort Euodias and Syntyche It is an almost universally received opinion that Paul was desirous to settle a quarrel, I know not of what sort, between those two women. While I am not inclined to contend as to this, the words of Paul do not afford ground enough for such a conjecture to satisfy us that it really was so. It appears, from the testimony which he gives in their favor, that they were very excellent women; for he assigns to them so much honor as to call them fellow-soldiers in the gospel . Hence, as their agreement was a matter of great moment , and, on the other hand, there would be great danger attendant on their disagreement, he stirs them up particularly to concord.

We must take notice, however, that, whenever he speaks of agreement, he adds also the bond of it--in the Lord. For every combination will inevitably be accursed, if apart from the Lord, and, on the other hand, nothing is so disjoined, but that it ought to be reunited in Christ.

3 I entreat thee, also, true yokefellow I am not inclined to dispute as to the gender of the noun, and shall, accordingly, leave it undetermined , whether he addresses here a man or a woman. At the same time there is excessive weakness in the argument of Erasmus, who infers that it is a woman from the circumstance, that mention is made here of other women -- as though he did not immediately subjoin the name of Clement in the same connection. I refrain, however, from that dispute: only I maintain that it is not Paul''s wife that is designated by this appellation. Those who maintain this, quote Clement and Ignatius as their authorities. If they quoted correctly, I would not certainly despise men of such eminence.', false, false, 'sourced', 'published');
