-- Calvin commentary INSERT — Numbers (batch 4, rows 31-35)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 4, 32, 1, NULL, 'numbers-32', 'John Calvin', 'Commentaries', E'1. Now the children of Reuben and the children of Gad. In this narrative we behold, as in a glass, that whilst each individual is but too attentive to his own private interests, he forgets what is just and right. Those, indeed, who seek their own advantage, do not reflect that they are doing injury to others; but it is impossible for them to avoid seeking more than is their due, and preferring themselves to others; and thus they sin against that rule of charity, that we should not seek our own. The sons of Gad and Reuben, who had a great quantity of cattle, see a tract of rich and fertile land; self-interest takes possession of them, so that it does not occur to them that they were under an obligation to their brethren not to covet for themselves anything peculiar, or separate from them. Nevertheless, there was a specious pretext for this, whereby their eyes were blinded, viz., that nothing was taken away from the others, but rather that so much addition was made; for by these means the whole country on the other side of Jordan continued to be theirs; and, besides, they were rather relieved of an inconvenience than exposed to a loss; since the progress of their expedition would be less difficult, if the body of persons, who were charged with the cattle, should stay there, and thus should cease to be an incumbrance to the army, which would be in lighter condition for advancing. Their association, however, for the war had been established by God, and bound them by an indissoluble tie not to desert the rest of the people: whilst it was also a solemn duty (religio) imposed upon them not to alter the bounds of the inheritance promised by God. The land of Canaan was assigned to the whole race of Abraham, in which they were to be enclosed, and to inhabit it as a peculiar world, the tribes of Gad and Reuben now transgress those limits, and, at the same time disunite themselves from the body of the Church, as if they desired to be emancipated from God. Hence ought we to be the more on our guard, lest we should go astray after our own lusts. And when Moses says, that they saw, or considered, the land, let us learn to beware lest our eyes, by unlawful looks, should lead us into snares, and blind our minds; and thus that our senses should be so deceived by the envenomed sweetness, as that reason and equity should be utterly overthrown. The Hebrew word, which we have rendered peculium, signifies not only cattle and herds, but also flocks of sheep. Almost all the Israelites were indeed possessors of cattle; but we gather from the words of Moses, that these two tribes were especially rich in them; perhaps, because the district which they inhabited in Egypt, being more suited for pasture, had invited them to apply themselves more earnestly to that mode of', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 4, 33, 1, NULL, 'numbers-33', 'John Calvin', 'Commentaries', E'21. Thou shalt not plant thee. It is plain from the end of this verse that it is part of the Second Commandment. We know that amongst the heathen nations groves were sacred, so that with them no religious object would receive due reverence, except under the shade of trees. Wherefore lest conformity with this general custom should vitiate the pure worship of God, this distinction was made; and this then is the intent of the prohibition, that the Jews should fly from all strange rites, lest by too closely approaching the Gentiles, they should introduce a sinful medley. But how necessary this prohibition was, appears from their eager imitation (of the heathen), of which mention is constantly made in the sacred history. For there was scarcely any period in which they abstained from "high places." Nor is it without reason that Isaiah and Jeremiah reprove them for "playing the harlot under every green tree." (Isaiah 57:5; Jeremiah 2:20; 3:6.) __________________________________________________________________

See Lucian in Dea Syria, sub initium; Protoi men on anthropon, ton hemeis idmen, Aiguptioi legontai theon te ennoian labein, kai hira eisasthai, kai temenea, k. t. l., -- Tacitus Germ. 9. "Lucos et nemora consecrant." Virgil. Eccl. 6:73. "Ne quis sit lucus, quo plus se jactet Apollo." __________________________________________________________________

Exodus 34:11, 12, 15, 16

11. Observe thou that which I command thee this day: behold, I drive out before thee the Amorite, and the Canaanite, and the Hittite, and the Perizzite, and the Hivite, and the Jebusite.

11. Custodi quod ego praecipio tibi hodie. Ecce ego ejiciam a facie tua Amorrhaeum, Chananaeum, Hittaeum, Pheresaeum, Hivaeum, et Jebusaeum.

12. Take heed to thyself, lest thou make a covenant with the inhabitants of the land whether thou goest, lest it be for a snare in the midst of thee:

12. Cave tibi ne forte percutias foedus cum habitatoribus ejus terrae ad quam ingressurus es, ne forte sint in laqueum vel offendiculum in medio tui.

15. Lest thou make a covenant with the inhabitants of the land, and they go a whoring after their gods, and do sacrifice unto their gods, and one call thee, and thou eat of his sacrifice;

15. Ne forte percutias foedus cum habitatoribus ejus terrae, ut scortentur post deos suos, et sacrificent diis suis: vocet autem to quispiam, et comedas e sacrificio ejus.

16. And thou take of their daughters unto thy sons, and their daughters go a whoring after their gods, and make thy sons go a whoring after their gods.

16. Et forte accipias e filiabus ejus filiis tuis, et scortentur filiae ejus post deos ipsarum, et scortari faciant filios tuos post deos earum.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 4, 34, 1, NULL, 'numbers-34', 'John Calvin', 'Commentaries', E'1. And the Lord spake unto Moses. God here undertakes the office of a prudent and careful father of a family, in fixing the boundaries of the land on every side, lest their right to posses it should ever be called in question. He begins on the southern side, where it must be observed that the district of Bashan is included in it, and all that the Israelites had acquired before their passage of the Jordan, so that this addition was approved of by God. He extends this part as far as the wilderness of Sin, and the borders of Edom, and brings it round from Kadesh-barnea to Addar, and the passage of Azmon, and, finally, to the stream which washes the city of Rhinocorura, in the immediate vicinity of Egypt; for by "the river of Egypt" the Nile is by no means to be understood, the course of which was not at all in that direction. The southern boundary, therefore, was from the Mediterranean Sea towards Arabia. On the western side the land was washed by the Mediterranean Sea, which is here called "the Great Sea," in comparison with the Lake of Gennesareth, and the Salt Sea, by which name the Lacus Asphaltires is here meant. The beginning of the northern boundary was the promontory of Hor, for it would not accord to suppose that the mountain is here referred to in which Aaron died, and which was far away, and situated on the opposite side of the land. It extended from hence to Epiphania in Syria, which is called Hamath; for I agree with Jerome in thinking that there were two cities of this name, and it is undoubtedly probable that Antioch is called "Hamath the great" by the Prophet Amos (Amos 6:2,) in comparison with the lesser city here mentioned, the name of which was given it by that wicked and cruel tyrant (Antiochus) Epiphanes; whether, however, the greater Antioch was formerly called Hamath and Riblab, as Jerome states, I leave undecided. It then passed on to Zedad and Ziphron, and its extremity was the village of Enan. The eastern boundary passed from thence through Shephan, Riblah, and Ain, until it reached the Lake of Gennesareth, a lake sufficiently well known, and here called the Sea of Chinnereth. Thus the eastern boundary pointed from Arabia in the direction of Persia, and Babylon was situated to the north-east of it. 13. And Moses commanded the children of Israel. Though this is a repetition, yet it is not a superfluous one; for he contrasts the new allotment of the nine tribes and a half with the former grant; for the exception, which is immediately added, as to the lands beyond Jordan, given to the Reubenites, and Gadites, and half tribe of Manasseh, does not exclude them from their part of the promised inheritance was if they were disinherited, and therefore banished beyond the boundaries prescribed by God -- but only from being subject to the casting of lots, because', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 4, 35, 1, NULL, 'numbers-35', 'John Calvin', 'Commentaries', E'1. And the Lord spake unto Moses. Although there was no inheritance assigned to the tribe of Levi, yet it was necessary that they should be supplied with dwelling-places. No lands were given then where they might sow and reap; but by way of compensation the tithes were a sufficient means of subsistence, even after deducting the tithes which were paid to the poor. God now, however, makes provision for their residences; and here we must carefully remark, that they were so distributed over the whole land, as to be, as it were, guards regularly posted for the preservation of the worship of God, lest any superstition should creep in, or the people should fall into gross contempt of God. For we know that they were chosen by Him, not only to attend to the ceremonies, but to be the interpreters of the law, and to cherish sincere piety among the people. Now if all had been placed in one station, it was dangerous lest the doctrine of the Law should immediately fall into oblivion through the whole land; and thus the other tribes should grow irreligious. Wherefore the incomparable goodness of God here shone forth, since their punishment was turned as it were into a reward of virtue, and their disgrace into honor; for this dispersion of the tribe of Levi had been foretold by the holy patriarch Jacob, (Genesis 46:7,) that their posterity should be scattered in that land, which Levi the father of their race had polluted by a detestable murder and wicked perfidy. God proved eventually that this prophecy, which proceeded from Him, did not fall to the ground unfulfilled; nevertheless, although the Levites were to be banished here and there in token of their disgrace, yet were they set in various parts of the land, that they might retain the other tribes under the yoke of the Law. It was then in God''s wonderful providence that they were rather placed in peculiar and fixed residences, than allowed to mingle themselves promiscuously with the rest of the people; for the cities which God assigned to them were so many schools, where they might better and more freely engage themselves in teaching the Law, and prepare themselves for performing the office of teaching. For if they had lived indiscriminately among the multitude, they were liable to contract many vices, as well as to neglect the study of the Law; but when they were thus collected into separate classes, such an union reminded them that they were divided from the people that they might devote themselves altogether to God. Besides, their cities were like lamps shining into the very furthest corners of the land. They were therefore fortified, as it were, by walls, lest the corruptions of the people should penetrate to them.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 4, 36, 1, NULL, 'numbers-36', 'John Calvin', 'Commentaries', E'1. And the chief fathers of the families. It might appear strange that God had given an imperfect law with reference to succession, as if what will be now stated had not occurred to His mind until Moses was reminded by the chief men of the families (of Machir,) that it was unjust that the inheritances should be alienated, which would have been the case if the daughters of Zelophehad had married into other tribes, whereas their portion had fallen in the lot of the tribe of Manasseh. For whatever fell into the hands of those of another tribe, was a diminution of that lot. As, therefore, God had lately made provision for preserving the rights of individuals, He now treats of the general advantage or loss. What, then, can be the meaning of the objection, that God only half considered what was right? In my opinion, He so arranged His replies, that only when inquired of He assigned to each one his rights. The daughters of Zelophehad come, and demand justice of Moses and the elders, and God complies with their prayers. Now the heads of the tribe come, and agitate the question respecting the loss they would incur by the alienation of the inheritances; and it is then provided that other tribes should not be enriched by their loss. In short, whereas God might have spontaneously anticipated this, He preferred to grant it at the request of those who asked nothing but what was just and equitable. For it cannot be said that in this case it happened, as it often does, that, whilst every one pertinaciously maintains his own cause, and is eager to advance his own interests, one question arises out of another; for, when God has taken cognizance of the case, He pronounces that both parties only demanded what was right. It follows, therefore, that God designedly withheld His decisions until they naturally arose out of the circumstances of the case. It is a common saying that the law makes no provision for those things which rarely occur. Thus it would have been commonly supposed that this law was superfluous; and especially it would have detracted somewhat from the authority of his teaching, if Moses had treated of this trifling matter, had not circumstances led to it. In fine, God allowed Himself to be interrogated familiarly with respect to doubtful points of no primary importance, in order that posterity might recognize His reply as a proof of His fatherly indulgence. Meanwhile, let us bear in mind that if heavenly things are the subject of as much anxiety to us, as earthly things were to the children of Manasseh, the rule that we should observe will always be made clear to us.

2. And they said, The Lord commanded my lord.', false, false, 'sourced', 'published');
