-- Calvin commentary INSERT — Micah (batch 1, rows 1-7)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 33, 1, 1, NULL, 'micah-1', 'John Calvin', 'Commentaries', E'1. The word of the LORD that came to Micah the Morasthite in the days of Jotham, Ahaz, and Hezekiah, kings of Judah, which he saw concerning Samaria and Jerusalem.

1. Sermo Jehovae qui factus est (vel, directus) ad Michah Morasthitem, diebus Jotham, Achaz, Jehizkiae, regum Judae, quem vidit super Samariam et Jerusalem.

This inscription, in the first place, shows the time in which Micah lived, and during which God employed his labors. And this deserves to be noticed: for at this day his sermons would be useless, or at least frigid, except his time were known to us, and we be thereby enabled to compare what is alike and what is different in the men of his age, and in those of our own: for when we understand that Micah condemned this or that vice, as we may also learn from the other Prophets and from sacred history, we are able to apply more easily to ourselves what he then said, inasmuch as we can view our own life as it were in a mirror. This is the reason why the Prophets are wont to mention the time in which they executed their office.

But how long Micah followed the course of his vocation we cannot with certainty determine. It is, however, probable that he discharged his office as a Prophet for thirty years: it may be that he exceeded forty years; for he names here three kings, the first of whom, that is Jotham, reigned sixteen years; and he was followed by Ahab, who also reigned as many years. If then Micah was called at the beginning of the first reign, he must have prophesied for thirty-two years, the time of the two kings. Then the reign of Hezekiah followed, which continued to the twenty-ninth year: and it may be, that the Prophet served God to the death, or even beyond the death, of Hezekiah. We hence see that the number of his years cannot with certainty be known; though it be sufficiently evident that he taught not for a few years, but that he so discharged his office, that for thirty years he was not wearied, but constantly persevered in executing the command of God.

I have said that he was contemporary with Isaiah: but as Isaiah began his office under Uzziah, we conclude that he was older. Why then was Micah joined to him? That the Lord might thus break down the stubbornness of the people. It was indeed enough that one man was sent by God to bear witness to the truth; but it pleased God that a testimony should be borne by the mouth of two, and that holy Isaiah should be assisted by this friend and, as it were, his colleague. And we shall hereafter find that they adopted the very same words; but there was no emulation between them, so that one accused the other of theft, when he repeated what had been said.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 33, 2, 1, NULL, 'micah-2', 'John Calvin', 'Commentaries', E'1. Woe to them that devise iniquity, and work evil upon their beds! when the morning is light, they practice it, because it is in the power of their hand. 1. Vae cogitantibus iniquitatem et fabricantibus malitiam super cubilibus suis! Quum illuxerit mane, exequentur eam, quia est ad potentiam manus ipsorum. The Prophet does not here speak only against the Israelites, as some think, who have incorrectly confined this part of his teaching to the ten tribes; but he, on the contrary, (in discharging his office, addresses also the Jews. He refers not here to idolatry, as in the last chapter; but inveighs against sins condemned in the second table. As then the Jews had not only polluted the worship of God, but also gave loose reins to many iniquities, so that they dealt wrongfully with their neighbors, and there was among them no attention to justice and equity, so the prophet inveighs here as we shall see, against avarice, robberies, and cruelty: and his discourse is full of vehemence; for there was no doubt such licentiousness then prevailing among the people, that there was need of severe and sharp reproofs. It is at the same time easy to perceive that his discourse is mainly directed against the chief men, who exercised authority, and turned it to wrong purposes. Woe, he says, to those who meditate on iniquity, and devise evil on their beds, that, when the morning shines, they may execute it Here the Prophet describes to the life the character and manners of those who were given to gain, and were intent only on raising themselves. He says, that in their beds they were meditating on iniquity, and devising wickedness. Doubtless the time of night has been given to men entirely for rest; but they ought also to use this kindness of God for the purpose of restraining themselves from what is wicked: for he who refreshes his strength by nightly rest, ought to think within himself, that it is an unbecoming thing and even monstrous, that he should in the meantime devise frauds, and guiles, and iniquities. For why does the Lord intend that we should rest, except that all evil things should rest also? Hence the Prophet shows here, by implication, that those who are intent on devising frauds, while they ought to rest, subvert as it were the course of nature; for they have no regard for that rest, which has been granted to men for this end, -- that they may not trouble and annoy one another. He afterwards shows how great was their desire to do mischief, When it shines in the morning, he says, they execute it He might have said only, They do in the daytime what they contrive in the night: but he says, In the morning; as though he had said, that they were so heated by avarice, that they rested not a moment; as soon as it shone, they were immediately ready to perpetrate the frauds they had', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 33, 3, 1, NULL, 'micah-3', 'John Calvin', 'Commentaries', E'1. And I said, Hear, I pray you, O heads of Jacob, and ye princes of the house of Israel; Is it not for you to know judgment? 1. Et dixi, Audite quaeso principes Jacob et gubernatores domus Israel; annon vestrum est (vel, ad vos spectat) scire judicium? 2. Who hate the good, and love the evil; who pluck off their skin from off them, and their flesh from off their bones; 2. Atqui oderunt bonum et dilligunt malum, rapiunt pellem ab ipsis, et carnem ab ossibus eorum; 3. Who also eat the flesh of my people, and flay their skin from off them; and they break their bones, and chop them in pieces, as for the pot, and as flesh within the caldron. 3. Et tunc vorant carnem populi mei, et pellem ipsorum ab ipsis excoriant; et ossa eorum frangunt, et comminuunt; sicuti ad ollam (vel, ac si destinata essent ollae,) et carnem eorum in medio aheni. The Prophet in this chapter assails and severely reproves the chief men as well as the teachers; for both were given to avarice and cruelty, to plunder, and, in short, to all other vices. And he begins with the magistrates, who exercised authority among the people; and briefly relates the words in which he inveighed against them. We have said elsewhere, that the Prophets did not record all that they had spoken, but only touched shortly on the heads or chief points: and this was done by Micah, that we might know what he did for forty or more years, in which he executed his office. He could have related, no doubt, in half-an-hour, all that exists of his writings: but from this small book, however small it is, we may learn what was the Prophet''s manner of teaching, and on what things he chiefly dwelt. I will now return to his words. He says that the chief men of the kingdom had been reproved by him. It is probable, that these words were addressed to the Jews; for though at the beginning he includes the Israelites, we yet know that he was given as a teacher to the Jews, and not to the kingdom of Israel. It was as it were accidental, that he sometimes introduces the ten tribes together with the Jews. This address then was made, as I think, to the king as well as to his counselors and other judges, who then ruled over the people of Judah. Hear this, I pray, he says. Such a preface betokens carelessness in the judges; for why does he demand a hearing from them, except that they had become so torpid in their vices, that they would attend to nothing? Inasmuch then as so brutal a stupor had seized on them, he says, Hear now ye chiefs, or heads, of Jacob, and ye rulers of the house of Israel But why does he still speak of the house of Israel? Because that name was especially known and celebrated, whenever a mention', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 33, 4, 1, NULL, 'micah-4', 'John Calvin', 'Commentaries', E'1. But in the last days it shall come to pass, that the mountain of the house of the LORD shall be established in the top of the mountains, and it shall be exalted above the hills; and people shall flow unto it. 1. Accidet ultimis diebus, ut sit mons domus Jehovae dispositus in capite montium, et extollentur ipse prae sublimitatibus; et venient ad eum populi: 2. And many nations shall come, and say, Come, and let us go up to the mountain of the LORD, and to the house of the God of Jacob; and he will teach us of his ways, and we will walk in his paths: for the law shall go forth of Zion, and the word of the LORD from Jerusalem. 2. Et proficiscentur gentes multae et dicent, Venite, et ascendemus ad montem Jehovae, et ad domum Dei Jacob; et docebit nos de viis suis, et ambulabimus in semitis ejus; quia ex Sion prodibit lex, et verbum Jehovae ex Jerusalem. Here Micah begins his address to the faithful, who were a remnant among that people; for though the infection had nearly extended over the whole body, there were yet a few, we know, who sincerely worshipped God. Hence Micah, that he might not dishearten God''s children by extreme terror, reasonably adds what we have now heard, -- that though for a time the temple would be demolished and laid waste, it would yet be only for a season, for the Lord would be again mindful of his covenant. When, therefore, the Prophet had hitherto spoken of God''s dreadful vengeance, he directed his discourse to the whole people and to the princess; but now, especially, and as it were apart, addresses the pious and sincere servants of God; as though he said, "There is now a reason why I should speak to the few: I have hitherto spoken of the near judgment of God on the king''s counselors, the priests and the prophets; in short, on the whole community, because they are all become wicked and ungodly; a contempt of God and an irreclaimable obstinacy have pervaded the whole body. Let them therefore have what they have deserved. But now I address the children of God by themselves, for I have something to say to them." For though the Prophet publicly proclaimed this promise, there is yet no doubt but that he had regard only to the children of God, for others were not capable of receiving this consolation; nay, he had shortly before condemned the extreme security of hypocrites, inasmuch as they leaned upon God; that is, relied on a false pretense of religion, in thinking that they were redeemed by a lawful price when they had offered their sacrifices. And we know that we meet with the same thing in the writings of the Prophets, and that it is a practice common among them to add consolations to threatening, not for the sake of the whole people, but to sustain the faithful in their', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 33, 5, 1, NULL, 'micah-5', 'John Calvin', 'Commentaries', E'1. Now gather thyself in troops, O daughter of troops: he hath laid siege against us: they shall smite the judge of Israel with a rod upon the cheek.

1. Nunc colligas te (vel, obsidione cingeris, ut alii vertunt) filia congregationis (hoc est, turmae;) obsidionem posuit contra nos; in virga percutient ad maxillam judicem Israel.

2. But thou, Bethlehem Ephratah, though thou be little among the thousands of Judah, yet out of thee shall he come forth unto me that is to be ruler in Israel; whose goings forth have been from of old, from everlasting.

2. Et tu Beth-lehem Ephrata, parva ad essendum (ut ita loquar) inter millia Jehudah; ex te mihi egredietur ad essendum dominatorem (sic transfero durius, ut sit dominator) in Israel: et egressus ejus ab initio, a diebus seculi.

To encourage the faithful to patience, the Prophet again reminds them that hard and severe time was nigh; for it was needful to put them in mind often of the approaching calamity, lest terror should wholly discourage them. As then there was danger from despair, the Prophet often repeats what he has already said of God''s judgment, which was then suspending over the people of Israel. And this mode and order of teaching ought to be observed. When the Prophets threaten us, or denounce the punishment we have deserved, we either become torpid, or grow angry with God, and murmur: but when they set forth any thing of comfort, we then indulge ourselves and become too secure. It is therefore necessary to connect threatening with promises, so that we may be always ready to endure temporal evils, and that our minds, sustained by hope, may, at the same time, depend on the Lord, and recomb on him. It was for this reason that the Prophet again mentions what he had already several times stated, -- that the Jews would be surrounded by a siege. How do these two things agree, -- that the enemies, assembled together, would be like sheaves which are taken to the floor to be trodden by the feet of animals, -- and that the Jews would be besieged? I answer, that these things harmonize, because the temporary punishment, which God would inflict on his Church, would not prevent him to restore it again whenever it pleased him. Lest, therefore, security should creep over the minds of the godly, the Prophet designed often to remind them of that dreadful calamity which might have entirely upset them, had no support been afforded them, that is, had not God sustained them by his word.

Now then thou shalt assemble thyself, he says, O daughter of a troop The verb htgddy, etgaddi, and the noun gdvd, gadud, sound alike; as though he said, Thou shalt he collected, O daughter of collection. The Prophet addresses Jerusalem: but we must see why he calls her the daughter of collection.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 33, 6, 1, NULL, 'micah-6', 'John Calvin', 'Commentaries', E'1. Hear ye now what the Lord saith; Arise, contend thou before the mountains, and let the hills hear thy voice. 1. Audite nunc (vel, quaeso) quod dicit Jehova, -- Surge, litiga coram montibus, et colles audiant vocem tuam: 2. Hear ye, O mountains, the Lord''s controversy, and ye strong foundations of the earth: for the Lord hath a controversy with his people, and he will plead with Israel. 2. Audite montes disceptationem Jehovae, et fortia undamenta terrae: quia disceptatio Jehovae cum populo suo, et cum Israele contendet. Here the Prophet avowedly assumes that the people were sufficiently proved guilty; and yet they resisted through a hardiness the most obdurate, and rejected all admonitions without shame, and without any discretion. He is therefore commanded to direct his discourse to the mountains and to the hills; for his labor had now for a long time been useless as to men. The meaning then is that when the Prophet had spent much labor on the people and derived no fruit, he is at length bidden to call the mountains and the hills to bear their testimony to God; and thus before the elements is made known and proved the ungodliness and the obstinacy of the people. But before he relates what had been committed to him, he makes a preface, in order to gain attention. Hear ye what Jehovah says. The Prophets are wont, on very serious subjects, to make such a preface as is here made by Micah: and it is indeed sufficiently evident from the passage, that he has here no ordinary subject for his teaching, but that, on the contrary, he rebukes their monstrous stupidity; for he had been addressing the deaf without any advantage. As then the Prophet was about to declare no common thing, but to be a witness of a new judgment, -- this is the reason why he bids them to be unusually attentive. Hear, he says, what Jehovah saith. What is it? He might have added, "Jehovah has very often spoken to you, he has tried all means to bring you to the right way; but as ye are past recovery, vengeance alone now remains for you: he will no more spend labor in vain on you; for he finds in you neither shame, nor meekness, nor docility." The Prophet might have thus spoken to them; but he says that another thing was committed to his charge by the Lord, and that is, to contend or to plead before the mountains. And this reproach ought to have most acutely touched the hearts of the people: for there is here an implied comparison between the mountains and the Jews; as though the Prophet said, -- "The mountains are void of understanding and reason, and yet the Lord prefers to have them as witness of his cause rather than you, who exceed in stupidity all the mountains and rocks." We now then perceive the design of God. Some take mountains and hills in a metaphorical sense', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 33, 7, 1, NULL, 'micah-7', 'John Calvin', 'Commentaries', E'1. Woe is me! for I am as when they have gathered the summer fruits, as the grapegleanings of the vintage: there is no cluster to eat: my soul desired the firstripe fruit.

1. Vae mihi (alii deducunt a yll, ululare meum; sed est particula dolentis apud Hebraeos; Vae mihi ergo,) quia fui sicut collectiones aestatis (sic est ad verbum,) et sicuti racemi vindemiae; nullus botrus ad comedendum; maturos fructus (vel, primitias frugum) desideravit anima mea.

2. The good man is perished out of the earth: and there is none upright among men: they all lie in wait for blood; they hunt every man his brother with a net.

2. Periit humanus (vel, mansuetus) e terra, et rectus in hominibus nemo est; et omnes sanguinibus insidiantur, quisque fratrem suum venatur reti (alii, ad perniciem; et hrm, etiam Hebraeis interdum est occisio.)

The meaning of the first verse is somewhat doubtful: some refer what the Prophet says to punishment; and others to the wickedness of the people. The first think that the calamity, with which the Lord had visited the sins of the people, is bewailed; as though the Prophet looked on the disordered state of the whole land. But it may be easily gathered from the second verse, that the Prophet speaks here of the wickedness of the people, rather than of the punishment already inflicted. I have therefore put the two verses together, that the full meaning may be more evident to us.

Woe then to me! Why? I am become as gatherings Too free, or rather too licentious is this version, -- "I am become as one who seeks to gather summer-fruits, and finds none;" so that being disappointed of his hope, he burns with desire. This cannot possibly be considered as the rendering of the Prophet''s words. There is indeed some difficulty in the expressions: their import, however, seems to be this, -- that the land, which the Prophet undertakes here to represent and personify, was like to a field, or a garden, or a vineyard, that was empty. He therefore says, that the land was stripped of all its fruit, as it is after harvest and the vintage. So by gatherings we must understand the collected fruit. Some understand the gleanings which remain, as when one leaves carelessly a few clusters on the vines: and thus, they say, a few just men remained alive on the land. But the former comparison harmonizes better with the rest of the passage, and that is, that the land was now stripped of all its fruit, as it is after the harvest and the vintage. I am become then as the gatherings of summer, that is, as in the summer, when the fruit has been already gathered; and as the clusters of the vintage, that is when the vintage is over.

There is no cluster, he says to eat. The Prophet refers here to the scarcity of good men; yea, he says that there were no longer any righteous men living.', false, false, 'sourced', 'published');
