-- Calvin commentary INSERT — Luke (batch 3, rows 21-24)
INSERT INTO commentaries (
  scholar_id, book_id, chapter, verse_start, verse_end,
  verse_reference, author, source, commentary_text,
  featured, founder_curated, author_type, status
) VALUES
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 21, 1, NULL, 'luke-21', 'John Calvin', 'Commentaries', E'41. And while Jesus was sitting opposite to the treasury, he perceived how the multitude threw money into the treasury, and many rich persons put in much. 42. And a poor widow came, and threw in two mites, which make a farthing. 43. And having called his disciples to him, he said, Verily I say to you, that this poor widow hath thrown in more than all who have thrown into the treasury: 44. For they all have thrown in out of their abundance; but she out of her poverty hath thrown in all that she had, all her living.

1. And, lifting up his eyes, he saw those rich men who were throwing their gifts into the treasury. 2. And he saw also a certain poor widow throwing into it two mites. 3. And he said, Verily I say to you, that this poor widow hath thrown in more than all: 4. For all these, out of their abundance, have thrown into the offering of God; but she out of her poverty hath thrown in all the living which she had.

Mark 12:43. Verily I say to you. This reply of Christ contains a highly useful doctrine that whatever men offer to God ought to be estimated not by its apparent value, but only by the feeling of the heart, and that the holy affection of him who according to his small means, offers to God the little that he has, is more worthy of esteem than that of him who offers a hundred times more out of his abundance. In two ways this doctrine is useful, for the poor who appear not to have the power of doing good, are encouraged by our Lord not to hesitate to express their affection cheerfully out of their slender means; for if they consecrate themselves, their offering, which appears to be mean and worthless, will not be less valuable than if they had presented all the treasures of Croesus. On the other hand, those who possess greater abundance, and who have received from God larger communications, are reminded that it is not enough if in the amount of their beneficence they greatly surpass the poor and common people; because it is of less value in the sight of God that a rich man, out of a vast heap, should bestow a moderate sum, than that a poor man, by giving very little, should exhaust his store. This widow must have been a person of no ordinary piety, who, rather than come empty into the presence of God, chose to part with her own living. And our Lord applauds this sincerity, because, forgetting herself, she wished to testify that she and all that she possessed belonged to God. In like manner, the chief sacrifice which God requires from us is self-denial.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 22, 1, NULL, 'luke-22', 'John Calvin', 'Commentaries', E'28. Verily I say to you. That the disciples may not think that they have lost their pains, and repent of having begun the course, Christ warns them that the glory of his kingdom, which at that time was still hidden, was about to be revealed. As if he had said, "There is no reason why that mean condition should discourage you; for I, who am scarcely equal to the lowest, will at length ascend to my throne of majesty. Endure then for a little, till the time arrive for revealing nay glory." And what does he then promise to them? That they shall be partakers of the same glory.

You also shall sit on twelve thrones By assigning to them thrones, from which they may judge the twelve tribes of Israel, he compares them to assessors, or first councilors and judges, who occupy the highest seats in the royal council. We know that the number of those who were chosen to be apostles was twelve, in order to testify that, by the agency of Christ, God purposed to collect the remnant of his people which was scattered. This was a very high rank, but hitherto was concealed; and therefore Christ holds their wishes in suspense till the latest revelation of his kingdom, when they will fully receive the fruit of their election. And though the kingdom of Christ is, in some respects, manifested by the preaching of the Gospel, there is no doubt that Christ here speaks of the last day.

In the regeneration. Some connect this term with the following clause. In this sense, regeneration would be nothing else than the renovation which shall follow our restoration, when life shall swallow up what is mortal, and when our mean body shall be transformed into the heavenly glory of Christ. But I rather explain regeneration as referring to the first coming of Christ; for then the world began to be renewed, and arose out of the darkness of death into the light of life. And this way of speaking occurs frequently in the Prophets, and is exceedingly adapted to the connection of this passage. For the renovation of the Church, which had been so frequently promised, had raised an expectation of wonderful happiness, as soon as the Messiah should appear; and therefore, in order to guard against that error, Christ distinguishes between the beginning and the completion of his reign.

Luke 22:28. You are they who have continued with me. Although Luke appears to relate a different discourse of Christ, and one which was delivered at a different time, yet I have no doubt that it refers to the same time. For it is not a continued discourse of Christ that is here related, but detached sentences, without any regard to the order of time, as we shall shortly afterwards have occasion to state.', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 23, 1, NULL, 'luke-23', 'John Calvin', 'Commentaries', E'3. Then Judas, perceiving that he was condemned. By this adverb (tote) then, Matthew does not fix the exact point of time; for we shall find him shortly afterwards adding, that Judas, when he saw that the priests disdainfully refused to take back the reward of his treason, threw it down in the temple. But from the house of Caiaphas they came straight to the Pretorium, and stood there until Christ was condemned. It can scarcely be supposed that they were found in the temple on that day; but as the Evangelist was speaking of the rage and madness of the council, he inserted also the death of Judas, by which their blind obstinacy, and the hardness of their hearts like iron, were more fully displayed. He says that Judas repented; not that he reformed, but that the crime which he had committed gave him uneasiness; as God frequently opens the eyes of the reprobate, so as to begin to feel their miseries, and to be alarmed at them. For those who are sincerely grieved so as to reform, are said not only (metamelein), but, also (metanoein), from which is derived also (metanoia), which is a true conversion of the soul to God. So then, Judas conceived disgust and horror, not so as to turn to God, but rather that, being overwhelmed with despair, he might serve as an example of a man entirely shut out from the grace of God. Justly, indeed, does Paul say, that the sorrow which leads to repentance is salutary, (2 Corinthians 7:10;) but if a man stumble at the very threshold, he will derive no advantage from a confused and mistaken grief. What is more, this is a just punishment with which God at length visits the wicked, who have obstinately despised his judgment, that he gives them up to Satan to be tormented without the hope of consolation. True repentance is displeasure at sin, arising out of fear and reverence for God, and producing, at the same time, a love and desire of righteousness. Wicked men are far from such a feeling; for they would desire to sin without intermission, and even, as far as lies in their power, they endeavor to deceive both God and their own conscience, but notwithstanding their reluctance and opposition, they are tormented with blind horror by their conscience, so that, though they do not hate their sin, still they feel, with sorrow and distress, that it presses heavily and painfully upon them. This is the reason why their grief is useless; for they do not cheerfully turn to God, or even aim at doing better, but, being attached to their wicked desires, they pine away in torment, which they cannot escape. In this way, as I have just said, God punishes their obstinacy; for although his elect are drawn to him by severe chastisements, and as it were contrary to their will, yet he heals in due time the wounds which he has inflicted, so that they', false, false, 'sourced', 'published'),
((SELECT id FROM scholars WHERE slug = 'calvin'), 42, 24, 1, NULL, 'luke-24', 'John Calvin', 'Commentaries', E'1. And on the first day of the Sabbaths, very early in the morning, they came to the tomb, carrying the spices which they had prepared, and some women with them. 2. And they found the stone rolled away from the tomb. 3. And having entered, they found not the body of the Lord Jesus. 4. And it happened, while they were in consternation on this account, lo, two men stood near them in shining garments. 5. And when the women were terrified, and bowed their face to the earth, they said to them, Why do you seek the living among the dead? 6. He is not here, but is risen: remember how he told you, while he was still in Galilee, 7. Saying, that the Son of man must be delivered into the hands of the wicked men, and be crucified and rise again on the third day. 8. And they remembered his words.

We now come to the closing scene of our redemption. For the lively assurance of our reconciliation with God arises from Christ having come from hell as the conqueror of death, in order to show that he had the power of a new life at his disposal. Justly, therefore, does Paul say that there will be no gospel, and that the hope of salvation will be vain and fruitless, unless we believe that Christ is risen from the dead, (1 Corinthians 15:14.) For then did Christ obtain righteousness for us, and open up our entrance into heaven; and, in short, then was our adoption ratified, when Christ, by rising from the dead, exerted the power of his Spirit, and proved himself to be the Son of God. No though he manifested his resurrection in a different manner from what the sense of our flesh would have desired, still the method of which he approved ought to be regarded by us also as the best. he went out of the grave without a witness, that the emptiness of the place might be the earliest indication; next, he chose to have it announced to the women by the angels that he was alive; and shortly afterwards he appeared to the women, and, finally, to the apostles, and on various occasions.

Thus he gradually brought his followers, according to their capacity, to a larger measure of knowledge. He began with the women, and not only presented himself to be seen by them, but even gave them a commission to announce the gospel to the apostles, so as to become their instructors. This was intended, first, to chastise the indifference of the apostles, who were like persons half-dead with fear, while the women ran with alacrity to the sepulcher, and likewise obtained no ordinary reward. For though their design to anoint Christ, as if Ire were still dead, was not free from blame, still he forgave their weakness, and bestowed on them distinguished honor, by taking away from men the apostolic office, and committing it to them for a short time.', false, false, 'sourced', 'published');
